### ISSUE TITLE
Feature request: get_param_as_datetime

### ISSUE THREAD

**Issue by macdjord** [falconry/falcon#1007]
The `get_param_as_date()` function is useful, but what I need for my current use case is a date _and time_.

**Comment by kgriffs** [comment]
In your case, how is the date/time string formatted?

**Comment by macdjord** [comment]
'yyyy_mm_dd_hh_mm_ss', I think. I can no longer check; I've changed jobs.

**Comment by jmvrbanac** [comment]
I believe this is resolved with #1053 and should be included in the next release.
