### ISSUE TITLE
req.get_param  It could not be parsed as JSON

### ISSUE THREAD

**Issue by fengfangqian** [falconry/falcon#1020]
like the pic   ,the json format is right  why, it's bug??

![qq 20170421114153](https://cloud.githubusercontent.com/assets/3350372/25261988/bf8ce7ee-2687-11e7-8807-37e50ec240d8.png)
![qq 20170421114205](https://cloud.githubusercontent.com/assets/3350372/25261989/bf919776-2687-11e7-9a89-5383fbff67dc.png)
![qq 20170421114230](https://cloud.githubusercontent.com/assets/3350372/25261990/bf92ce20-2687-11e7-8337-a13728b328bd.png)

**Comment by joidegn** [comment]
Try urlencoding the json before appending it to the url.

**Comment by fengfangqian** [comment]
how can i get post data?
i use req.get_param get the post data, must query_string

**Comment by cnds** [comment]
i think you need to try req.stream.read()

**Comment by kgriffs** [comment]
Hi @fengfangqian, if you're passing JSON in the query string, you'll need to set the [auto_parse_qs_csv](http://falcon.readthedocs.io/en/stable/api/api.html?highlight=auto_parse_qs_csv#RequestOptions.auto_parse_qs_csv) option, e.g.:

```py
api = falcon.API()
api.req_options.auto_parse_qs_csv = False
```

For form posts (using `application/x-www-form-urlencoded`) you can either read and parse the body directly from `req.stream`, or set the [auto_parse_form_urlencoded](http://falcon.readthedocs.io/en/stable/api/api.html#RequestOptions.auto_parse_form_urlencoded) request option to have Falcon merge them into the query params (in which case you will also want to set `auto_parse_qs_csv` per above).
