### ISSUE TITLE
Remove all deprecated behaviors and shims

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1029]
Grep the code for "deprecated", etc. and remove relevant code/interfaces.

**Comment by kgriffs** [comment]
NOTE: It would be best to do this is a series of small-ish PRs so that we can review each change carefully before merging.

**Comment by steven-upside** [comment]
I'll take a look at this.

**Comment by afs2015** [comment]
Are there any existing deprecated code I am missing? Otherwise I think this can be marked as closed.

**Comment by kgriffs** [comment]
I'm going to go ahead and close this out since I think we are in a good place for 3.0. I created a similar issue for the 4.0 milestone so we don't forget: https://github.com/falconry/falcon/issues/1853
