### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1037]
Remove any code needed to support Python 2.6, update docs, and remove package classifier.

**Comment by cclauss** [comment]
While doing this, it might be useful to add Python _3_.6 to the testing.  Those changes will touch all the same files.

**Comment by hugovk** [comment]
How about dropping Python 3.3 as well? It went EOL and is little used.

Here's the pip installs for falcon from PyPI for the last month:
```
$ pypinfo --percent --pip falcon pyversion
python_version percent download_count
-------------- ------- --------------
3.6              54.5%         61,811
2.7              34.6%         39,183
3.5               7.7%          8,715
3.4               3.1%          3,494
3.3               0.1%             62
None              0.0%             52
3.7               0.0%             12
2.6               0.0%             12

```

**Comment by hugovk** [comment]
Please see PR #1129, feedback welcome!
