### ISSUE TITLE
Update the FAQ to talk about consuming a JSON query string value

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1052]
See also: https://github.com/falconry/falcon/issues/1020

**Comment by santeyio** [comment]
Hey @kgriffs, I'm a fan of the framework and would love to help out, thought I might be able to get my toes wet by doing some documentation -- would it be helpful if I sent you a PR for this?

**Comment by kgriffs** [comment]
Hi @santeyio, thanks for contributing! This looks like a great addition to the FAQ. 👍

**Comment by kgriffs** [comment]
Fixed by #1111
