### ISSUE TITLE
Create an official Falcon stable PPA build for users of older distributions

### ISSUE THREAD

**Issue by jmvrbanac** [falconry/falcon#1061]
Some of older distributions are using quite old versions of Falcon. It would probably be good if we created a PPA containing the stable versions of Falcon.

**Comment by vytas7** [comment]
Now that as of Falcon 2.0 we have vendored the last remaining dependency, building packages should be easier than ever. Even though the majority of users seem to install packages from PyPi, Anaconda etc, having a PPA could obviously be useful for some cases, it is just a question of focus and available bandwidth.

@jmvrbanac Would you be able to spare some time for working on this yourself?

**Comment by vytas7** [comment]
It seems this hasn't gathered much interest, and we have no bandwidth to spare for a Debian repository. Moreover, recent versions of Debian and Ubuntu sport Falcon 3.x series, and we don't release that often either.
