### ISSUE TITLE
Why the post over the data will become a plus sign

### ISSUE THREAD

**Issue by fengfangqian** [falconry/falcon#1068]
![image](https://cloud.githubusercontent.com/assets/3350372/26825522/f35107d4-4ae7-11e7-9f30-d19c397127ef.png)
![image](https://cloud.githubusercontent.com/assets/3350372/26825534/016a2e7c-4ae8-11e7-8c69-2dc51b4a2a15.png)

req.stream.read()

pelease help me thank you

**Comment by ak64th** [comment]
Because it's `urlencoded`... 
Try post raw data

**Comment by cnds** [comment]
![capture](https://cloud.githubusercontent.com/assets/16872316/26833893/4e44146a-4b06-11e7-94b7-7d0758b752fd.PNG)

try this
