### ISSUE TITLE
How to compile Falcon using Cython

### ISSUE THREAD

**Issue by ajan1019** [falconry/falcon#1070]
I followed below steps when installing falcon

```
$ pip install cython
$ pip install --no-binary :all: falcon
```
Everything went well.
But when I tried to do load test(Gatling) I can't find any notable difference between both.
Both(With Cython and without Cython) gives the same performance.

Do we have any way or log file to confirm that api is compiled by Cython.

**Comment by kgriffs** [comment]
Hi @ajan1019, if you pass `-v` to pip, it should show you the Cython output (look for lines starting with "byte-compiling".

It could be that other parts of your app are slow enough relative to the Falcon framework itself, that compiling just the framework with Cython doesn't make a noticeable difference. Profiling will help track down any slow algorithms or I/O that may need to be optimized

You might also try compiling your entire app with Cython or switching to PyPy.
