### ISSUE TITLE
I try to return request value but failed

### ISSUE THREAD

**Issue by ericxin1982** [falconry/falcon#1089]
I post a {gender:'female', age:22, addr:'high tech'} to falcon, and I get_param addr, I can print, but when I set it back to resp.body,  from the postman output, it says Unexpected 'h'.

What is wrong, please help.

**Comment by cnds** [comment]
can you show us your detail error msg?

**Comment by anekix** [comment]
@cnds maybe you are setting to `resp.body` a dictionary? instead do like this:
```python
import json
resp.body = json.dumps( {'gender':'female', 'age':22, 'addr':'high tech'} )
```

**Comment by ericxin1982** [comment]
Thanks for your help, I would go get a try.


Thanks
Eric Xin






At 2017-08-24 11:23:01, "anekix" <notifications@github.com> wrote:


@cnds maybe you are setting to resp.body a dictionary? instead do like this:

import json
resp.body = json.dumps( {'gender':'female', 'age':22, 'addr':'high tech'} )

**Comment by kgriffs** [comment]
FWIW, 1.3 (final release in a week or two) supports serialization out of the box. See also: http://falcon.readthedocs.io/en/latest/api/media.html#media
