### ISSUE TITLE
Can i create websocket connection?

### ISSUE THREAD

**Issue by Mike667** [falconry/falcon#1102]
Can i create websocket connection without other applications?

**Comment by kgriffs** [comment]
Hi Mike, Falcon has so far been focused on HTTP use cases, so it does not support WebSockets. We are keeping an eye on the Django Channels effort to see where that goes and whether it would make sense for Falcon to also provide a unified protocol abstraction.

**Comment by dabo02** [comment]
Why don't you take a look at the flask socketio extension? It is way better than django channels and much easier to use
