### ISSUE TITLE
Optimize request cookie parsing

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1107]
In 1.3, the request cookie parser was changed to parse individual cookies so that malformed ones could be skipped, rather than giving up on parsing the entire header. However, this is significantly slower than parsing the entire header value in one shot, esp. since the SimpleCookie parser is rather inefficient.

We should be able to do better. We can start with the SimpleCookie code from the latest CPython 3.7 code base, optimize it, and make it compatible with Python 2.

See also:

[request.py#L894](https://github.com/falconry/falcon/blob/master/falcon/request.py#L894)

**Comment by santeyio** [comment]
Assuming no one else is working on this, I can take a shot at this

**Comment by kgriffs** [comment]
@santeyio that would be great, thanks!

**Comment by kgriffs** [comment]
@santeyio P.S. If you like, you might want to first register for Hacktoberfest so this will count towards that. 🎃

**Comment by kgriffs** [comment]
The bulk of this work has been moved to a standalone project:

https://github.com/pyrates/biscuits/

We'll watch this project and add support for it in Falcon once it is mature.
