### ISSUE TITLE
Incorrect handling of commas inside a Forwarded header

### ISSUE THREAD

**Issue by vfaronov** [falconry/falcon#1116]
To implement [`Request.forwarded`](http://falcon.readthedocs.io/en/stable/api/request_and_response.html#Request.forwarded), Falcon splits the incoming Forwarded header on commas. Because of this, it cannot correctly handle forwarded-elements that contain a comma inside a quoted-string.

To reproduce, run the following `fwd_demo.py`:

```
import falcon

class ForwardedResource(object):
    def on_get(self, req, resp):
        resp.body = req.forwarded[-1].src

app = falcon.API()
app.add_route('/fwd', ForwardedResource())
```

under Gunicorn:

```
$ gunicorn fwd_demo:app
```

and send requests like this:

```
curl -s localhost:8000/fwd -H 'Forwarded: for=1.2.3.4;some="extra,info"'
```

The expected response is `1.2.3.4`, but the actual response is empty.

A more correct solution would be to parse the Forwarded header carefully with regard to quoted-strings. However, this is complicated by the fact that the Forwarded header may be partly controlled by an external attacker, who might submit a request with:

```
Forwarded: for=_trusted_addr;by="
```

Unless a reverse proxy eagerly validates and fixes/strips such a header, appending another forwarded-element might give:

```
Forwarded: for=_trusted_addr;by=", for=_real_addr
```

In this case, `req.forwarded[-1].src` ought to be `_real_addr`, not `_trusted_addr`.

See [aiohttp’s implementation of Forwarded](https://github.com/aio-libs/aiohttp/blob/1609acd5802364fa3bd11adfb34a4b2b0d07fc42/aiohttp/web_request.py#L188-L246) for an example of how to deal with this correctly (I hope).

“`Request.forwarded` should not be trusted anyway” would be a poor solution, I think. As long as a reverse proxy is correctly configured to append a header, that header may be and often is trusted by the application for important purposes such as rate limiting.

**Comment by kgriffs** [comment]
Hi @vfaronov, good catch. Let's schedule this issue for the next release.
