### ISSUE TITLE
Mature support for WebSocket

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1122]

**Comment by santiago** [comment]
Any progress on this?

**Comment by CoreyCole** [comment]
It's part of the version 2.0 milestone (40 open issues / 43 total). Is there any roadmap of the priorities for these issues?

**Comment by vytas7** [comment]
Closing this. The WebSocket functionality was delivered some 10 months ago, and it's unclear the criteria are for truly mature support. Hopefully we're getting there :smiling_imp:
