### ISSUE TITLE
falcon.util.uri.decode CPU and realloc calls when POST body is large and heavily encoded.

### ISSUE THREAD

**Issue by thatsafunnyname** [falconry/falcon#1124]
Hello and thank you for Falcon,

I noticed when POSTing a large and heavily urlencoded body that the `falcon.util.uri.decode` function uses a lot of user CPU and performs many memory reallocations.  This was noticed as the service using Falcon was running in a memory constrained environment.

I have a reproducer, it may be considered somewhat extreme, but does demonstrate the behaviour when compared to https://github.com/acg/python-percentcoding#notes .

Note the difference in behaviour from both urllib.parse.unquote and falcon.util.uri.decode.  `falcon.util.uri.decode` will decode escaped UTF-8 mutibyte sequences and the str returned will be of type ``unicode`` on Python 2 IFF the URL contained escaped non-ASCII characters, in which case UTF-8 is assumed per RFC 3986.

I am testing with Python 2.7.5 and Falcon 1.3.0 on RHEL7 (kernel 3.10.0* on x86_64).

Run the following to generate a large encoded (122M) file:

```
> echo "from __future__ import print_function
n = 0
while n < 16000000:
    n += 1
    print('%%%02X+' % n, end='')" | python > ~/tmp.tmp
```
 
The test script:

```
> cat test.py
import sys
import falcon

if sys.argv[2] == '1':
    print "Monkey patch"
    orig_decode = falcon.util.uri.decode
    from percentcoding import unquote_plus
    # note that if input was originally Unicode, it can be recovered using .decode('utf8')
    falcon.util.uri.decode = lambda x: unquote_plus(x)
else:
    print "No monkey patch"

in_filename = sys.argv[1]
in_file = open(in_filename, "rb")
data = in_file.read()
in_file.close()

print 'len=',len(falcon.util.uri.decode(data))
```
Test run using `falcon.util.uri.decode`
``` 
> /usr/bin/time -v python test.py ~/tmp.tmp 0
No monkey patch
len= 94881540
        User time (seconds): 10.00
        System time (seconds): 0.70
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.72
        Maximum resident set size (kbytes): 1592572
        Minor (reclaiming a frame) page faults: 239161
```
Test run using `percentcoding.unquote_plus`
``` 
> /usr/bin/time -v python test.py ~/tmp.tmp 1
Monkey patch
len= 94881540
        User time (seconds): 0.63
        System time (seconds): 0.11
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.77
        Maximum resident set size (kbytes): 351648
        Minor (reclaiming a frame) page faults: 7192
```
Memusage when using `falcon.util.uri.decode`
``` 
> memusage python test.py ~/tmp.tmp 0 2>&1 | egrep -i '(memory|_|alloc|free|len|monkey)'
No monkey patch
len= 94881540
Memory usage summary: heap total: 1899568728, heap peak: 1634629329, stack peak: 22288
         total calls   total memory   failed calls
 malloc|      16688     1664650482              0
realloc|   16004555      234869595              0  (nomove:15999009, dec:54, free:0)
 calloc|         71          48651              0
   free|      13786     1894213621
```
Memusage when using `percentcoding.unquote_plus`
```
> memusage python test.py ~/tmp.tmp 1 2>&1 | egrep -i '(memory|_|alloc|free|len|monkey)'
Monkey patch
len= 94881540
Memory usage summary: heap total: 365223878, heap peak: 355089528, stack peak: 22288
         total calls   total memory   failed calls
 malloc|      13714      364740615              0
realloc|       4577         433259              0  (nomove:802, dec:54, free:0)
 calloc|         73          50004              0
   free|      10815      360062648
```

Anything to help improve the efficiency/performance of decoding large urlencoded POSTs would be useful.  Thanks again.

**Comment by kgriffs** [comment]
We may be able to alleviate this somewhat by switching to the ''.join() pattern for large strings. Let me play around with it and see what I can do. It may also make sense to just adopt percentcoding at some point.

**Comment by thatsafunnyname** [comment]
Just to let you know that the reproducer being used that led to this issue being created did not reflect the actual encoding being used in the system.  While the (curl command line) reproducer used a lot of memory and this matched what was being observed, the system was not sent urlencoded POSTs, and the high memory used was from large JSON parsing in python using the "json" lib prior to python 3.3 ( https://blog.ionelmc.ro/2015/11/22/memory-use-and-speed-of-json-parsers/ ).
 
  So while improving the efficiency and performance would be useful, it is not as important as when I first created the issue.

**Comment by vytas7** [comment]
See also a newer discussion on https://github.com/falconry/falcon/issues/1594
