### ISSUE TITLE
How to implement redirection?

### ISSUE THREAD

**Issue by Iflier** [falconry/falcon#1127]
Hello, I am a newer to Falcon. Does Falcon  has a way to redirect ? Such as:  self.redirect in Tornado or redirect() in Falsk ?

**Comment by karmux** [comment]
You just raise `falcon.HTTPMovedPermanently(location)` or `falcon.HTTPFound(location)`.
See http://falcon.readthedocs.io/en/stable/api/redirects.html for more info.

**Comment by Iflier** [comment]
@karmux , thanks for your reply, I will have a try.
