### ISSUE TITLE
How to run example

### ISSUE THREAD

**Issue by holic-cl** [falconry/falcon#1138]
Hi, i want to try the example code but have a problem:

I try to run on this way:
`$ gunicorn3 look.app:get_app`

the server is running and listening but when i try to access by the browser y get this error:
`TypeError: get_app() takes no arguments (2 given)`

I am using:
gunicorn3 (version 19.7.1)
Python 3.6.3

What i am doing wrong?

Regards.

**Comment by im-auld** [comment]
From the tutorial (scroll down from [here](https://falcon.readthedocs.io/en/stable/user/tutorial.html#refactoring-for-testability))

> The command to run the application is now:
> 
> `$ gunicorn --reload 'look.app:get_app()'`

**Comment by holic-cl** [comment]
Um, thanks for answer, i am very noob, but i am lerning.

It worked, thanks
