### ISSUE TITLE
Max file size.

### ISSUE THREAD

**Issue by Spawn** [falconry/falcon#1164]
When I try POST multipart/form-data with a file whose size >32 MB I got an 413 error: `Upload limited to 32 megabytes.` I did not find any information about maximum size of downloadable file in Falcon. Any ideas?

**Comment by kgriffs** [comment]
Hmm, that sounds like something related to your web server or settings or hosting provider rather than you Falcon app itself. The Falcon framework does not limit the request body length.

**Comment by kgriffs** [comment]
[Please reopen if we can help you further.]
