### ISSUE TITLE
Unexpected Internal Server Error

### ISSUE THREAD

**Issue by samuelrey** [falconry/falcon#1166]
I have an Item class defined inside of a separate file called user_resource.py.
```python
import falcon
from .user_repo import User


class Item(object):
    def on_get(self, req, res, username=None):
        try:
            user = User.get(User.username == username)    # using peewee
            res.content_type = falcon.MEDIA_JSON
            res.body = json.dumps(user.__dict__['_data'])
        except User.DoesNotExist:
            error_msg = {
                'ERROR': 'User not found: {}'.format(username)
            }
            res.body = json.dumps(error_msg)
            res.status = falcon.HTTP_404
```
I route requests to an instance of the Item class. 
```python
import falcon
from .user_resource import Item


api = application = falcon.API()
user_item = Item()
api.add_route('/users/{username}', user_item)
```
I finally run the server using gunicorn with this command - `gunicorn --reload -b 0.0.0.0:8000 'userservice.app'`. The server runs fine, except on occasion when I send requests to the endpoint.

When I try `GET /users/han%20solo` (who does not exist), I will sometimes get the appropriate 404 error & other times an Internal Server Error. 
Nothing appears in the terminal running the server. I don't know how to debug the problem & haven't found anything quite like my situation. Any help would be greatly appreciated!

**Comment by kgriffs** [comment]
Hi @samuelrey, it sounds like an unhandled exception is bubbling up out of your falcon app. You version of Gunicorn may not be logging errors to the console by default (see http://docs.gunicorn.org/en/stable/faq.html#why-i-don-t-see-any-logs-in-the-console). 

In terms of Falcon, one thing you could try is adding a custom error handler for the base ``Exception`` class and then either print/log the exception or enter the debugger via ``import pdb; pdb.set_trace()``. See also: http://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_error_handler

**Comment by samuelrey** [comment]
Hey @kgriffs, I found out why the error was slipping through the cracks! I had accidentally left an import of the sqlite.IntegrityError.  As of this moment, everything is working just fine! Thank you for the help!
