### ISSUE TITLE
Implement rfc5987?

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#119]
https://tools.ietf.org/html/rfc5987
http://stackoverflow.com/questions/8558662/detect-browser-support-of-rfc5987

**Comment by kgriffs** [comment]
Let's wait and see if anyone in the community requests this feature.

**Comment by vytas7** [comment]
We already support this for compatibility reasons when parsing the `Content-Disposition` header of a form part. As to other headers, it seems that the world has moved on, and today's web is mostly UTF-8 and JSON (and headers are sometimes still Latin-1).
