### ISSUE TITLE
Extend falcon.media.JSONHandler to support specifying a ``default()`` type handler

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1192]
Per [the docs](https://docs.python.org/3.6/library/json.html#basic-usage):

> If specified, *default* should be a function that gets called for objects that can’t otherwise be serialized. It should return a JSON encodable version of the object or raise a TypeError. If not specified, TypeError is raised.

Also consider providing a way to specify *object_hook* when deserializing to support round-tripping.

In either case, include a note in the docs that specifying one or both of these options will significantly reduce processing speed for JSON documents.

**Comment by jhildreth** [comment]
I think I'd like to take a shot at this one, if that's alright.
