### ISSUE TITLE
README.rst formatting is broken on PyPi for 1.4.0

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1204]
https://pypi.python.org/pypi/falcon/1.4.0 looks like plaintext markdown dump.

Looks like some tags in ``README.rst`` are not understood by their parser.

The previous https://pypi.python.org/pypi/falcon/1.3.0 renders correctly.

**Comment by kgriffs** [comment]
Thanks! There was a heading underline that was a few chars short. I'm working on adding a `readme_renderer` check to the build script to avoid this in the future.

See also: https://github.com/pypa/warehouse/issues/2170

**Comment by kgriffs** [comment]
[Fixed in 1.4.1]
