### ISSUE TITLE
Third party json support

### ISSUE THREAD

**Issue by hynek** [falconry/falcon#1206]
Congratulations on shipping 1.4!  I’ve noticed you’ve added direct support for ujson which I find unfortunate for at least three reasons:

1. It’s mostly abandoned: latest release was in 2016, latest commit almost a year ago.  Maintainers aren’t very responsive on the bug tracker.
1. It doesn’t allow for customising serialisation (`default` and `object_hook`) – and this is my biggest point.
1. It has/had some standards issues (I’ve lost the link to info on that and I’m too lazy to look for it – but I think the other reasons are enough :))

Personally I’ve come to use [python-rapidjson](https://pypi.org/project/python-rapidjson/) which is comparable in terms of performance, under active development, and supports `default` and `object_hook`.  Its only possible downside is that it only supports Python 3 – but hey, 2020 is looming. :)

***

I’ve looked how falcon implemented ujson and it seems like it’s just a protected imports.

Now, I could ask you to add another `import/except ImportError` block, but maybe this whole thing could be solved differently and more elegantly.  Maybe by allowing to parametrize dumps/loads functions when they are used?  I don’t know your code well enough but I suspect there could be a way to make everyone happy without adding support to everyone’s pet JSON library. :)

**Comment by kgriffs** [comment]
Thanks for the feedback and I agree. It would be great to have a more flexible approach and give everyone the ability to choose from any of a number of alternative JSON libraries. The danger of picking one, as you point out, is that it may stop being maintained, or may not support certain features one might need, etc. 

Let's explore dropping ujson in 2.0 and looking for a way to make alternative loads/dumps functions configurable. I don't think it would be too terribly difficult to make it happen.

**Comment by hynek** [comment]
oh and totally related to #1192 – I just forgot to link it :)

**Comment by kgriffs** [comment]
@mattgiles I really like mujson and would consider using it if you can get it to Production/Stable status. It would be especially great if it could detect PyPy (by checking for the presence of ``sys.pypy_version_info``, for example) and modifying what it loads accordingly.

**Comment by steven-upside** [comment]
@kgriffs What specifically do you think is required to get `mujson` to Production/Stable status? 

As indicated in the issue, `mujson` is very useful for me outside of falcon, and since I'm planning to add PyPy detection anyways--which you also expressed interest in--I figured it would make sense to see if I could take it all the way to `1.0`.

If you have a good idea of what's required to make it usable within falcon, I'll create a Pull Request resolving the issue I just opened on the `mujson` project.
If the author of the library does not respond to the PR, I'm willing to fork it and maintain that fork.

**Comment by mattgiles** [comment]
@kgriffs and @steven-upside I added support for PYPY and bumped the status / version for `mujson`. I note that as far as I can tell PYPY should just be using the standard library -- but I may be ignorant of ways to get better performance from third party libraries when using PYPY.

**Comment by kgriffs** [comment]
@mattgiles awesome, thanks! AFAIK that's the way to go with PyPy.

**Comment by mattgiles** [comment]
@kgriffs I'm happy to throw together a PR which would make use of `mujson` to handle third party json support. But I am interested in your thoughts on two fronts.

First, whether to require `mujson` outright or just replace the protected imports of `ujson`. I see both sides of this one. All else being equal, the latter option would definitely break/impair builds that install `ujson` today but not `mujson`.

Second, whether or not #1192 would be better addressed at the same time.
