### ISSUE TITLE
Add Response.expires to set the Expires header to a datetime instance

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1210]

**Comment by MichaelYusko** [comment]
@kgriffs Hello, I'm happy to solve the issue, but could you provide a little bit more details?

Thank you.

**Comment by alysivji** [comment]
Started to look into this, but looks like it has already been completed.

This issue is a duplicate of https://github.com/falconry/falcon/issues/1268 which was resolved by https://github.com/falconry/falcon/pull/1298

**Comment by kgriffs** [comment]
[closes]

**Comment by vytas7** [comment]
(Looks like we simply forgot to close this.)
