### ISSUE TITLE
testing.simulate_request allows not to modify the env

### ISSUE THREAD

**Issue by ghost** [falconry/falcon#1215]
The function "falcon.testing.client.simulate_request" of the testing module currently accepts multiple optional arguments that are written into the env, which is ultimately used in the simulated request. Other env options are fixed.

It would be great if this function would accept an environment created by testing.create_environ. 

This way one could simulate e.g. ...

- ... requests from different hosts 
- ... requests with SSO

**Comment by vytas7** [comment]
That is a very valid issue, +1 from me as well.

An possible ugly workaround, at least I have gone that way, would be to monkey-patch environment creation:

```
    def override_environ(update):
        def wrapper(*args, **kwargs):
            env = original_create_environ(*args, **kwargs)
            env.update(update)
            return env

        # Save the original function since it will be temporarily patched
        original_create_environ = falcon.testing.helpers.create_environ
        return wrapper
```

Then ``mock.patch`` ``falcon.testing.helpers.create_environ`` with this one.

**Comment by kgriffs** [comment]
This sounds like a reasonable feature to add. I will schedule it for 2.x. If anyone is interested in implementing this for 2.0 or 2.1, feel free to submit a PR and we'll take a look. Thanks!

**Comment by vytas7** [comment]
This is done now, leaving the issue open as a checklist item to also mention this one in ``CHANGES.rst``.

**Comment by kgriffs** [comment]
Usually I just review the commit log to make sure everything is enumerated in CHANGES.rst in the process of finalizing a new release, so it should be safe to close this.

**Comment by vytas7** [comment]
Aha, thanks, closing then!
