### ISSUE TITLE
printenv: write error: Disk quota exceeded

### ISSUE THREAD

**Issue by kaikaixinxi** [falconry/falcon#1218]
i run my project with fc_run.py fc_run.cfg  , my  screen display the error information below:

[INFO]!bkill -J Pf33381c90ccbbc
Job <Pf33381c90ccbbc> is not found
[INFO]!bkill -J P7a1b7276c6771f
Job <P7a1b7276c6771f> is not found
[INFO]!bkill -J Pcd100ecb7ab653
Job <Pcd100ecb7ab653> is not found
Traceback (most recent call last):
  File "/YZGROUP/genewiz/public/app/FALCON-integrate/fc_env/bin/fc_run.py", line 9, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run.py')()
  File "/YZGROUP/genewiz/public/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 504, in main
    main1(argv[0], args.config, args.logger)
  File "/YZGROUP/genewiz/public/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 150, in main1
    input_fofn_plf=input_fofn_plf,
  File "/YZGROUP/genewiz/public/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 259, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/YZGROUP/genewiz/public/app/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/YZGROUP/genewiz/public/app/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 344, in _refreshTargets
    failures, len(unsatg)))
Exception: We had 580 failures. 581 tasks remain unsatisfied.

 0-rawreads/job_0758/pwatcher.dir/stderr ：
   printenv: write error: Disk quota exceeded
   + python2.7 -m pwatcher.mains.fs_heartbeat --
   directory=/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/0-rawreads/job_0758 --
  heartbeat-
  file=/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/mypwatcher/heartbeats/heartbeat-
  Pa896ef4f166954 --exit-
  file=/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/mypwatcher/exits/exit-
  Pa896ef4f166954 --rate=10.0 /bin/bash run.sh
   Namespace(command=['/bin/bash', 'run.sh'], 
  directory='/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/0-rawreads/job_0758', 
  exit_file='/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/mypwatcher/exits/exit-Pa896ef4f166954', 
  heartbeat_file='/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/mypwatcher/heartbeats/heartbeat-Pa896ef4f166954', rate=10.0)

  cwd:'/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/0-rawreads/job_0758'
  hostname=njblade08-14.yzgroup.local
  
  heartbeat_fn='/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/mypwatcher/heartbeats/heartbeat-Pa896ef4f166954'
  exit_fn='/YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/mypwatcher/exits/exit-Pa896ef4f166954'
  sleep_s=10.0
  before setpgid: pid=28646 pgid=28635
 after setpgid: pid=28646 pgid=28646
  In cwd: /YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/0-rawreads/job_0758, Blocking 
  call: '/bin/bash run.sh'
   cd /YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/0-rawreads/job_0758
  + cd /YZGROUP/genewiz/genewiznj/SMRT_Denovo/N05311_HGAP/0-rawreads/job_0758
  bash task.sh
  + bash task.sh
  sort: write error: Disk quota exceeded

but my quota have no limit , please help me .

**Comment by kaikaixinxi** [comment]
we find the answer, my home dir have 500M quota, but falcon will write some file in home dir , it exceed 800M , so it runs wrong.

**Comment by vytas7** [comment]
Hello @kaikaixinxi !

I am pretty sure you have happened to report against a wrong project.

Judging by the errors and the paths reported, you are most likely using FALCON, https://github.com/PacificBiosciences/FALCON , tools for genetics.

Consider reporting the problem against the said project. This *Falcon* is a web framework.
