### ISSUE TITLE
Perform same task for multiple users once with locking/caching

### ISSUE THREAD

**Issue by marcusmercier** [falconry/falcon#1222]
**Is there a way to respond to the same, long running, CPU intensive task on the same endpoint/URL only once when there are multiple requests to it?** For Twisted web I had to implement custom queuing, locking, caching functionality to accomplish this with the use of threads. Maybe there is a better way to do this with Falcon?

_I recently came across Falcon framework to replace Twisted Web. I read the docs and searched for keywords, but could not find what I needed._

**Comment by kgriffs** [comment]
Hi @marcusmercier, sorry for not getting back to you on this until now. As you've probably found, Falcon does not currently support this out of the box. You might try bringing up the topic in https://gitter.im/falconry/user to see if any other community members have implemented something similar and would be able to share some insights.
