### ISSUE TITLE
req_options.auto_parse_form_urlencoded converting string[] of length 1 to string

### ISSUE THREAD

**Issue by CoreyCole** [falconry/falcon#1229]
WARNING: I'm a falcon noob. I have auto form parsing enabled:
```python
APP = falcon.API()
APP.req_options.auto_parse_form_urlencoded = True
```

I have a route that parses a JSON object via a POST request from my frontend
```javascript
{
  arr1: ['one-element'],
  arr2: ['two', 'elements']
}
```

When I print out `req.params` in my `on_post` handler...
```python
def on_post(self, req, resp):
  self.info_logger.info('POST call with params %s', req.params)
```
...I see
```bash
{ arr1: 'one-element', arr2: ['two', 'elements'] }
```

Is this the intended behavior? Or am I missing something / is there a different way I should be accessing `req.params`?

In the docs, Request.params is described:
> dict – The mapping of request query parameter names to their values. Where the parameter appears multiple times in the query string, the value mapped to that parameter key will be a list of all the values in the order seen.

So I guess `arr1` has only seen 1 value when the stream is parsed? This means it is not converted into a list?

Note: I'm on falcon==1.4.1

**Comment by CoreyCole** [comment]
If this clarification helps, I'm using angular on the frontend passing my JSON params as [HttpParams](https://angular.io/api/common/http/HttpParams)

```javascript
this.http.post(`${this.apiUrl}/routeName`, {}, { params: paramData });
```

These are of type
> An HTTP request/response body that represents serialized parameters, per the MIME type application/x-www-form-urlencoded

**Comment by CoreyCole** [comment]
Ah, I think I understand. In the docs, Request.params is described:
> dict – The mapping of request query parameter names to their values. Where the parameter appears multiple times in the query string, the value mapped to that parameter key will be a list of all the values in the order seen.

The actual URL with the query params being passed looks like
```
http://localhost:5000/routeName?arr1=one-element&arr2=two&arr2=elements
```

So I guess `arr1` has only seen 1 value when the stream is parsed? This means it is not converted into a list? My hacky fix is:

```python
if 'arr1' in req.params:
      req.params['arr1'] = [req.params['arr1']]
```

Is there a more elegant solution to this?

**Comment by vytas7** [comment]
I would say you did a fair investigation of this yourself.

If you only have a very limited amount of params with expected key names known in advance, another option is to use Falcon's ``get_param()`` and friends, including ``get_param_as_list()`` which seems to be of interest in your case.

For instance, if you saved the snippet below as ``test.py``, and ran it with ``gunicorn test:api``

```python
import falcon
import falcon.uri


class ParametersTest(object):

    def on_post(self, req, resp):
        tests = []
        tests.append(['params', req.params])
        tests.append(['get_param', req.get_param('arr1')])
        tests.append(['get_param_as_list', req.get_param_as_list('arr1')])

        resp.media = tests


api = falcon.API()
api.req_options.auto_parse_form_urlencoded = True
api.add_route('/', ParametersTest())

```

Then ``POST``ing some HTTP form like in your example gives

```http
http --form POST localhost:8000 arr1=one-element arr2=two arr2=elements
HTTP/1.1 200 OK
Connection: close
Date: Fri, 09 Mar 2018 17:51:29 GMT
Server: gunicorn/19.7.1
content-length: 127
content-type: application/json; charset=UTF-8

[
    [
        "params", 
        {
            "arr1": "one-element", 
            "arr2": [
                "two", 
                "elements"
            ]
        }
    ], 
    [
        "get_param", 
        "one-element"
    ], 
    [
        "get_param_as_list", 
        [
            "one-element"
        ]
    ]
]

```

**Comment by CoreyCole** [comment]
Ah, `get_param_as_list` is what I need to solve this most elegantly. Thanks!

**Comment by vytas7** [comment]
Another option would be not using ``auto_parse_form_urlencoded``, and parsing the URL-encoded payload directly.

Let us rework our example slightly:

```
try:
    from urlparse import parse_qs  # PY2
except ImportError:
    from urllib.parse import parse_qs  # PY3

import falcon
import falcon.uri


class ParametersTest(object):

    def on_post(self, req, resp):
        body = req.stream.read()
        if isinstance(body, bytes):
            body = body.decode()

        resp.media = parse_qs(body)


api = falcon.API()
api.add_route('/', ParametersTest())
```
