### ISSUE TITLE
Request media access fails for empty body when called twice

### ISSUE THREAD

**Issue by nav-agarwal** [falconry/falcon#1234]
I am using req.media to fetch post request's body. If I pass empty dictonary in json_data, calling req.media twice results in error message:

> '{"title": "Invalid JSON", "description": "Could not parse JSON body - No JSON object could be decoded"}'

Bug is present in https://github.com/falconry/falcon/blob/master/falcon/request.py line 952. In case of empty dict as body, self._media will always return False. As falcon uses req._media cache for subsequent interactions, this will fail.

Correct behavior would be to return empty dict.

Possible fix: 
- if self._media:
+ if self._media is None:

Code:
Server
```
import falcon


class Test(object):
    def on_post(self, req, resp):
        # b = req.bounded_stream.read()
        # print b
        # a = req.stream.read()
        # print a
        print req.content_length
        a = req.media
        print a
        b = req.media
        print b
        resp.body = b


app = falcon.API()
app.add_route('/', Test())
```
Client
```
 resp = requests.post('http://localhost:8000', json={})
resp.content
```

**Comment by nav-agarwal** [comment]
Any update?

**Comment by kgriffs** [comment]
Hi @nav-agarwal, thanks for the bug report. I was able to reproduce and verify the problem. The following demonstrates the fix:

```py
import falcon


class Request(falcon.Request):
    @property
    def media(self):
        if self._media is not None:
            return self._media

        handler = self.options.media_handlers.find_by_media_type(
            self.content_type,
            self.options.default_media_type
        )

        # Consume the stream
        raw = self.bounded_stream.read()

        # Deserialize and Return
        self._media = handler.deserialize(raw)
        return self._media


class Test(object):
    def on_post(self, req, resp):
        m1 = req.media
        m2 = req.media

        assert m1 is m2

        resp.media = m2


app = falcon.API(request_type=Request)
app.add_route('/', Test())
```
I'll schedule this to be fixed in the next release.

**Comment by vytas7** [comment]
Note that the fix does not work if the incoming JSON is ``null``, for instance, running something in line with

```python
requests.post('http://localhost:8000', data='null', headers={'Content-Type': 'application/json'})
```

I guess there are two possible ways to tackle this:

* Use some private singleton object instead of ``None``
* Ignore this as a super edge case

**Comment by nav-agarwal** [comment]
@vytas7 : Agreed it wouldn't work with your example. 

This is not super edge case. If you use middleware and validate your data against req.media and then pass req.media to library, this will hit every time.

One more approach would be to keep a flag if data has already been consumed from stream, don't read it again and return whatever is present in "media".

**Comment by vytas7** [comment]
I meant sending null as JSON payload was an edge case in the light of the proposed solution, your report is otherwise very valid.

**Comment by DmitriiTrofimov** [comment]
Probably it decided in #1311

**Comment by vytas7** [comment]
Note to self: recheck if @DmitriiTrofimov 's changes fixed this (or enabled a cleaner fix).
