### ISSUE TITLE
Did not find in the docs so I am asking here. How can I "abort/skip straight to the response" a request while in a middleware method like the "process_request/process_resource"?

### ISSUE THREAD

**Issue by phtdacosta** [falconry/falcon#1237]

**Comment by phtdacosta** [comment]
Until now I made no good progress finding any solid solution. The only way to abort a request in middleware before it reach any endpoint (route function) is manually raising some exception like:

    def process_request(self, request, response):
        raise Exception('Will not let it reach any route!')

But this way is ugly as hell, and **will always send a response with the 500 Internal Server Error no matter the status number you set before raising the error**...

**Comment by nZac** [comment]
Hi @phtdacosta! When you say "skip strait to the response" do you mean you want to skip all future middleware and go to the resources which that route points to, OR do you mean you want to not proceed any further?

If you would like to do the later, you might want to checkout out the available `HTTPError` exceptions. You can find them here: http://falcon.readthedocs.io/en/stable/api/errors.html

**Comment by phtdacosta** [comment]
Thank you @nZac! That's exactly what I'm looking for. I want to say sorry for the simple question, but my background with web development in python was just using Flask, and there, just returning inside the function was enough to force the response.

For real, maybe with Flask it's more spontaneous for beginners, but with Falcon and it's proper classes is a lot more elegant and professional way to code web services.

Anyways, thank you again for pointing out what I should consult.

**Comment by vytas7** [comment]
Hi @phtdacosta !
Sorry for a bit of necro-bumping, but I just wanted to let you know that this feature has been implemented in Falcon 2.0 in form of [Response.complete](https://falcon.readthedocs.io/en/latest/api/request_and_response.html#falcon.Response.complete).

At the time of writing, Falcon 2.0 is in alpha, and we are hoping to release the first beta really soon.

cheers
Vytas
