### ISSUE TITLE
Misleading doc string in JSON media handler

### ISSUE THREAD

**Issue by sciatro** [falconry/falcon#1243]
Looks like the [JSON media handler's doc string](https://github.com/falconry/falcon/blob/3ba0412acee1eaddf36b9a35d9859fd43798e4a9/falcon/media/json.py#L11) (``"""Handler built using Python's :py:mod:`json` module."""``) is incorrect since ``falcon.util.json`` [could be ujson](https://github.com/falconry/falcon/blob/3ba0412acee1eaddf36b9a35d9859fd43798e4a9/falcon/util/__init__.py#L24).

Looks like it became incorrect in 24d51a4808e72d14108d61c2a089158cb6757435.

**Comment by kgriffs** [comment]
Good catch, we'll get that fixed!

**Comment by Nateyo** [comment]
This looks completed and already in master. Just needs CHANGES.rst I guess?

**Comment by vytas7** [comment]
It seems that this has been rectified in the linked #1303 .

It might need a yet another update after https://github.com/falconry/falcon/issues/1206 , but lets handle it in that issues depending on the decisions made.
