### ISSUE TITLE
docs: Add a warning to the Request.path docstring re url encoding

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1259]
If the original path requested by the client was url-encoded, it will be decoded before being returned by `Request`'s `path` attribute. Therefore, if this attribute is to be used by the app for any upstream requests (say, when implementing a proxy), any non-url-safe characters in the path must be url-encoded back, before making the request. Not all HTTP client libraries handle this automatically.

**Comment by danilito19** [comment]
Hello! Was looking to contribute to this issue, but I believe it's already been addressed [here](https://github.com/falconry/falcon/blob/master/falcon/request.py#L178). Should this issue be closed?

**Comment by vytas7** [comment]
Indeed, this has already been tackled by @brooksryba in https://github.com/falconry/falcon/pull/1374 !
