### ISSUE TITLE
Change the default value of RequestOptions.keep_blank_qs_values to True

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1274]
At the same time, modify the `blank_as_true` kwarg of `Request.get_param_as_bool()` to default to`True` instead of `False`.

**Comment by DmitriiTrofimov** [comment]
Solved in #1316

**Comment by foresmac** [comment]
I'm not sure I understand why a blank query param should default to `True`; this seems counter-intuitive, especially since most languages interpret an empty string as comparable to `False`, including Python itself.

**Comment by DmitriiTrofimov** [comment]
In issue context `True` is default value for option but not for empty value. If `RequestOptions.keep_blank_qs_values` is `True` then empty values will be provided to `Request.params`, when `RequestOptions.keep_blank_qs_values` is `False` consume empty values.

**Comment by foresmac** [comment]
I'm not 100% sure I understand your explanation, but whether blank values should be thought of as `True` for a boolean seems entirely separate from the idea of whether or not to retain blank values from a query string.

 It just seems to me like this is going to cause more confusion to link the two this way, especially if the query param itself is actually meant to be thought of as strictly true/false. If someone wants to have the existence of an query param merely thought of as a switch, they could opt-in to that behavior with the `blank_as_true`, but it seems like `if 'param' in req.params` seems like a better, more explicit test. I think most people are pretty used to empty string being `false-y` in Python, so the opposite being the default behavior here seems pretty confusing.

**Comment by DmitriiTrofimov** [comment]
Sorry, I thought you were asking about `RequestOptions.keep_blank_qs_values`.

Empty values in bool context can mean that it present in the query parameters and legally represent them as `True`.
