### ISSUE TITLE
Add the method append_error_handler for falcon.API?

### ISSUE THREAD

**Issue by xgfone** [falconry/falcon#1308]
`falcon.API` only has the method `add_error_handler`, which will insert the exception handler to the front. And `falcon.API` also adds the default error handlers for `falcon.HTTPError` and `falcon.HTTPStatus` automatically.

If the user want to add the error handler for `Exception`, it will ignore the default error handlers, which may not be what the user want.

By adding the method `append_error_handler()` for `falcon.API`, it will allow the user to append the error handler. For example,
```python
app = falcon.API()
app.append_error_handler(Exception, handler)
```

At the moment, When `falcon.HTTPError` and `falcon.HTTPStatus` occur, it will use the default error handlers. And for other exceptions, it will use the `Exception` handler.

------

Updated:

If no `append_error_handler`, in order to do that, the user must write as the follow,
```python
app = falcon.API()
app.add_error_handler(Exception, handler)
app.add_error_handler(falcon.HTTPError, app._http_error_handler)
app.add_error_handler(falcon.HTTPStatus, app._http_status_handler)
```

`app._error_handlers` will has five exception handlers, `[(falcon.HTTPStatus, self._http_status_handler), (falcon.HTTPError, self._http_error_handler), (Exception, handler), (falcon.HTTPStatus, self._http_status_handler), (falcon.HTTPError, self._http_error_handler)]`.

It's NOT GOOD!

**Comment by vytas7** [comment]
@xgfone you are right in saying that error handlers could be more user-friendly.

The way I (and I think @jmvrbanac was recommending this way too) normally go with the current version of Falcon (2.0) is along the lines:
```python
# inside the Exception handler
if isinstance(ex, (falcon.HTTPError, falcon.HTTPStatus)):
    raise
```
There is a special clause catching errors raised by errors handlers, and `HTTPErrors` are understood there.

We have been discussing these error handling issues in general during the last PyCon US '19, and one possible way to improve this is attempting to sort handlers by their inheritance: https://github.com/falconry/falcon/issues/1514

Our contributor @csojinb has even submitted a PR implementing this idea: https://github.com/falconry/falcon/pull/1603
We hope to get the PR backlog merged soon-ish, which would hopefully also improve our exception handling in cases like you're describing here.

I'm going to thus close this issue in favour of https://github.com/falconry/falcon/issues/1514. Do not hesitate to post your ideas/suggestions/thoughts on that issue!

**Comment by csojinb** [comment]
I can try to get this PR cleaned up this weekend
