### ISSUE TITLE
fallback_filename in api.add_static_route() always served as application/octet-stream

### ISSUE THREAD

**Issue by snobu** [falconry/falcon#1313]
When `fallback_filename` is defined,

```python
api.add_static_route('/', '/absolute/path', downloadable=False,
        fallback_filename='index.html')
```

`suffix` always comes up empty which results in the fallback file being sent over the wire as `application/octet-stream` (browser prompts for file download instead of rendering the HTML).

https://github.com/falconry/falcon/blob/master/falcon/routing/static.py#L109

The caveman-simple fix would be:

<s>

```python
        # suffix = os.path.splitext(file_path)[1] # comes up empty
        suffix = os.path.splitext(self._fallback_filename)[1]
        resp.content_type = resp.options.static_media_types.get(
            suffix,
            'application/octet-stream'
        )
```
I guess this completely skips the normalization logic so a more elegant fix should be in place.

</s>

^ Scratch that, the solution needs a bit more research.

I could take a short at a PR once you validate these findings.
I'm on Python 3.5.2, Linux with the current master HEAD as my falcon module.

**Comment by vytas7** [comment]
Fixed in https://github.com/falconry/falcon/pull/1348 (see also https://github.com/falconry/falcon/pull/1314, https://github.com/falconry/falcon/pull/1325 & https://github.com/falconry/falcon/pull/1341).
