### ISSUE TITLE
running falcon without wsgi

### ISSUE THREAD

**Issue by kaldown** [falconry/falcon#1319]
How to run falcon app with no any wsgi ?
There is no example in documentation, and no hint telling is it even possible

**Comment by DmitriiTrofimov** [comment]
Maybe it help you https://docs.python.org/2/library/wsgiref.html#module-wsgiref.simple_server
```python
import falcon
from wsgiref import simple_server

if __name__ == "__main__":
    app = falcon.API()
    server = simple_server.make_server('127.0.0.1', 8000, app)
    server.serve_forever()
```

**Comment by kaldown** [comment]
Thanks
