### ISSUE TITLE
JSON validator - change exception class

### ISSUE THREAD

**Issue by Sirtea** [falconry/falcon#1320]
I found a little bit harder to override the exception thrown by falcon.media.validators.jsonschema.validate(). When I raise an instance of HTTPBadRequest is really easy to override it to get my custom error message.

Looking at the code it seems like the exception class is hardcoded, so it will always be the pristine HTTPBadRequest that comes with falcon, not mine, so the error is not myapi-compilant.

¿Is there another way of doing this by not duplicating the validator code to raise my own exception?

**Comment by jgirardet** [comment]
You can rewrite the decorator.
Just copy past it and change HTTPBadREquest by MYHTTPCOmpliantBadREquest

or maybe propose a PR adding, an optional argument "CustomError" to the decorator.
