### ISSUE TITLE
How to get the numeric HTTP status?

### ISSUE THREAD

**Issue by JamesMessinger** [falconry/falcon#1326]
The `Response`, `HTTPError` , and `HTTPStatus` classes all have a `status` property, but it's a string (e.g. `"404 Not Found"`) which makes it difficult to do comparison checks (e.g. `if resp.status >= 400`). 

**What is the recommended way of getting the _numeric_ status?**  

There's a [`get_http_status()` utility function](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.get_http_status), but it does the exact opposite.  It accepts a numeric status and returns the status string.

Perhaps there could be a `get_http_status_number()` utility function?  Or, even better, a new property on the `Response`, `HTTPError`, and `HTTPStatus` classes.

**Comment by DmitriiTrofimov** [comment]
This is should also works:
```python
import falcon

if resp.status >= falcon.HTTP_400:
    # do somthing
```

Numeric HTTP status you can get something like this:
```python
http_code = int(resp.status[:3])
```
You may use custom response type with additional property `code` for extracting http code from `status`.

**Comment by zubairakram** [comment]
can be solved by using tuples instead of string.

```python
# before
HTTP_100 = HTTP_CONTINUE = '100 Continue'
# after
HTTP_100 = HTTP_CONTINUE = (100, 'Continue')

# status code for comparison
>>> HTTP_100[0]
100

# status code description
>>> HTTP_100[1]
'Continue'
```

**Comment by vytas7** [comment]
Falcon 3.0 will support [http_status_to_code](https://falcon.readthedocs.io/en/3.0.0a1/api/util.html#falcon.http_status_to_code) exactly as described by @JamesMessinger .
