### ISSUE TITLE
ImportError: cannot import name UserDict

### ISSUE THREAD

**Issue by iron2414** [falconry/falcon#1328]
I have the same issue, what is described here:
 https://github.com/falconry/falcon/issues/1139

However i cannot seem to solve the problem. Could anyone tell me step by step what am i supposed to do when i have a fresh ubuntu install? I can't even import falcon.

Heres what i did on the fresh ubuntu:
apt install python-pip
apt install python3-pip
pip3 install gunicorn
pip3 install falcon
And i modified the usr/local/bin/gunicorn file header to "#!/usr/bin/python3" so it will start my application in python3.
When i run gunicorn -c gunicorn_conf.py --reload test:app
i get the same error message. What am i doing wrong?

I Cant even run python3
>> import falcon

Because it gives me the same error

**Comment by TheMushrr00m** [comment]
Can you share more info please? What's your OS version? Python3 version?
If you try to import falcon from an interactive shell 
>>> import falcon

What's the output?

**Comment by vytas7** [comment]
Hi @iron2414 !
Are you still experiencing the described issue?

In addition to ideas by @TheMushrr00m , just to make sure, are you using ``virtualenv``, or just installing packages locally?

What do ``pip freeze`` and ``pip3 freeze`` say?

Also, if you are not using ``virtualenv``, note that newer ``pip`` versions (starting with 10.0.0 IIRC) do not play nicely with ``apt``-installed ones.

You may try removing  ``apt``-installed ``pip`` altogether, and bootstrapping it with [get-pip.py](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py) . And then either installing and creating a ``virtualenv``, or retrying the same as above. You may also try ``pip install --upgrade falcon``.

**Comment by vytas7** [comment]
Hi again @iron2414 !
I'm going to close this now hoping you've found the culprit(s).

But do not hesitate to reopen or post a new question if you believe it was Falcon packaging issue! As said in my previous post, things like `pip freeze` and `pip -V` would be really helpful in trying to diagnose this.
