### ISSUE TITLE
perf: Revisit micro-optimizations

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1331]
Newer versions of 2.7.x and 3.x exhibit different performance characteristics vs. 2.6 and 3.4. Revisit micro-optimizations such as the following and adjust where it makes sense:

> #NOTE(kgriffs): Reference via self since that is faster than module global...

**Comment by vytas7** [comment]
Since the example above originates from my HTTPStatus experiments, I will split some of the improvements off in a separate PR.

**Comment by vytas7** [comment]
Resolved in the referenced PR.
