### ISSUE TITLE
Pybuilder and Falcon Test case

### ISSUE THREAD

**Issue by somaz80** [falconry/falcon#1336]
Hi,
I  am facing an issue when running Unit test simulation POST from Pybuilder console. It seems that req.stream fails in parsing at API end.

**Comment by nZac** [comment]
Hi @somaz80! We will need more information to help you. Some starter questions would be, what is the responder doing, can you share that code? Do you have any errors? Can you provider a working example?

It might be best to ask on the gitter.im channel (https://gitter.im/falconry/user).

**Comment by vytas7** [comment]
Hello @somaz80 !
Have you had a chance to look at @nZac 's questions? Or have you maybe resolved the issue yourself?

**Comment by nZac** [comment]
@somaz80, I am going to close this for now, if you can provide additional info please reopen it or hope on our gitter channel for assistance.
