### ISSUE TITLE
Resource level hook doesn't apply to suffixed methods

### ISSUE THREAD

**Issue by mumrau** [falconry/falcon#1351]
Hello,

I believe the title of the issue is pretty clear, a @falcon.before hook wouldn't apply to a suffixed method (on_get_suffix) handler while it would perfectly apply to the classic legacy handlers (on_get, on_post,...).
Consider that piece of code:
```python
import json
from wsgiref import simple_server
import falcon

def hook(req, resp, resource, params):
    print("Inside the hook for resource: ", type(resource))
    resp.body = json.dumps("HOOKED")

@falcon.before(hook)
class HookedResource:
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
    def on_get_suffix(self, req, resp):
        resp.status = falcon.HTTP_202

class HookedMethod:
    @falcon.before(hook)
    def on_get_suffix(self, req, resp):
        resp.status = falcon.HTTP_202

api = falcon.API()

hkr = HookedResource()
hkm = HookedMethod()

api.add_route("/hooked_resource", hkr)
api.add_route("/hooked_resource_suffix", hkr, suffix="suffix")
api.add_route("/hooked_method_suffix", hkm, suffix="suffix")

if __name__ == '__main__':
    httpd = simple_server.make_server('127.0.0.1', 8000, api)
    httpd.serve_forever()
```

The hooked_resource route (resource level hook) would have a functional hook, but the hooked_resource_suffix won't.
Nevertheless, the hooked_method_suffix (method level hook) will behave correctly, which gives a lot of hope in terms of implementation effort for a fix.

I hope I have been clear enough.

Falcon still rocks!

EDIT:
I believe this code is responsible in https://github.com/falconry/falcon/blob/master/falcon/hooks.py :
```python
    def _before(responder_or_resource):
        if isinstance(responder_or_resource, six.class_types):
            resource = responder_or_resource

            for method in COMBINED_METHODS:
                responder_name = 'on_' + method.lower()
```
It only iterates through COMBINED_METHODS which relates to the default responders which are constants.
Maybe it would be worth to iterate through every functions of the class and select starting with `on_HTTP_VERB_` as well.
On handlers registrations, we could also register in the class an attribute like "additional_responders" or something like that. I peeked at the source code but can't really take any decision cause I'm not fully aware of the guidelines in terms of implementation.

**Comment by vytas7** [comment]
Thank you for the detailed report! It seems this has been indeed overlooked when adding suffixed resources, well spotted.

We will take a look at this as soon as possible. If we suggested the preferred solution path, could you consider materializing the above into a PR?

**Comment by Mumrau** [comment]
@vytas7 Might we give this a little inertia? I don't wanna be a "pusher", but I'm using my ""PR"" (#1352) (quotes to underline the fact that this is just code, not a proper PR with regressions-tests and such) in production and it's working quite well, but I don't wanna fall behind master.

In addition, might this issue be flagged appropriately? I don't think I have the right to do that but it will probably give it more visibility.

**Comment by vytas7** [comment]
No worries, it is fine to bump this up since it is important to fix this bug in the new functionality, particularly if we go to the interim 1.5 release before 2.0.

Adding unit/regressions would help greatly, that is true. I have just not got the time to do that yet :grimacing: 

Regarding falling behind master, you can always keep the PR updated by merging master into the branch ;)

**Comment by Mumrau** [comment]
Oh I haven't heard anything about that possible "interim" release.
I'll try to give it a deeper look (maybe this week-end), I just got lost when trying to dig in _quickly_ in the tests code.

Yup, but to be honest, I'm building docker images and I would like to "not care" when building my images by just pulling master and being confident into The Work :blush:  .
