### ISSUE TITLE
Prefer exact match without parameters to match with extra parameters.

### ISSUE THREAD

**Issue by suola** [falconry/falcon#1367]
If server supports both 'type/subtype' and 'type/subtype;param=foo', a request which accepts 'type/subtype' should be served with 'type/subtype'. Currently the extra parameter is not taken into account when determining the preference of the two types, and preference is selected by order of the types.

Relevant PR in mimeparse:

https://github.com/dbtsai/python-mimeparse/pull/36

**Comment by vytas7** [comment]
Indeed, that sounds like a logical suggestion.

FWIW, we vendored `python-mimeparse` into Falcon as part of the 2.0 release as it was the last dependency.
In that light, a question arises what to do with your PR if we agree to go ahead with it. Maybe we should ask @dbtsai to take over maintenance of the project :thinking: Or whether we should fork our version.

**Comment by vytas7** [comment]
Note that I'm reluctant to label this as a breaking change, as we don't seem to provide exact guarantees how subtypes are chosen.

**Comment by vytas7** [comment]
Related:
* Vendoring `python-mimeparse` (implemented as of Falcon 2.0) https://github.com/falconry/falcon/issues/1420
* Discussion re contributing back to `python-mimeparse` / its maintenance https://github.com/falconry/falcon/issues/1183

**Comment by vytas7** [comment]
@suola I know this has taken us a long time, but the issue has finally been fixed in 4.0.0.
See the description of the new algorithm here: [`falcon.mediatypes.quality()`](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.mediatypes.quality).
