### ISSUE TITLE
Accept nullable values as input in parameters in Request.get_param_as_*

### ISSUE THREAD

**Issue by dannyhajj** [falconry/falcon#1370]
Currently, the `get_param_as_*` functions don't allow null values as input. I think there should be an extra parameter to those functions which we would use to allow null value as input.

Example, consider I have the following user resource:

```javascript
{
    "first_name": "John",
    "last_name": "Doe",
    "age": 18
}
```

I want to implement a `PATCH` endpoint which allows a frontend application to update one or more parameters. The `age` parameter is not required, and we want to allow users to unset it.

Normally, the frontend would need to send a request like the following:

```
PATCH /user/current
{
    "age": null
}
```

However, if I use the `Request.get_param_as_int("age")` method, this method would raise an `HTTPInvalidParam` exception because `null` is not actually a number.

Would it be possible to implement a functionality similar to the following?
```
Request.get_param_as_int("age", required=False, nullable=True)
```

**Comment by anekix** [comment]
@dannyhajj , Doing so would make the API more confusing. if you know a param might be `null` value, why call it with a function that returns an `int`? 
Instead,

1. first get the value of `age` param 
2. Check if its `null` ? if so do the actions you wanted.

a `null` value being returned in this case would also make someone hard to reason about it when the  function name is clearly `get_param_as_int()`.

Things like these are better when checked explicitly imho.

**Comment by vytas7** [comment]
I would tend to agree with @anekix , adding support for arbitrary values in `get_param_as_int` would actually make it somewhat less `_as_int`, so to say.

@dannyhajj Normally it is more common to accept `PATCH` changeset as a JSON payload, although that is of course up to you.

@dannyhajj With JSON payload in mind, could [`Request.get_param_as_json`]
(https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.get_param_as_json) actually fit your bill almost out of the box?
```python
import falcon


class User:

    def on_get(self, req, resp):
        resp.media = {'age_from_query': req.get_param_as_json('age')}


app = falcon.API()
app.add_route('/user/current', User())
```
You would probably need to add some validation for non-`int` values though.

**Comment by dannyhajj** [comment]
I agree @vytas7. I was assuming that `get_param_as_int` would work on the request body. Which is not the case.

My initial proposal is wrong. Thanks for the feedback though!
