### ISSUE TITLE
Why only '+' is converted to space and no other delimiters are taken care

### ISSUE THREAD

**Issue by nsonic001** [falconry/falcon#1371]
https://falcon.readthedocs.io/en/stable/user/faq.html#why-are-characters-in-my-params-being-converted-to-spaces

Why don't give options to handle delimiter needs to convert or not or which delimiters should be parsed to what value. 

I can raise a PR if that is valid, As Pyramid doesn't convert '+' to space and all. Why should Falcon ?

**Comment by vytas7** [comment]
Hi @nsonic001 !
The FAQ item you are linking to does, IMHO, a pretty good job explaining this framework behaviour choice.

On the other hand, yeah, this could probably be made configurable. I'll mark your proposal as such.

FWIW, note that [`parse_qs()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.parse_qs) in the Python std lib behaves the same way, decoding pluses to spaces.

**Comment by vytas7** [comment]
I'm going to close this proposal as it hasn't generated much interest.

Falcon only converts `+` to space when parsing the query string to [params](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Request.params), however, the original query string is preserved unmodified as [`req.query_string`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Request.query_string). So the recommended workaround is to use another query string parsing library to parse `req.query_string` manually.
