### ISSUE TITLE
Routes added to add_sink override static routes added with add_static_route

### ISSUE THREAD

**Issue by johnnyman727** [falconry/falcon#1372]
Hi Falcon team,

Thanks for all your hard work. I ran into an issue today when I tried to make use of the `add_static_route` method. 

Our project uses `add_sink` to implement a custom handler for requests with no corresponding handler. However, that `add_sink` function would gobble up any requests that we intended to be handled by the static route:

```py
api.add_static_route('/static', valid_static_file_path) # Would never get called
api.add_sink(unmatched_route_handler) # Would always swallow calls to assets at `/static/WHATEVER`
```
The case was the same whether the static route was added before or after the sink.

I would expect that if a static route is added, that resource path is excluded for any sink handlers.

My workaround for now was to basically use a regex on the sink to exclude the static path:
```
api.add_sink(unmatched_route_auth_wrapper, '^((?!static).)*$')
```

**Comment by vytas7** [comment]
Hi @johnnyman727 !
And sorry for the somewhat delayed response... better late than never, hopefully.

The documentation states that
> If **no route** matches a request, but the path in the requested URI matches a sink prefix, Falcon will pass control to the associated sink, regardless of the HTTP method requested.

A static route is also a route, so it does sounds like a bug, either in logic or documentation.

**Comment by nZac** [comment]
@vytas7 I would think a static route would take priority. 

Looking at [`_get_responder`](https://github.com/falconry/falcon/blob/master/falcon/app.py#L841-L855) it is rather obvious that a static route is taken after a sink. Since that code is so close in proximity I wonder if it was by choice. [Here is the commit](https://github.com/falconry/falcon/commit/c17372fa34e6488a9222a51a6659fbbec0bef3b3#diff-d2bd49ba8f513e9a9c10a3d30a2919eeR615-R621). This would be a breaking change if we reverse that now. 

@kgriffs, when the static route work was being done was it intentional to have a sink take precedence?

**Comment by vytas7** [comment]
@nZac Good point regarding a breaking change. I'll reschedule to the upcoming 3.0 release, and if it doesn't make it, we'll have to push to the next major version.

**Comment by CaselIT** [comment]
I actually don't mind the current logic.
I think at least some use cases for static_routing is as catch all after all the other routes have been tried. This is especially true when using [`fallback_filename`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_static_route)

Maybe a setting could be added to the App constructor to specify the precedence? This would enable moving it to back to `3.x`?

**Comment by vytas7** [comment]
I would vote on not over-complicating things too much by adding such a setting, however, it is true that we could afford making a non-breaking change in that case.

Agreed regarding the preference. FWIW, if I was given a task to build this alone, I would have probably gone for something like `add_file_sink()`, where it would add a specialized sink, but the order would be equal to other sinks (i.e., insertion order).

**Comment by CaselIT** [comment]
I think how the `App` interacts with the sinks and static files could bi unified to have a single for loop, The two arrays can be simply chained one way or the other according to the setting (this could also be done statically, each time a sink/static file route is added).

**Comment by CaselIT** [comment]
I've added a pr #1769 to invert the precedence of the sinks and static routes via a configuration parameter of the app.

By default the behavior is the same as the current one, so no breaking change was added
