### ISSUE TITLE
doc: How to properly return different kinds of responses?

### ISSUE THREAD

**Issue by cykerway** [falconry/falcon#1375]
The `Response` object has several fields that application authors can fill:

    media, data, body, stream, context

While I understand they are designed for different types of responses, it's not obvious from documentation how they conflict with one another and which has priority. I think the doc better adds some examples show different kinds of usage.

**Comment by anekix** [comment]
@cykerway . isn't it clear from the docs here? https://falcon.readthedocs.io/en/stable/api/request_and_response.html#response.
I can see all fields are very clearly defined.

**Comment by cykerway** [comment]
> @cykerway . isn't it clear from the docs here? https://falcon.readthedocs.io/en/stable/api/request_and_response.html#response.
> I can see all fields are very clearly defined.

I can see the fields are defined, but the doc doesn't say *how they conflict with one another and which has priority*. Furthermore, it's not very clear what `context` is and how to use it.

**Comment by vytas7** [comment]
Thanks for this very valid suggestion @cykerway !

On a related note, we have also created an umbrella issue to stress the fact that we are striving after better docs: https://github.com/falconry/falcon/issues/1393
