### ISSUE TITLE
jsonschema validation of a post request not working

### ISSUE THREAD

**Issue by anekix** [falconry/falcon#1376]
`jsonschema` validator is not working .

```python


user_schema = {
    "type":"object",
    "properties": {
        "name":{ "type": "string" },
         "address":{ "type" : "string" }
      }
}

from falcon.media.validators import jsonschema
class Users

    @jsonschema.validate(user_schema)
    def on_post(self, req, resp):
       print("called")


```
The above code seems to work fine when `address` param is missing in the request body.
request is sent using `POST`, **content-type** is `application/json`

**Comment by vytas7** [comment]
@anekix cool that you sorted it out!

I am closing this issue then, but I will check if we need a follow-up documentation issue: I understand the current [*See json-schema.org for more information on defining a compatible dictionary*](https://falcon.readthedocs.io/en/stable/api/media.html#validating-media) is not necessarily the most helpful for the user.

We have also create a new umbrella issue for better documentation: https://github.com/falconry/falcon/issues/1393
