### ISSUE TITLE
Avoid python built-in function names.

### ISSUE THREAD

**Issue by mikeylight** [falconry/falcon#1387]
After little discussion with @kgriffs in [falconry/dev](https://gitter.im/falconry/dev) channel, I decided to open ticket and follow-up it here.

> Hey, regarding to the answer https://stackoverflow.com/questions/9109333/is-it-bad-practice-to-use-a-built-in-function-name-as-an-attribute-or-method-ide
> 
> Maybe we should rename arguments of the https://github.com/falconry/falcon/blob/master/falcon/request.py#L1161 method? `min_=None, max_=None` instead of `min=None, max=None`?

Arguments which we will need to change[ line1](https://github.com/falconry/falcon/blob/master/falcon/request.py#L1161) , [line2](https://github.com/falconry/falcon/blob/master/falcon/request.py#L1232), these are just the ones I found.

cc @vytas7 @nZac

**Comment by mikeylight** [comment]
@vytas7 Hm, I found interesting paragraph https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments

The paragraph says

> If a function argument's name clashes with a reserved keyword, it is generally better to append a single trailing underscore rather than use an abbreviation or spelling corruption. Thus class_ is better than clss. (Perhaps better is to avoid such clashes by using a synonym.)

And I agree with you, `min_valu/max_value` sounds better.

**Comment by vytas7** [comment]
Reserved keywords ≠ builtins though. Reserved keywords are Python lexemes as the above mentioned **class**, **if**, **while** etc.

So there is (at least formally) nothing I could find in PEP8 wrt shadowing builtins with keyword parameters. Or furthermore, class method names, for that matter. From what I have seen, ``get`` / ``set`` is actually very common for method names among various caches, containers etc. Although ``set`` is clashing with the ``set`` builtin data type.

**Comment by mikeylight** [comment]
Yeah, in PEP8 nothing mentioned about builtins functions and etc. But in this case I agree with Raymond Hettinger, that all builtins functions and etc should be avoided.

Anyway, up to decide to you guys, it's just my opinion 🙂

**Comment by kgriffs** [comment]
I think we can take a pragmatic approach where we don't worry so much about things that are common/idiomatic (e.g., get/set), but then we do rename/avoid clashes in other cases. Scheduling for 2.0 since this work involves breaking changes.

**Comment by mikeylight** [comment]
I'll work on it.
