### ISSUE TITLE
[Roadmap 2019]

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1394]
### High Priority

We can not release 3.0 without completing these work items. Note that in the interest of keeping the 3.0 cycle as short as possible, we will aggressively postpone anything of Medium Priority or lower to 3.1+.

* ASGI+HTTP
* Native support for handling HTML Form posts
* Drop Python 2 support
* Drop Python 3.4 support
* Important breaking changes that didn't land in time for 2.0
* Fix any critical bugs found since 2.0

### Medium Priority

Parts of these can be postponed, but we will try to at least make significant progress for the 3.1 release.

* ASGI+WebSocket
* Improve educational resources and community outreach
* Improve performance with Cython and other optimizations
* Improve benchmark suite
* Fix any medium-severity bugs found since 2.0

### Low Priority

These can be postponed past 3.1 as needed.

* Nice-to-have cleanup work, such as migrating to HTTPStatus
* Come up with a more consistent interface for getting and setting response headers. For example, properties all work on raw string values only, and then add methods for higher-level manipulations (e.g., setting a range of bytes).
* Development web server (updraft)
* Fix any minor bugs found since 2.0

**Comment by kgriffs** [comment]
[Added note about benchmark suite[

**Comment by vytas7** [comment]
Roadmap progress is also tracked in this Gist: [Falcon 3.0 Roadmap](https://gist.github.com/kgriffs/a719c84aa33069d8dcf98b925135da39).

**Comment by kgriffs** [comment]
Closing this; I've noted the things that we weren't able to get to for 3.0.0
