### ISSUE TITLE
Official Support for Python 3.7 

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1405]
- [x] README
- [x] Docker images
- [x] Docs
- [x] Tox
- [x] Travis
- [x] setup.py

**Comment by soultech67** [comment]
@vytas7 is this something I can help with? I have a vested interest in 3.7.2 support...

**Comment by vytas7** [comment]
Sure, you are very welcome to help!

See also the checklist by @kgriffs above, that may be helpful in which changes are needed.

**Comment by vytas7** [comment]
@soultech67 have you had a chance to look at this?
I think this issue is important to get out for Falcon 2.0, so do not hesitate to ask for help, or you are constrained by time, could we join forces on this one?

**Comment by vytas7** [comment]
@soultech67 ping!
I am sorry if I am interrupting your work on this due to the imminence of Falcon 2.0. I'll try to quickly sketch something working provided there are no hidden rocks with 3.7.

**Comment by vytas7** [comment]
Done in https://github.com/falconry/falcon/pull/1437
