### ISSUE TITLE
How to implement redirection in auth_request?

### ISSUE THREAD

**Issue by czelsa** [falconry/falcon#1413]
hi, I have a problem with the redirecting in falcon.
I have configuration in ngnix: 
location / {
                auth_request /login_check;
               ...
}
location = /login_check {
               proxy_pass    localhost/login_check;
               ...
}

and I want to redirect to another page that will authenticate me (for example - I want to call some api)
def on_get(self, req, resp):
       ...
       raise falcon.HTTPMovedPermanently(location)

is it possible? or should I use something else?

**Comment by vytas7** [comment]
Hi @czelsa !
Yes, raising an instance of `HTTPStatus` is a perfectly fine way of implementing redirects.

See also:
* [How do I implement redirects within Falcon?](https://falcon.readthedocs.io/en/stable/user/faq.html#how-do-i-implement-redirects-within-falcon) (FAQ)
* [Redirection](https://falcon.readthedocs.io/en/stable/api/redirects.html#redirects) (Framework Reference)

I'm closing this issue hoping the above mentioned resources shed light on the topic, but do not hesitate to reopen or file a new issue if needed. You are also very welcome to ask questions [on our Gitter channels](https://falconframework.org/#sectionCommunity).
