### ISSUE TITLE
WebDAV methods not supported

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1426]
Falcon defines supported HTTP methods in `falcon/constants.py`: supported are "usual" `HTTP_METHODS` and, in addition to that, `WEBDAV_METHODS`. However, only WebDAV versioning extension methods from RFC 3253 are supported, but not the "ordinary" WebDAV ones (i.e. from RFCs 2518 & 4918) like `COPY`, `LOCK`, `MKCOL`, `MOVE` etc.

Supporting only an extension, but not the core upon which that extension builds looks somewhat inconsistent.

**Comment by screamingskulls** [comment]
working on this

**Comment by kgriffs** [comment]
I addressed the requested changes and merge conflicts in #1588
