### ISSUE TITLE
Submit falcon benchmark to TechEmpower

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#143]
See also: https://www.techempower.com/benchmarks/#section=data-r4&hw=i7&test=query

**Comment by kgriffs** [comment]
Or, at least, add to our own benchmark suite and compare against the "official" ones.

**Comment by nZac** [comment]
We are there: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Python/falcon
