### ISSUE TITLE
jsonschema.validate decorator removes docstring, encounter while using Sphinx

### ISSUE THREAD

**Issue by paneru-rajan** [falconry/falcon#1431]
The `jsonschema.validate` decorator does not have `@wraps(func)` which removes the docstring when applied to the methods  like `on_get`, `on_post` etc.. 
This is detected while creating docs with **Sphinx** on methods with the decorator `@jsonschema.validate`.

I have modified the decorator to this:
```
def decorator(func):
        @wraps(func)
        def wrapper(self, req, resp, *args, **kwargs):
            try:
                jsonschema.validate(req.media, schema, format_checker=jsonschema.FormatChecker())
```
Just added `@wraps(func)` inside the function, and it start working...

References:
[https://github.com/sphinx-doc/sphinx/issues/3783](https://github.com/sphinx-doc/sphinx/issues/3783)
[https://docs.python.org/3/library/functools.html#functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps)

**Comment by vytas7** [comment]
Hi @paneru-rajan !
And thank you for the report.

Since you have already solved the issue yourself, would you mind creating a pull request with your change?

**Comment by vytas7** [comment]
Fixed by https://github.com/falconry/falcon/pull/1432
