### ISSUE TITLE
Consider using black to normalize coding style

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1453]
See: https://github.com/ambv/black

**Comment by kgriffs** [comment]
(...as suggested by tribals and carlodri in the chat room.)

**Comment by carlodri** [comment]
thanks @kgriffs! My experience, albeit somehow limited (I'm not a professional programmer), is that black is really helpful in automating cleanness, readability and "pep8-ness" of your code, like set-and-forget-about-style.

**Comment by tribals** [comment]
Black has one major advantage: it stops (and prevents) people from arguing about coding style.
