### ISSUE TITLE
Quick start guide don't explain how to deal with errors

### ISSUE THREAD

**Issue by FabriceSalvaire** [falconry/falcon#1460]
First bad things that happen when using falcon is

* gunicorn don't boot the application
* something goes wrong in the application

Unfortunately the documentation doesn't give hints on` gunicorn -preload` and `API.add_error_handler`

**Comment by nZac** [comment]
Hello @FabriceSalvaire, thanks for submitting an issue. 

We are thinking we should expand the quick start to demonstrate more features. The [more features](https://falcon.readthedocs.io/en/stable/user/quickstart.html#more-features) section of the quickstart has an example of a fully functioning app with error handling.

**Comment by vytas7** [comment]
Potentially useful: https://gist.github.com/vytas7/068ac5bd8a0fd118052d32e30be67792

**Comment by vytas7** [comment]
Closing since this one more or less duplicates #1324.
