### ISSUE TITLE
Consider using an automated changelog management tool

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1461]
As our community continues to grow, the amount of changelog items such as new features, breaking changes etc continues to increase between releases, making the development version of documentation trail behind, as well as making aggregation of these a very laborious process before release.

We should consider demanding these items together with PRs (or directly thereafter in follow-up PRs), and using automated tools to aggregate these into Changelogs.

A popular choice among Python core projects like Pip, Devpi and others seems to be [towncrier](https://github.com/hawkowl/towncrier).

This and other alternatives:
* https://github.com/hawkowl/towncrier - mentioned above
* https://github.com/bitprophet/releases
* https://github.com/openstack/reno

The idea was originally brought up on Gitter by @nZac .

**Comment by Nateyo** [comment]
I'm all for making it part of the PR process and putting the onus on the PR creator. Should relieve the load on you core maintainers so all you have to do is verify the correct changes have been made to the log. I haven't used any of the above packages, but will look into using them for some projects at work. 👍
