### ISSUE TITLE
Why can't we define routes with different field expression parameter names for same routes?

### ISSUE THREAD

**Issue by tribals** [falconry/falcon#1471]
I can't see any reason why I can't first define route with URI template `/users/{id}`, then with `/users/{user_id}/posts`.

I think that this constraint comes from ability to match URI template to responder, with right "path" parameter names. But It can be done even if the same param named differently in different routes.

How can I avoid such behavior?

**Comment by tribals** [comment]
The only thing needed to be done for successful routing is to keep consistency of param names in URI templates and responder methods signatures.

**Comment by vytas7** [comment]
Hi @tribals !
I am no expert on just that part of Falcon, but as I understand the way the compiled router is built (see `falcon/routing/compiled.py`), routing logic is compiled into a Python-bytecode backed decision tree where nodes `/users/{user_id}` and `/users/{user_id}/posts` would share the same base node corresponding to `/users/{user_id}`.

As I understand you propose to lift this restriction. At least for this case it could possibly be done by somehow remapping the argument names. 

In the time being, could you just rename the `id` parameter in your responder to `user_id` to make this work?


Kindly,
Vytas

**Comment by tribals** [comment]
Unfortunately, I can't do such params mangling because I'm using generic resource implementation with different strategies, so I pass "path" param name(s) to strategy constructor and expect it to extract right param from responder's `**kwargs` based on expression paremeter name in URI template.

**Comment by vytas7** [comment]
Duplicates https://github.com/falconry/falcon/issues/663
