### ISSUE TITLE
Test client fails when WSGI application is a generator

### ISSUE THREAD

**Issue by tribals** [falconry/falcon#1479]
Here is the test that proves it:

```
from falcon.testing import TestClient


def another_dummy_wsgi_app(environ, start_response):
    start_response('200 OK', [('Content-Type', 'text/plain')])

    yield 'It works!'


def test_falcon_testing_client():
    client = TestClient(another_dummy_wsgi_app)

    client.simulate_get('/nevermind')
```

Here is [the link](/tribals/falcon/blob/feature%2Fgenerator-app/tests/test_testing.py) for convenience.

**Comment by vytas7** [comment]
Btw, just to clarify, I've tested this myself, and this applies to all recent (or probably even all) Falcon versions, including the 2.0 beta, 1.4.1 etc.

Interesting find @tribals !
