### ISSUE TITLE
Trailing slash behavior doesn't match documentation

### ISSUE THREAD

**Issue by mumrau** [falconry/falcon#1489]
Hello! 

I want to raise a question about the way trailing slashes are handled. #1289 states that it sets the default `.req_options.strip_url_path_trailing_slash` to `False`, which is the behavior I noticed.

Nonetheless, in the documentation (namely [here](https://falcon.readthedocs.io/en/0.2.0/community/faq.html?highlight=trailing#why-are-trailing-slashes-trimmed-from-req-path)), it states that 
> Falcon normalizes incoming URI paths to simplify later processing and improve the predictability of application logic. In addition to *stripping* a trailing slashes

I think there is something incoherent somewhere.
Thank you again, falcon rocks!

PS: I'm glad 2.0 is alsmot out, and already available on PyPi, i've been using master branch for a while and it showed great stability so I'm quite confident everything wille be rolled out soon!

Code test snippet: 
```python
from wsgiref import simple_server
import falcon

class Receiver:
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200

api = falcon.API()
#api.req_options.strip_url_path_trailing_slash = True -> it works flawlessly when uncommented

api.add_route("/path", Receiver())

if __name__ == '__main__':
    httpd = simple_server.make_server('127.0.0.1', 8080, api)
    httpd.serve_forever()
```
`curl -v localhost:8080/path/` -> 404
`curl -v localhost:8080/path` -> 200

**Comment by vytas7** [comment]
Hi @mumrau !
And first of all, thanks for continuous testing the master branch/2.0 beta, contributing to 2.0, and for filing this discrepancy.

Just a note, the documentation you linked to is _very_ old. But the issue is nevertheless present in the current (development version) FAQ as well: https://falcon.readthedocs.io/en/latest/user/faq.html#why-are-trailing-slashes-trimmed-from-req-path:
> **Why are trailing slashes trimmed from req.path?**
> By default, Falcon normalizes incoming URI paths to simplify later processing and improve the predictability of application logic. This behavior can be disabled via the ``strip_url_path_trailing_slash`` request option.
> Note also that routing is also normalized, so adding a route for “/foo/bar” also implicitly adds a route for “/foo/bar/”. Requests coming in for either path will be sent to the same resource.

One gets the impression that ``strip_url_path_trailing_slash``is still `True` by default, even though it is no longer the case. We should rectify this.

**Comment by mumrau** [comment]
Oh, yeah, I was surprised by the readthedocs appearance indeed, I thought it was old in appearance but not in content, which I didn't check cause I don't need much documentation anymore :tada: , except for the trailing slash behavior.

I mixed up `0.2.0` with `2.0.0` which is surprisingly not present in the menu yet, you need to go through `latest`, adding an href `2.0` could be useful as well, if anyone's into the documentation :package:

**Comment by kgriffs** [comment]
Nice catch, we'll get this fixed for rc1

**Comment by kgriffs** [comment]
Please take a look at that PR and let me know what you think.
