### ISSUE TITLE
Falcon issue posting params unittest

### ISSUE THREAD

**Issue by praveen-kalpavruksh** [falconry/falcon#1491]
I am not sure what I am doing wrong but not able to post params during unit-test.
Below is my code.

```
config = {"config": "abc"}
result = self.simulate_post(f"/path/{id}", params=config)
```

When I receive call to api, I get `None` for `req.get_params('config')`. Any Idea?

**Comment by nZac** [comment]
Hi @praveen-kalpavruksh, I took a look at this and I am not running into the same problem. I have attached a functioning example.

```python
import falcon
import falcon.testing


class Resource:
    def on_post(self, req, resp, **params):
        resp.media = req.params


if __name__ == '__main__':
    api = falcon.API()
    api.add_route('/path/{id}', Resource())
    client = falcon.testing.TestClient(api)

    id = 1
    config = {"config": "abc"}
    result = client.simulate_post(f"/path/{id}", params=config)

    print(result.json)
    print(result.json == {'config': 'abc'})
```

Can you verify this is what you are trying to do? If not, can you provide an example?

**Comment by praveen-kalpavruksh** [comment]
@nZac Thanks for the solution and your time. This is what I was doing as well but had a minor error on my side, eventually figured out.
