### ISSUE TITLE
perf(Request): Short-circuit path encode/decode when possible

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1492]
See if we can quickly determine if the following is required for a given path and short-circuit it when it is not (from `Request.__init__`):

```py
# PEP 3333 specifies that PATH_INFO variable are always
# "bytes tunneled as latin-1" and must be encoded back
path = path.encode('latin1').decode('utf-8', 'replace')
```

See also this section from `falcon/testing/helpers.py`:

```py
# NOTE(kgriffs): The decoded path may contain UTF-8 characters.
# But according to the WSGI spec, no strings can contain chars
# outside ISO-8859-1. Therefore, to reconcile the URI
# encoding standard that allows UTF-8 with the WSGI spec
# that does not, WSGI servers tunnel the string via
# ISO-8859-1. falcon.testing.create_environ() mimics this
# behavior, e.g.:
#
#   tunnelled_path = path.encode('utf-8').decode('iso-8859-1')
#
# falcon.Request does the following to reverse the process:
#
#   path = tunnelled_path.encode('iso-8859-1').decode('utf-8', 'replace')
#
path = path.encode('utf-8').decode('iso-8859-1')
```

**Comment by kgriffs** [comment]
FWIW, one way to quickly check whether a string contains only allowed chars:

```py
if not some_string.rstrip(allowed_chars):
     return some_string
```

**Comment by vytas7** [comment]
I was testing this briefly, and I cannot get any speedups from the `rstrip` / `lstrip` approach...

One thing that seems to work is to do EAFP this way:
```python
try:
    path.encode('ascii')
except ValueError:
    path = path.encode('latin1').decode('utf-8', 'replace')
```
However, as it is often the case with EAFP, the exception path becomes way more expensive.
But maybe it is a quite unusual case as normally URIs should be encoded in the first place?

Another approach is of course... Cython :slightly_smiling_face:

**Comment by vytas7** [comment]
FWIW, rewriting this in Cython to avoid memory allocation and EAFP doesn't seem to make any difference from the cythonized `path.encode('ascii')`.
However, it works much better compared to the exception path, so maybe worth implementing?
Thoughts @kgriffs ?
