### ISSUE TITLE
No on_delete option

### ISSUE THREAD

**Issue by popovvasile** [falconry/falcon#1494]
I am trying to implement the DELETE request method. Seems like on_delete is not supported and the documentation says nothing about this.
It is especially confusing and frustrating to spend so much time trying to understand if such a basic option is supported at all.

```
class ThingsResource(object):
    def on_delete(self, req, resp):
        doc = {}
        if req.content_length:
            doc = falcon.json.load(req.stream)
```

**Comment by jmvrbanac** [comment]
Falcon supports all standard HTTP verbs so it should work just fine.
Here is an example of a resource that echos the JSON you give it on delete:
```
import falcon

class EchoResource:
    def on_delete(self, req, resp):
        resp.media = req.media

api = falcon.API()
api.add_route('/echo', EchoResource())
```
```
$ curl -X DELETE localhost:8000/echo -H "Content-Type: application/json" -d '{"trace": "boom"}'

{"trace":"boom"}
```

**Comment by popovvasile** [comment]
Thank you. My bad, I had a bug in the request. I would still update the docs regarding the "on_delete" option. I close the issue
