### ISSUE TITLE
Golang-inspired Falcon API

### ISSUE THREAD

**Issue by sisp** [falconry/falcon#1499]
I understand that Falcon aims to be a "no-batteries-included" modular and extensible web framework. Having worked with Golang's stdlib HTTP handlers and stdlib-compatible routers, I'm wondering about some of Falcon's design decisions.

1. **Routes**: Let's take, e.g., the [chi router](https://github.com/go-chi/chi). A stdlib-compatible request handler function is associated with a path (pattern) and a request method instead of providing an entire resource class (or struct in Golang) which relies on methods following naming conventions like `on_get`, `on_post` etc. In my opinion, adding a request handler function with `r.Get("/path/{pattern}", func(w http.ResponseWriter, r *http.Request) { ... })` is very intuitive and transparent. This way, adding handler-specific middleware is very easy as a middleware is just a handler factory which receives a handler and returns a new handler. This approach also alleviates the problem of related resources which have to be split into multiple resource classes, e.g. `/path` and `/path/{id}`, there are simply as many request handler functions as there are method-path pairs.
1. **Middlewares**: In Golang, a middleware is simply a handler factory which receives a handler and returns a new handler. There is no explicit distinction between execution before routing, before request handling, and after request handling. Instead, code that is executed before `next.ServeHTTP(w, r)` is executed before request handling and code that is executed after this call is executed after request handling. This way, there is no need for a separate error handler mechanism like `add_error_handler` which makes writing, e.g., a logging middleware more difficult because request/response logging happens in the middleware and "catch-all" exception logging happens in the error handler. In my opinion, Golang's approach is much more predictable and straightforward.

Any opinions?

**Comment by nZac** [comment]
Hi @sisp, thanks for the suggestions, we love hearing about how other frameworks are streamlining development for their users. 

Falcon has made some design decisions which enable related API requests to be logically grouped within the same resource class. With the recent changes to 2.0 we are able to support alternative route / path pairs on the same resource using suffix. See https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_route for how that will work.

Middlewares do pose some unique challenges, they certainly aren't a silver bullet. If you want the functionality similar to Go, you might want to check out [hooks](https://falcon.readthedocs.io/en/stable/api/hooks.html#hooks) which give you a lot of flexibility. You can also use standard Python decorators.

You can find us on the Falcon #dev Gitter.im channel where we can have higher-bandwidth conversations if you have more suggestions. You can find that here: https://gitter.im/falconry/dev.

**Comment by vytas7** [comment]
Hi @sisp ,
adding to what @nZac said, I would like to comment on your second point, Golang middlewares.

Python [PEP-3333 WSGI Middleware](https://www.python.org/dev/peps/pep-3333/#middleware-components-that-play-both-sides) acts exactly the same way as you describe. You can use generic WSGI middleware with Falcon.
