### ISSUE TITLE
doc: Request ID logging

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1500]
Document in the FAQ or a tutorial how you can use a middleware `process_request()` method to generate a request ID (or extract one from an HTTP header if provided downstream ala tracing) and then add that to `req.context` so you can reference it later when you want to log it out. Alternatively, you can use something like `structlog` and bind the request id to an instance that you then pass around via `req.context`.

**Comment by kgriffs** [comment]
Also, perhaps we need a more generalized tutorial or set of recipes for managing application state... See also: https://gist.github.com/kgriffs/ea37ede4480ac5e080018eed81d292af

**Comment by kgriffs** [comment]
See also: https://www.structlog.org/en/stable/getting-started.html#building-a-context

**Comment by kgriffs** [comment]
OK, so I think the best approach here is to add a recipe to the docs (let's create a new recipes section in the docs) somewhat along the lines of the gist above but that focuses on per-request state. The config example probably belongs in a separate recipe.

**Comment by rmyers** [comment]
I'm going to take this on.
