### ISSUE TITLE
Proxying requests - multiple HTTP methods

### ISSUE THREAD

**Issue by danielloader** [falconry/falcon#1501]
> Note that at least ``requests.Response`` features the ``iter_content`` method (which automatically defaults to the equivalent of ``decode_content=True``, not sure if this is always desired though).
> 
> Could we alternatively start with a recipe in FAQ/documentation?
> 
> Something like the below seems to work for me on Python 2.7/3.5, but not tested in-depth:
> 
> ```python
> import io
> 
> import falcon
> import requests
> 
> 
> class Proxy(object):
>     ALLOWED_METHODS = ['GET']
> 
>     UPSTREAM = 'https://falconframework.org'
> 
>     @classmethod
>     def on_get(cls, req, resp):
>         if req.method not in cls.ALLOWED_METHODS:
>             raise falcon.HTTPMethodNotAllowed(cls.ALLOWED_METHODS)
> 
>         from_upstream = requests.get(cls.UPSTREAM + req.path, stream=True)
> 
>         resp.content_type = from_upstream.headers.get('Content-Type',
>                                                       falcon.MEDIA_HTML)
>         resp.status = falcon.get_http_status(from_upstream.status_code)
>         resp.stream = from_upstream.iter_content(io.DEFAULT_BUFFER_SIZE)
> 
> 
> api = falcon.API()
> api.add_sink(Proxy.on_get)
> ```
> 
> Not the fastest proxy in the world, but the page did load in the web browser :slightly_smiling_face:
> 

_Originally posted by @vytas7 in https://github.com/falconry/falcon/issues/1271#issuecomment-401612434_

Having seen this quick implementation, is there a way to modify this to work with POST, DELETE and PATCH methods too?

Not having any luck trying to use a sink with multiple HTTP methods.

**Comment by vytas7** [comment]
Hi @danielloader !
As also written on Gitter, sinks are method-agnostic, and all HTTP methods are routed to a sink. In my snippet I explicitly check that `req.method` is within the allowed methods, which is basically only `['GET']`.

Furthermore, note that my method name `Proxy.on_get` is a bit of a misnomer -- any callable would do. Sink names are **not** used to match HTTP verbs.

**Comment by vytas7** [comment]
@danielloader I have updated my example to supports multiple methods: https://gist.github.com/vytas7/cf49d061894bbff66e63b1dd9500e2cb

Hope the updated snippet is more helpful this time.

**Comment by danielloader** [comment]
That's great, example works perfectly and shows some of the functionality in a clear way - all the examples I've been looking at assume on_get is all you'd ever want to proxy with a sink!
