### ISSUE TITLE
feat: Support Non-standard HTTP methods

### ISSUE THREAD

**Issue by jmvrbanac** [falconry/falcon#1503]
To support porting legacy APIs with non-standard HTTP method names, we should allow the ability to extend our acceptable HTTP method list. It should be documented, that this is not a preferred usage of Falcon, but it's there to support porting odd edge-cases and legacy APIs.

**Comment by seanharrison** [comment]
I'm tackling this one this morning.

**Comment by seanharrison** [comment]
I'll have a go at this one.

**Comment by vytas7** [comment]
This has been implemented
* https://github.com/falconry/falcon/pull/1522
* https://github.com/falconry/falcon/pull/1540
