### ISSUE TITLE
Make testing resource methods easier by creating arbitrary req/resp

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1506]
It can be useful when you want to test a resource method in isolation to manually create a `Request` and `Response` object and pass them directly to the resource method.

```python
def test_my_resource():
    resource = MyResource()
    req, resp = Request(helpers.create_environ()), Response()
    resource.on_get(req, resp)
```

There are some gotchas with manually creating the environ and it could be much easier.
- [ ] Provide a global method in `testing.helpers` which creates a `Request` and `Response` object.
  - [ ] Enable passing `json`, `body`, and `stream`
  - [ ] Automatically set `Content-Length`
  - [ ] Do best effort to set `Content-Type` 
  - [ ] Enable passing arbitrary WSGI envs
- [ ] Create a method on `TestClient` which will utilize the global method but fill in some of the `environment` details and utilize application specific `Request` and `Response`.

```python
def create_test_request_response(json: dict = None, body: string = None, context: dict = None, **env):
    env['body'] = (
        (body if body is not None else None)
        or (json.dumps(json) if json else '')
    )

    env = falcon.testing.create_environ(**env,)
    req = falcon.Request(env)
    req.context.update(context or {})
    return (req, falcon.Response())

def test_my_resource():
    resource = MyResource()
    req, resp = create_test_request_response(json={'hello': 'world'})
    resource.on_get(req, resp)
```

**Comment by nZac** [comment]
@hynek, is this close to what you were talking about during our open space regarding testing?

**Comment by hynek** [comment]
Yep, something like that! Just let me set context and body/json and I should be fine.

**Comment by vytas7** [comment]
@kgriffs :ping_pong: Friendly ping checking if this is still on your radar.
Looks like we now have [`create_req()`](https://falcon.readthedocs.io/en/latest/api/testing.html#falcon.testing.create_req) and [`create_asgi_req()`](https://falcon.readthedocs.io/en/latest/api/testing.html#falcon.testing.create_asgi_req), although they probably don't fully live up to @hynek 's requirements yet :thinking: 
> Yep, something like that! Just let me set context, url/fields, access_route, and body/json and I should be fine I think.

**Comment by kgriffs** [comment]
I feel like we have made good progress on this. Perhaps close it and we can create a followup issue if someone would really like additional features?

**Comment by vytas7** [comment]
IMHO we should either document the pattern you laid out in the description, or add a helper to also create a `Request`, because it may be unclear you can instantiate it directly like that.

**Comment by vytas7** [comment]
Resolved fixed as part of ASGI developments, see:
* [`create_req`](https://falcon.readthedocs.io/en/latest/api/testing.html#falcon.testing.create_req)
* [`create_asgi_req`](https://falcon.readthedocs.io/en/latest/api/testing.html#falcon.testing.create_asgi_req)
* [`create_scope_ws`](https://falcon.readthedocs.io/en/latest/api/testing.html#falcon.testing.create_scope_ws)

**Comment by vytas7** [comment]
The remaining work items and documentation improvements were deferred to https://github.com/falconry/falcon/issues/1793.

**Comment by kgriffs** [comment]
Thanks, I think it makes sense to delay the rest of this to 3.1 so that we can get 3.0 out that match sooner.
