### ISSUE TITLE
Add a generic error handler that returns the application's default media type

### ISSUE THREAD

**Issue by jmvrbanac** [falconry/falcon#1507]
If a generic Python exception is raised while running in gunicorn. The user will see an HTML Internal Server Error even though the default media type is `application/json`. This is due to the exception getting raised to the WSGI server which is defaulting the output. We should gracefully handle this with the default media type. According to the the WSGI spec applications should `In general, applications should try to trap their own, internal errors, and display a helpful message in the browser.`

Tasks:

1. Add a default handler that can be overridden
2. Output a notice and hint to wsgi.errors / stderr?
3. ~Add Recipe in docs~ Add to documentation about adding error handling.

**Comment by csojinb** [comment]
I am taking a look at this

**Comment by csojinb** [comment]
@jmvrbanac for #3 -- do you mean a recipe for overriding the handler?

**Comment by jmvrbanac** [comment]
@csojinb Sorry, I should've called that "example" or something a bit clearer instead. The idea is that this is something people end up doing more often than we thought, so just having a code example showing how a user would go about doing this.

**Comment by vytas7** [comment]
Resolved in https://github.com/falconry/falcon/pull/1527 [Merged]
