### ISSUE TITLE
Sending local requests to an app

### ISSUE THREAD

**Issue by velovix** [falconry/falcon#1541]
I'm considering a batching solution similar to the one used by [Gmail](https://developers.google.com/gmail/api/guides/batch) and a few others. It involves providing a new endpoint (like /api/v1/batch) that takes a `multipart/mixed` request body that has individual API requests to other endpoints. As the writer of this batching endpoint, I need a way to send requests to my Falcon app based on the content of this `multipart/mixed` body. I'm aware of `falcon.testing.TestClient`, which is what I'm planning on using, but it seems a little strange to use a testing package in production and I'm wondering if there is another suggested way to do this sort of thing.

**Comment by nZac** [comment]
Hi @velovix, thanks for asking.

I can't give you a full rundown of what to do, I would need to know a bit more. 

At first glance this sounds like you might want to restructure some things in your app so that you could do something like this:

```python
import thing_editor

class EditThingResource():
    def on_post(self, req, resp):
        thing_editor(req.media)

class BatchEditThingResource():
    def on_post(self, req, resp):
        for thing in req.media:
            thing_editor(thing)
```

Would something like that work?

Also, you might want to pop onto our Gitter Users channel, https://gitter.im/falconry/user, where it is much easier to help with these kinds of application specific questions.

**Comment by velovix** [comment]
Thank you for your suggestion @nZac! This is what I would reach for as well if I had batch endpoints that correspond to each of my regular endpoints, so..

`/api/edit_thing` would point to `EditThingResource`
`/api/edit_thing/batch` would point to `BatchEditThingResource`

However, I'm not sure if this makes sense for the style of batching I'm attempting to replicate, where a batch request has a body of _other requests_. In that case, I would like to be able to utilize Falcon's routing system for each one of these request bodies. If I don't do that, I would have to parse each request myself to extract the endpoint URL and method, then map that information to my resources.

I will follow up on the Gitter Users channel and report back here if I find anything out. In the meantime I'll close this issue. Thanks!
