### ISSUE TITLE
How can I get session id of a request?

### ISSUE THREAD

**Issue by wotulong** [falconry/falcon#1543]
I want to log  request information, but how can i get the session id of a request?

**Comment by nZac** [comment]
Hi @wotulong, Great question and one we get often...

It isn't on the main docs page yet, but we have a recipe that will be published. You can find the guide here: https://github.com/falconry/falcon/blob/023e5e3446dd16ff7743f8fe8558b37ec5ecd82a/docs/user/recipes/request-id.rst

I am going to close this for now, reopen it if you have more questions or this doesn't meet your needs.
