### ISSUE TITLE
get_param_as_list failing to parse list as of 2.0.0 release

### ISSUE THREAD

**Issue by stmcginnis** [falconry/falcon#1547]
There appears to be an issue with the get_param_as_list call starting with the 2.0.0 release. With the query string containing:

    'ids=5ced7dac61a1a1461b49d567,5ced7dac61a1a1461b49d568,5ced7dac61a1a1461b49d569'

using falcon 2.0.0 the following code returns a single result:

    ids = req.get_param_as_list('ids')
    LOG.error('"ids" param as list: %s', ids)

With 2.0.0:

    "ids" param as list: ['5ced7dac61a1a1461b49d567,5ced7dac61a1a1461b49d568,5ced7dac61a1a1461b49d569']

Downgrading to the last pre-2.0 release of 1.4.1, the result is:

    "ids" param as list: ['5ced7dac61a1a1461b49d567', '5ced7dac61a1a1461b49d568', '5ced7dac61a1a1461b49d569']

**Comment by stmcginnis** [comment]
Tracked down to this being the cause:

https://github.com/falconry/falcon/commit/93cd3e6906e62a753621e87feaee2f3845a5696f

Have to agree with the bug report comments that this change is a little counter-intuitive. It's also not clear in the change log how this impacts other method calls, hence my reading through and not finding anything that looked like it would be the root cause for the issue I was seeing.

Not going to close quite yet, since I think it should be considered for 3.0 to change the default so that something like "ids=a,b?id=c" doesn't seem right to return a list of two items of ["a,b", "c"] and not ["a", "b", "c"].

**Comment by kgriffs** [comment]
Thanks for raising this issue. I'll schedule it for 3.0 so we can be sure to make a decision on this.

**Comment by jimbobhickville** [comment]
I'm hitting this as well. The biggest pain point for me is that the testing client serializes GET params as CSV when you pass in a list, so this change breaks basic behavior in our unit tests. IMO, if you're explicitly requesting a list, and the method says it parses CSV values into a list, then it should do that, regardless of some unrelated setting elsewhere in the code.

**Comment by philipaconrad** [comment]
This bug is breaking a production system at my workplace that uses `req.get_param_as_list` on a URL that processes data for analysis.

Sanitized example shown below, with the current (inconvenient) workaround:

-----

Parameters (and the code used to parse them):

 - `calibration`:  `req.get_param("calibration")`
 - `events`: `req.get_param_as_list("events", transform=int)`

Example (failing) input URL:

    http://localhost:8000/service/analyze?calibration=example&events=23,24,25,26,27,28

Server response:

    <?xml version="1.0" encoding="UTF-8"?>
    <error>
      <title>Invalid parameter</title>
      <description>The "events" parameter is invalid. The value is not formatted correctly</description>
    </error>

Current workaround:

    http://localhost:8000/service/analyze?calibration=example&events=23&events=24&events=25&events=26&events=27&events=28

Encoding a list parameter in its alternate form (many parameters with the same name) seems to work.

**Comment by suola** [comment]
In Falcon v2 the default value of [`falcon.RequestOptions.auto_parse_qs_csv`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.auto_parse_qs_csv) was changed from `True` to `False`, therefore comma-separated values are no longer split unless you set the option explicitly.

**Comment by jhuitema** [comment]
Can the TestClient be updated to _not_ specify list arguments as CSV then? Currently there is no way I can find to allow the TestClient to work with get_param_as_list without setting ``auto_parse_qs_csv``.

Having to set ``auto_parse_qs_csv`` for the tests isn't great since that changes the behaviour of the entire app.

**Comment by vytas7** [comment]
Hi @jhuitema ,
just to make sure I understand you correctly, are you talking about the `params` parameter of the `TestClient` `simulate_*()` methods, i.e.:
```python
import falcon
import falcon.testing


class Parameters:

    def on_get(self, req, resp):
        resp.media = req.params


def test_params():
    app = falcon.API()
    app.add_route('/params', Parameters())
    client = falcon.testing.TestClient(app)

    resp = client.simulate_get(
        '/params', params={'x': '5', 'items': ['a', 'b', 'c']})
    assert resp.json == {'items': 'a,b,c', 'x': '5'}
    #                               ^
```

That does sound inconsistent with the new `auto_parse_qs_csv` default in Falcon 2.0.
I'll create a new issue for this.

**Comment by vytas7** [comment]
@jhuitema Note that although this may be infeasible for your test suite, you can also explicitly specify `params_csv=False` in your `simulate_*` calls as a workaround for the time being.

I created https://github.com/falconry/falcon/issues/1730 to change the default to match the [`RequestOptions.auto_parse_qs_csv`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.auto_parse_qs_csv) default value.

**Comment by jhuitema** [comment]
Ah, the params_csv keyword arg on the simulate_* method was what I was asking for. I didn't notice there was a way to change the list params output by the TestClient.

Feel free to ignore me :)

**Comment by vytas7** [comment]
@jimbobhickville @jhuitema I have now merged the fix for https://github.com/falconry/falcon/issues/1730 , so at least the testing client will now be consistent with the default [`RequestOptions.auto_parse_qs_csv`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.auto_parse_qs_csv) setting.

**Comment by vytas7** [comment]
The question what to do with `get_param_as_list()` still remains open.

There is a bit of an ugly issue what to do with escaped commas.
In case we decide that `get_param_as_list()` should split on commas regardless of the [`RequestOptions.auto_parse_qs_csv`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.auto_parse_qs_csv) value (either by default, or controlled by an optional parameter, or as another method `get_param_as_csv_list()`?), the query is already percent-decoded.

We could split post-decoding, but then the behaviour is not equivalent. Or maybe we do want that distinction based on the [`RequestOptions.auto_parse_qs_csv`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.auto_parse_qs_csv) setting?

Cf
```python
>>> [falcon.uri.decode(value) for value in 'a,b%2Cc'.split(',')]
['a', 'b,c']
>>> falcon.uri.decode('a,b%2Cc').split(',')
['a', 'b', 'c']
```

Any feedback/ideas are welcome.

**Comment by dangtoanphat** [comment]
I have upgraded from 1.4.1 to 2.0.0 and I came up with 2 workarounds:
- Option 1: using auto_parse_qs_csv = True in RequestOption
- Option 2: get the params as a string and then split by commas

**Comment by kgriffs** [comment]
The following note in the `get_param()` docstring needs to be corrected, since it is only true when `auto_parse_qs_csv` is enabled:

```
        Note:
            Similar to the way multiple keys in form data is handled,
            if a query parameter is assigned a comma-separated list of
            values (e.g., ``foo=a,b,c``), only one of those values will be
            returned, and it is undefined which one. Use
            :meth:`~.get_param_as_list` to retrieve all the values.
```

**Comment by kgriffs** [comment]
> In case we decide that `get_param_as_list()` should split on commas regardless...

@vytas7 I think this approach would make a lot of sense from the app developer's perspective. The docstring also currently sets this expectation: "List items must be comma-separated..."

As for the handling of strings that mix percent-encoded and literal commas, I feel like it is an edge case that we shouldn't bend over backwards to support. We can note in the docs how we've chosen to handle it (in terms of the inconsistency with `auto_parse_qs_csv`). If someone really needs to do this, they can parse the parameter themselves. And if we are wrong about this being an edge case, we can add a configuration option in a future release.

**Comment by kgriffs** [comment]
On the other hand, if `get_param_as_list()` always splits on commas, what then would be the purpose of `auto_parse_qs_csv`? I guess we need to step back and think about the big picture since this area of the framework design has become a bit muddled over the past couple of iterations.

**Comment by kgriffs** [comment]
Per our discussion in the https://gitter.im/falconry/dev channel earlier this week, we have improved the documentation and fixed a somewhat related bug regarding `auto_parse_qs_csv` and the mixing of csv and multiple-instance styles.

We will not change the `auto_parse_qs_csv` default for 3.0.0 since doing so would cause another disruptive change, and it is thought that the current behavior is sufficient once better documented.

If we missed any critical use cases, please let us know, but otherwise I am going to go ahead and close this issue.
