### ISSUE TITLE
Falcon returns HTML on unhandled exceptions

### ISSUE THREAD

**Issue by jceresini** [falconry/falcon#1555]
When an unhandled exception is raised, falcon returns HTML. For a framework that aims to make writing APIs simpler, I would think it should never return HTML unless explicitly configured to do so. We were able to setup an error handler to solve the issue, but should the default behavior be to send either JSON or XML back for unhandled exceptions?

I'm using falcon version 2.0.0

Simple example:

```
import falcon

class BadEndpoint:

    def on_get(self, req, resp):
        raise AttributeError("oops")

api = falcon.API()
api.add_route('/raise', BadEndpoint())
```

```
$ curl http://localhost:8000/raise
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
```

I searched through the issues and didn't see this mentioned anywhere else.

**Comment by jmvrbanac** [comment]
Thanks for reporting this! This issue is currently due to the fact that we're currently surfacing uncaught errors to the WSGI server and a number of WSGI servers (such as Gunicorn) return an html error by default. We're currently investigating a way to deal with this as a part of PR #1527 . If you need an immediate workaround, you can add a custom error handler to your falcon app to handle generic exceptions: https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_error_handler . Hopefully that helps you workaround the issue until we can get a more long-term solution released.

**Comment by jceresini** [comment]
Thanks, I'll keep an eye on that PR. For now we are using the suggestion we found here, which works really well: https://github.com/falconry/falcon/issues/948#issuecomment-379366891

**Comment by vytas7** [comment]
Hi @jceresini ,
this has hopefully been addressed in the mentioned PR 

I am using the Falcon _master_ at the time of writing:
```
pip install git+https://github.com/falconry/falcon
```

I was a testing a simple division-over-HTTP end-point, something along the lines:
```python
import falcon


class Division:
    def on_get(self, req, resp):
        dividend = req.get_param_as_float('dividend')
        divisor = req.get_param_as_float('divisor')
        resp.media = dividend / divisor


app = falcon.API()
app.add_route('/division', Division())
```

And it was working great until something went wrong with this URI:
```
GET /division?dividend=5.0&divisor=0.0 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8000
User-Agent: HTTPie/1.0.3


HTTP/1.1 500 Internal Server Error
Connection: close
Date: Sun, 03 Nov 2019 21:47:29 GMT
Server: gunicorn/19.9.0
content-length: 38
content-type: application/json
vary: Accept

{
    "title": "500 Internal Server Error"
}
```

The Gunicorn stderr was:
```
2019-11-03 22:47:29 [FALCON] [ERROR] GET /division?dividend=5.0&divisor=0.0 => Traceback (most recent call last):
  File "<... my virtual env ...>/lib/python3.7/site-packages/falcon/api.py", line 292, in __call__
    responder(req, resp, **params)
  File "<... test.py ...>", line 8, in on_get
    resp.media = dividend / divisor
ZeroDivisionError: float division by zero
```

I'm thus closing the issue, but let us know if you find this inadequate.

**Comment by jceresini** [comment]
Awesome, ill check it out. Thanks!
