### ISSUE TITLE
Include "SameSite" keyword parameter option for the set_cookie() method

### ISSUE THREAD

**Issue by pushshift** [falconry/falcon#1556]
There is a somewhat new option for cookies to have the SameSite parameter set which helps protect against CSRF attacks (More information here: https://www.netsparker.com/blog/web-security/same-site-cookie-attribute-prevent-cross-site-request-forgery/)

Adding this keyword option for the set_cookie method would be a great addition.

**Comment by pushshift** [comment]
Thanks @kgriffs for the fast action on this! Much appreciated.

**Comment by 5onic** [comment]
@kgriffs @vytas7 Is someone working on it? otherwise I can pick up this issue.

**Comment by vytas7** [comment]
@5onic I don't think anyone is working on this. You're welcome to grab it :+1:

**Comment by vytas7** [comment]
Implemented in https://github.com/falconry/falcon/pull/1557
