### ISSUE TITLE
Can Falcon first response to request then execute other code?

### ISSUE THREAD

**Issue by Cylkal** [falconry/falcon#1564]
I'm sorry that I can't find a method to response immediately and then execute other time consuming cods.

**Comment by kgriffs** [comment]
Hi @Cylkal, Falcon does not (yet) support this directly. However, you can try using Python's standard multiprocessing module to enqueue background jobs to a local worker pool. If you need to scale up from localhost processing, you might consider using a queueing service ala SQS with a set of worker boxes. The use case of processing background tasks is a very general one, and so there are many different options out there. 

The upcoming Falcon 3.0 will have built-in support for scheduling background tasks that run after the response has been returned, as part of the new ASGI interface.

**Comment by Cylkal** [comment]
@kgriffs Thanks for reply, I will try multiprocessing.
