### ISSUE TITLE
Not able to override the default falcon.HTTPInternalServerError 

### ISSUE THREAD

**Issue by Jithinqw** [falconry/falcon#1568]
I have written a falcon middleware to check for 500 status code and return a message to user. But the server still gives the generic XML format of error code, instead of the message I have given. If there is an error sometimes this middleware returns a stacktrace to the user.

Reproduce the error:
```
def process_response(self, req, resp, resource, req_succeeded):
       
        if resp.status is "500 Internal Server Error":
            raise falcon.HTTPInternalServerError(
                title="Internal Server Error",
                description="Something really went wrong. Please try again later.",
            )
        else:
            pass```

**Comment by vytas7** [comment]
Hi @Jithinqw ,
May I guess you have probably meant `resp.status == "500 Internal Server Error"`?

In Python, operator `is` means that two Python objects are the **same** / **identical**, i.e. under the hood their pointers point to the same memory location. If you assigned one with `falcon.HTTP_500`, that would be equal to `"500 Internal Server Error"`, but it wouldn't be the same string in the memory:
```python
>>> falcon.HTTP_500 == '500 Internal Server Error'
True
>>> falcon.HTTP_500 is '500 Internal Server Error'
False
>>> falcon.HTTP_500 is falcon.HTTP_INTERNAL_SERVER_ERROR
True
```

Changing the operator to `==` works for me:
```python
import falcon


class Middleware:

    def process_response(self, req, resp, resource, req_succeeded):
        if resp.status == "500 Internal Server Error":
            raise falcon.HTTPInternalServerError(
                title="Internal Server Error",
                description="Something really went wrong",
                href="https://github.com/falconry/falcon/issues/1568",
            )


class FaultyResource:

    def on_get(self, req, resp):
        # Sorry, I haven't got the time to implement the response due to
        # pressure from the management...
        resp.status = falcon.HTTP_500


api = falcon.API(middleware=[Middleware()])
api.add_route('/new/feature', FaultyResource())
```

I am thus closing this issue hoping the above helps, but do not hesitate to reopen if you have further issues or questions on the subject!

cheers
Vytas
