### ISSUE TITLE
Rename resp.body to resp.text

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1578]
For both the WSGI and ASGI interfaces, rename Response.body to Response.text to provide a better contrast to Response.data. Response.body should then be made a deprecated alias.

Don't forget to also grep the docstrings and /docs for references to 'body' and update them accordingly.

NOTE: It may be best to wait to implement this issue until #1573 is merged to avoid conflicts.

**Comment by mrpycharm** [comment]
@kgriffs i'll try to do it.

**Comment by vytas7** [comment]
@mrpycharm great :+1: 

I added `blocked-by-release` just to reflect upon the relation to merging ASGI branch/the first async alpha release, but you can start working on it in the meanwhile. Just that we'll probably want to merge the mentioned large PR first, and you may have to do a second round of changes if that's OK @mrpycharm .

**Comment by mrpycharm** [comment]
@vytas7 sure.

**Comment by vytas7** [comment]
@mrpycharm thought just checking if you were still working on this?
And sorry for not removing the label earlier. This is no longer blocked on any issues as #1573 landed some months ago.

**Comment by mrpycharm** [comment]
Hi @vytas7, apologies for not updating here. I might not be able to complete it because I am caught up in some urgent things these days.

**Comment by vytas7** [comment]
No worries! I'm then leaving the `needs contributor` label for now, but don't hesitate to let us know if you wish to grab this (or another) issue again!

**Comment by mrpycharm** [comment]
Sure @vytas7 I'll pick it up again if I get a chance to :)
