### ISSUE TITLE
Rename the API class to App

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1579]
API can be confusing in that it is unclear that the class represents a WSGI "app", not the Falcon "api". Therefore, we have decided to rename the class and module. `falcon.API` should continue to be available as a deprecated alias. The docs will need to be updated accordingly.

**Comment by mikeyusko** [comment]
@kgriffs I'll pick up that one.

**Comment by vytas7** [comment]
This has been addressed in https://github.com/falconry/falcon/pull/1592
