### ISSUE TITLE
Revisit RequestOptions.auto_parse_form_urlencoded

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1580]
Create a media handler for `application/x-www-form-urlencoded` that can be used via `req.media`. As part of this work, deprecate the use of the `auto_parse_form_urlencoded` (which merges form params into query string params) by adding a note to the docs to that effect.

The implementation can be patterned after `Request._parse_form_urlencoded()`

**Comment by vytas7** [comment]
Work remaining after https://github.com/falconry/falcon/pull/1537:
* Decide whether we want to add this to default handlers (@nZac expressed support for this in another discussion IIRC, I agree)
* Deprecate `auto_parse_form_urlencoded` in the docs
