### ISSUE TITLE
Official support for CPython 3.8

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1587]
CPython 3.8.0 was [released Oct 14, 2019](https://www.python.org/downloads/release/python-380/).

Make Falcon offically support CPython 3.8:
- [ ] README
- [ ] Docker images
- [ ] Docs
- [ ] Tox
- [ ] Travis
- [ ] setup.py

**Comment by vytas7** [comment]
@waghanza started work on this.

**Comment by waghanza** [comment]
`PR` https://github.com/falconry/falcon/pull/1593

**Comment by waghanza** [comment]
@vytas7 what do you mean by 
+ `README`
   + is there any version requirements on `README` ?
+ `Docker images`
   + is the an **official** `falcon` docker image ?
+ Docs
   + ?

**Comment by vytas7** [comment]
@waghanza I think I ripped this from @kgriffs ' checklist for 3.7 :slightly_smiling_face: 

The checklist should nevertheless be relevant for 3.8 too:
* `README`, Docs -- yes, we mention which CPython / PyPy versions Falcon runs on. We need to extend those advertisements to mention CPython 3.8
* Docker images -- we have Docker images for replicating framework overhead benchmark results showcased on the Falcon homepage, take a look at the `docker/` directory inside the source tree
