### ISSUE TITLE
Improve docs re suffixed responders

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1596]
- [ ] Add an example to the `suffix` kwarg docstring for `add_route()`
- [ ] Add a section about suffixed responders to the [routing](https://falcon.readthedocs.io/en/stable/api/routing.html) page

**Comment by MinesJA** [comment]
I can take this one if you still need someone to

**Comment by vytas7** [comment]
That would be awesome @MinesJA !
Go ahead!

**Comment by MinesJA** [comment]
Just submitted. First time submitting so let me know if I'm missing anything. Thanks!
