### ISSUE TITLE
RequestOptions.auto_parse_qs_csv documentation is misleading for the True case

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1597]
[`uri.parse_query_string`](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.uri.parse_query_string) supports splitting parameter values on comma, however, only the first occurrence is actually split:
```python
>>> uri.parse_query_string('interesting&stuff=1,2&key=value&stuff=3,4,5', csv=True)
{'stuff': ['1', '2', '3,4,5'], 'key': 'value'}
```

This is a known and documented limitation of `uri.parse_query_string`:
> The two different ways of specifying lists may not be mixed in a single query string for the same parameter.

However, documentation for [`RequestOptions.auto_parse_qs_csv`](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.RequestOptions.auto_parse_qs_csv) mentions neither this limitation nor the fact that `uri.parse_query_string` is used for parsing. Moreover, it provides a misleading (although the example values are technically correct since only the first occurrence of `t` has commas) example:
> When `auto_parse_qs_csv` is set to ``True``, the query string value
> is also split on non-percent-encoded commas and these items
> are added to the final list (i.e. ``/?t=1,2,3&t=4``
> becomes ``['1', '2', '3', '4']``).

**Comment by frad00r4** [comment]
Also I found another bug with `auto_parse_qs_csv`

If a http client send quoted query string it doesn't work

for example
```python
print(req.query_string)
print(req.params)
t=1%2C2%2C3
{'t': ['1,2,3']}
```
but
```python
print(parse_query_string(unquote(req.query_string), csv=True))
{'t': ['1', '2', '3']}
```
