### ISSUE TITLE
msgpack.exceptions.ExtraData: unpack(b) received extra data. 

### ISSUE THREAD

**Issue by mthri** [falconry/falcon#1605]
I try to learn and deploy sampel code for falcon tutorial in readthedocs. in this [section](https://falcon.readthedocs.io/en/stable/user/tutorial.html#testing-your-application) when testing app by `pytest tests` get 1 failed with this title:

> E msgpack.exceptions.ExtraData: unpack(b) received extra data.

how to solve this problem?

pytest output:

```
tests/test_app.py F                                                      [100%]

=================================== FAILURES ===================================
_______________________________ test_list_images _______________________________

client = <falcon.testing.client.TestClient object at 0x7f2cceed5490>

    def test_list_images(client):
        doc = {
            'images': [
                {
                    'href': '/images/1eaf6ef1-7f2d-4ecc-a8d5-6e8adba7cc0e.png'
                }
            ]
        }

        response = client.simulate_get('/images')
>       result_doc = msgpack.unpackb(response.content, raw=False)

tests/test_app.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   msgpack.exceptions.ExtraData: unpack(b) received extra data.

msgpack/_unpacker.pyx:209: ExtraData
============================== 1 failed in 0.15s ===============================
```

**Comment by vytas7** [comment]
Hi @mthri !
It's hard to tell without knowing more details. We had issues with these examples being out of date, but I don't think `msgpack` was one of those issues.

Could it be that you happen to have an old `msgpack` version?
Could you run `pip freeze` in your environment and report your package versions?
Also your Python version (`python -V`).

**Comment by vytas7** [comment]
Hmm, I see our recipes and `look` example requirements are actually a bit dated...

It would be still interesting to now which versions you have issues with.

Also, could you try the following...
```
pip uninstall msgpack-python
pip install -U falcon msgpack
```
... and report whether it solves your issue.

I'll try to get these fixed/modernized.

**Comment by mthri** [comment]
Hi @vytas7 
Thanks for trying to fix my problem.

More details:
python version: 3.7.5rc1
os: ubuntu 19.10
pip3 freeze:
```
astroid==2.3.3
atomicwrites==1.3.0
attrs==19.3.0
falcon==2.0.0
importlib-metadata==0.23
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
more-itertools==7.2.0
msgpack==0.6.2
packaging==19.2
pluggy==0.13.0
py==1.8.0
pylint==2.4.3
pyparsing==2.4.4
pytest==5.2.2
six==1.13.0
typed-ast==1.4.0
wcwidth==0.1.7
wrapt==1.11.2
zipp==0.6.0
```
and try to do this
> pip uninstall msgpack-python
> pip install -U falcon msgpack
but dosen't fix my problem.

**Comment by vytas7** [comment]
Hi again,
hmm... that sounds a bit strange. I still suspect you might have `msgpack-python` hanging around somewhere... Are you using a `virtualenv`? Could it that your environment allows external site packages?

Just to check, wouldn't you mind to run these commands in your environment, and report the output?
```
pytest --version
python -V
python -c "import msgpack; print(msgpack.version)"
```
```

**Comment by mthri** [comment]
yes, im using `virtualenv`.
how to know environment is configured to also include external system-wide Python site-packages?

```
(.env) x@y:~$ pytest --version
This is pytest version 5.2.2, imported from /home/x/working-on/python/.env/lib/python3.7/site-packages/pytest.py
(.env) x@y:~$ python -V
Python 3.7.5rc1
(.env) x@y:~$ python -c "import msgpack; print(msgpack.version)"
(0, 6, 2)
```

**Comment by vytas7** [comment]
Everything looks fine in the environment @mthri .

Could you show me how your `images.py` looks like?

**Comment by mthri** [comment]
To ensure i show you all code:

**app.py:**
```
import falcon
from .images import Resource

api = application = falcon.API()
img = Resource()
api.add_route('/images',img)
```

**images.py:**
```
import json
import falcon

class Resource(object):

    def on_get(self, req, resp):
        doc = {
            'images': [
                {
                    'href': '/images/1eaf6ef1-7f2d-4ecc-a8d5-6e8adba7cc0e.png'
                }
            ]
        }
        resp.body = json.dumps(doc, ensure_ascii=False)
        resp.status = falcon.HTTP_200

```

**test_app.py:**
```
import falcon
from falcon import testing
import msgpack
import pytest

from look.app import api


@pytest.fixture
def client():
    return testing.TestClient(api)


def test_list_images(client):
    doc = {
        'images': [
            {
                'href': '/images/1eaf6ef1-7f2d-4ecc-a8d5-6e8adba7cc0e.png'
            }
        ]
    }

    response = client.simulate_get('/images')
    result_doc = msgpack.unpackb(response.content, raw=False)

    assert result_doc == doc
    assert response.status == falcon.HTTP_OK
```

**Comment by vytas7** [comment]
Heh, I think in `images.py`, you are using `json.dumps(...)` instead of `msgpack.pack(...)`. Which then confuses Msgpack when it tries to deserialize JSON media :slightly_smiling_face:

See the updated version of `images.py` just above [_Testing your application_](https://falcon.readthedocs.io/en/stable/user/tutorial.html#testing-your-application).

Let me know if this helps!

**Comment by mthri** [comment]
Yes,that work🤦‍♂️

I replace:
```
resp.body = msgpack.pack(doc, ensure_ascii=False)
resp.status = falcon.HTTP_200
```
to:
```
resp.data = msgpack.packb(doc, use_bin_type=True)
resp.content_type = falcon.MEDIA_MSGPACK
resp.status = falcon.HTTP_200
```
in images.py

thank for help @vytas7

**Comment by vytas7** [comment]
Cool that this is understood now :+1: 

I also added a note to https://github.com/falconry/falcon/issues/1423 as we also realized our `requirements` in look are a bit dated and may cause issues in the future.
