### ISSUE TITLE
Errors in response serialization are not handled

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1607]
I found this when testing @kgriffs' ASGI branch, but this is an issue in all (recent) Falcon version, including the (at the time of writing) stable 2.0.

Errors in response serialization are not handled, for example:
* Missing media handler for the given [response content-type](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.content_type) results in an [HTTPUnsupportedMediaType](https://falcon.readthedocs.io/en/stable/api/errors.html#falcon.HTTPUnsupportedMediaType).
* Any exceptions raised in [media serialization](https://falcon.readthedocs.io/en/stable/api/media.html#falcon.media.BaseHandler.serialize).

This is somewhat more important now with the recently merged https://github.com/falconry/falcon/issues/1507. The user might expect that at least the generic handler catches the cases above. They would be instead propagated to the WSGI server.

**Comment by kgriffs** [comment]
It does seem like `HTTPUnsupportedMediaType` should be converted to an appropriate 415 response, and in the general case should be caught by the generic handler. I think we ought to fix this for 3.0 or 3.1.

**Comment by vytas7** [comment]
Scheduling this tentatively for 3.0 then, although we may need to push it to 3.1 or 4.0.

**Comment by vytas7** [comment]
Adding **blocked-by-release** while blocking on the ASGI branch (it makes sense to sync this change for both App flavours).

**Comment by vytas7** [comment]
I cannot reproduce this bug, it looks like it was fixed at some point (~2020 Jan).
I'll just add a couple of more explicit regression tests as per the issue's description.
