### ISSUE TITLE
Simulating POST request failing to decode json values.

### ISSUE THREAD

**Issue by Jithinqw** [falconry/falcon#1608]
I am using the falcon.testing to simulate a POST request, which is failing to decode my json values send from the tests

This is my test
```

@pytest.fixture()
def client():
    return testing.TestClient(api)

def test_param(client):
    body ={
        u'username':u'fsdfsdf',
        u'password':u'sdfsfsdf'
    }
    headers = {
        'Content-Type': 'application/json'
    }
    result = client.simulate_request(path='/api/v1/auth/user/register',method='POST', body=body, headers=headers)
    print(result.json)
    assert result.json
```

I have written a middleware to decode the json values from the user 

```
if req.content_length:
                    body = req.stream.read()
                    req.data = json.loads(body.decode('utf-8'))
                    print(req.data)
                return
```

This test raises an exception of not able to decode the JSON.

**Comment by xakiy** [comment]
Hi @Jithinqw, I think you should pass JSON string in body payload or use json.dumps() to serialize dict for you.

**Comment by Jithinqw** [comment]
I tried that still getting a decode error.

**Comment by xakiy** [comment]
Maybe you could provide some codes so we can reproduce the error.

**Comment by vytas7** [comment]
@xakiy thanks for helping out!

@Jithinqw indeed, it would be fantastic if could you craft a test case, as small as possible (ideally contained in one file or Gist), illustrating how to reproduce the issue.

As @xakiy pointed out, you should indeed use either `body=json.dumps(your_data)` or just `json=your_data` when simulating requests. If you use `json=`, you don't even need to set up any special content-type headers.

**Comment by Jithinqw** [comment]
@xakiy  The `json` or the `body` is not working. 
I am including a gist of my code
https://gist.github.com/Jithinqw/434f3f97baa54841429e0b17000b0f85
Here when I am sending the request, error is raised from the middleware. 
`{'title': 'Bad request', 'description': 'Invalid body. Unable to parse the given content'}`

Thank you @xakiy  and @vytas7 for helping out.

**Comment by vytas7** [comment]
Aha, I see... Could it be the same issue as this one https://github.com/falconry/falcon/issues/1569#issuecomment-531106395 ?
See also the related issues linked that comment.

@Jithinqw could you try replacing `json.loads(req.stream.read().decode("utf-8"))` with [`json.loads(req.bounded_stream.read().decode("utf-8"))`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.bounded_stream), and report the results?

**Comment by Jithinqw** [comment]
`json.loads(req.bounded_stream.read().decode("utf-8"))` perfectly. @vytas7 thank you for resolving this issue this fast :smile:
