### ISSUE TITLE
How to calculate request and response size if content-length is not provided?

### ISSUE THREAD

**Issue by darwinyip** [falconry/falcon#1610]
Content-Length is not always provided but it is good to know for monitoring purposes. Is there a way to calculate the responses and request size?

**Comment by vytas7** [comment]
Hi @darwinyip !
The request `Content-Length` should be IIRC always provided by the WSGI application server, i.e. the WSGI standard does not support streaming chunked requests. WSGI servers must handle any supported inbound "hop-by-hop" headers on their own, such as by decoding any inbound `Transfer-Encoding`, including chunked encoding if applicable [1](https://www.python.org/dev/peps/pep-0333/#other-http-features). To be precise, the WSGI standard states that `CONTENT_LENGTH` may be empty or absent, but Falcon interprets that case as if the request body was empty, when, for instance, utilizing `req.bounded_stream` [2](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.bounded_stream).

The response `Content-Length` is, on the other hand, up to you. You may set `resp.stream` to an iterable where the total amount bytes it would yield is unknown in advance. You could probably write a wrapper or a middleware to calculate the total length along the iteration, if this is desired, however, Falcon does not do that out of the box.

Does this shed some light on the topic, or did you have something else in mind?


1. https://www.python.org/dev/peps/pep-0333/#other-http-features
2. https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.bounded_stream

**Comment by vytas7** [comment]
Hi again @darwinyip ,
I am going to close this, assuming the above has answered your question, however, do not hesitate to reopen if you would like to further discuss the topic.

Adding to my previous answer, this type of monitoring is more common on the WSGI application server and/or the front-end proxy server (such as Nginx) side.
