### ISSUE TITLE
Can only import API, not App

### ISSUE THREAD

**Issue by NeilduToit13** [falconry/falcon#1624]
I'm not able to call falcon.App. I've seen in the code that API is a compatability patch set to be removed. falcon.API worked. I have no idea why. Looks to me like both are imported in __init__. Maybe something todo with Cython?

Environment:
- Ubuntu 16.04 lts

Steps to reproduce:
    $virtualenv --python=python3.8 venv
    $source venv/bin/activate
    $pip install cython
    $pip install -v --no-binary :all: falcon
    $pip install gunicorn

    #test2.py 
    import falcon
    app = falcon.App

    $ python test2.py 
    Traceback (most recent call last):
      File "test2.py", line 3, in <module>
        app = falcon.App
    AttributeError: module 'falcon' has no attribute 'App'
    

However it works if I do app = falcon.API

loving falcon otherwise! thanks for library.

**Comment by vytas7** [comment]
Hi @NeilduToit13 !
`falcon.API` will be renamed to `falcon.App` in our next major release, Falcon 3.0.

The current stable version is Falcon 2.0.

**Comment by NeilduToit13** [comment]
Haha okay. Yes it did. Thanks for clarifying.

**Comment by vytas7** [comment]
Heh, sorry for realtime editing of my answer. I happened to push it out via keyboard shortcuts a bit prematurely.

I'm going to close this issue, but I'll create another follow-up for the `README.rst` chicken-and-egg problem.

Besides from just giving it a try, if you're interested in the developmental version of Falcon, you can track our road towards 3.0 in this [Falcon 3.0 Roadmap Gist](https://gist.github.com/kgriffs/a719c84aa33069d8dcf98b925135da39) and the [3.0 Milestone here on GH](https://github.com/falconry/falcon/milestone/33).
