### ISSUE TITLE
Add to FAQ: How to set cookies in simulate request for testing 

### ISSUE THREAD

**Issue by kemingy** [falconry/falcon#1631]
Hi, Is there any way to set cookies in `simulate_request` for the testing client?

I didn't find the method to set cookies in the document. Setting `{'Set-Cookie': 'xxx=yyy'}` also does not work.

**Comment by vytas7** [comment]
Hi @kemingy!
There is indeed no explicit parameter to pass cookies to the simulated request, i.e. setting headers is the way to go.

Could it be that you happened to confuse the asymmetric nature of the cookie headers (i.e. [`Cookie` vs `Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies))?

The following case seems to work for me:
```python
import falcon
import falcon.testing
import pytest


class TastyCookies:

    def on_get(self, req, resp):
        resp.media = {'cookies': req.cookies}


@pytest.fixture
def client():
    app = falcon.API()
    app.add_route('/cookies', TastyCookies())

    return falcon.testing.TestClient(app)


def test_cookies(client):
    resp = client.simulate_get('/cookies', headers={'Cookie': 'xxx=yyy'})

    assert resp.json == {'cookies': {'xxx': 'yyy'}}
```

```
pytest test.py -v

<...>
collected 1 item                                                                                                                                                                                                                                                                              

test.py::test_cookies PASSED  
```

Let me know if this helps.

I'll keep the issue open though, it looks like it could be useful to add this question to our FAQ.

**Comment by kemingy** [comment]
Hi @vytas7 , thanks for your help. This method works!

**Comment by kemingy** [comment]
Hi @vytas7 , I just make a PR #1632 for this. Your example is excellent. So I just use it without any changes.

**Comment by kgriffs** [comment]
I think it would be great to add a _cookies_ kwarg to `simulate_request()` & friends. That way, you could just pass a mapping object of cookie key-value pairs, and the framework would serialize that out to a `cookie-string` per https://tools.ietf.org/html/rfc6265#section-5.4

In the meantime, however, updating the FAQ seems appropriate. 👍

**Comment by vytas7** [comment]
Yeah, my bad, I thought also creating a new issue for the proper `simulate_request()` parameter, but it never materialized. Until now: https://github.com/falconry/falcon/issues/1640 :slightly_smiling_face:

I thought just updating the FAQ in the meantime would be practical as the testing client is undergoing terraforming wrt the impending ASGI support.
