### ISSUE TITLE
Code listing for app.py in "look” Tutorial has a bug

### ISSUE THREAD

**Issue by robguinness** [falconry/falcon#1633]
In the [Serving images](https://falcon.readthedocs.io/en/stable/user/tutorial.html#serving-images) section, the code listing for `app.py` tries to import the `images` module as `import images`. I believe this should be `from look import images` or depending on one's preferences `import look.images` and refactor references to `images` as `look.images`. I prefer the former:

```python
import os

import falcon

from look import images


def create_app(image_store):
    api = falcon.API()
    api.add_route('/images', images.Collection(image_store))
    api.add_route('/images/{name}', images.Item(image_store))
    return api


def get_app():
    storage_path = os.environ.get('LOOK_STORAGE_PATH', '.')
    image_store = images.ImageStore(storage_path)
    return create_app(image_store)
```

**Comment by vytas7** [comment]
Indeed, well spotted!

**Comment by vytas7** [comment]
(It's probably better to use `from .images import ImageStore, Resource` etc just to stay consistent with the rest of the WSGI tutorial.)
