### ISSUE TITLE
Asynchronous interaction with the testing client

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1634]
Implement support and/or recipes for asynchronous interaction with the testing client, i.e. that the response content would not be computed in a single pass, but one could stream updates.

This is mostly relevant for testing ASGI SSE and WebSocket (when implemented).

It should be possible to simulate receiving SS events or WebSocket messages in response to other parallel simulated requests altering the tested app state.

**Comment by kgriffs** [comment]
I'll schedule for 3.0 for now, but we may need to push to 3.1

**Comment by kgriffs** [comment]
Here is an initial stab at designing the interface. Thoughts?

```py
# This context manages the ASGI app lifecycle, including lifespan events 
async with testing.ASGIConductor(some_app) as conductor:
    async def post_events():
        for i in range(100):
            await conductor.simulate_post('/events', json={'id': i})
            await asyncio.sleep(0.01)

    async def get_events_sse():
        while some_condition:
            # This will get the SSE body chunks emitted so far; subsequent calls
            #`  will get the next set of body lines emitted, etc.
            result = await conductor.simulate_get('/events')

    async def get_events_ws():
        # Simulate a WebSocket connection
        async with conductor.simulate_ws('/events') as ws:                
            while some_condition:
                message = await ws.receive_text()                

    asyncio.gather(post_events(), get_events_sse(), get_events_ws())
```

**Comment by onecrayon** [comment]
This makes sense to me as far as testing ASGI concurrent behavior (since you need to be able to run both read/write events simultaneously to emulate how the system works). It seems like overkill for testing of random endpoints where internal state matters less, though (like simple CRUD). Will it also be possible to run a synchronous `simulate_*()` call against an ASGI endpoint without setting up a conductor? Or does querying an ASGI endpoint with `simulate_*` necessitate asynchronous testing code?

**Comment by vytas7** [comment]
@onecrayon: I would let @kgriffs confirm, but I don't think any of this means that "normal" `simulate_*`s are going away.

My understanding is that they would continue to work with both sync and async _as-is_, this is just a bonus feature for people that actually _need_ this (as I wrote, I could imagine this being useful for testing WebSocket and, to a degree, SSE).

**Comment by kgriffs** [comment]
That's correct; I was thinking about adding this in addition to the synchronous `simulate_*()` interface. Although the conductor will probably be the only way to test WebSocket.

**Comment by onecrayon** [comment]
Yeah, that makes total sense; you can't really test a Websocket connection without some level of persistent connection handling. This all sounds good to me!

**Comment by vytas7** [comment]
A thought on the proposed design btw.
That's looking good, but maybe we could add a convenience shortcut to simply enter a [`TestClient`](https://falcon.readthedocs.io/en/latest/api/testing.html#falcon.testing.TestClient) as an async context manager:
```python
app = falcon.asgi.App()
# ...
client = falcon.testing.TestClient(app)
# ...
async with client as conductor:
    await conductor.simulate_brew(...)
    # etc...
```

**Comment by kgriffs** [comment]
Update: I have a draft of this in my fork...hoping to put up a PR soon.

See also: https://github.com/kgriffs/falcon/blob/feat/test-conductor/falcon/testing/client.py
