### ISSUE TITLE
Codify style for doctring summary lines

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1638]
Currently, we ask contributors to strive for consistency with existing code, but it would be helpful to clarify the following regarding docstrings:

- Docstrings should begin with a short (~70 characters or less) summary line that ends in a period.
- The summary line should begin immediately after the opening quotes (do not add a line break before the summary line)
- The summary line should describe what it *is* if it is a class (e.g., "An asynchronous, file-like object for reading ASGI streams.")
- The summary line should describe what it *does* when called, if it is a function, structured as an imperative (e.g., "Delete a header that was previously set for this response.")

We will need two patches to address this issue:

- [x] Update CONTRIBUTING.md to include the guidelines above
- [x] Fix up any existing docstrings to provide a baseline of consistency going forward

**Comment by danilito19** [comment]
@kgriffs I can help in updating CONTRIBUTING.md

**Comment by vytas7** [comment]
Hi @danilito19 ,
Awesome, thanks for your contribution :exclamation:

Could you attempt the second part too? It shouldn't be too hard either, mostly mechanical `grep`ping plus some touch ups in case people (for instance, me :smiling_imp: ) happened to merge non-conforming docstrings.

**Comment by danilito19** [comment]
Absolutely! I thought I needed a bit more understanding on the functions but I can grep and update without changing the wording / meaning.

**Comment by vytas7** [comment]
Fixed by @danilito19 in https://github.com/falconry/falcon/pull/1763
