### ISSUE TITLE
Setup.py uses the imp module that is deprecated

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1651]
while trying to run `python setup.py test` I get the warning
`DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses`

Since python 2 is no longer supported I think we can migrate to `importlib`

**Comment by CaselIT** [comment]
I can try to fix it @nZac

**Comment by nZac** [comment]
Whoops, didn't see you had made the comment @CaselIT and submitted a PR.

**Comment by CaselIT** [comment]
same :/
