### ISSUE TITLE
Improve test readme. Without setting the proper env variable 300+ failure occur

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1652]
If I follow the readme to run the test

> You can manually test changes to the Falcon framework by switching to the directory of the cloned repo and then running pytest:

> $ cd falcon
> $ pip install -r requirements/tests
> $ pytest tests

I get the following result 
` 261 failed, 1819 passed, 20 skipped, 40 warnings, 128 errors`

I've tried with tox and it works correctly.

I've traced the issue to the missing env variable `FALCON_ASGI_WRAP_NON_COROUTINES=Y`

I think the readme should mention it

**Comment by CaselIT** [comment]
maybe the variable `FALCON_ASGI_WRAP_NON_COROUTINES` should just be set in `conftest` since it is clearly required by the test?

**Comment by vytas7** [comment]
We ought to clean this up the 3.0 beta release.

**Comment by CaselIT** [comment]
This can be solverd by placing in `setup.cfg` under the `[tool:pytest]` key
```
env =
    FALCON_ASGI_WRAP_NON_COROUTINES = Y
    FALCON_TESTING_SESSION = Y
    PYTHONASYNCIODEBUG = 1
```

**Comment by vytas7** [comment]
Reopening this, as it apparently requires the [`pytest-env`](https://pypi.org/project/pytest-env/) plugin that we haven't documented.

Alternatively, we could just look at what the said plugin does, and vendor it in `conftest.py` (considering it hasn't been updated in 3 years+).
