### ISSUE TITLE
Falcon middleware is not returning error when in try catch block

### ISSUE THREAD

**Issue by Jithinqw** [falconry/falcon#1660]
Falcon middleware is not returning HTTP error when the code breaks in try catch block.

Instead of getting` User name does not exist`, I am getting `Some thing went wrong`
```
try:
            session = db_session()
            user_exist_instance = (
                session.query(users_table.email)
                .filter(users_table.email == req.data["email"])
                .first()
            )
            if not user_exist_instance:
                raise falcon.HTTPBadRequest(
                    title="Bad Request", description="User name does not exist"
                )
            else:
                return
        except Exception as err:
            raise falcon.HTTPBadRequest(
                title="Bad Request", description="Some thing went wrong"
            )
```

**Comment by CaselIT** [comment]
the error `raise falcon.HTTPBadRequest(title="Bad Request", description="User name does not exist"           )` is intercepted by the except cause that you have placed ` except Exception as err:`
This is the default python behavior.
Try adding 
```py
except falcon.HTTPError:
    raise
```
before the other exception, so that falcon errors are reraised as is

**Comment by vytas7** [comment]
@Jithinqw does @CaselIT's answer shed some light on the subject, or would you still like to suggest an improvement how the framework could be helpful in this scenario?

**Comment by Jithinqw** [comment]
Thank you @CaselIT and @vytas7 for your response. Your solution have worked. 
@vytas7  don't you think we could make this implementation cleaner. People reading code will think I am doing some kind of hacking.

**Comment by vytas7** [comment]
@Jithinqw how could the framework implementation be cleaner in this case?
I'm all ears if you have any concrete suggestions.

To rephrase @CaselIT 's answer, if you had a code block
```python
try
    # do things
    raise MyError
except Exception:
    # handle exceptions
```
The `except` clause will catch any exception inheriting from `Exception`, including Falcon's `HTTPError` & `HTTPStatus`. This is how the Python language works.

Maybe you don't need to catch that exception at all, and rely on [exception handlers](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_error_handler), or alternatively raise more specialized exception classes and catch/reraise only these.

I'm going to close this question now, but as said, do not hesitate to reopen if you have any suggestions to improve Falcon's error handling!
