### ISSUE TITLE
[pylint E1101] [E] Module 'falcon' has no 'HTTP_200' member (no-member)

### ISSUE THREAD

**Issue by zubairakram** [falconry/falcon#1671]
pylint is not recognizing falcon status codes. e.g HTTP_201

```python
import falcon

class ObjectRequestClass:
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_201
```

**Comment by vytas7** [comment]
Hi @zubairakram !
And thanks for reporting this issue!

However, I do believe it is already tracked in our system: https://github.com/falconry/falcon/issues/1553

Closing this one as duplicate, but don't hesitate to provide more information if you believe this is a separate problem!
