### ISSUE TITLE
FAQ item "How do I consume a query string that has a JSON value?" is outdated

### ISSUE THREAD

**Issue by suola** [falconry/falcon#1676]
The default value of `falcon.RequestOptions.auto_parse_qs_csv` was changed to `False` in v2.0 and handled in https://github.com/falconry/falcon/issues/842 and https://github.com/falconry/falcon/pull/1318.

The FAQ item https://falcon.readthedocs.io/en/stable/user/faq.html#how-do-i-consume-a-query-string-that-has-a-json-value assumes the old default value and needs an update.

**Comment by vytas7** [comment]
Scheduling for 3.1 since the current FAQ item is not technically wrong _per se_, it is just unaware of the new default value. I.e. one can still follow the recipe and achieve the documented outcome.

**Comment by vytas7** [comment]
Hm, OTOH, the first part is outright contradicting the current behaviour and other docs... :grimacing:

**Comment by vytas7** [comment]
From @suola on Gitter:
> it is not clear to me how to fix this, e.g.
> 1) update the text in the FAQ item
> 2) delete it altogether,
> 3) replace it with e.g. an item describing how to use commas as a list separator, or
> 4) something else.

We ought to rewrite this FAQ item by linking to [`Request.get_param_as_json`](https://falcon.readthedocs.io/en/latest/api/request_and_response_wsgi.html#falcon.Request.get_param_as_json), and provide an example demonstrating how to do that.

**Comment by kgriffs** [comment]
Let's try to get this into 3.0; should be an easy task.

**Comment by AR4Z** [comment]
Hi, I'm interested in contributing. Could I help to solver this?

**Comment by vytas7** [comment]
@AR4Z , yes you're very welcome!

**Comment by vytas7** [comment]
Resolved fixed in #1700
