### ISSUE TITLE
Can I disable http logging to stdout if I run app without gunicorn

### ISSUE THREAD

**Issue by MasterSoft24** [falconry/falcon#1677]
I've run the falcon app simply run serve_forever() and got to stdout many records like a
127.0.0.1 - - [19/Feb/2020 08:54:00] "GET /queue/collected HTTP/1.1" 200 70

Can I disable this?

**Comment by vytas7** [comment]
Hi @MasterSoft24 !
As Falcon does not ship any WSGI server, I presume you are using `wsgiref.simple_server` or similar, e.g., as shown in [`wsgiref` examples](https://docs.python.org/3.8/library/wsgiref.html#examples).

Falcon is not logging requests itself, so this sounds more like a Python stdlib question.

Maybe something along the lines of https://stackoverflow.com/a/31904641 could do? (May be outdated, haven't tested myself).

**Comment by MasterSoft24** [comment]
Thanks a lot! Yes, this is it!
