### ISSUE TITLE
Unify behavior between asgi and wsgi

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1679]
Currently the implementation of the response class for the wsgi and the asgi differ when handling the `data` property. Namely the asgi version does not override data with the media value, while the wsgi version overrides the data with the media serialization data.

In the code on master there are currently these todos
https://github.com/falconry/falcon/blob/c3e91875f1030c68d17efa27cf8df3d18f337761/falcon/response.py#L192-L195
https://github.com/falconry/falcon/blob/c3e91875f1030c68d17efa27cf8df3d18f337761/falcon/response.py#L192-L195

Should the wsgi response class behave like the asgi, and use the method `render_body` to get the body in the response?

**Comment by CaselIT** [comment]
@vytas7 on gitter pointed out that there are also other differences between wsgi and asgi. Like the `Request.get_media` and the current draft of the async multipart media handler

This is mainly because an async property is odd, and may trick people that are not used to this.

To try and have an api as uniform as possible between asgi and wsgi, maybe an heuristic could be:
- take constant time to execute regardless of the request? a property is probably fine in both cases
- depends on the request/resposne? a function is probably better, and the asgi would be async

**Comment by vytas7** [comment]
Anything doing I/O is probably better off as a method.
Async makes it crystal clear by requiring you to `await` things.

However, even if we adopt this thinking, we'll have to provide WSGI property compatibility aliases for a long time. Serious interface stability is among the main selling points of Falcon, after all.

**Comment by CaselIT** [comment]
If they are just getters, the property would be just `media = property(get_media)`

Maybe the path could be. Alias in v3 (maybe deprecated just in the comments), deprecate in v4, remove v5?

For asgi and multipart, since they are new, the alias would not be there?

**Comment by kgriffs** [comment]
> Maybe the path could be. Alias in v3 (maybe deprecated just in the comments), deprecate in v4, remove v5?

I'd say just alias in v3 but do not deprecated until v4. 

> For asgi and multipart, since they are new, the alias would not be there?

For ASGI we are trying to make it as similar as possible to WSGI (minus stuff that is deprecated in WSGI for v3), so I think it would still be a good idea to, for example, add a req.media property alias.

**Comment by CaselIT** [comment]
I can try working on it. I'll start by unifying the request and response classes

**Comment by vytas7** [comment]
@CaselIT I think you should coordinate this with @kgriffs as we've just merged the PR for ASGI reintroducing the async media property. 
It might be worth getting some feedback from the community first, i.e., whether people want to move away from properties at all wrt WSGI Falcon.

**Comment by CaselIT** [comment]
Yes, that was the plan for now I think. Have both, at least in the wsgi version.
Then for v4 it can be decided if only one solution should be kept or not, and apply the appropriate deprecations.

**Comment by kgriffs** [comment]
Let's start with a PR and breaking change notes in docstrings and towncrier news for updating WSGI per `render_body()`.

Can you enumerate/add a checklist for any other changes you were considering?

**Comment by CaselIT** [comment]
Here is something I've found:
- Request: bounded_stream vs stream. Not sure any change can be made here since in wsgi are two different values, while asgi are aliased
- BodyPart: I guess all properties should be alias of methods `get_X`
