### ISSUE TITLE
Adopt PEP 517

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1683]
It is getting increasingly annoying to install Falcon with Cython support using anything but the official stable release wheels.
At some point we'll need to switch the Falcon package build system to use [PEP 517](https://www.python.org/dev/peps/pep-0517/).

- [x] Pick a [PEP 517](https://www.python.org/dev/peps/pep-0517/) compliant build tool
- [x] Support Cython by default on the relevant platforms
- [x] Make it easy to skip cythonization

A non-exhaustive list of build tools that could be used
* [Setuptools](https://setuptools.readthedocs.io/en/latest) -- most incremental change; check if it fits the requirements above though
* [Flit](https://flit.readthedocs.io/en/latest) -- a bit spartan for our use?
* [Poetry](https://python-poetry.org) -- very solid machinery for dependency management, but we don't have any runtime deps :stuck_out_tongue_winking_eye:
* [Enscons](https://bitbucket.org/dholth/enscons) -- interesting but best suited if one already is a `scons` user?
* Anything else?

**Comment by CaselIT** [comment]
> Anything else?

- setuptools is a valid build tool even with pep517. See example https://github.com/pypa/setuptools/blob/f63c4335178512ad1db730222d54fc0df84ae798/pyproject.toml#L7

**Comment by vytas7** [comment]
Yeah, thanks @CaselIT ! I was actually about to write that too, but it never happened. Fixing now.

**Comment by CaselIT** [comment]
Btw, I've tried setuptools pep517 mode for sqlalchemy, and it seems to execute the setup.py as when running in non-pep 517 mode, so it respects the env arguments and/or fallback if the compiler or cython is not found.

**Comment by vytas7** [comment]
I meant that while at it, it would be great if we could encapsulate cythonization as part of the PEP-517 build system, i.e. the user would only have to `pip install`, even from a source checkout.

**Comment by CaselIT** [comment]
I think you can do something like this with setuptools that works with or without pep517. Take a look at the [setup.py of sqlalchemy](https://github.com/sqlalchemy/sqlalchemy/blob/master/setup.py). It first tries to build the c extension and fallback it that fails

Using pep517 allows a package to specify a list of requirements to install your package, cython could be one of them, I guess. I have not tried it so I may be wrong.
Example pyproject.toml with the requirements:
https://github.com/pypa/setuptools/blob/3aeec3f0e989516e9229d9a75f5a038929dee6a6/pyproject.toml#L2-L7

**Comment by CaselIT** [comment]
I've tried to adapt the sqlalchemy setup to falcon here:
https://github.com/CaselIT/falcon/commit/bedc2fb06d604bf3e9395a7ad93d5206674e25f3
The tests seen to pass https://travis-ci.org/github/CaselIT/falcon/builds/669415425

Should I open a draft pr so we can discuss / experiment it there?

**Comment by kgriffs** [comment]
If we could get this to work, then hopefully we won't need the --no-build-isolation hack

**Comment by CaselIT** [comment]
You can add the pyproject.toml to the ignore list when distributing to pypi.
Its absence makes pip not use pep517

**Comment by CaselIT** [comment]
Sqlalchemy currently is doing that, since pep517 seems still broken in some cases. Like in debian unstable the system pip has a broken pep517 module.
https://github.com/pypa/pip/issues/7874#issuecomment-606839554

**Comment by CaselIT** [comment]
An alternative to this may be to use a ci to build wheels for the various oses.
I've just experimented with using github actions to build wheels for sqlalchemy that has similar requirements, (has optional c modules).
I think I could adapt that github action workflow fairly easily for falcon.

For reference this is the current version of the action https://github.com/CaselIT/sqlalchemy/blob/36b3100b07e83866d8d5e6fa211c05c0aaacdf9c/.github/workflows/create-wheels.yaml

**Comment by vytas7** [comment]
Resolved fixed in #1709
