### ISSUE TITLE
Update of "Getting started" doc part about falcon.App()

### ISSUE THREAD

**Issue by leefyi** [falconry/falcon#1699]
A tiny normal issue about the verbal part in "Getting started".
I think in version 2.0.0, there is no more 
"""
app=falcon.App()
"""
but 
"""
app=falcon.API()
"""
![image](https://user-images.githubusercontent.com/8380059/76737453-c6270e80-67a3-11ea-9e00-a60ac1f59d72.png)

Could you please try to update it as to be more friendly to new users such as me.

**Comment by CaselIT** [comment]
version 3 renames `API` to `App`, so the docs are actually correct for v3, which the master branch is traking.

**Comment by vytas7** [comment]
Hi @leefyi !
Indeed, this became a bit of a time warp; as also explained by @CaselIT , `App` is actually newer than `API`.

I am going to close this by merging with https://github.com/falconry/falcon/issues/1625 though, as the underlying problem is the same.
