### ISSUE TITLE
text/xml; charset=utf-8 is an unsupported media type

### ISSUE THREAD

**Issue by lon91ong** [falconry/falcon#1718]
Client request raw:
```
POST http://127.0.0.1:9542/BizService.svc HTTP/1.1
Content-Type: text/xml; charset=utf-8
SOAPAction: "http://www.ustcori.com/2009/10/IBizService/DoService"
Host: 127.0.0.1:9542
Content-Length: 590
Expect: 100-continue
Connection: Keep-Alive

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><DoService xmlns="http://www.ustcori.com/2009/10"><request>...</request></DoService></s:Body></s:Envelope>
```
Server response raw:
```
HTTP/1.1 415 Unsupported Media Type
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 18000
Content-Length: 107
Content-Type: application/json
Date: Sun, 26 Apr 2020 13:07:54 GMT
Server: waitress
Vary: Accept

{"title": "Unsupported media type", "description": "text/xml; charset=utf-8 is an unsupported media type."}
```

source code:
```
import falcon
from waitress import serve
from falcon.http_status import HTTPStatus
from xml.etree.ElementTree import fromstring

class HandleCORS(object):
    def process_request(self, req, resp):
        resp.set_header('Access-Control-Allow-Origin', '*')
        resp.set_header('Access-Control-Allow-Methods', 'POST')
        resp.set_header('Access-Control-Allow-Headers', '*')
        resp.set_header('Access-Control-Max-Age', 18000)  # 5 hours
        if req.method == 'OPTIONS':
            raise HTTPStatus(falcon.HTTP_200, body='\n')

class Resource(object):
    def on_post(self, req, resp):
        ...

if __name__ == '__main__':
    svrRes = Resource()
    app = falcon.API(media_type='text/xml',middleware=[HandleCORS()])
    app.add_route('/BizService.svc', svrRes)
    
    serve(app, listen = '127.0.0.1:9542')
```

HELP PLEASE .... !

**Comment by vytas7** [comment]
Hi @lon91ong !
I'm assuming you are attempting to use [Falcon Media](https://falcon.readthedocs.io/en/stable/api/media.html) to consume the submitted XML document.

Out of the box, Falcon 2.0 only supports JSON media (Falcon 3.0 will add HTML form support).
Which means you need to either read the request stream, and parse it in your responders/hooks/middleware, or implement a new [custom Media handler](https://falcon.readthedocs.io/en/stable/api/media.html#custom-handler-type) to parse XML.

Just for the heck of it, let's try the latter.
I was able to run the example below with `gunicorn test:app`, assuming I named the file `test.py`:
```python
from xml.etree import ElementTree

import falcon
from falcon import media


class XMLHandler(media.BaseHandler):

    def deserialize(self, stream, content_type, content_length):
        return ElementTree.fromstring(stream.read())

    def serialize(self, media, content_type):
        raise NotImplementedError


class XMLResource:

    def on_post(self, req, resp):
        resp.media = [child.attrib for child in req.media]
        resp.set_header('X-Rant', 'Does S in SOAP really stand for Simple?')


app = falcon.API()
# Replace the default request media handlers to only support XML
app.req_options.media_handlers = media.Handlers({
    'text/xml': XMLHandler(),
})

app.add_route('/test', XMLResource())
```

**Comment by lon91ong** [comment]
@vytas7 Thank you very much, your code work well.
but when I add `waitress` as server , then got `HTTP/1.1 500 Internal Server Error`
test code:
```
import falcon
from falcon import media
from waitress import serve
from xml.etree.ElementTree import fromstring

class XMLHandler(media.BaseHandler):
    def deserialize(self, stream, content_type, content_length):
        return fromstring(stream.read())

    def serialize(self, media, content_type):
        raise NotImplementedError

class XMLResource:
    def on_post(self, req, resp):
        resp.media = [child.attrib for child in req.media]
        resp.set_header('Content-Type', 'text/xml')
        resp.status = falcon.HTTP_200

if __name__ == '__main__':
    app = falcon.API(media_type='text/xml')
    app.req_options.media_handlers = media.Handlers({
        'text/xml': XMLHandler(),
    })
    app.add_route('/test', XMLResource())
    
    serve(app, listen = '127.0.0.1:9542')
```

**Comment by vytas7** [comment]
@lon91ong The above solution should roughly translate to the response media as well.

See that `XMLHandler.serialize`? We could either extend that to be able to serialize XML, or just serialize it in the responder, and set the response content to it.
See also here (from the unstable 3.0.0 alpha docs, but it should apply verbatim to Falcon 2.0 too): [When would I use media, data, and stream?](https://falcon.readthedocs.io/en/latest/user/faq.html#when-would-i-use-media-data-and-stream).

Our [Tutorial](https://falcon.readthedocs.io/en/latest/user/tutorial.html) could also be helpful as a reference, as it illustrates serving MessagePack responses instead of the default `application/json`.

Getting back to our example from my first answer, XML serialization is more complex since the data is potentially more complex, so it might be hard to write an XML Media serializer that is both convenient, and flexible.
Let's try just to set the response data instead:
```python
from xml.etree import ElementTree

import falcon
from falcon import media


class XMLHandler(media.BaseHandler):

    def deserialize(self, stream, content_type, content_length):
        return ElementTree.fromstring(stream.read())

    def serialize(self, media, content_type):
        raise NotImplementedError


class XMLResource:

    def on_post(self, req, resp):
        countries = []
        for child in req.media:
            countries.extend(child.attrib.values())

        resp.set_header('X-Rant', 'Does S in SOAP really stand for Simple?')

        document = ElementTree.Element('resp')
        msg1 = ElementTree.SubElement(document, 'message')
        msg1.text = 'Hello, World!'
        msg2 = ElementTree.SubElement(document, 'message')
        msg2.text = ', '.join(sorted(countries))

        resp.content_type = 'text/xml; charset=utf-8'
        resp.data = ElementTree.tostring(document, encoding='utf8')


app = falcon.API()
# Replace the default request media handlers to only support XML
app.req_options.media_handlers = media.Handlers({
    'text/xml': XMLHandler(),
})

app.add_route('/test', XMLResource())
```

Sending the same example request from my previous answer:
```python
>>> resp = requests.post('http://localhost:8000/test', data=EXAMPLE, headers={'Content-Type': 'text/xml; charset=utf-8'})
>>> print(resp.text)
<?xml version='1.0' encoding='utf8'?>
<resp><message>Hello, World!</message><message>Liechtenstein, Panama, Singapore</message></resp>
```

One more side note on XML. Beware most XML parsers are unsafe against untrusted input. A highly recommended read if you are dealing with external requests: [XML vulnerabilities](https://docs.python.org/3/library/xml.html#xml-vulnerabilities).

**Comment by lon91ong** [comment]
@vytas7 Thanks a lot！
`resp.data` confused with `media` and `stream`，I need read the manual carefully.
Thanks !

**Comment by vytas7** [comment]
Heh, no worries, `resp.stream` vs `resp.data` vs `resp.data` vs `resp.media` were admittedly causing some confusion, particularly among new Falcon users. That's exactly why we've added [the said FAQ item](https://falcon.readthedocs.io/en/latest/user/faq.html#when-would-i-use-media-data-and-stream) to the upcoming Falcon 3.0 docs.

I'm going to close this issue, but don't hesitate to reopen or create a new one, should you stumble upon further Falcon issues.
