### ISSUE TITLE
Updating to Falcon 2.0 breaks my tests with simulate_post

### ISSUE THREAD

**Issue by MirkoRossini** [falconry/falcon#1720]
Hello,

I started working on a project that I shelved some time ago. I upgraded to falcon 2 but many of my tests are now broken.

When I try to use simulate_post with json like this (using pytest):

```python
@pytest.fixture(scope='function')
def client(connection: PsqlConnection):
    app = configure_app(connection)
    return testing.TestClient(app)


def test_update(client: TestClient):
  
    result = client.simulate_post(f'/book/{book.id}/chapters', json=TEST_JSON)
    assert result.status_code == 201
```

I get this error:

 ```
_ 
python3.6/site-packages/falcon/testing/client.py:711: in simulate_post
    return self.simulate_request('POST', path, **kwargs)
python3.6/site-packages/falcon/testing/client.py:764: in simulate_request
    return simulate_request(self.app, *args, **kwargs)
python3.6/site-packages/falcon/testing/client.py:348: in simulate_request
    iterable = validator(env, srmock)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/wsgiref/validate.py:181: in lint_app
    iterator = application(environ, start_response_wrapper)
python3.6/site-packages/falcon/api.py:269: in __call__
    responder(req, resp, **params)
python3.6/site-packages/falcon/hooks.py:179: in do_before
    action(req, resp, self, kwargs, *action_args, **action_kwargs)
app/resources/_hooks.py:45: in json_data_extract
    params['json_data'] = json.load(req.stream)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py:296: in load
    return loads(fp.read(),
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/wsgiref/validate.py:197: in read
    assert_(len(args) == 1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cond = False, args = ()

    def assert_(cond, *args):
        if not cond:
>           raise AssertionError(*args)
E           AssertionError
```

I found some related bugs but they seem to be resolved except https://github.com/AndreiRegiani/falcon-jsonify/issues/13, although I don't know if this library is used in falcon.

Thanks

**Comment by vytas7** [comment]
Hi @MirkoRossini !
Falcon 2.0 has no hard dependencies itself. It is not using `falcon-jsonify` by any means out of the box, unless you choose to install the said middleware yourself.

It seems you have decorated your `on_post` responder with a hook, could you post the source code for that hook?

Another change that may be of interest here is that as of 2.0, [Falcon is no longer shimming `req.stream` by default, which may cause issues in certain cases](https://falcon.readthedocs.io/en/stable/user/faq.html#why-does-req-stream-read-hang-for-certain-requests).
Could you try [`req.bounded_stream`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.bounded_stream) in your hook, something along the lines of
```python
params['json_data'] = json.load(req.bounded_stream)
```
Let me know if the above makes any difference :arrow_upper_left: 

Furthermore, FWIW, an even easier way to access JSON payload in recent versions of Falcon is just using [`req.media`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.media).

**Comment by MirkoRossini** [comment]
Hi Vytautas,
Thank you so much for your help, modifying the hook to use bounded_stream solved the issue!

Sorry for wasting your time, I'm a bit rusty on Falcon.

Thanks again for the prompt response!

Mirko

**Comment by vytas7** [comment]
Heh, no worries.
Although ostensibly simple and well documented, this change has easily been among the most confusing ones.
We do believe it was a necessarily evil though, because we want to provide the raw `req.stream` for users that do not need this (`req.bounded_stream`) layer of abstraction.

E.g.,
* https://github.com/falconry/falcon/issues/951
* https://github.com/falconry/falcon/issues/1469
* https://github.com/falconry/falcon/issues/1554
* https://github.com/falconry/falcon/issues/1565

Closing this issue, but don't hesitate to report any other Falcon problems you encounter!
