### ISSUE TITLE
CPython 3.9 support

### ISSUE THREAD

**Issue by carlwgeorge** [falconry/falcon#1724]
Last week CPython 3.9 had it's first beta release.  The final release is scheduled for 2020-10-05.  Fedora has already packaged 3.9 and is working on rebuilding all packages for 3.9.  The falcon test suite fails when run on 3.9.

https://bugzilla.redhat.com/show_bug.cgi?id=1793129

If you can point me to any relevant pull requests or commits that resolve the failures, I can include them in the package as temporary patches until a new version of falcon is tagged.

**Comment by vytas7** [comment]
Hi @carlwgeorge !
And first of all, let me thank you for your awesome work in maintaining Falcon packages for Fedora Linux :+1: 

Regarding the stable Falcon version (2.0.0) and the 2.x series on 3.9 in general... I'm afraid we might be unable to spare resources to make that happen... Any contributions in that direction are very welcome though.

However, I'm fairly confident Falcon 3.0 should see a stable release before CPython 3.9.0 is out.

FWIW, I've just tested 3.0.0a1 and `tox -e py39` passes for me. Using commands along the lines of:
```shell
docker run --rm -it python:3.9.0b1 /bin/bash
```
```shell
git clone https://github.com/falconry/falcon /tmp/falcon
cd /tmp/falcon
git checkout 3.0.0a1

pip install tox
tox -e py39
```

I'm thinking we could add a CPython 3.9 beta (with and without Cython) gate to our CI as the first step.

**Comment by carlwgeorge** [comment]
That's great news.  Currently CPython 3.9 is only in Fedora Rawhide (the development branch), so it's perfectly acceptable for me to update the Rawhide python-falcon package to an alpha release.  I'll need to create packages for uvicorn and daphne first in order to update it, but it's good to hear confirmation that Falcon 3.0 is expected to work.

**Comment by vytas7** [comment]
@carlwgeorge As part of migration to GitHub actions, we are now running CPython 3.9 gates for both pure-Python and Cython builds for every commit and PR.

I will leave this issue open for now though, we'll add proper CPython 3.9 support when it is released.

**Comment by vytas7** [comment]
Closing this; even though our tooling is still slightly more centered on CPython 3.8, CPython 3.9 is now fully supported, as mentioned above, in the CI, as well as in form of Falcon 3.0 shipping 3.9 binary wheels for all major platforms: https://pypi.org/project/falcon/3.0.0/#files.
