### ISSUE TITLE
No way

### ISSUE THREAD

**Issue by dmproia** [falconry/falcon#1726]
He took the code beginning of 2017, not 7 years ago. Don’t be a dick as the source code was stolen at that point and implemented on this.

**Comment by vytas7** [comment]
Hi again,
please be civilized and refrain from profanities as required by our [Code of Conduct](https://github.com/falconry/falcon/blob/master/CODEOFCONDUCT.md), or I'll ban you from all Falconry projects. This is the last warning.

If you are claiming that some of your code (that was proprietary or open source with a license that is incompatible to [ours](https://github.com/falconry/falcon/blob/master/LICENSE)) was allegedly appropriated into the Falcon code base, please specify which files, lines etc are affected, and please provide proof behind your claims.

**Comment by dmproia** [comment]
While that may be true, I started it using a baremetal Rackspace hack I created locally around beginning of Jan 2017 using Ubuntu 12 and updating to Ubuntu’s 16 from an msige72-6qf laptop where I have comodo certificates linked to my original source code. If you require me to get a lawyer I can but this was legally registered to me and from what it appears kgriffs did a few major overhauls to his code using 99% of my stuff within a few months. I have you guys with your names hard coded all over my machine where you kept doing updates. See you in Tahiti, David

**Comment by kgriffs** [comment]
We simply can not address unsubstantiated claims. Regardless, this appears to be bot spam.

**Comment by dmproia** [comment]
I’m not a bot but if you wish to ignore me go ahead and I’ll get a lawyer

**Comment by dmproia** [comment]
![image](https://user-images.githubusercontent.com/62180168/83285129-5a99ee00-a1a3-11ea-9e0c-143817c4a476.jpeg)

Proof and your name is tied to it which is tied to my source code and certificates.

**Comment by vytas7** [comment]
Getting a lawyer sounds like a smart idea, particularly when one is involved in questionable activities such as operating spam bots.

In any case, this is a technical bug tracker, and we cannot resolve legal disputes here. Closing this issue.
