### ISSUE TITLE
Add support for getting the routes and resources set on a falcon.API instance

### ISSUE THREAD

**Issue by jhuitema** [falconry/falcon#1727]
Can we get a publicly exposed way of getting the resources that have routes on a falcon.API object?

Currently I'm only aware of one way to do this, which does not seem clean or safe:

```python
app = falcon.API()
...
routes = copy.copy(app._router._roots)
for route app._router._roots:
    routes.extend(route.children)
print(routes)
```

The use case I want to be able to support is auto-generating the "/info" endpoint based on the currently added routes. The example above is a simplified version of what [falcon-apispec](https://github.com/alysivji/falcon-apispec/blob/a5e665ec3c95e3a83320e50498897b78439116aa/falcon_apispec/falcon_plugin.py#L15) has to do to get the URI -> resource mapping that it uses for this use case.

Could we get something like ``app.get_routes()`` or ``app.get_resources()``? My initial thought is the return value would be a dict with each URI as the key and the connected resource class instance as the value but as long as I can tell which resources are connected to which URI(s) I'll be happy.

**Comment by vytas7** [comment]
Hi @jhuitema !
We have recently merged some improvements on that front, mainly thanks to @CaselIT .

Could you try installing the latest version from Git `master`, and check whether the new [Inspect Module](https://falcon.readthedocs.io/en/latest/api/inspect.html) fits your bill?

**Comment by CaselIT** [comment]
Currently the inspect module only saves the string info of most things, but it should not be too hard to also save the actual object alongside them, so that they could be further used for additional analysis.

**Comment by jhuitema** [comment]
That's looks like it will solve my problems nicely. I'll have a play and let you kknow how it goes.

Thanks

**Comment by vytas7** [comment]
Hi again @jhuitema !
Have you had a chance to experiment with the new [Inspect Module](https://falcon.readthedocs.io/en/stable/api/inspect.html)?

As of 3.0.0+, the functionality in question is now a part of our stable releases.

**Comment by jhuitema** [comment]
Sorry for the slow response. I've had a play with this and this does exactly what I need (and more).

Thanks so much!
