### ISSUE TITLE
Why the examples need to modify, or it can not run

### ISSUE THREAD

**Issue by mansonami** [falconry/falcon#1744]

**Comment by vytas7** [comment]
Hi @mansonami !
You'll need to be more specific.
Do you mean that some of our examples are buggy, and don't run unmodified?
If so, which examples do you mean specifically, and which errors are you seeing?

Could it be the same issue as https://github.com/falconry/falcon/issues/1534 ?

**Comment by vytas7** [comment]
Hi again @mansonami ,
just checking whether you had a chance to look at my counterquestion, and whether it is still an issue for you?

**Comment by vytas7** [comment]
Hi again @mansonami ,
In the absence of further information, I am going to close this issue now.

Do not, however, hesitate to reopen it or file a new one in case you would like to share more details.
