### ISSUE TITLE
Response.downloadable_as does not follow RFC 6266 recommendations for UTF-8

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1749]
At the time of writing, [Response.downloadable_as](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.downloadable_as) always uses the `attachment; filename="filename.ext"` form regardless of the provided filename. However, [RFC 6266](https://tools.ietf.org/html/rfc6266) specifies that a quoted `filename` shall be interpreted as ISO-8859-1 (although some agents are able to sniff UTF-8), and recommends using `filename*` whenever `filename` cannot be faithfully represented with US-ASCII.

**Comment by CaselIT** [comment]
I believe we have to escape a comma `,` because chrome does not like this.

The following example breaks on chrome, (but works on firefox)
```py
import falcon

class R:
    def on_get(self, req,res):
        res.text = '123'
        res.downloadable_as = '≥,.txt'

app = falcon.App()
app.add_route('/try', R())
```
