### ISSUE TITLE
Is it possible to access the route that the data will be forwarded to inside a middleware (process request)?

### ISSUE THREAD

**Issue by FerusAndBeyond** [falconry/falcon#1762]
I have a middleware where I want to process some data depending on what route it will be forwarded to, thus I'm wondering if it's possible to obtain any information on what route the data will be forwarded to.

**Comment by vytas7** [comment]
Hi @FerusAndBeyond !

It depends on which [middleware stage](https://falcon.readthedocs.io/en/stable/api/middleware.html) you are processing at:
* In `process_request`, you have **no access** to the routing decision; it is yet to be made. In fact, you can even rewrite `req.path` at this stage to redirect internally.
* In `process_resource`, you are provided with the routed `resource` object, as well as the chosen route is reflected in the req.uri_template.

Does that shed some light on the issue, or do you have further thoughts on the subject?

**Comment by FerusAndBeyond** [comment]
Okay, I should use `process_resource` instead of `process_request` 👍  Thanks!
