### ISSUE TITLE
Parameters unexpectedly captured from field expressions in multiple routes

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1779]
Based on a report by @tim-clipchamp on Gitter.

Consider the following example
```python
import falcon
import falcon.testing


class Resource:
    def __init__(self, name):
        self.name = name

    def on_get(self, req, res, **kw):
        print(self.name, kw)


api = falcon.API()
api.add_route("/upload/{service}/auth/token", Resource('service'))
api.add_route("/upload/youtube/{project_id}/share", Resource('project'))

client = falcon.testing.TestClient(api)
client.simulate_get('/upload/youtube/auth/token')
```
which produces the following output (tested with Falcon 1.4.1, 2.0 and 3.0.0a2; the 3.0 series also emit the expected `API` deprecation warning):
```
service {'project_id': 'auth', 'service': 'youtube'}
```

The expectation is that only field expressions from the matched route should be used.
Instead, the observed result here is that the `{project_id}` field expression from a non-matching route is also present in the evaluated responder parameters.

**Comment by CaselIT** [comment]
This is the find src generated. The issue is obvious looking at it, but I'm not sure how to best solve it

```py
def find(path, return_values, patterns, converters, params):
    path_len = len(path)
    if path_len > 0:
        if path[0] == 'upload':
            if path_len > 1:
                if path[1] == 'youtube':
                    if path_len > 2:
                        params['project_id'] = path[2]
                        if path_len > 3:
                            if path[3] == 'share':
                                if path_len == 4:
                                    return return_values[0]
                params['service'] = path[1]
                if path_len > 2:
                    if path[2] == 'auth':
                        if path_len > 3:
                            if path[3] == 'token':
                                if path_len == 4:
                                    return return_values[1]
            return None
        return None
    return None
```

**Comment by CaselIT** [comment]
I've traced this issue since at least falcon 1.1 (and is probably even older, but falcon 1.0 does not have a test client)

**Comment by vytas7** [comment]
It might be easier said than done, but one possible path of solution is trying to unroll conditional branches to reflect the routing decision tree first, and only assign to params inside the last block just before `return`.

This could slightly increase the bytecode size (and thus CPU cache locality), but it should not otherwise affect the compiled code speed.

**Comment by CaselIT** [comment]
The easy alternative is probably to add `del param['key']` if the return is missed, but it incurs a performance hit

**Comment by CaselIT** [comment]
> 
> 
> The easy alternative is probably to add `del param['key']` if the return is missed, but it incurs a performance hit

nevermind. this does not work every time, since the params could come from a regexp.

I've gone for @vytas7 suggestion of delaying param setting until the return is reached.
The code is bigger, but i think we could also gain something in terms of speed, since we may avoid dick key set while descending branched that are not taken

**Comment by tim-clipchamp** [comment]
Thanks for looking into this so quickly. Do you think you will be making a bugfix release for version 2 after you have a fix?

**Comment by vytas7** [comment]
@tim-clipchamp that is unfortunately not the highest priority right now, we will be focusing at getting 3.0 out the door as soon as possible.
Do you need 2.x for Python 2 support, or can you migrate to 3.x when it's out?

As a workaround, you can add a dummy keyword argument for the affected route until this is fixed.

**Comment by tim-clipchamp** [comment]
Thanks for your response @vytas7.

It's a bit of extra effort for us to change the paths of the endpoints so that we don't hit this issue, but it shouldn't be too big a deal for us.

> Do you need 2.x for Python 2 support, or can you migrate to 3.x when it's out?

We need Python 2 support at least temporarily. Migrating to `falcon` is one of the steps in our migration to Python 3. Doing it all in one go would not be ideal.

**Comment by CaselIT** [comment]
You may also use a middleware to remove thw unwanted params by implementing the `process_resource` method. This was there would be no need to change the responder code.

Take a look at the docs here https://falcon.readthedocs.io/en/stable/api/middleware.html
