### ISSUE TITLE
Cache the mimeparse.best_match result in Handler.find_by_media_type

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1788]
In the current implementation if a media type is not present in the handlers, we yield to `mimeparse.best_match` to provide the best match for the provided media type.
https://github.com/falconry/falcon/blob/820c51b5f0af8d1c6e9fb8cccb560b6366f97332/falcon/media/handlers.py#L45-L58

We could cache the resolved media type so that betch match calls happens only once for each different media type.

Some care would be needed in order to invalidate the cache of the user modifies the handler dict, and with regards to thread safety (even if in this case the only drawback should be duplicated calls to the `best_match` function.

Before any decision in this regards we should also check what is the performance of `best_match` to see if the speed up would be worth the extra complexity

This discussion started in issue #1717 at https://github.com/falconry/falcon/issues/1717#issuecomment-730631675

**Comment by vytas7** [comment]
It looks like this has been already implemented, @CaselIT could you confirm?

**Comment by CaselIT** [comment]
indeed
