### ISSUE TITLE
Improve docs and checks for sink when using ASGI

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1789]
Currently there is no documentation or checks in `add_sink` that require an async function when using the asgi app.

This is a follow up of https://github.com/falconry/falcon/pull/1769#discussion_r531449969

cc @vytas7

**Comment by vytas7** [comment]
Not checking sinks and static routes for "asyncness" sounds like a release blocker tbh.
@kgriffs thoughts?

**Comment by CaselIT** [comment]
static routes are managed, since we use a different class in the async app (that just wraps the sync one, but it's managed)

https://github.com/falconry/falcon/blob/2f1109a476420e0c74e551b53028085c4c2fc5f2/falcon/routing/static.py#L131-L138

In the sink instead it's missing, unless I'm forgetting something
https://github.com/falconry/falcon/blob/2f1109a476420e0c74e551b53028085c4c2fc5f2/falcon/app.py#L612-L619

I'll change the milestone to 3.0. I don't think it's required for the alpha/beta, but I agree that's best if it's done for the stable

**Comment by vytas7** [comment]
Thinking it's actually required for `b1` because we want to be feature complete by then. But it is still the same **Version 3.0** milestone.
