### ISSUE TITLE
chore: emit deprecation warning when Response.add_link() is used

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1803]

**Comment by vmdhhh** [comment]
Hi @kgriffs 
Using `Deprecated` library would make this job easier.
Would it be ok?

**Comment by abid1998** [comment]
I can try this. I am new to this project so guidance would be helpful.

**Comment by vytas7** [comment]
Awesome sauce, do not hesitate to ask if you run into issues.

**Comment by vytas7** [comment]
@abid1998 You could take a look at how our `@deprecated` decorator is used in [`falcon/util/misc.py`](https://github.com/falconry/falcon/blob/master/falcon/util/misc.py#L316) (to mark `get_http_status(...)` as deprecated).

**Comment by vytas7** [comment]
Fixed as part of https://github.com/falconry/falcon/pull/1928
