### ISSUE TITLE
Add non-prefixed aliases to test client methods, e.g., simulate_get() -> get()

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1806]
The original intention of including the `simulate_*` prefix was to make tests self-documenting in terms of which requests are real, and which are simulated. However, it does make test cases more verbose and requires a bit more typing. Is it worth it?

Also, consider that httpx uses the same interface regardless of whether requests are being sent directly to an app vs. over a socket.

Thoughts?

**Comment by CaselIT** [comment]
I personally don't mind the simulate, but I'm not against aliasing them without the prefix.

**Comment by vytas7** [comment]
> I personally don't mind the simulate, but I'm not against aliasing them without the prefix.

:+1: 

I would like to keep `simulate_`, but it does not hurt to provide convenience shortcuts.
