### ISSUE TITLE
Contrary to the docs, Response.text is faster than Response.data

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1823]
[Documentation for `Response.text`](https://falcon.readthedocs.io/en/latest/api/request_and_response_wsgi.html#falcon.Response.text) gives a handy tip:

> Falcon will encode the given text as UTF-8 in the response. If the content is already a byte string, use the `data` attribute instead (it’s faster).

Unfortunately, this seems to be patently untrue, both looking at the [`Response.render_body()`](https://falcon.readthedocs.io/en/latest/api/request_and_response_wsgi.html#falcon.Response.render_body) source code, and benchmarking in cachegrind.

**Comment by vytas7** [comment]
See also: https://github.com/falconry/falcon/issues/1822

**Comment by CaselIT** [comment]
Maybe I'm missing something, but if we set bytes to the text property we have to take the except path in render_body, since bytes has no encode function.

That should not be faster than just using data

**Comment by vytas7** [comment]
Aha... you could read it that way too.

Maybe it's just me. I got an impression that using `data` (if we had `bytes`) should be faster `text`. Now it's almost worth to `decode()` `bytes` and set `resp.text` to the result, which would be later `encode()`ed again by the framework.

**Comment by vytas7** [comment]
@CaselIT And I've just benchmarked again, setting `resp.text` to a bytestring **is** slightly faster than setting `resp.data` to the same bytestring.

**Comment by vytas7** [comment]
Ah... nevermind... I seem to messed up Falcon versions a bit where setting `resp.text` is a no-op in the older version... :man_facepalming:

**Comment by CaselIT** [comment]
I guess that it depends on the size of the string. 
That observation should not hold for longer strings, since the overhaul of calling encode would become larger than the extra if used by `data`

**Comment by vytas7** [comment]
The difference is indeed very tiny. Maybe this issue should be converted to discussion or smth :thinking:

**Comment by CaselIT** [comment]
> 
> 
> I guess that it depends on the size of the string.
> That observation should not hold for longer strings, since the overhaul of calling `encode` would become larger than the extra if used by `data`

Done some tests, the time used by `.data` is basically constant vrt size, while `.text` time increases with the size.

**Comment by vytas7** [comment]
Killing this issue, the difference is not very significant, and it exists because we evaluate `text` first
