### ISSUE TITLE
Update sponsor links

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1838]
- [x] Ensure that sponsor links in RTD and on the website are not broken
- [x] Remove old sponsors
- [x] Check Open Collective for any new sponsors to add
- [x] Update falconframework.org

**Comment by CaselIT** [comment]
See also https://github.com/falconry/falconry.github.io/pull/29

**Comment by kgriffs** [comment]
done

**Comment by CaselIT** [comment]
@kgriffs I believe the website is still not up to date

**Comment by kgriffs** [comment]
Shoot, I forgot about that. I'll reopen and add a new checklist item.

**Comment by kgriffs** [comment]
Website should be update to date now
