### ISSUE TITLE
Fix unresolved Python object links in news fragments for 3.0

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1841]
As witnessed on https://falcon.readthedocs.io/en/3.0.0b1/changes/3.0.0.html, some links to Python objects are not resolved (shown as dark bold text instead). Revise and improve the affected news fragments.

An easy way to build the preview version is:
```
tox -e towncrier
```

- [ ] Fix Towncrier fragments
- [ ] Explore Sphinx options if there is a flag to emit a warning in this scenario

**Comment by CaselIT** [comment]
don't we have an action gate for this?

**Comment by vytas7** [comment]
We do, but apparently this does not generate _any_ warning in Sphinx.

**Comment by CaselIT** [comment]
I think sphinx should have a flag for it. I definitely saw them sometimes, but I'm far from being an expert, so I may be mistaken

**Comment by vytas7** [comment]
Sphinx warns about broken `:ref:`s, and similar, but AFAICT not about unresolved Python links.

**Comment by kgriffs** [comment]
Factored out part of this issue so we can delay to 3.1 -- https://github.com/falconry/falcon/issues/1888
