### ISSUE TITLE
Adding codecs.BOM_UTF8 to the beginning of resp.data is not working as expected

### ISSUE THREAD

**Issue by profana23** [falconry/falcon#1855]
I am trying to add a BOM to the beginning of the response output:
`resp.data = codecs.BOM_UTF8 + bytes('test', 'UTF-8')`
Now when I view this file in a Hex Editor, I cannot see the BOM at the beginning of the file.
The content will be just 'test'.

However, when I add the BOM twice, it works:
`resp.data = codecs.BOM_UTF8 * 2 + bytes('test', 'UTF-8')`
The content will be ONE BOM (instead of two BOMs) and the string 'test'.

How is this possible? What is going on here?

**Comment by vytas7** [comment]
Hi @profana23 !
I cannot reproduce the issue.

Could you post more details about your environment, such as your Python version, Falcon version, WSGI (or ASGI?) server details etc?

This is my test case (`test.py`):
```python
import codecs

import falcon


class Data:
    def on_get(self, req, resp):
        resp.data = codecs.BOM_UTF8 + bytes('test', 'UTF-8')


app = falcon.API()
app.add_route('/data', Data())
```
FWIW, I was running this `app` with `gunicorn test:app`.

Accessing the end point in Python REPL:
```python
>>> import codecs
>>> import requests
>>> resp = requests.get('http://localhost:8000/data')
>>> resp.content
b'\xef\xbb\xbftest'
>>> resp.content == codecs.BOM_UTF8 + b'test'
True
```

Could it be that the application is working as you would expect it to, just your HTTP client is playing tricks on you?

**Comment by profana23** [comment]
@vytas7 You were right, it's a client issue. I didn't think of that.
Thanks for your fast response & support.

**Comment by vytas7** [comment]
You're welcome :+1: Happy tinkering!
