### ISSUE TITLE
falcon.to_query_str does not properly encode query parameters

### ISSUE THREAD

**Issue by aetherknight** [falconry/falcon#1871]
# Version details

* Python version tested: 3.7.9
* Falcon version tested: 2.0.0

# Observed Behavior

`falcon.testing.TestClient`'s `simulate_*` methods do not correctly encode query parameters when using the `params` keyword argument.

```python
import urllib.parse

import falcon
import falcon.testing
import falcon.util


class SomeHandler:
    def on_get(self, request, response):
        print("parsed params       ", request.params)


app = falcon.API()
app.add_route("/", SomeHandler())

test_client = falcon.testing.TestClient(app)


# Try a params dict with the TestClient. Note that it does not encode any special characters, and this results in a
# query string that does not decode back to the same parameters.
#
# This is because falcon.testing uses falcon.util.to_query_str, which does not apply any encoding to the supplied query
# params dict.
params = {"foo": "bar", "baz": "boz&something"}
print("original params dict", params)
print("to_query_str        ", falcon.util.to_query_str(params))
response = test_client.simulate_get("/", params=params)
print(response.status_code)
# => original params dict {'foo': 'bar', 'baz': 'boz&something'}
# => to_query_str         ?foo=bar&baz=boz&something
# => parsed params        {'foo': 'bar', 'baz': 'boz', 'something': ''}
# => 200

# Now try manually encoding the params dict ourselves with urllib. Note that the query string is then correctly
# interpreted by falcon.
params = {"foo": "bar", "baz": "boz&something"}
encoded_params = urllib.parse.urlencode(params)
print("encoded params      ", encoded_params)
response = test_client.simulate_get("/", query_string=encoded_params)
print(response.status_code)
# => encoded params       foo=bar&baz=boz%26something
# => parsed params        {'foo': 'bar', 'baz': 'boz&something'}
# => 200
```

# Expected Behavior

I expect a WSGI app testing library that supports a way to specify query parameters as a dict to correctly encode my parameters so that the application interprets them the same way (although it is reasonable to require both sides to agree on how to handle lists as CSV vs repeating a query parameter)

I think that merely documenting this shortcoming is insufficient because the argument specifically exists to allow me to pass in query parameters as a dict.

# Root Cause

This is caused by `falcon.util.misc.to_query_str` not applying any URL encoding to the query parameters as it constructs the query string. `to_query_str` looks like it is currently only used by `falcon.testing.simulate_request`.

**Comment by vytas7** [comment]
Hi @aetherknight !
Indeed, that's embarrassing.

As you demonstrated, It affects not only the testing interface, but also the public utility function [`to_query_str`](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.to_query_str):
```python
>>> falcon.to_query_str({'foo': 'bar', 'baz': 'bar&bar&baz'})
'?foo=bar&baz=bar&bar&baz'
```

We'll try to rectify this for the impending 3.0 release.

**Comment by vytas7** [comment]
Unless you want to contribute a PR @aetherknight, that would be very welcome too :wink:

**Comment by CaselIT** [comment]
The behaviour the same also for the keys.

```py
>>> falcon.to_query_str({'a&b':'3'})
'?a&b=3'
```

**Comment by vytas7** [comment]
Hm... :thinking: 
IMHO, while at it, we should also make a breaking change in the function's signature, switching the default value of `comma_delimited_lists` to `False` in order to better match the csv-related default values elsewhere in the framework (in line with https://github.com/falconry/falcon/issues/1730 etc).

Thoughts?
