### ISSUE TITLE
deprecated() utility raises AttributeError under Meinheld

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1882]
The inner function of our [`deprecated()`](https://falcon.readthedocs.io/en/latest/api/util.html#falcon.deprecated) utility generator grabs the current stack frame object via [`inspect.getcurrentframe()`](https://docs.python.org/3/library/inspect.html#inspect.currentframe), and then uses its attributes to provide a more informative deprecation warning.

However, as warned in the latter's docs, this function is not guaranteed to return a valid stack frame object on all Python implementations; it may also return `None`. It seems that running Gunicorn+Meinheld workers can trigger this situation even under CPython.

Discovered using the following command line under CPython 3.7 and 3.8:
```
gunicorn --workers=8 --worker-class="egg:meinheld#gunicorn_worker" test:app
```

For instance, assigning a value to the deprecated [`Response.body`](https://falcon.readthedocs.io/en/latest/api/request_and_response_wsgi.html#falcon.Response.body) yields
```
2021-03-11 23:31:42 [FALCON] [ERROR] GET /things => Traceback (most recent call last):
  File "falcon/app.py", line 361, in falcon.app.App.__call__
  File "/tmp/benchmark/test3.py", line 13, in on_get
    resp.body = ('\nTwo things awe me most, the starry sky '
  File "falcon/util/deprecation.py", line 67, in falcon.util.deprecation.deprecated.decorator.wrapper
AttributeError: 'NoneType' object has no attribute 'f_code'
```

**Comment by kgriffs** [comment]
Good find. I think we should also consider reducing the frequency of these warnings (perhaps only emitting them the first time or every N times?) to further improve performance.

**Comment by kgriffs** [comment]
For 3.0 we should at least add a check for `None`.

**Comment by vytas7** [comment]
While at it, it would be good to reason about another potential caveat of referencing a frame object: it is easy to unintentionally create reference cycles this way; see also [this warning in CPython docs](https://docs.python.org/3/library/inspect.html#the-interpreter-stack), which suggests explicit disposal in the `finally` clause:
```python
def handle_stackframe_without_leak():
    frame = inspect.currentframe()
    try:
        # do something with the frame
    finally:
        del frame
```

**Comment by vytas7** [comment]
It seems we don't need to care of the number of times the deprecation is invoked. The interpreter does the job itself by warning once per process without doing anything special.

The issue under Meinheld was that we used to explode before even reaching that warning invocation, resulting in handling generic `Exception` upon every request.
