### ISSUE TITLE
FAQ: explain the case where URL path contains escaped slash `%2F` 

### ISSUE THREAD

**Issue by seamons** [falconry/falcon#1895]
For example, i've set up the following route with field expression:
```
/user/{name}
```
However sometimes the variable will contains slashes `/`, such as:
```
/user/foo/bar
```
I know the slash character is a reserved character of URL, so i encoded my request URL as below:
```
/user/foo%2Fbar
```
I was expecting receiving the argument `name` with value `foo/bar` in responder method, but instead, i got a 404 error.

**Comment by vytas7** [comment]
Hi @seamons !
Yes, this is an unfortunate artefact of the WSGI [`PATH_INFO`mechanics](https://www.python.org/dev/peps/pep-3333/#environ-variables), and unfortunately nothing Falcon can easily work around in the general case.

See also @kgriffs' answer here: https://github.com/falconry/falcon/issues/897#issuecomment-247486014

You could probably work around this in middleware, either Falcon or generic WSGI, by inspecting the WSGI environ extension variables specific to your app server of choice (such as `RAW_URI` in Gunicorn).

I'll leave this issue open in terms of documentation. We ought to add at least a FAQ item or a recipe explaining this.

**Comment by vytas7** [comment]
Also take a look at what the ASGI spec has to say on this.

**Comment by vytas7** [comment]
When working on the related docs, also revise this answer: [How can I handle forward slashes within a route template field?](https://falcon.readthedocs.io/en/3.0.0/user/faq.html#how-can-i-handle-forward-slashes-within-a-route-template-field).

At the time of writing this, the way the answer is worded might give a false impression that it is possible for a client to escape slashes in a way that is easily accessible to the framework.

**Comment by flying-sheep** [comment]
How would an example middleware look that does this?

**Comment by vytas7** [comment]
Hi @flying-sheep!
This is how it could look for WSGI:

As for ASGI, I don't think it's any different. No, we don't handle it out of the box, it seems.
The spec states (emphasis mine):
>  **Some web server implementations** may be **unable** to provide this. Optional; if missing defaults to `None`.

**Comment by flying-sheep** [comment]
That’s almost it! Since the parameters should be decoded, it needs some code in the router, right?

So how about we make Falcon’s default router should look something like this? (remove the second if branch if you don’t want to support nonstandard things)

```py
from urllib.parse import unquote

class CompiledRouter:
    def find(self, uri, req=None):
        if isinstance(req, falcon.asgi.Request):
            raw_path = req.scope.get('raw_path')
        elif isinstance(req, falcon.Request):  # WSGI request
            raw_path = req.env.get('RAW_URI') or req.env.get('REQUEST_URI')
        else:
            raw_path = None
        node = self._find(...)
        if node is None:
            return None
        resource, methodmap, params, template = node
        if raw_path:
            params = {k: unquote(v) for k, v in params.items()}
        return resource, methodmap, params, template
````

**Comment by vytas7** [comment]
Yeah, it would need code in the router if you want full support out of the box.
As to my middleware example above, the expectation is that the respective resource should manually decode the path segment.

I don't think we want to add it to the WSGI flavour of the framework, since it is not standardized in PEP 3333.

Regarding ASGI, I've filed an issue: https://github.com/falconry/falcon/issues/1919
Not that this would be a breaking change wrt the current 3.0 behaviour, so either it needs to be made optional, or wait until 4.0 if we decide to pursue this.

**Comment by flying-sheep** [comment]
I’m going to go out on a limb and claim that nobody doing `GET /foo/bar%2Fbaz` expects that encoded part to be interpreted as a path separator. A bit sad that nobody noticed this before 3.0, since it’s been like *the* problem in the WSGI spec, but what’s done is done.

Until then, maybe make it optional behavior that’s easy to opt-in with some kwarg somewhere?

**Comment by vytas7** [comment]
At least on the WSGI side, I don't think we can do much without deviating from the spec, and it don't think it is specific to Falcon.
IIRC it was also closed as a Won't Fix in the popular Werkzeug: https://github.com/pallets/werkzeug/issues/477.

As noted on that discussion, other HTTP servers such as front-end proxies, load balancers etc in front of your WSGI/ASGI app server may still choose to decode the path, so there might be cases where this improvement would be moot anyway.

**Comment by flying-sheep** [comment]
Werkzeug added both nonstandard env variables (RAW_URI & REQUEST_URI): pallets/werkzeug#1419

But sure, it’s up to your policy if you want to do this or say “if you want nonstandard, implement it yourself”

> As noted on that discussion, other HTTP servers such as front-end proxies, load balancers etc in front of your WSGI/ASGI app server may still choose to decode the path, so there might be cases where this improvement would be moot anyway.

I’d consider it a bug if some passthrough infrastructure modifies data without being asked to.

**Comment by vytas7** [comment]
Yes, but note that Werkzeug added this behaviour to their dev server, but not to parsing of the request path.

Their updated docs state:
> If you want to route based on this value, you can use middleware to replace `PATH_INFO` in the environ before it reaches the application. However, keep in mind that these keys are non-standard and not guaranteed to be present.

**Comment by vytas7** [comment]
@flying-sheep 
> A bit sad that nobody noticed this before 3.0, since it’s been like the problem in the WSGI spec, but what’s done is done.

Just for reference, this has been noticed before, see the above [referenced discussion](https://github.com/falconry/falcon/issues/897) from 2016.

**Comment by flying-sheep** [comment]
I know! I meant while designing Falcon 3. I think having the behavior described in https://github.com/falconry/falcon/issues/1919#issuecomment-843959216 by default would be ideal.

**Comment by vytas7** [comment]
@seamons We have now added a recipe and a FAQ entry illustrating how to work around the issue on selected WSGI and ASGI servers:
* https://falcon.readthedocs.io/en/latest/user/recipes/raw-url-path.html
* https://falcon.readthedocs.io/en/latest/user/faq.html#routing-encoded-slashes

Supporting this out-of-the-box in the ASGI flavour of the framework itself is tracked as https://github.com/falconry/falcon/issues/1919.

**Comment by flying-sheep** [comment]
Great! I think first class support will still be nice but the recipe is a good step for people who need this now.
