### ISSUE TITLE
Build wheels for macOS AArch64

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1899]
Extend our wheel automation to produce wheels for macOS AArch64 (Apple Silicon).

If we want to do this in GitHub Actions, we might need to wait until an appropriate runner is added: https://github.com/actions/virtual-environments/issues/2187.

**Comment by CaselIT** [comment]
my vote goes on waiting for github actions

**Comment by vytas7** [comment]
Yes, I think that's pretty much a prerequisite in either case. (Unless anyone wants to connect some Apple Silicon via a custom GH Actions worker.)

**Comment by CaselIT** [comment]
There seem to be a wheel version for arm osx. see https://pypi.org/project/orjson/#files that published them as universal2 wheels

No clue how to create them yet

**Comment by vytas7** [comment]
It is apparently possible to cross-compile [1] from an x86 Mac, but that also sounds risky in terms of distributing broken builds, or maybe there is a way to emulate?

1. See, e.g., https://github.com/conda-forge/falcon-feedstock/commit/13e1085d2ba0bb29551ea7ba78a229a22384b075

**Comment by CaselIT** [comment]
There is now a package maintained by the pypi people that should handle all that for you. it's called cibuildwheel

**Comment by vytas7** [comment]
Yeah, but is it possible to also run `pytest` etc in some emulated environment?

**Comment by CaselIT** [comment]
it seems so, see here https://github.com/pypa/cibuildwheel#options
> Testing 	CIBW_TEST_COMMAND 	Execute a shell command to test each built wheel

**Comment by vytas7** [comment]
Hm, I may be wrong, but it seems that you're responsible for setting up the Docker host infrastructure or emulator yourself in order to be able to run the said container.

**Comment by vytas7** [comment]
Update: [GitHub Actions: Self-hosted runners now support Apple M1 hardware](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/).

**Comment by vytas7** [comment]
It seems that we somehow built some of them without knowing, since Actions now support these.
In any case, both Apple archs will be formalized when moving to Cibuildwheel: #2259.
