### ISSUE TITLE
Unannounced breaking change in renaming falcon.api_helpers

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1902]
The `falcon.api_helpers` module used to contain several semi-public (not documented, but not underscored either) utilities, that people may be relying on.

During the 3.0 release cycle, `falcon.api_helpers` was renamed to `falcon.app_helpers` in order to reflect the `API` :arrow_right: `App` renaming.
However, the old name disappeared without any deprecation notice, and without any information in the 3.0 changelog notes. This is a bug.

In the spirit of SemVer, we cannot afford marking the change as deprecation in 3.0.1 either.
Let us make the name available as-is in 3.0.1, and mark as deprecated in 3.1; remove in 4.0.

**Comment by vytas7** [comment]
This is used by Sentry's Falcon integration plugin, so we need to make sure the coming fix re-enables that plugin at least on the import level.

**Comment by kgriffs** [comment]
Released: Released: https://github.com/falconry/falcon/releases/tag/3.0.1
