### ISSUE TITLE
DeprecatedWarning: Call to deprecated property body

### ISSUE THREAD

**Issue by wilwet** [falconry/falcon#1905]
I get the following warning, any idea?

.local/lib/python3.7/site-packages/gunicorn/workers/sync.py:179: DeprecatedWarning: Call to deprecated property body. Please use text instead.
respiter = self.wsgi(environ, resp.start_response)

using gunicorn  20.1.0 and falcon  3.0.0

**Comment by vytas7** [comment]
Hi @wilwet !
Yes, it is basically as the deprecation warning reads :slightly_smiling_face: 
> Call to deprecated property body. Please use text instead.

To elaborate, in Falcon 3.0, [`resp.body`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Response.body) was renamed to [`resp.text`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Response.text).
So if you had your responder along the lines of,
```python
def on_get(self, req, resp):
    # Simply rename resp.body to resp.text:
    # resp.body = 'Hello, World!\n'
    resp.text = 'Hello, World!\n'

    # ...
```

You may also want to check this brief overview: [When would I use media, data, and stream?](https://falcon.readthedocs.io/en/stable/user/faq.html#when-would-i-use-media-data-and-stream)

Hope this sheds some light on the subject, or did you have something else in mind?

**Comment by wilwet** [comment]
Thank you for your swift response and your great support! This fixes the warnings.

**Comment by vytas7** [comment]
Awesome sauce, closing this then.

Happy tinkering!
