### ISSUE TITLE
How to change option for json parser ?

### ISSUE THREAD

**Issue by Stargateur** [falconry/falcon#1906]
I read https://falcon.readthedocs.io/en/stable/api/media.html but I fail to understand how I could simply update option for the json parser, or just replace it.

**Comment by vytas7** [comment]
Hi @Stargateur!

You need to customize the JSON media handler. Under [JSONHandler](https://falcon.readthedocs.io/en/stable/api/media.html#falcon.media.JSONHandler), there are a couple of snippets how to use a different JSON library, or how to pass custom parameters to it.

Once you have a customized handler, you need to change the application's [request](https://falcon.readthedocs.io/en/stable/api/app.html#falcon.RequestOptions.media_handlers) and/or [response options](https://falcon.readthedocs.io/en/stable/api/app.html#falcon.ResponseOptions.media_handlers) to use your custom handler object for `application/json` (or any other Internet media type). From one of those snippets:
```python
extra_handlers = {
    'application/json': json_handler,
}

app = falcon.App()
app.req_options.media_handlers.update(extra_handlers)
app.resp_options.media_handlers.update(extra_handlers)
```

See also: [Replacing the Default Handlers](https://falcon.readthedocs.io/en/stable/api/media.html#custom-media-handlers).

Does any of the above shed some light on the subject? Or did you mean some other part of the framework by "the JSON parser"?

**Comment by Stargateur** [comment]
Yes, I have read the page, but I don't understand how to use this to change an option, put it simply I would like that the default use `str`.

I have understand that I need to use `https://docs.python.org/fr/3/library/json.html#json.dumps` but I'm not a python dev so it's hard for me to guess what to do next. Or maybe use https://docs.python.org/fr/3/library/json.html#json.JSONEncoder but here again I don't have much clue about what to do.

And... I think I understand by writing this:

```python
from functools import partial

from falcon import media
import json

app = falcon.App()
json_handler = media.JSONHandler(
    dumps=partial(
        json.dumps,
        ensure_ascii=False,
        default=str,
    ),
)
extra_handlers = {
    'application/json': json_handler,
}
app.resp_options.media_handlers.update(extra_handlers)
```

It's confusing example say the default use `json` from std but use `rapidjson` in example. But this seem to work perfectly thanks.

**Comment by vytas7** [comment]
Ah, right, that's a fair point; maybe we're conflating those two concepts (using a custom JSON library vs just customizing the stdlib's `json`) in a way that it gets confusing. It does make sense to clearly illustrate both concepts separately.

We also have this recipe excercising customization of the standard `json.dumps`: [Prettifying JSON Response](https://falcon.readthedocs.io/en/stable/user/recipes/pretty-json.html), although it seems you got it under control now nevertheless.
