### ISSUE TITLE
Hey there.

### ISSUE THREAD

**Issue by tvheems** [falconry/falcon#1915]
We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by vytas7** [comment]
Hey there @tvheems !
Unfortunately, this issue tracker is not a suitable place for running survey advertisements; dealing with stuff like this takes away from our precious hobby time spent on maintaining the project.

If you wish to collaborate or get help from the framework's maintainers on your private project that is not directly related to Falcon, please consider at least [Gold Membership](https://opencollective.com/falcon). Thanks!
