### ISSUE TITLE
Improve Pyston support

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1918]
[Pyston](https://github.com/pyston/pyston) is a faster and highly-compatible fork of CPython, aiming at CPython 3.8.8 compatibility at the time of writing.

Quick tests show that Pyston can speed up Falcon up to 2x, and interestingly, its JIT is faster than our cythonization of pure Python code, so if Pyston is detected, we should not do that. However, most of `falcon.cyutil.*` is still worth compiling, e.g., the C-based `parse_query_string` is still 2x faster than our Python implementation run in Pyston. Not to complicate the matters too much, we could opt to only cythonize `cyutil` if Pyston is detected.

Detecting Pyston: use `hasattr(sys, "pyston_version_info")` as per its maintainers' suggestions in https://github.com/pyston/pyston/issues/36.

- [ ] Mention Pyston in the installation docs alongside PyPy and CPython.
- [ ] If Pyston is detected, tune cythonization as per the above discussion.
- [ ] Run a Pyston CI gate?

**Comment by vytas7** [comment]
Coordinate with https://github.com/falconry/falcon/pull/1709 -- we probably want to get PEP 517 stuff working properly first, to make the things easier.

**Comment by CaselIT** [comment]
For sure I think this should be after #1709

**Comment by vytas7** [comment]
Closing this, it seems Pyston has been abandoned 😬
It's GitHub repo reads _(No longer maintained)_.
