### ISSUE TITLE
Clarify mutual exclusivity of `cors_enable=True` and `falcon.CORSMiddleware`

### ISSUE THREAD

**Issue by forana** [falconry/falcon#1930]
A tired/frustrated reader (such as myself) might see https://falcon.readthedocs.io/en/stable/api/cors.html#usage and incorrectly interpret the example code comments to mean that a "correct" solution requires both setting `cors_enable=True` in the `App` constructor, and passing a `falcon.CORSMiddleware` object to it. This is incorrect, but in a very subtle way - because the `CORSMiddleware` header effectively consumes the `Allow` header from the response (https://github.com/falconry/falcon/blob/7efb46f4068428eb62b422b4b3c2e40129e5a914/falcon/middleware.py#L112-L113), a request including the `Access-Control-Request-Method` header will receive a response with `access-control-allow-methods: None`.

**Comment by CaselIT** [comment]
Hi,

I agree that that section may benefit for a clarification. It would be great if you could suggest a change!

**Comment by forana** [comment]
> Hi,
> 
> I agree that that section may benefit for a clarification. It would be great if you could suggest a change!

Made a PR: https://github.com/falconry/falcon/pull/1933 - happy to update that however maintainers would like.
