### ISSUE TITLE
Update asgi look examples to use aioredis 2

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1938]
A new major vesion of aioredis was released, and it has some api changes.
This is the changelog https://github.com/aio-libs/aioredis-py/blob/master/CHANGELOG.md

**Comment by the-bets** [comment]
Myself and [Mihai Todor](https://github.com/mihaitodor) can pick this up and work on it, if nobody else is!

**Comment by vytas7** [comment]
Awesome @the-bets & @mihaitodor, go ahead!
(Bonus points if you find and fix any other funky things in that tutorial.)
