### ISSUE TITLE
Hook after params attribute is missing 

### ISSUE THREAD

**Issue by bronte2k7** [falconry/falcon#1954]
Hi

```python
def do_before(req, resp, resource, params):
	# here params is available

def do_after(req, resp, resource, params):
	# here params is not available

```

How can I access the params?

**Comment by vytas7** [comment]
Hi @bronte2k7 !
Currently, the framework is designed in a way that "after" hooks do not have access to `params`, and the signature they should follow is [`func(req, resp, resource)`](https://falcon.readthedocs.io/en/stable/api/hooks.html#falcon.after) (plus any additional args/kwargs you can pass via `falcon.after`).

I see though that documentation for the `*args` parameter in `falcon.after` does mention `params`, but that's most likely a copy-paste mistake that we'll try to rectify.

The idea of _after_ hooks is that they are thought to be used for post-processing the response, where access to `params` is seldom needed. See also the [`process_response` middleware method](https://falcon.readthedocs.io/en/stable/api/middleware.html#middleware).

However, if you do happen to need access to `params`, or pass any other custom data along the request-response cycle, you can also use [`req.context`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Request.context) and/or [`resp.context`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Response.context) for that purpose.

For instance:
```python
import falcon


def do_before(req, resp, resource, params):
    if params.get('vegetable') == 'cucumber':
        colour = 'green'
    elif params.get('vegetable') == 'tomato':
        colour = 'red'
    else:
        colour = None

    resp.context.colour = params['colour'] = colour


def do_after(req, resp, resource):
    if resp.context.colour:
        resp.set_header('X-Colour', resp.context.colour)


class Vegetables:
    @falcon.before(do_before)
    @falcon.after(do_after)
    def on_get(self, req, resp, vegetable, colour):
        resp.media = {'vegetable': vegetable, 'colour': colour}


app = falcon.App()
app.add_route('/vegetables/{vegetable}', Vegetables())
```

See also: [How can I pass data from a hook to a responder, and between hooks?](https://falcon.readthedocs.io/en/stable/user/faq.html#how-can-i-pass-data-from-a-hook-to-a-responder-and-between-hooks)

**Comment by bronte2k7** [comment]
Thanks for the detailed answer. Using context is a great idea)))
