### ISSUE TITLE
Support pathlib.Path for directory in `App.add_static_route(...)`

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1962]
It has become trendy to support [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) objects in addition to, or even instead of, `str` where the argument in question denotes a filesystem path.

We could support and document _directory_ of type [`Path`](https://docs.python.org/3/library/pathlib.html) in [`App.add_static_route(...)`](https://falcon.readthedocs.io/en/stable/api/app.html#falcon.App.add_static_route).

It currently already works implicitly via our invocation of `os.path.normpath` in Python 3.6+, but explodes on 3.5.

We could either fix this for 3.5, or wait for Falcon 4.0 which will presumably drop 3.5 support, and then just document the implicit support, backed by unit tests.

**Comment by CaselIT** [comment]
An alternative is to just support it for 3.6+ in v3. Personally I don't think it makes much sense to do something special for 3.5, since it's very marginal at this point
