### ISSUE TITLE
Deprecate `compile_uri_template()`

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#1967]
The `compile_uri_template()` function is not consistent with compiled router regarding tailing slash.

> I don't know either what the plan for `compile_uri_template()` is. I think it is left as a utility method for building custom routers, and I suppose, may continue to exist as such.

> This PR does a good job at explaining the _status quo_, so maybe let's just merge it, and create a new issue for making this method slightly more consistent with `CompiledRouter`.

_Originally posted by @vytas7 in https://github.com/falconry/falcon/pull/1961#pullrequestreview-777018325_

The options may be
- to leave it as is, with the warning provided by the above referenced pr
- add a flag to select what behaviour to have
- deprecate and eventually remove it, since it's not used internally by falcon.

**Comment by CaselIT** [comment]
As a datapoint, it does not seem very used, https://github.com/search?q=compile_uri_template&type=code

My vote goes to deprecation followed by leaving as is.

**Comment by CaselIT** [comment]
do you think we can deprecate it in v3 for removal in v4?

**Comment by vytas7** [comment]
Fixed in #1971
