### ISSUE TITLE
Add support for Content-Encoding

### ISSUE THREAD

**Issue by queertypes** [falconry/falcon#197]
It'd be great to facilitate the use of `Content-Encoding` and `Accepts-Encoding` request/response headers (`accepts_encoding`, `content_encoding`).

I might tackle this soon, so interacting with compressed, streaming content through Falcon is easy.

More info: [(wiki) HTTP Compression](http://en.wikipedia.org/wiki/HTTP_compression#Client.2FServer_compression_scheme_negotiation)

**Comment by kgriffs** [comment]
Seems like this would be better left to the WSGI container or reverse proxy in front of your app...

**Comment by mevinbabuc** [comment]
@lichray Hey were you able to get this working on falcon itself ?

**Comment by lichray** [comment]
> @lichray Hey were you able to get this working on falcon itself ?

I haven't been using falcon for a long time.
