### ISSUE TITLE
Warn upon importing Falcon using deprecated Python?

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1975]
We use to declare certain Python language, or specific implementation, versions as deprecated, or later, completely unsupported.
Maybe we should emit a deprecation (or EOL) warning in the case `falcon` is imported in such an interpreter?

**Comment by vytas7** [comment]
Me neither, it's just an idea.

> Do popular libraries do this?

I know that, for instance, Pip does that.

> Personally I think we should not add it, since if someone continues to use a deprecated python version, like 3.6 on falcon 3.1, has no way of removing the warning.

That's true -- they would have to live with one warning upon startup.

**Comment by CaselIT** [comment]
> I know, for instance, `pip` does that.

Yes, but I was thinking more of numpy/pandas/django. I know all of they deprecated some python version early, so we may look at them

**Comment by vytas7** [comment]
An argument against doing this is that `pip` now supports dependency resolution while taking into account the `python_requires` specifier. So even if not pinning anything, the user automatically get the highest supported version, which in turn would always warn about the "upcoming" deprecation. That is seen with `pip` itself in older environments.

**Comment by vytas7** [comment]
We probably have no bandwidth to manage this anyway, and, moreover, we will likely be effectively cutting off old interpreters by typing or Python features they don't support anyway.
