### ISSUE TITLE
Better handling of `cors_enable=True` + added `CORSMiddleware`

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1977]
Although similar to https://github.com/falconry/falcon/issues/1930, this issue proposes to improve not only documentation, but also provide a clearer indication to the developer who has happened to pass this unsupported combination of parameters.

Maybe we could emit a warning, silently disable the implicitly added middleware component if we detect that any instance of `CORSMiddleware` is already present, or even raise an Exception? (Although the latter might be seen as a breaking change -- discuss).

**Comment by CaselIT** [comment]
connected to https://github.com/falconry/falcon/pull/1976

Probably the best choice here is to deprecate the flag, since any other case would not be immediately clear to understand.
An alternative may be to raise a deprecation warning and the raise an exception in the next major

**Comment by vytas7** [comment]
See also https://github.com/falconry/falcon/discussions/2095. Rescheduling for 4.0.

**Comment by vytas7** [comment]
I went ahead and decided to simply raise a `ValueError` in this case.

**Comment by CaselIT** [comment]
makes sense
