### ISSUE TITLE
Would you consider maintaining a devcontainer for VS Code?

### ISSUE THREAD

**Issue by mihaitodor** [falconry/falcon#1979]
I struggled a bit to get `tools/mintest.sh` to run and since I'm not a very experienced Python developer, setting up the prerequisites on OSX proved to be a challenge. Having multiple versions of Python in parallel seems a bit error-prone to me. I guess using `pyenv` from the start is the way to go, but wasn't sure based on the instructions from [here](https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md). On the other hand, I recently played around with a project called Keda and I found [their devcontainer setup](https://github.com/kedacore/keda/tree/main/.devcontainer) quite easy to use, assuming one is willing to run Docker. Basically, VS Code starts a headless server in the container automatically and then the UI communicates with it seamlessly.

For Falcon, I found it easier to install all the dependencies in a Docker container and run everything there without worrying about messing up Python on my local laptop:
```shell
> docker run --rm -it -v$(pwd):/workspace ubuntu bash
>> apt update && DEBIAN_FRONTEND=noninteractive apt install -y software-properties-common ca-certificates curl build-essential python3-distutils python3-pip
>> add-apt-repository -y ppa:deadsnakes/ppa && apt update
>> apt install -y python3.5 python3.8 python3.5-dev python3.8-dev
>> pip install -U pip setuptools tox wheel
>> cd /workspace
>> # Run mintest
>> tools/mintest.sh
>> # Run asgilook test
>> tox --recreate -e asgilook
>> # Run asgilook tests without refreshing dependencies
>> tox --skip-pkg-install -e asgilook
```

I can easily wrap the above in a devcontainer if you'd like.

**Comment by vytas7** [comment]
@mihaitodor are you still interested in creating a devcontainer for Falcon?
We have otherwise cleaned up those tests scripts, just `tox` (without any special parameters) is now enough to invoke the standard set of environments equivalent to the previous `mintest.sh`.

**Comment by mihaitodor** [comment]
@vytas7 Ugh, I really should've followed up on this... Thanks for the reminder!

I took a quick stab at it in #2132. Would be interesting to hear what you guys think of the ergonomics. It does add some overhead to opening the project the first time, but, once that's done, the container will be stopped when VS Code is closed, so it can be resumed when VS Code is opened again. I believe the tests run a bit slower inside the container, since the virtual machine that Docker spins up adds a bit of overhead. I'd be curious to hear what is the difference on your machine. I ran `tox` successfully in the container and then I ran `time tox` and it took 5m38s on a Macbook from 2013 with 4 GB RAM and 6 CPUs allocated for Docker. I didn't bother to see what I need to install locally to run it outside of Docker :)

I can imagine scenarios in which people who aren't familiar with Docker will get tripped up, like the fact that any terminal they open inside VS Code when running in the Dev Container will not have most of the tools they might be using locally (stuff like RipGrep or The Silver Searcher or various other network utils, perf analysis tools etc). They might also get tripped up if they launch some Falcon test app inside the container and then try to access it from their browser, only to notice that it doesn't work, because the port wasn't exposed on the host... Lots of stuff to consider. However, it probably lowers the entry bar for some people who have a hard time getting the tests to run locally. Worst case, nobody will use it :)

**Comment by vytas7** [comment]
@mihaitodor no worries, thanks for getting back! :slightly_smiling_face:
I'm not using VS Code myself, @CaselIT what do you think? Could you test the proposed dev container?

**Comment by CaselIT** [comment]
I'll take a look. I've never used it myself, but i have docker and vscode so it should be testable :)

Regarding documenting it, maybe we could mention it in the contribution docs? Do you have suggestions @vytas7

**Comment by vytas7** [comment]
Adding a couple of sentences to `CONTRIBUTING.md` just after the chapter about running `tox` sounds good.
