### ISSUE TITLE
Request to add a github action 

### ISSUE THREAD

**Issue by Jassi10000** [falconry/falcon#1984]
This is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome contributors on their each issue and PR so as to make repository more interactive

If you love the idea , please assign this to me

**Comment by Jassi10000** [comment]
@vytas7 Should I move further with this  ?

**Comment by vytas7** [comment]
No, the maintainer team needs to make a decision whether we want this behaviour. Let us get back to you once we've discussed this.

**Comment by vytas7** [comment]
Hi again @Jassi10000,
We have now discussed this and decided not to proceed with such an action at this time, but thanks for bringing this up.

If anything, we will probably explore Github issue templates as a first step, which could potentially make the triage process more efficient.

**Comment by Jassi10000** [comment]
Sure sir , no issues
