### ISSUE TITLE
Implement FloatConverter

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2022]
Implement `FloatConverter` along the lines of [`IntConverter`](https://falcon.readthedocs.io/en/stable/api/routing.html#falcon.routing.IntConverter). Draw inspiration from `IntConverter`, or even find an efficient way to share code between the two!

Add the new converter to the list of [Built-in Converters](https://falcon.readthedocs.io/en/stable/api/routing.html#built-in-converters) under the `float` identifier.

Open questions: should we support converting `nan`, `inf` & `-inf` from path?

**Comment by Rangeeshar** [comment]
Hi, @vytas7  I am picking up this task for adding float converter, Do let me know if any pointers to keep in mind while doing so.
