### ISSUE TITLE
Add `__repr__` to test Result

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2044]
At the time of this writing, [`falcon.testing.Result`](https://falcon.readthedocs.io/en/stable/api/testing.html#falcon.testing.Result) has no custom `__repr__`:
```python
>>> import falcon
>>> import falcon.testing
>>> app = falcon.App()
>>> client = falcon.testing.TestClient(app)
>>> result = client.get('/something')
>>> result
<falcon.testing.client.Result object at 0x7f292ce046d0>
```

`__repr__` is also picked up and shown by the popular `pytest`.

It could be nice to add a representation with a concise summary describing the most important attributes of the result (status code etc).

**Comment by CaselIT** [comment]
I think it would make sense to log the status and maybe a substring of the text, something like the first 50 / 100 chars? or maybe the first 25 - last 25?

**Comment by vytas7** [comment]
Yeah, something like that. Maybe the response's `Content-Type` too?

**Comment by RioAtHome** [comment]
Hello, i would like to work on this issue.
From my understatement of this issue i just need to add a `__repr__` function to `falcon.testing.client.Result` class.
Should i just log the status code, a part of the text and the header content-type ?

**Comment by vytas7** [comment]
Hi @RioAtHome!
Sure, go ahead!

Yes, your understanding is correct -- you just need to add a `__repr__` for the class in question (and add a test for it). Although it is a bit open ended -- feel free to tweak that representation to your liking or come up with your own suggestions.

**Comment by RioAtHome** [comment]
Hello!.
How about logging the status code, most important headers(Content-Type, Content-length, Authorization and Cookie) and parts of the text/content(as stated above, just log the beginning and end)?

**Comment by vytas7** [comment]
Hi again!
Cookies are probably not the most common case for APIs, although it of course varies.
`__repr__` should be reasonably short... So probably we cannot afford cramming in too much stuff, although it is tempting.

**Comment by vytas7** [comment]
Implemented in https://github.com/falconry/falcon/pull/2046
