### ISSUE TITLE
Drop 3.5 & 3.6 support

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2049]
We are going to drop Python < 3.7 support in 4.0.

A non-exhaustive checklist:
- [x] Update Trove classifiers and `python_requires`
- [x] Move/adapt the Python 3.5 exception from `falcon.asgi` to the root module
- [x] Remove obsolete CI gates
- [x] Remove obsolete `tox` environments
- [x] Remove 3.5 and 3.6 from wheel preparation scripts/CI
- [x] Remove any usage of `CoroWrapper`, it was there only to service 3.6, and it was slated for removal in 3.10, and it is finally gone in 3.11.

**Comment by CaselIT** [comment]
Should we also do an f-string pass?

**Comment by vytas7** [comment]
> Should we also do an f-string pass?

Not strictly required, but I suppose we could, yes :wink:

**Comment by ihood** [comment]
Hi! Another developer and I are interested in completing a few of these tasks, may we work on this?

**Comment by vytas7** [comment]
@ihood this isn't among the tasks which we would seek a contributor for, but why not? :smiling_imp:
Go ahead, we'll try to support you!

**Comment by vytas7** [comment]
Hi again @ihood!
I've decided to tackle this myself since this is blocking a couple of other issues that we would love to start moving forward with.

If you're still open to contributing to Falcon, we'd be happy to come up with other contributor-friendly issue suggestions.

**Comment by vytas7** [comment]
Done in #2074
