### ISSUE TITLE
3.1.0: examples directory not contained in pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [falconry/falcon#2051]
Hi! I'm packaging falcon for Arch Linux. When trying to update to 3.1.0 I attempted to run the included tests.
This fails unfortunately, because pytest can not find required files contained in the examples directory:

```
============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-7.1.1, pluggy-1.0.0 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /build/python-falcon/src/falcon-3.1.0, configfile: setup.cfg
plugins: asyncio-0.17.1, anyio-3.5.0
asyncio: mode=strict
collecting ... collected 3384 items / 1 error

==================================== ERRORS ====================================
________________ ERROR collecting tests/test_things_example.py _________________
ImportError while importing test module '/build/python-falcon/src/falcon-3.1.0/tests/test_things_example.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_things_example.py:1: in <module>
    from examples.things import app
E   ModuleNotFoundError: No module named 'examples'
=============================== warnings summary ===============================
../../../../usr/lib/python3.10/site-packages/testtools/distutilscmd.py:7
  /usr/lib/python3.10/site-packages/testtools/distutilscmd.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.core import Command

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR tests/test_things_example.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 4.65s ==========================
```

**Comment by vytas7** [comment]
Hi @dvzrv!
I see what you mean. Unfortunately, it seems to be an unintended regression from https://github.com/falconry/falcon/pull/1917 where the `examples` module was prevented from being installed as such (a bug independently discovered by IIRC Gentoo and Debian maintainers), which effectively removed it from the `sdist` too.

How hard is it to override this on your side? Or are you dependent on us cutting `3.1.1` to solve this?

**Comment by vytas7** [comment]
Whoever takes this: note that while this is trivial to add in `MANIFEST.in`, it looks like we need to add a CI gate where Falcon tests are run from the `sdist` tarball as opposed to the local checkout managed by _Actions_.

**Comment by dvzrv** [comment]
@vytas7 thank you for the fast reply! I can revert to using the github tarball for now.

**Comment by vytas7** [comment]
@dvzrv btw this was fixed long ago, so you can change back to sourcing _sdist_ (which is the [recommended alternative](https://falcon.readthedocs.io/en/stable/community/packaging.html#obtaining-release)) in the `PKGBUILD` for [4.1.0](https://falcon.readthedocs.io/en/stable/changes/4.1.0.html), but of course, GitHub release archives will continue to work just fine too.

**Comment by dvzrv** [comment]
I see. We have meanwhile fully switched to only rely on direct upstream sources, see https://rfc.archlinux.page/0020-sources-for-python-packaging/ and https://rfc.archlinux.page/0046-upstream-package-sources/

(we'll stick to auto-generated source tarballs or locked git tags)

**Comment by vytas7** [comment]
Aha, that makes sense. Both approaches are perfectly fine.
