### ISSUE TITLE
Make it possible to unvendor `python-mimeparse`

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2054]
As pointed out on https://github.com/falconry/falcon/issues/1420#issuecomment-1101448759, some distributions and package managers may want to unvendor `python-mimeparse`, in order to reduce duplication, and because it carries a different licence, among other reasons.

Alternatively, we don't really make heavy use of `python-mimeparse`. Maybe we could instead reimplement & optimize the relevant function or two that we need? :thinking:

**Comment by CaselIT** [comment]
since falconry is now maintaining the mimeparse project, an option may be to depend on that.
