### ISSUE TITLE
`falcon.testing.TestClient.simulate_request` creating validation middleware

### ISSUE THREAD

**Issue by zilakmarian** [falconry/falcon#2057]
Hi, this is more of a question than an issue, but I could not find any mention of this in open (or closed) issues.
Why is `falcon.testing.TestClient.simulate_request` creating a middleware validating the app for compliance with wsgi? And why is it that the same middleware is not created for the app using `falcon.API`?
It is just little bit confusing, because it makes testing app behave differently than production app.

The middleware in question is `wsgiref.validate`. While this middleware is cool, I think it is enforcing rules too strictly. For example, the `read` method of environment variable `wsgi.input` is enforcing to have exactly one argument (number of bytes to read). Even though the wsgi specs suggest the `read` method **should** allow calling without arguments.

**Comment by vytas7** [comment]
Hi @zilakmarian!
That's a good point.
I believe one of the reasons behind the current behaviour is that using the vanilla `wsgiref` server, calling `read()` without arguments simply hangs, see also: [Why does req.stream.read() hang for certain requests?](https://falcon.readthedocs.io/en/stable/user/faq.html#why-does-req-stream-read-hang-for-certain-requests)

In addition, IIRC your concern has already been brought up by another user, and I filed it as an issue to keep track of. Could you check if we close yours (or the other issue) as a duplicate, or do you consider the two to depict different problems: https://github.com/falconry/falcon/issues/1617?

**Comment by zilakmarian** [comment]
I missed those issues, my bad...
I was just surprised that the testing environment was failing on me, while the actual code is running in production.
The `req.stream.read()` hanging is actually understandable, as far as I know the app itself does not have much to do with. It is up to the server how it deals with these edge cases and whether it implements the **should** behavior of wsgi.

My question was answered, so I am closing this issue. Thanks!

**Comment by vytas7** [comment]
Thanks for checking! :+1:
