### ISSUE TITLE
Write a packager's guide

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2081]
It seems that people packaging Falcon for various OSes such as Linux distributions (or just hobby projects) have very different ideas how the process should look like, although PEP 517 was supposed to simplify that.

For instance, how do I test the built binary? It seems some packagers opt to invoke `pytest` directly without parameters and expect it to work, disregarding our `tox` environments completely (see: #2080, #2006 etc).

**Comment by CaselIT** [comment]
Where should this documentation be? A section in readme or a separate file?
@kloczek do you have a suggestions?

**Comment by vytas7** [comment]
Absent better ideas, maybe `README` could link to a section on RtD.
