### ISSUE TITLE
Release 3.1.1

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#2101]
Issues to include for release in version 3.1.1 (checklist indicates if it's merged in 3.1.1 branch)

- [x] https://github.com/falconry/falcon/pull/2043
- [x] https://github.com/falconry/falcon/pull/2064 (not strictly needed, but in order to avoid mundane merge conflicts)
- [x] https://github.com/falconry/falcon/pull/2069
- [x] https://github.com/falconry/falcon/pull/2088 (contains an important CI workaround)
- [x] https://github.com/falconry/falcon/pull/2089
- [x] https://github.com/falconry/falcon/pull/2102
- [x] https://github.com/falconry/falcon/pull/2105
- [x] https://github.com/falconry/falcon/pull/2122

Write release notes, prepare the branch for `b1`:
- [x] https://github.com/falconry/falcon/pull/2123

Ship :shipit:
- [x] `3.1.1.b1`
- [x] `3.1.1.rc1`
- [x] `3.1.1` (final)

**Comment by vytas7** [comment]
Thanks for summarizing this. I'll create a Milestone too.

**Comment by vytas7** [comment]
We'll probably want to include the migration to `blue` for practical purposes, since later PRs originate from code after the switch.

**Comment by vytas7** [comment]
Released!
