### ISSUE TITLE
Replace the obsolete JS media type

### ISSUE THREAD

**Issue by euj1n0ng** [falconry/falcon#2110]
[RFC-4329](https://www.rfc-editor.org/rfc/rfc4329) is obsolete.

According to [RFC-9239](https://www.rfc-editor.org/rfc/rfc9239),

- Changed the intended usage of the media type "text/javascript" from OBSOLETE to COMMON.
- Changed the intended usage for all other script media types to obsolete.

**Comment by vytas7** [comment]
Thanks for heads up @euj1n0ng!

Falcon isn't heavily tied to Javascript, so I suppose this is just about updating [`constants.py::MEDIA_JS`](https://github.com/falconry/falcon/blob/master/falcon/constants.py#L115). Would you like to create a PR?

**Comment by MS-Ignis** [comment]
Hey, this is my first time contributing to open source. Is this issue still open? @vytas7 @euj1n0ng 
Also will this contribute to hacktoberfest?

**Comment by vytas7** [comment]
Aha, I was unaware of the context. In fact, we need to check if this type constant is actually enforced when serving static files, otherwise you'll need to submit a PR to the CPython (or PyPy) itself :slightly_smiling_face:

(Or we need to modify Falcon to prioritize these constants to the system's mimetypes.)

**Comment by harshashetty67** [comment]
Hi all, is this issue fixed? if not, I would like to contribute. I'm new to open source and was looking for good first issues. 
@vytas7 @euj1n0ng

**Comment by vytas7** [comment]
Hi @harshashetty67, this is not fixed, but there is already an open PR.

@harshashetty67 if you are okay with contributing documentation, we have a bunch of good first issues. We don't have that many good first issues for coding at the moment...
You can view all issues that need a contributor here: https://github.com/falconry/falcon/issues?q=is%3Aopen+is%3Aissue+label%3A%22needs+contributor%22
Maybe one of these could suit you?
* https://github.com/falconry/falcon/issues/1026
* https://github.com/falconry/falcon/issues/1137
And as said, if you're fine with writing documentation, that we have tons of good first issues. I can help you picking something there.
