### ISSUE TITLE
Handle chunked transfer encoding 

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#212]

**Comment by smcclstocks** [comment]
+1 as well

**Comment by davidbgk** [comment]
If someone copy-pasted the quickstart example and had issues with the transfer encoding header (like testing with Silk), you might want to replace:

```python
class JSONTranslator:

    def process_request(self, req, resp):
        if req.content_length in (None, 0):
            return
```

by:

```python
class JSONTranslator:

    def process_request(self, req, resp):
        if (req.headers.get('TRANSFER-ENCODING') != 'chunked'
                and req.content_length in (None, 0)):
            return
```

**Comment by carlodri** [comment]
+ for me as well (looks like I'm necrobumping...)!

**Comment by vytas7** [comment]
Closing this, it does not seem to be feasible/worth the effort to do anything like that on the WSGI side when the standard explicitly forbids it.

Furthermore, ASGI is now getting more and more mature and widespread, and ASGI supports streaming requests out of the box (along with other goodies useful for streaming interaction with the service such as WebSocket etc). Falcon 3.0 will support ASGI.
