### ISSUE TITLE
Request: Add sameSite parameter to unset_cookie

### ISSUE THREAD

**Issue by agulab** [falconry/falcon#2124]
It would be appreciated if I could use the _unset_cookie_ method to unset a cookie I created with the parameter _sameSite='None'_. Otherwise, I'm forced to use _set_cookie_ for the sole purpose of unsetting that cookie...

With current behaviour, _sameSite_ is set to 'Lax' by default and so the browser ignores it because I'm using different domains for front and backend, and so using Cross Site requests. 

Thank you

**Comment by TigreModerata** [comment]
Hi, I just submitted a draft in a pull request.

**Comment by vytas7** [comment]
Awesome, thanks, we'll take a look!
