### ISSUE TITLE
TestClient doesn't work for HEAD and HTTPRouteNotFound error handler

### ISSUE THREAD

**Issue by mattwarrick** [falconry/falcon#2154]
I have a custom error handler for `HTTPRouteNotFound` to provide friendlier error message "route not found" then generic "something not found".

```py
import falcon
import falcon.testing


def route_not_found_handler(req, resp, ex, params):
    raise falcon.HTTPRouteNotFound(
        title=route_not_found_handler.title,
        description=route_not_found_handler.description,
    )

route_not_found_handler.title = "No such route"
route_not_found_handler.description = "The API doesn't know endpoint with specified URL."
```

For testing, I create simple resource:

```py
class HelloResource:
    def on_get(self, req, resp):
        resp.text = "Hello"

app = falcon.App()
app.add_route('/hello', HelloResource())
```

and add ``route_not_found_handler()``

```
app.add_error_handler(falcon.HTTPRouteNotFound, route_not_found_handler)
```

Testing it with GET to non-existing route works well:

```py
client = falcon.testing.TestClient(app)

# For GET it's ok
result = client.get("/non-existing")
assert result.status == falcon.HTTP_404
assert result.json == {
                "title": route_not_found_handler.title,
                "description": route_not_found_handler.description }
```

However, if method is HEAD, response code is 404 but body is empty

```py
# For HEAD it fails
result = client.head("/non-existing")
assert result.status == falcon.HTTP_404
# result.json is None
assert result.json == {
                "title": route_not_found_handler.title,
                "description": route_not_found_handler.description }
```

**Comment by vytas7** [comment]
Hey @mattwarrick!
I believe the test client is working as intended -- it is the framework itself that does not render any content; and that is **by design**.

Falcon conforms to the HTTP semantics, see, e.g. [RFC 9110, 9.3.2. HEAD](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2):
> The HEAD method is identical to GET except that the server **MUST NOT** send content in the response.

(emphasis mine)

**Comment by mattwarrick** [comment]
Ooo, you are correct. I didn't realize HEAD responses have no bodies. Thank you for making Falcon so great.
