### ISSUE TITLE
Missing wheels for Python 3.12

### ISSUE THREAD

**Issue by hynek** [falconry/falcon#2175]
Hi, would it be possible to add Python 3.12 wheels for the current release? It seems to build and run just fine, but the delays are a bit annoying. :)

**Comment by vytas7** [comment]
Hey @hynek!
That's not an unreasonable request, we'll see what we can do about it. :slightly_smiling_face:

**Comment by vytas7** [comment]
Hi again @hynek!
I'm closing the issue as the wheels for 3.12 are out now, however, the 3.1.2 release is lacking wheels for 3.8 & 3.9 as our build process was interrupted by an incompatible release of `pytest-asyncio`... :grimacing:

(We are readying a yet another micro-release to address this.)

**Comment by hynek** [comment]
thanks!
