### ISSUE TITLE
`DefaultEventLoopPolicy.get_event_loop()` is deprecated (in the case of no loop)

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2178]
As of Python 3.12, if there is no event loop, `DefaultEventLoopPolicy.get_event_loop()` emits a deprecation warning, and threatens to raise an error in future Python versions.

No replacement is suggested by the official docs. When it does start raising an error, I suppose one can catch it, and create a new loop instead.

We have already updated our code to use this method to combat another deprecation... it seems Python wants to make it harder and harder obtaining the current loop from sync code (which makes no sense to me).

**Comment by CaselIT** [comment]
seems that what they want you to do for #reasons is the following
```py
try:
  loop = asyncio.get_running_loop()
except RuntimeError: # lol custom exception are for noobs
  loop = asyncio.new_event_loop()
  asyncio.set_event_loop(loop)
```

I have no idea how someone looked at this and thought "yeah that's a great api to replace `get_event_loop`" -.-'

**Comment by CaselIT** [comment]
> seems that what they want you to do for #reasons is the following
> 
> ```python
> try:
>   loop = asyncio.get_running_loop()
> except RuntimeError: # lol custom exception are for noobs
>   loop = asyncio.new_event_loop()
>   asyncio.set_event_loop(loop)
> ```
> 
> I have no idea how someone looked at this and thought "yeah that's a great api to replace `get_event_loop`" -.-'

nope that's too simple. the following seems correct
```py
def get_event_loop() -> asyncio.AbstractEventLoop:
    """vendor asyncio.get_event_loop() for python 3.7 and above.

    Python 3.10 deprecates get_event_loop() as a standalone.
    Python 3.12 deprecates get_event_loop_policy().get_event_loop() call
    with no running loop.

    This is starting to become ridiculous.

    """
    try:
        return asyncio.get_running_loop()
    except RuntimeError:
        # avoid "During handling of the above exception, another exception..."
        pass
    if sys.version_info < (3,12):
        return asyncio.get_event_loop()
    else:
        with warnings.catch_warnings(action='error'):
            loop = None
            try:
                loop = asyncio.get_event_loop()
            except (DeprecationWarning, RuntimeError):
                # avoid "During handling of the above exception,
                # another exception..."
                pass
            if loop is None:
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
            return loop
```

**Comment by vytas7** [comment]
See also the discussion on https://github.com/python/cpython/issues/100160
