### ISSUE TITLE
`http_date_to_dt()` should return a timezone-aware datetime

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2182]
In line with the [upstream deprecation of `utcnow()` in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html#deprecated), I think that we should change [`http_date_to_dt()`](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.http_date_to_dt) to return a timezone-aware datetime. Since HTTP dates are normally in GMT, we could use our own [`GMT`](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.TimezoneGMT) zone, or simply use UTC.

This is a breaking change of relatively low value, so unfortunately we won't be able to prioritize it for 4.0. (And we need a longer deprecation window in any case.)

**Comment by chgad** [comment]
Sprintign on this one rn.

**Comment by chgad** [comment]
Looking into the `time_formats` allowed for checking there is one time format [here](https://github.com/falconry/falcon/blob/89ccb9871f6bec7847048532f0ed20cd483b1f18/falcon/util/misc.py#L198), namely `'%a %b %d %H:%M:%S %Y'`, which
would allow for non-timezone-awareness.

How should we handle that?
1. Do not allow those datetimes
 &rarr; potential major breaking change
2. Assume a timezone like `UTC` or `GMT`
 &rarr; ambiguity what the "correct" choice is
 &rarr; extra breaking change in addition to the overall breaking change

**Comment by vytas7** [comment]
Re these alternative datetime formats, I think we can break them quite liberally since they are already hidden by the `obs_date` parameter (defaults to `False`).

**Comment by chgad** [comment]
Matching timezones, except UTC/GMT and the locally defined one, is an ongoing problem see [here](https://github.com/python/cpython/issues/66571).

So without using a package, like the popular pytz library,  it is not yet possible to parse any other timezone.
