### ISSUE TITLE
Docs facelift

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2198]
Look into an alternative docs theme as the current one (Alabaster) is not too appealing and still exhibits various glitches despite extensive tweaking.
Maybe @pradyunsg's [`furo`](https://pypi.org/project/furo/) could work well for us?

**Comment by CaselIT** [comment]
Furo seems to be extremely popular, wirh many projects adopting it.

Another similar one seems to be the pydata one https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html, but I'm not sure how popular it is outside of the pydata circle (polars uses it and as far as I know it's not in the pydata org)

**Comment by vytas7** [comment]
A couple of years ago I chose [book theme](https://sphinx-book-theme.readthedocs.io/en/stable/index.html) for our internal dev portal at work, it's really nice too. But I think Furo has some relation to it, because they feel similar.
