### ISSUE TITLE
TestClient methods are typed to return _ResultBase, but actually return Result

### ISSUE THREAD

**Issue by davetapley** [falconry/falcon#2207]
All these methods are typed to return `_ResultBase`:

https://github.com/falconry/falcon/blob/4910dd73ecd1b9c8cf6cae045b26ad432fa56128/falcon/testing/client.py#L1041-L1046

But actually returns `Result` here:
https://github.com/falconry/falcon/blob/4910dd73ecd1b9c8cf6cae045b26ad432fa56128/falcon/testing/client.py#L638

And `Result` defines the methods which are useful in testing:
https://github.com/falconry/falcon/blob/4910dd73ecd1b9c8cf6cae045b26ad432fa56128/falcon/testing/client.py#L328-L348

---

But because it's typed `_ResultBase` I get e.g. `Cannot access member "json" for type "_ResultBase"`, 
even though the methods work 😬 

I _presume_ this is an oversight and not intentional?

**Comment by CaselIT** [comment]
That seems likely yes. PR to fix would be appreciated!

**Comment by CaselIT** [comment]
it seems doable, with a lot more effort

**Comment by davetapley** [comment]
@CaselIT I agree! See https://github.com/falconry/falcon/discussions/2210 😁
