### ISSUE TITLE
Deprecate asyncio aliases in `falcon.util`

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2253]
I have soft-deprecated them in the docs in https://github.com/falconry/falcon/pull/2252.
Emit a deprecation warning in a 4.x release, remove in 5.0. Unless we need them again for, e.g., Trio support (?)

**Comment by CaselIT** [comment]
the deprecation would use module `__getattr__` right?

**Comment by vytas7** [comment]
Yes, just like we did with `json` somewhere.
