### ISSUE TITLE
Update request-id recipe to use `contextvars` instead of `threading.local()`

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2260]
[`contextvars`](https://docs.python.org/3/library/contextvars.html) is a newer module in the stdlib (3.7+) that is more advanced than `theading.local()` as it not only understand threads, but also `asyncio` coroutines, etc.

Update the [Request ID Logging](https://falcon.readthedocs.io/en/stable/user/recipes/request-id.html#request-id-logging) recipe to use `contextvars`.

**Edit**: also add tests for this recipe.

**Comment by CaselIT** [comment]
I don't think there is any need to use threadlocal or contextvar. just use `req` or `resp` `context`.

**Comment by vytas7** [comment]
Yes, using global thread-locals is usually not a very bright idea and it leads to a spaghetti code base. But sometimes, particularly when working with a code base migrated from another framework that builds on this paradigm, or when very deep inside nested code, it might be a useful escape hatch.

**Comment by EricGoulart** [comment]
Hello, I would like to work on this issue. Please let me know if there is any information that I should know before proceeding. Thank you.

**Comment by vytas7** [comment]
Hi @EricGoulart! We are glad to hear, sure, go ahead!
You can skim through our docs on how to [contribute to Falcon](https://falcon.readthedocs.io/en/latest/community/contributing.html).

Regarding the issue itself, I hope the description is clear enough, but just [ask here or on Gitter](https://falcon.readthedocs.io/en/latest/community/help.html#chat) if you run into any problems.
The recipe that needs to be updated is this file: [`docs/user/recipes/request-id.rst`](https://github.com/falconry/falcon/blob/master/docs/user/recipes/request-id.rst) (but it also includes snippets from small Python files).

You can render out the docs with `tox -e docs`. Then open [`docs/_build/html/user/recipes/request-id.html`](https://falcon.readthedocs.io/en/latest/user/recipes/request-id.html) in your browser.

**Comment by EricGoulart** [comment]
Hello, just wanto to say sorry about that, It`s my first time contribuiting to a public repository and I am making some mistakes.
