### ISSUE TITLE
Allow parsing of all urlencode parameters

### ISSUE THREAD

**Issue by xiaclo** [falconry/falcon#231]
Looking over the util.uri code for query strings, there is massive ommisions of valid query string keys (but not values).  Is there a reason for this?

There was an earlier commit to add dots (https://github.com/racker/falcon/pull/169), but I'm not sure why spaces and other characters are restricted in the first place.

```python
>>> falcon.util.uri.parse_query_string(urllib.urlencode({'first name': 'John', 'last name': 'Smith'}))
{'name': 'John'}
```

**Comment by kgriffs** [comment]
Thanks, just closing the loop on this. It was fixed in version 0.3 of the framework.
