### ISSUE TITLE
Typing cleanup for 4.0

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#2313]
Once all the typing of the code has been completed, make a final pass to:
- [ ] normalise names
- [x] decide what type alias should be public and which should not
- [x] add future annotattion in any missed package (there should be a ruff code we can use for it)
- [x] should JSON handlers' main argument be typed as `JSONSerializable` or `Any`?
- [x] The argument type of [`secure_filename()`](https://github.com/falconry/falcon/blob/master/falcon/util/misc.py#L375) has recently been changed to `Optional[str]`, whereas before it was just `str`, which I (@vytas7) believe is correct, although it fails some type checks; should we maybe revise these places instead , or alternatively type-ignore them if it is strictly internal use?
- [x] Revise the typing of headers, the latest iteration reads
```python
Headers = Dict[str, str]
HeaderList = List[Tuple[str, str]]
HeaderArg = Union[Headers, HeaderList]
```
If `HeaderArg` is what is used most commonly, maybe it should be just called `Headers`?
Also, we define `HeaderList` as iterable of tuples in the docstrings, but here it is just called `List[...]`. Will Mypy understand that, or should we use `Iterable[...]` instead?

**Comment by vytas7** [comment]
I think we might want to privatize the whole `typing` module, i.e. call it `falcon._typing` instead of `falcon.typing`, to make it obvious that we don't make any guarantees.

@CaselIT told me that SQLAlchemy did something similar, and they re-export selected names via a public module.
