### ISSUE TITLE
Improve cors middleware to handle cases where allow header is not set by options responder

### ISSUE THREAD

**Issue by CaselIT** [falconry/falcon#2325]
See discussion at https://github.com/falconry/falcon/pull/2304#pullrequestreview-2261582271

Also allow cors in static routes and sinks (??)

**Comment by CaselIT** [comment]
@vytas7 I don't think we can automate much when using sinks, since it must be managed by the sink function.

I can test that it works if allows is set in the header and document it

**Comment by vytas7** [comment]
I don't think we need to do anything for sinks. I just somehow thought that it worked for static files out of the box, and as a user I can see it can be useful to hack together some dev server for the frontend part. But this doesn't need to go out strictly with 4.0 either.

**Comment by CaselIT** [comment]
I think the changes made are small enough that it's worth having for v4
