### ISSUE TITLE
Enable PDF on Read the Docs

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#2365]
Provided one has the correct dependencies on, e.g., Ubuntu Linux 22.04, our docs can be built to a Latex PDF, but this is no longer enabled on Read the Docs (long ago, it was automatically included).

Check what is needed to enable the PDF output again.

**Comment by AkshayAwate** [comment]
Looks like we need to update

**Comment by vytas7** [comment]
Hi @AkshayAwate!
We don't assign per se, just your comment here is enough to know you're working on it :slightly_smiling_face:

**Comment by AkshayAwate** [comment]
@vytas7  Here is PR: https://github.com/falconry/falcon/pull/2371
