### ISSUE TITLE
Add Pyramid to benchmarks

### ISSUE THREAD

**Issue by sontek** [falconry/falcon#237]
This looks like a great framework and since I'm coming from the Pyramid world I thought it would be interesting to have it in your benchmark comparisons!

Looking at this benchmark from 2012:
http://mindref.blogspot.com/2012/09/python-fastest-web-framework.html

It is much faster than most of the frameworks you included in your benchmarks and when looking at pypi it had 80,000 downloads in the last month vs bottle only having 40,000.

**Comment by sontek** [comment]
Happy New Year @kgriffs! Any chance you could update your benchmarks now?

**Comment by sontek** [comment]
Here are current download statistics of what are posted in the benchmarks:

```
Pecan:       31675 downloads in the last month
Pyramid:    43038 downloads in the last month
Werkzeug: 55286 downloads in the last month*
Bottle:        59555 downloads in the last month
Flask:         289161 downloads in the last month
```

* Werkzeug numbers adjusted to exclude Flask downloads.

Its the holidays so in general downloads are lower than normal, but you can see that Pyramid does have a very good showing and shares the same Response/Request library with Pecan, which is `WebOb`.

**Comment by bertjwregeer** [comment]
I would love to see Pyramid benchmarked against Falcon too, as a current Pyramid user it would help me decide on whether to continue using it or move on to a different framework.

**Comment by vytas7** [comment]
Pyramid is not that popular nowadays, we'll probably prioritize ASGI benchmarks vs the likes of Starlette.
