### ISSUE TITLE
Falcon 4.0.0 adds possibly unintended directories when installed

### ISSUE THREAD

**Issue by LenardJensen** [falconry/falcon#2384]
Hello,
after the update to Falcon 4.0.0 I noticed my venv site-packages contained directories that I could not match to a specific library. After checking my different dependencies I managed to connect those directories to the new Falcon update and wanted to ask if these changes were intended.

## Expected Behavior
When installing Falcon using pip, a falcon and falcon-xxx.dist-info directory gets created in the site-packages directory.

## Actual Behavior
Falcon 4.0.0a1 and Falcon 4.0.0 also installs their docs, e2e-tests, examples, tests and tools directories into the site-packages of a virtualenv.

## Steps to Reproduce the Problem

  1. Create a new venv using `python -m venv my-venv`
  1. Install either Falcon 4.0.0 or 4.0.0a1 using `pip install "falcon==4.0.0"`
  1. Navigate into `my-venv/Lib/site-packages/` which contains the additional directories. `falcon-4.0.0.dist-info\RECORD` will contain the paths to those additional directories

## Specifications

  - Version: Tested using Python 3.11 and pip 22.2.1
  - Platform: Windows 11

**Comment by CaselIT** [comment]
Hi,

Looking at the created wheels that seems to be the case.
@vytas7 can you look at it? It looks like a 4.0.1 candidate (also not connected to this, what is the milestone for 4.0.x?)

**Comment by CaselIT** [comment]
IIRC `MANIFEST.in` is still used to devine what's included.

It's actually strange since for example `tests` have no files, but includes `test/asgi` and that folder includes all the test files, so it seems there is some file filtering going on, but it's likely failing for some reason

**Comment by vytas7** [comment]
It is some trickery of the new mode of Setuptools, `MANIFEST.in` is used to define what is included in the sdist, but the wheels used to only include modules and package data. I'll check what our options are...

I've checked our older builds prior to removing `setup.cfg`, and they look as expected.

**Comment by vytas7** [comment]
Thanks once again for reporting @LenardJensen , we have now released [Falcon `4.0.1`](https://pypi.org/project/falcon/4.0.1/) that hopefully addresses this issue.
