### ISSUE TITLE
Request.stream.read blocks on Python 3.3.5 wsgiref server

### ISSUE THREAD

**Issue by sebasmagri** [falconry/falcon#239]
Hi!

req.stream.read seems to still block while running the sample at the [Tutorial](http://falcon.readthedocs.org/en/latest/user/tutorial.html#serving-images) under Python 3.3.5 using the wsgiref server. Running on gunicorn or mod_wsgi works.

I'll do further research on this.

Regards,

**Comment by kgriffs** [comment]
I believe this is fixed, but please reopen if that is not the case. Thanks!
