### ISSUE TITLE
Add a testing tutorial to the docs

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#253]
Add additional docs re how to test falcon-based apps.

**Comment by butla** [comment]
@kgriffs I think that testing documentation is most need. I'm just starting to pick up Falcon (but it looks really promising) and it took me more than a moment to make my first test.

It looks like this:

    from falcon import testing
    #an app returning 'Hello world\n' on GET
    import app
    
    class SampleTest(testing.TestBase):
        def setUp(self):
            super().setUp()
            self.api = app.app
    
        def test_sample_get(self):
            self.assertEquals(
                self.simulate_request('/', decode='utf-8'),
                'Hello world\n'
            )

Maybe I can add it somewhere in the tutorial and make a PR. Do you have some suggestions or guidelines?

**Comment by kgriffs** [comment]
@butla version 1.0.0 of the framework includes a new testing framework. I think it's a good time now to write up a testing tutorial. It could be incorporated into the main tutorial, perhaps showing how to write a few tests along the way as different parts of the app are built up. I think a testing guide ala `doc/api/cookies.rst` would also be helpful.

If you happen to be at PyCon in Portland we can meet up and discuss further. This could be a good issue to tackle during the sprints. 😄

**Comment by butla** [comment]
@kgriffs Too bad I'll be half a world away :) Though I might still create a pull request with some docs and simple Pytest support. I've mentioned it in #16, but just now I'll finally have some time for "charitable" coding :)

**Comment by kgriffs** [comment]
FWIW, the 1.1 docs have some example code now (see also: http://falcon.readthedocs.io/en/latest/api/testing.html). But I'd still love to get someone's help with a testing tutorial if anyone can help out.

**Comment by butla** [comment]
@kgriffs I think I could help. How should it be made? A "Testing" section after "Error Handling" in http://falcon.readthedocs.io/en/stable/user/tutorial.html?

Also, what should be in it? I guess I would show a simplest GET, POST with JSON body, POST with urlencoded params and an example of how to organize the application code to be able to inject mocks in the API objects.

**Comment by kgriffs** [comment]
Awesome, thanks! That sounds like a pretty good plan. You don't need to show how to do everything, but enough to point the reader in the right direction. Once someone has the big picture, they can refer to the testing reference docs to learn about all the different parameters supported by `simulate_request()`, etc.

It may also be useful to have a dedicated "testing.rst" similar to what we have for cookies and middleware.

**Comment by butla** [comment]
@kgriffs So I guess that after merging #934 this can be closed?

**Comment by kgriffs** [comment]
Indeed, good catch! Thanks!
