### ISSUE TITLE
Return if-modified-since, if-unmodified-since as datetime.datetime

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#254]
Currently, the HTTP date string is returned. It might as well be parsed, since the app will need to do that anyway before it can use the value.

**Comment by lwcolton** [comment]
Adding some good links

This explains why python's email module may not be 100% correct:
http://stackoverflow.com/questions/1471987/how-do-i-parse-an-http-date-string-in-python

This is a function that implements correct parsing:
http://werkzeug.pocoo.org/docs/0.10/http/#werkzeug.http.parse_date

Line 670:
https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/http.py
