### ISSUE TITLE
Support obsolete HTTP date formats

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#255]
In looking at [RFC 7231](http://tools.ietf.org/html/rfc7231#section-7.1.1.1), Falcon date parsing is actually restricted to IMF-fixdate and does not support the other two obsolete formats. Should we support those formats? Doing so may have minor performance implications for little benefit.

Otherwise, we should update the docstrings and such to reference IMF-fixdate instead of HTTP-Date.

**Comment by mcmasterathl** [comment]
I forgot to say so before I started working on this but I will do this. About to submit a PR for it.

**Comment by kgriffs** [comment]
Let's wait just a sec. There's a PR about to merge that may give you conflicts.

**Comment by kgriffs** [comment]
See also: #482

**Comment by mcmasterathl** [comment]
@kgiffs I thought I had commented here but yeah, #482 and/or #495 should be merged first, and then I'll redo this on top of that.
