### ISSUE TITLE
Merge/simplify Response.{body,data,stream}

### ISSUE THREAD

**Issue by ex-nerd** [falconry/falcon#260]
per #256...

Looking at https://github.com/racker/falcon/blob/master/falcon/api.py#L122-L123 is there any reason why content_length is set _before_ the body?  Would it make more sense if `Response.body_encoded` did both encoding and length calculation (putting it into `stream_len`, likely renamed to `body_len`) for both body and data?  This would also be a natural place to put a call to some sort of (user-specified) "body encoding" hook (or check for an `encode_body` type method on `data`), maybe even something that would allow replacing `api_helpers.get_body` (assuming there was a way to get `env['wsgi.file_wrapper']` into the Response object).

Anyway, that seems like the natural place to look for merging body/data/stream, especially since there are already property markers on `body` to make sure that updating it resets `_body_encoded` (something which updating `data` or `stream` might should do as well)

**Comment by kgriffs** [comment]
Here's a proposal demonstrating how the new interface might work:

```python
resp.body = u'Hello world!'
resp.body = b'Hello world!'
resp.body = (file_like, expected_len)
resp.body = (byte_yielding_iterable, expected_len)
```

**Comment by CaselIT** [comment]
I don't think this applicable any longer
