### ISSUE TITLE
Setting multiple Cookies in Response

### ISSUE THREAD

**Issue by marcelalburg** [falconry/falcon#270]
Hello,

it's not possible to add more "Set-Cookies" in the header.

In the http://tools.ietf.org/html/rfc6265 ->

 == Server -> User Agent ==

   Set-Cookie: SID=31d4d96e407aad42; Path=/; Secure; HttpOnly
   Set-Cookie: lang=en-US; Path=/; Domain=example.com

**Comment by kgriffs** [comment]
Implemented in #405
