### ISSUE TITLE
The name Falcon really needs to be reconsidered/changed

### ISSUE THREAD

**Issue by Kentoseth** [falconry/falcon#272]
I say this because of this:

http://www.falconframework.com/

and this:

http://phalconphp.com/

Any and all feedback requested.

**Comment by vytas7** [comment]
FWIW, the domain in question is, at the time or writing, for sale with *hugedomains.com* (at a lofty price though).

**Comment by vytas7** [comment]
@kgriffs IMHO we should close this one, thoughts?

Given the huge amount of TLDs available nowadays, we won't have the financing to buy `falconframework.<anything>`.
As pointed out above, at least falconframework.com is not owned by any real framework. And we are not really a `.com` (commercial) entity anyway :slightly_smiling_face:

**Comment by kgriffs** [comment]
Yeah, when I originally contacted the domain owner he was hinting at an unreasonable price. I don't want to pay through the nose for something like this on principle, and I really haven't heard anyone even mention this as a problem for a very long time in any case. Plus, now that falconframework.com just goes to a "for sale" page people will quickly realize they got the wrong TLD. I suppose we could consider a different domain name that isn't taken, but it's probably not worth it at this point.

**Comment by vytas7** [comment]
Closing this for now. We could reopen/reconsider/take action in the future in case anyone buys falconframework.com and hosts anything that conflicts with our values and/or impersonates us.
