### ISSUE TITLE
Add support for link-extension to Response.append_link

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#288]
See also: https://tools.ietf.org/html/rfc5988

**Comment by kaichan1201** [comment]
Hi, I am interested to work on this issue. Could you give me some pointers?

**Comment by kaichan1201** [comment]
Am I correct in understanding that I need to provide an extra argument to the function append_link() to support link extension, and update the corresponding link header using the spec from rfc5988?

**Comment by vytas7** [comment]
Hi @kaichan1201!
And sorry for the delay in getting back to you.

It seems that we need to revise this in the light of [RFC 8288](https://datatracker.ietf.org/doc/html/rfc8288), which obsoletes the referenced (https://datatracker.ietf.org/doc/html/rfc5988). Sorry this issue got a bit more complex than it initially looked like... could you check how `link-extension` is defined in 8288?
