### ISSUE TITLE
Add helpers for getting and setting cookies

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#292]
Note: Cookies require special handling in responses because they must be set as distinct headers (cannot be folded using commas as you would other headers).

**Comment by tbug** [comment]
I need this feature, so I'll give this one a go.

I have a few questions though.

1. is there a reason for not using something like https://docs.python.org/2/library/wsgiref.html#wsgiref.headers.Headers
to represent headers. It seems like the obvious choice to me, and would really solve this Cookie problem out of the box. It is present in both Py2 and Py3, so should cause no trouble?
2. Is there a reason for lowercasing header keys? Is it simply to easy collision detection?
It is just a cosmetic thing - i know - but i'm annoyed by not being able to decide my header keys casing :smile:

**Comment by tbug** [comment]
- I did a quick implementation of `wsgiref.headers.Headers` for response headers.
- I exposed the `Headers` object on `Response.headers` as it is now safe to give
users access to it directly.
- I changed the existing Response object API to use the new header object.

I may need to do a bit of cleaning, as some of the helpers might not be needed anymore.
Could give a bit extra in perf. I also need to add a few extra lines to some of the test cases
to reach all code branches again.

If we need more flexibility out of the `Headers` object, we could grab it from `wsgiref.headers.Headers`
and just include it in falcon.
Might be useful to be able to add header utils directly on the class that manages headers,
and it will be easy to also use it for managing the request headers if we so desire.

@kgriffs Thougts?

**Comment by kgriffs** [comment]
Hi @tbug, thanks for helping out on this. I'm not necessarily opposed to moving towards a more object-oriented model, where we introduce a resp.headers class with various methods. However, `wsgiref.headers.Headers` may not be the most performant way to go. Out of curiosity, I whipped up a quick-and-dirty test:

https://gist.github.com/kgriffs/463951c9df0d38edfe78

%timeit results for CPython 3.4.2:

```
In [19]: %timeit test_a()
100000 loops, best of 3: 8.51 µs per loop

In [20]: %timeit test_b()
100000 loops, best of 3: 2.88 µs per loop
```

Like I said, this was a quick-and-dirty test, but these results make me hesitate to use wsgiref.headers.Headers as-is...

**Comment by tbug** [comment]
Ah. Right.
I'll have a try at doing a faster implementation.
Shouldn't be that hard, seeing as `wsgiref.headers.Headers` is pretty crappy :wink:

**Comment by tbug** [comment]
I gave this a try.
For reference, this is your exact code, on my machine, with CPython 3.4.0:
```
In [31]: %timeit bench.test_a()
100000 loops, best of 3: 5.61 µs per loop

In [32]: %timeit bench.test_b()
1000000 loops, best of 3: 1.42 µs per loop
```

And my own `Headers` implementation without user-cased keys

```
In [34]: %timeit bench2.test_a()
100000 loops, best of 3: 2.72 µs per loop

In [35]: %timeit bench2.test_b()
1000000 loops, best of 3: 1.66 µs per loop
```

And lastly, one with usecased keys:

```

In [9]: %timeit bench3.test_a()
100000 loops, best of 3: 3.55 µs per loop

In [10]: %timeit bench3.test_b()
1000000 loops, best of 3: 1.62 µs per loop
```

I tried moving the code out of the `Headers` object and directly onto the implementation and got:

```
In [7]: %timeit -n 100000 bench4.test_a()
100000 loops, best of 3: 2.46 µs per loop

In [8]: %timeit -n 100000 bench4.test_b()
100000 loops, best of 3: 1.63 µs per loop
```

So at least it is not creating the `Headers` object that slows anything down.

**Comment by tbug** [comment]
The best thing i've been able to come up with that uses a `Headers` object is timed at

```
In [74]: %timeit -n 100000 bench5.test_a()
100000 loops, best of 3: 3.45 µs per loop

In [75]: %timeit -n 100000 bench5.test_b()
100000 loops, best of 3: 1.65 µs per loop
```

And my best that is directly implemented on the `Response` that
still outputs headers in user-case is
```
In [78]: %timeit -n 100000 bench4.test_a()
100000 loops, best of 3: 2.36 µs per loop

In [79]: %timeit -n 100000 bench4.test_b()
100000 loops, best of 3: 1.65 µs per loop
```

and without usercase:

```
In [81]: %timeit -n 100000 bench4.test_a()
100000 loops, best of 3: 1.96 µs per loop

In [82]: %timeit -n 100000 bench4.test_b()
100000 loops, best of 3: 1.64 µs per loop
```

My take on this, is that i definitely think the solution to the cookie issue is to simply support multiple headers by the same name.

It will be much cleaner than handling cookies seperately.

If we just upgrade to support multiple headers by same name, the speed diff on my machine will be less than half a microsecond pr. req/resp.

Include usercased keys, and we have a 2 microsecond difference pr. response.
I think i might be able to speed this up a bit though, but i do see that ~2 microseconds is way to much for something that essentially adds nothing.

@kgriffs what do you think?

**Comment by tbug** [comment]
Thought about this some more.

If it is completely unacceptable to lose speed in cases where people don't use cookies, handling just the cookie case seperately, and merging cookie headers just before the return in `_wsgi_headers`, will most likely be way better for performance.

So that might also be an option. But then only cookies will be able to set multiple headers by the same name.

**Comment by kgriffs** [comment]
@tbug Thanks for your work on this. I think this latest approach is the best one for now. Using a `set_cookie` method should be pretty straightforward, and we can easily swap out the guts later on if/when the implementation changes.
