### ISSUE TITLE
Revisit form-based file uploads

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#294]
There's a sustained interest in having Falcon support HTML form-based file uploads.

"In django i just did, with form: file = request.FILES['image'].read()  without form: file = request.body"

How do we do this in a performant manner? How do we keep dependencies minimal?

**Comment by kgriffs** [comment]
Thinking about this again... should this be an add-on, or should form params and file uploads be part of the core framework? Either way, the functionality is needed!

**Comment by kgriffs** [comment]
See also:

- #493
- #418

**Comment by lwcolton** [comment]
Hey @kgriffs,

    I'm interested in seeing multipart file upload capabilities added to Falcon.  I think the main design decision is whether to use the multipart form parsing available in cgi.FieldStorage  or  write our own multipart form parser.  falcon-multipart uses cgi.FieldStorage so if that is acceptable to you, I think it would be pretty straightforward to add that to falcon.

**Comment by vytas7** [comment]
I'm going to close this now since the work is primarily tracked as https://github.com/falconry/falcon/issues/953 (within the [Falcon 3.0 milestone](https://github.com/falconry/falcon/milestone/33)).
