### ISSUE TITLE
Investigate PasteDeploy integration

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#297]
Is there anything Falcon can do to make it easier to deploy apps via PasteDeploy? And should we care about PasteDeploy in the first place (now that it support py3k)?

See also: http://pythonpaste.org/deploy/#paste-app-factory

**Comment by pior** [comment]
PasteDeploy seemed great to me for a long time. But using environment variable with a paster config is not really nice. Here is the best I found with Pyramid https://gist.github.com/pior/b1d181802fac750f0cc1

At the end I wonder if a documented pattern like the Django style settings.py is not preferable.

**Comment by vytas7** [comment]
@kgriffs I'm inclined to close this issue given that the idea (Falcon+PasteDeploy) hasn't really attracted much interest over 5-6 years.
Thoughts?
