### ISSUE TITLE
Friendly status code names

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#308]
Add friendly names for common status codes ala https://docs.python.org/3.0/library/http.client.html

**Comment by Neetuj** [comment]
we are already facing this issue 


using this in our code base :- 

    def on_get(self, req, resp):
        resp.status = falcon.HTTP_300


and travis complaints :- 


************* Module jumpgate.identity.drivers.sl.versions

E: 9,22: Module 'falcon' has no 'HTTP_300' member (no-member)

ERROR: InvocationError: '/home/travis/build/softlayer/jumpgate/.tox/pep8/bin/pylint -E jumpgate'



should i open a new bug? have the old status codes been deprecated?

**Comment by kgriffs** [comment]
@Neetuj That's odd; HTTP_300 has not been removed. In fact, this work item hasn't been started yet (at least I haven't seen any PRs referencing it). Maybe this is a false positive from pylint for some reason?

**Comment by Neetuj** [comment]
Yes seems like so .. since i also did not see any work or check in related
to it.

**Comment by kgriffs** [comment]
@Neetuj Any update on this issue? Is there a way to reproduce the issue outside of Travis?

**Comment by mcmasterathl** [comment]
I am working on this at the Pycon sprints
