### ISSUE TITLE
ASGI+WebSocket

### ISSUE THREAD

**Issue by kerwin** [falconry/falcon#321]
Is there a way to support websocket on falcon?

**Comment by joranbeasley** [comment]
I would also like to see something like FlaskWebsockets  for falcon ...

**Comment by kgriffs** [comment]
We've been toying with the idea of expanding the framework to support interfaces other than WSGI, such as twisted.web and aiohttp. If we start going down that path, WebSocket support in Falcon may make sense after all.

**Comment by s-trooper** [comment]
just as info, it seems django going to solve wsgi related problems this way: http://channels.readthedocs.org/en/latest/asgi.html

**Comment by kgriffs** [comment]
Related: #582

**Comment by ulgens** [comment]
Any progress?

**Comment by jrgp** [comment]
I'm interested in using Websockets with Falcon as well.

**Comment by pushshift** [comment]
+1 For any type of websocket functionality.  Would be great if we could find something workable.

**Comment by jrgp** [comment]
Definitely. I have a use case for websockets + falcon I'd implement if support was there. I haven't gone the node route as I don't want to maintain two codebases for the same project.

**Comment by kgriffs** [comment]
Hi everyone, I've started work on #1055 and so far [uvicorn](http://www.uvicorn.org) looks like a very promising (no pun intended!) avenue for adding WebSocket support to Falcon. I'd like to gather a few concrete use cases to help inform the design. If you can, please provide an overview of how you are using--or plan to use--WebSocket connections, including subprotocols (either IANA-registered or bespoke). Thanks!

**Comment by pushshift** [comment]
@kgriffs,  

Awesome -- thanks!  Quick question for you.  I understand from earlier in the conversation that you said Websockets uses the upgrade header in order for it to work correctly.  My question is whether SSE (Server Side Events) support within Falcon is doable currently?  My understanding is that SSE is more of a one-way channel from the server to the browser.

Does Falcon currently support SSE and if not, would implementing Websockets also implement SSE support?

Thanks again!

**Comment by kgriffs** [comment]
@pushshift The WSGI spec isn't really designed for things like SSE, but it should be possible with uvicorn/ASGI (see also: http://www.uvicorn.org/#streaming-responses). This would probably be an extension of #1055 since it is based on regular HTTP vs. WebSocket.

**Comment by kgriffs** [comment]
(We'll probably want to label this as "experimental" in the first iteration since there will likely be feedback and perhaps immature dependencies.)

**Comment by Camilo-HG** [comment]
Hey, hi! 

Any progress in this topic?

Falcon rocks! ... It would be great to have WebSocket support.

**Comment by singhrajesh8699** [comment]
any update for web socket implementation in Falcon.

**Comment by cboursinos** [comment]
Any update on this?

**Comment by kgriffs** [comment]
After meeting with Amber (daphne/twisted) at PyCon I'm going to move forward with ASGI. Based on Andrew's talk, it seems that the spec has settled down and this is the best way forward without inventing yet another one-off async web stack (hooray!). 

My current thinking is to add at least basic routing support so you can register a websocket handler for specific URLs that will be fed events with the connection scope (URL, template params, headers, etc.).

I plan to work on HTTP support first, and so WebSocket support may have to wait until 2.1 (TBD). If anyone would like to sponsor this feature for 2.0, I could certainly dedicate more time to it. http://falconframework.org/#sectionSupportFalconDevelopment

**Comment by jrgp** [comment]
Hi @kgriffs what are your thoughts on how https://github.com/jgelens/gevent-websocket does it as well as flask's integration? I might be wrong but I think the implementation described in this ticket is Python 3 only.

**Comment by kgriffs** [comment]
@jrgp That interface looks similar to what we were thinking for Falcon. To keep things lean-and-mean, we likely won't implement any subprotocols out of the box, but we should ensure that it is straightforward to implement plug-ins/add-ons in that vein.

**Comment by kgriffs** [comment]
Just a quick update on this, a generous community member has offered to sponsor the ASGI HTTP and WebSocket work. Either myself or one of the other core maintainers will work on the implementation for Falcon 2.0.

**Comment by Ei5enheim** [comment]
kgriffs, can you please let me know what is the tentative date for version 2.0 release? My project also requires web socket support in Falcon API.

**Comment by kgriffs** [comment]
Hi, sorry for the confusion. Since I made that last comment, we decided to ship 2.0 first (RC1 is currently available on PyPI) so that we could drop Python 2.7 and 3.4 support in 3.0 and do a cleaner ASGI implementation. 

3.0 development just opened on the master branch and we anticipate this milestone cycle to be significantly shorter than 2.0, with the primary focus being on ASGI and improved form data parsing. We'll be sprinting on the 3.0 milestone at PyCon US so stay tuned!

You can see what is currently planned here: https://github.com/falconry/falcon/milestone/33

**Comment by kgriffs** [comment]
Just a quick update on this, we are hoping to get it into 3.0 if we have time, but if not it will be a fast-follow feature in 3.1. Regardless, 3.0 will support server-sent events (SSE) when using the new ASGI interface, as an alternative to sending events via WebSocket (which does not work for HTTP/2).

The plan is to add support via ASGI for sure, and possibly also via uWSGI's native WebSocket support.

**Comment by jrgp** [comment]
Hey, just curious if there has been any update here?

**Comment by nmcbride** [comment]
> Hey, just curious if there has been any update here?

They have been keeping us pretty up to date here: https://gist.github.com/kgriffs/a719c84aa33069d8dcf98b925135da39

**Comment by kgriffs** [comment]
UPDATE: I have completed an alpha-quality implementation in my fork. Hoping to get it into 3.0.0a2. Docs and full test coverage will then be the focus for getting WebSocket scope support ready for 3.0.0b1.

**Comment by Camilo-HG** [comment]
Wow! Really ?? ... I was waiting for this!!

**Comment by kgriffs** [comment]
Tracking progress on this gist: https://gist.github.com/kgriffs/023dcdc39c07c0ec0c749d0ddf29c4da
