### ISSUE TITLE
Consider passing the return value from responders to after hooks

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#325]
I've heard from a couple of people in the community who would like to return values from on_\* methods and process them in after hooks or middleware. We should decide if this makes sense, given that `req.context` can be used to similar effect.

**Comment by kgriffs** [comment]
I think we just need to document using req.context (or perhaps add a resp.context if that would make more sense...

**Comment by vytas7** [comment]
Closing since the recommended (short-term at least) approach is using the context.

A longer term idea to use return chains to pass around things is tracked in #1047.
