### ISSUE TITLE
Docs re Async I/O

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#344]
See also the relevant ML thread, and this: http://bottlepy.org/docs/dev/async.html#greenlets-to-the-rescue

**Comment by kgriffs** [comment]
Related: with twisted.web.wsgi you can use crochet to do some things.

**Comment by sebasmagri** [comment]
Would be great to see a benchmark using [uvloop](http://magic.io/blog/uvloop-make-python-networking-great-again/)

**Comment by kespindler** [comment]
@sebasmagri did you ever try to mash those two up together? falcon + uvloop is something i'd be interested to see documentation as well

**Comment by sebasmagri** [comment]
@kespindler not yet, been swamped with some projects here. But I'm definitely interested on benchmarking against uvloop.

**Comment by vytas7** [comment]
Superseded by other issues as the async I/O documentation should probably revolve around the ASGI standard that we settled on, and it is better to track this separately.
See also:
* https://github.com/falconry/falcon/issues/1123
* https://github.com/falconry/falcon/issues/1542
