### ISSUE TITLE
Example skeleton project

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#346]
Suggestion from the IRC channel:

> I’m thinking something we could use as a starting point to figure out layout, understand how tests are structured, and so on...

**Comment by MackYoel** [comment]
@kgriffs I'm really interested in a falcon skeleton project, start as a newbie can be a head ache. Please consider at least share some of your code

**Comment by vytas7** [comment]
Closing in favour of #1520 (normally i would keep the older issue, but the other one is better structured & already scheduled in a project in this particular case).
