### ISSUE TITLE
Support more URI template stuff

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#35]
http://tools.ietf.org/html/rfc6570

* {/list*} => /red/green/blue
* Path Segment Expansion: {/var}
* Mandatory query params (when literals are specified, will also need query continuation support)
* Max length? Maybe not, because would mean 404 if exceeded unless rearchitect how route matching works. Have to match and then throw a different exception if too long.
* Etc.

Depends on issue #114

**Comment by bendemaree** [comment]
Another one for this list, brought in from IRC. This seems to be the parent issue for URI template things; if not, I'm happy to move this! :smile:

As far as I can tell, [the RFC](http://tools.ietf.org/html/rfc6570#section-2.3) allows leading underscores (`_`) in URI template variable names.

```
varname       =  varchar *( ["."] varchar )
varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```

This should allow for `varname`s of the form `_ref` or `_link`, for example.

**Comment by kgriffs** [comment]
Marking as invalid and closing this issue, since Falcon is moving away from the RFC altogether.
