### ISSUE TITLE
doc: Create a "who's using it" section

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#36]

**Comment by yasoob** [comment]
Hey do you currently know who is using it?

**Comment by kgriffs** [comment]
@yasoob Besides Rackspace, I've heard of Falcon being used at EMC, Hurricane Electric, and LeadPages. I know there are a good number of others but I haven't (yet) followed up with everyone in the community to find out where they work.

**Comment by jmvrbanac** [comment]
The Mailman folks use it in v3 for their REST api as well

**Comment by bendemaree** [comment]
Yep, we're using it at @LeadPages, though we haven't made it into production with Falcon yet.

**Comment by kgriffs** [comment]
Done. https://github.com/falconry/falcon/wiki/Who's-Using-Falcon%3F
