### ISSUE TITLE
Session support

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#366]
Should falcon support sessions in the core or as an add-on?

**Comment by houqp** [comment]
I vote for add-on :) We are planning to use beaker for now. Do you have other recommendations?

**Comment by kgriffs** [comment]
[Beaker](https://github.com/bbangert/beaker) seems like a reasonable solution. They claim to have "fast, robust performance", but you may want to do your own testing to make sure it meets your needs.

In Falcon 1.1 (currently in beta) you can now add additional properties to the `req` object, so you could use a Falcon middleware method to make the session a bit more accessible, e.g.:

```py
req.session = req.env['beaker.session']
```

**Comment by vytas7** [comment]
Sounds like an add-on is the way to go.
NB: in more recent Falcon versions, it's recommended to store custom data in [`req.context`](https://falcon.readthedocs.io/en/stable/api/request_and_response_wsgi.html#falcon.Request.context).
