### ISSUE TITLE
parse_query_string removes leading underscores

### ISSUE THREAD

**Issue by lwcolton** [falconry/falcon#374]
Line 264 of falcon/util/uri defines a function called parse_query_string which is used for the parsing of query parameters included in the URI of a request.  The regex being used currently excludes leading underscores (which are valid), among other things.  Recommend removing the first "[a-zA-Z]" of the regex.

Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from falcon.util.uri import parse_query_string
>>> parse_query_string("_id=foo")
{'id': 'foo'}
>>>

**Comment by mcmasterathl** [comment]
This was fixed inadvertently in #261.
