### ISSUE TITLE
Make "bytes" prefix in Range header value required

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#387]
Currently, range header values without a "bytes" prefix are allowed. Change the code to always require a "bytes" prefix.

**Comment by lwcolton** [comment]
Will work on this also

**Comment by lwcolton** [comment]
Can you explain this a little more?  Where in the code are we allowing a range header without a bytes prefix?  When a client sends one or when someone using the falcon framework sets one?

**Comment by kgriffs** [comment]
@lwcolton Here's the line of code in question:

https://github.com/falconry/falcon/blob/master/falcon/request.py#L344

Currently Falcon allows the sender to leave off the bytes prefix. We just want to make it mandatory.

**Comment by lwcolton** [comment]
@kgriffs sounds good
