### ISSUE TITLE
Make error class initializer signatures more consistent

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#391]
The goal is to prevent the developer from having to look up docs all the time to figure out how this or that error class is initialized; they should be initialized in a consistent way as much as possible.

Inconsistencies to address include:

* Not all classes may be initialized with a title and description. For classes where those are optional, we can add **kwargs, or introduce specializations such as ``HTTPRangeNotSatisfiable`` vs. ``HTTPRangeNotSatisfiableBlank``, where the former would take ``(self, title, description, resource_length, **kwargs)``.
* The above inconsistency alludes to the fact that some errors require title and description, while others do not. Perhaps some of the design could be cleaned up by making everything optional? It is good to set a title and description from a usability perspective, but does the framework need to enforce that?
* Some errors use a hard-coded title, while others do not. How to address localization for hard-coded strings, and should more of the errors have static titles, or none of them?

In any case, this must all be done in a backwards-compatible way. This might be accomplished (TBD) by creating generic \__init\__ methods and then discerning whether the old params are being used, or the new. Only the new ones will be documented so that over time apps will no longer use the deprecated signatures.

```python
def __init__(self, *args, **kwargs):
    # Check what args and kwargs were passed; hopefully this
    # will make it possible to support old and new signatures (TBD)
```

Alternatively, we could introduce a new errors module and deprecate the current one. A different naming convention could be used for the new-style error classes to distinguish them from the old.

Other ideas?

**Comment by admiralobvious** [comment]
I was about to open issue asking why some errors require a title and description. Falcon claims to be "un-opinionated" but I think having error classes that explicitly defines a JSON response with two fields "title" and "description" is pretty opinionated.

I know there's even already a mixin I can use to make my own error classes to remove the fields like:
```
class HTTPBadRequest(OptionalRepresentation, HTTPError):
   def __init__(self, **kwargs):
       super(HTTPBadRequest, self).__init__(status.HTTP_400, **kwargs)
```

but personally I think that by default error classes should not have any required fields to preserve the un-opinionated nature of Falcon.

**Comment by kgriffs** [comment]
@admiralobvious Thanks for the feedback. I do think it makes sense to make those args optional in `HTTPError` subclasses, as they are in `HTTPError` itself. That being said, for some errors, there are RFC *MUST* or *SHOULD* portions of a response that don't have a sensible default we'll have to consider, but for now I think 416 is the only one we've got that falls into that camp.

**Comment by admiralobvious** [comment]
@kgriffs Sure thing. 
So I did some more research on HTTP status codes vs RFCs and according to [RFC 2616](http://www.ietf.org/rfc/rfc2616.txt): 
   >The 4xx class of status code is intended for cases in which the
   client seems to have erred. Except when responding to a HEAD request,
   the server SHOULD include an entity containing an explanation of the
   error situation, and whether it is a temporary or permanent
   condition.

and

>Response status codes beginning with the digit "5" indicate cases in
   which the server is aware that it has erred or is incapable of
   performing the request. Except when responding to a HEAD request, the
   server SHOULD include an entity containing an explanation of the
   error situation, and whether it is a temporary or permanent
   condition.

So it seems none of the 4xx and 5xx status codes MUST have an entity but there is indeed a couple that SHOULD have one. Side note, I think Falcon implementing the SHOULDs is absolutely the right thing to do.
The 4xx and 5xx status codes that SHOULD have an entity are the following:

>406 Not Acceptable - Unless it was a HEAD request, the response SHOULD include an entity containing a list of available entity characteristics and location(s) from which the user or user agent can choose the one most appropriate.

>409 Conflict - The response body SHOULD include enough information for the user to recognize the source of the conflict. 

>413 Request Entity Too Large - If the condition is temporary, the server SHOULD include a Retry- After header field to indicate that it is temporary and after what time the client MAY try again.

>416 Requested Range Not Satisfiable - When this status code is returned for a byte-range request, the response SHOULD include a Content-Range entity-header field specifying the current length of the selected resource.

>505 HTTP Version Not Supported - The response SHOULD contain an entity describing why that version is not supported and what other protocols are supported by that server.

As you can see, technically only 409 mention anything about a body but I guess you can add 406 and 505 to that list as well as I don't really see where you'd return that information outside of a body. 413 and 416 only mention headers which Falcon already returns.

So I think if Falcon only required title and description (I also don't have a better idea for what those should be nor how they could be made user configurable) for 409 and perhaps 406 and 505 it would already make Falcon much less opinionated status code wise.

**Comment by foresmac** [comment]
We wrote a custom subclass of `HTTPBadRequest` to add a `handle()` method that sets the response status and body so we could capture both in our logging middleware. Otherwise all the middleware gets run in the inner `try/except` block of request processing before the outer `try/except` block actually handles any remaining uncaught `HTTPError`s.

I was thinking of writing a more generic subclass of `HTTPError` that sets the status to one of the constants in `status_codes`, pulls the `title` from that (i.e. `title = status_code[4:]`), and so the constructor only needs status, description, and kwargs. (It would also have the `handle` method added as well).

Then I could subclass that and make error-specific versions that only take description and kwargs, and set the status in the `__init__()`.

Either way, it would be more consistent and avoid having any errors that fall through without setting resp.body or resp.status before the request logger can run.

**Comment by kgriffs** [comment]
See also: #415

**Comment by foresmac** [comment]
Is this a change that won't make it into 1.0?

**Comment by foresmac** [comment]
I'm happy to try and adapt our solution into a patch if it's still possible to consider. Since it's a subclass of the existing HTTPError, I don't think it would technically introduce breaking changes.

**Comment by foresmac** [comment]
I think that the concept of #415 could be included in such a patch as well. Main difference is that I clip off the status code for the title. Makes sense to use a default description, though I'd prefer to document a best practice to include your own description to give more useful error reporting.

**Comment by kgriffs** [comment]
Thanks everyone for the comments. This issue is starting to get overloaded, so I've split it out into several work streams.

Making title and description optional, with a default for the title based on the status:

- #776
- #778

Reording initializer args to be more consistent:

- #777

 Please take a look and add any additional thoughts to these issues.

**Comment by kgriffs** [comment]
@foresmac We may be able to get something in 1.1 as long as it isn't a breaking change. Would you mind creating a new issue re:

> We wrote a custom subclass of HTTPBadRequest to add a handle() method that sets the response status and body so we could capture both in our logging middleware. Otherwise all the middleware gets run in the inner try/except block of request processing before the outer try/except block actually handles any remaining uncaught HTTPErrors.

Then we can pick up the conversation over there. I'm going to go ahead and close this one (#391).

Thanks!
