### ISSUE TITLE
Giving an after hook access to the responder return result?

### ISSUE THREAD

**Issue by kalefranz** [falconry/falcon#402]
Hi @kgriffs,

Today is my first day using Falcon, and I *really* like it so far. Thanks for continuing to develop on it and maintain it.

When writing an after hook, I encountered the case where I wanted access to the return value of the responder.  Currently in the framework it looks like even if a non-`None` result is returned by the responder, nothing is done with it and it is completely ignored.

It looks to be a simple feature to add.  For example, around line 206 of hooks.py in one of the `do_after` function definitions, replace

    responder(self, req, resp, **kwargs)
    shim(req, resp, self)

with 

    result = responder(self, req, resp, **kwargs)
    shim(req, resp, self, result)

There would be a few other changes--including cleaning up the unit tests--but that's the basics of what's required I think.

I was about to submit a pull request actually, but before spending time fixing the unit tests, I want to make sure you're ok with the concept and the solution.  One concern I have is that use cases of this feature could potentially touch on some of your implementation of `Response.body` and `Resonse.data`.  I want to confirm with you that the feature is compatible with the framework before submitting the pull request.

**Comment by kgriffs** [comment]
In 0.2 there is a new dict attribute, `req.context`, that can be used to pass arbitrary data around. We'll have to decide if it is more elegant in some cases to use return values as you propose. Have you had a chance to play around with using `req.context` already to see how that looks with your use case? I'd also like to get feedback from others in the community on how they would like to pass data between hooks and responders...

**Comment by kgriffs** [comment]
I'm going to go ahead and close this. Please reopen if `req.context` does not provide an adequate work-around.
