### ISSUE TITLE
Add a helper for redirects

### ISSUE THREAD

**Issue by rouge8** [falconry/falcon#406]
Flask, Pyramid, Django, etc. all include helpers for redirects. It would be nice if falcon had something similar, especially if it could be used from hooks.

Currently, I'm implementing a redirect in the same before hook I do validation from (e.g. returning `404` if an object doesn't match a route), but it seems like the responder methods on the resource must check the status code after the hook so as not to overwrite the redirect.

**Comment by kgriffs** [comment]
Makes sense. This is a pretty fundamental pattern, so I wouldn't be opposed to implementing it directly in the framework.

**Comment by csojinb** [comment]
I'd like to take a stab at this.

**Comment by aisola** [comment]
I've actually just completed it. Sorry forgot to comment to say I was going to try it.
