### ISSUE TITLE
Does a global before hook apply to sinks?

### ISSUE THREAD

**Issue by dukedougal** [falconry/falcon#409]
It appears that my global before hook applies to ordinary routes but not to sinks.

To make a before hook apply to a sink I have to use the before decorator.  I'd prefer to have a global before hook.

**Comment by kgriffs** [comment]
This is indeed a limitation of global hooks at the moment. However, in 0.2 ([now in beta][1]) we are introducing middleware support that should do what you need. Middleware components execute before and after sinks without having to decorate anything. 

[1]: https://pypi.python.org/pypi/falcon/0.2.0b2

**Comment by dukedougal** [comment]
This appears to prevent Talons authentication from working for sink based requests because Talons seems to work based on before event hooks.

**Comment by kgriffs** [comment]
@dukedougal  Good point about Talons. Once 0.2 is out we'll have to look at adding support for middleware to Talons (while keeping global hooks around for some amount of time for backwards-compat with 0.1).
