### ISSUE TITLE
TypeError raised when passing unicode string literal to set_header (uWSGI)

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#413]
The following raises an error:

```python
import falcon

class MyResource(object):
    def on_get(self, req, resp):
        resp.set_header('X-Name', u'value')
        resp.body = 'Hello world!'


application = api = falcon.API()

api.add_route('/', MyResource())
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/kgriffs/Code/falcon/falcon/api.py", line 265, in __call__
    start_response(resp.status, headers)
TypeError: http header value must be a string
```
Work items:
* Add a type check and convert the incoming value to `str`. Fence this code based on python version (no need to add the overhead of type checking in py3k)
* Add a performance warning to the docstring for py2 users

**Comment by ginoledesma** [comment]
I'll take a stab at this

**Comment by ginoledesma** [comment]
From what I can tell, uwsgi raises TypeError when either the header or value isn't a string. gunicorn, on the other hand, doesn't run into this because it str()-fies everything.

**Comment by kgriffs** [comment]
We neglected to address this for the header property setters.
