### ISSUE TITLE
How do I force an immediate response?

### ISSUE THREAD

**Issue by dukedougal** [falconry/falcon#414]
In Falcon I can force an immediate error code response to return from anywhere in my code by raising a Falcon exception with the appropriate error code.

Is there a way to force an immediate return of the response to the client for VALID (i.e. not errors) responses?

**Comment by kgriffs** [comment]
@dukedougal You could register a custom error handler and then raise exceptions of that type. It is a bit of a hack, but will work with 0.2. We'll look at doing something more elegant in 0.3 or 0.4.
