### ISSUE TITLE
It would be good if the errors had defaults for title and description fields, then they could be dispatched

### ISSUE THREAD

**Issue by dukedougal** [falconry/falcon#415]
I want to be able to pass error functions around for execution from a dispatcher. 

For example, to have a dict like {'operationname': HTTPMethodNotAllowed}

Then I could just invoke the method not allowed error by passing the function to something which executes it.

Currently I have to create a set of error functions like this with default values in them so I can dispatch error functions, just for the purpose of providing default values to title and description:

    from falcon.http_error import HTTPError
    import falcon.status_codes as status
    
    # a handful of simple HTTP errors that can be used without parameters
    def code400BadRequest(*args, **kwargs):
        # this is a request handler
        raise HTTPError(status.HTTP_400, title=status.HTTP_400, description=status.HTTP_400)
    
    def code401Unauthorized(*args, **kwargs):
        # this is a request handler
        raise HTTPError(status.HTTP_401, title=status.HTTP_401, description=status.HTTP_401)
    
    def code403Forbidden(*args, **kwargs):
        # this is a request handler
        raise HTTPError(status.HTTP_403, title=status.HTTP_403, description=status.HTTP_403)
    
    def code404NotFound(*args, **kwargs):
        # this is a request handler
        raise HTTPError(status.HTTP_404, title=status.HTTP_404, description=status.HTTP_404)
    
    def code503ServiceUnavailable(*args, **kwargs):
        # this is a request handler
        raise HTTPError(status.HTTP_503, title=status.HTTP_503, description=status.HTTP_503)

If you guys included default values for title and description then  I could delete all the above code from my app and deleting code is always nice :-)

**Comment by dukedougal** [comment]
Bump

**Comment by kgriffs** [comment]
I think it makes sense to make both title and description optional. If HTTPError receives `None` for the title, it will default to being the same as the status. Repeating the status in the description would not be necessary.

I've split this work into several issues to better track it. Thanks!

- #776
- #778
- #777
