### ISSUE TITLE
Research performance of SimpleCookie

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#421]
Our cookie handling in 0.3 will use the http.cookies.SimpleCookie (py3) or Cookie.SimpleCookie (py2) from the stdlib. See if there is any performance benefit to writing out own cookie rendering code or contributing to the stdlib directly.

**Comment by kgriffs** [comment]
Also look into cookie parsing performance for incoming requests.

**Comment by tgrant59** [comment]
Consider mentioning this in the docs, so newcomers will know there are no cookie helpers

**Comment by kgriffs** [comment]
See also #405
