### ISSUE TITLE
Add support for filters in route templates

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#423]
This is a request I've heard from the community, and that was previously mentioned in one of my comments on #161.  It would be nice to if we could support this within the path and for query string params (assuming we implement the latter). We can take inspiration from [bottle](http://bottlepy.org/docs/dev/tutorial.html#dynamic-routes). Default filters might include:
- [x] `int` (already implemented)
- [x] `float` deferred to https://github.com/falconry/falcon/issues/2022
- [ ] `path` prototype PR: https://github.com/falconry/falcon/pull/1945
- [x] `re` deferred to https://github.com/falconry/falcon/issues/857
- [ ] `in` will be deferred to another issue if needed

~~Also, we need to consider how this might be applies to query string parameters as well (which would require defining such parameters in the URI template)~~ :arrow_left: tracked separately in https://github.com/falconry/falcon/issues/838

**Comment by lindseybrockman** [comment]
I wouldn't mind looking into this!

**Comment by lindseybrockman** [comment]
@kgriffs I was glancing through the suggested default filters list again and realized I'm not sure what "in" is :P

**Comment by kgriffs** [comment]
@lindseybrockman  I honestly don't remember about "in", so let's just leave it out for now. However, we might want to add "uuid" since that is a fairly common way to specify resource IDs (in addition to "int").

I've split out the query string work into a separate issue (see also #838).

Here's what I was thinking regarding the contract for these filters...

Assume a sample template: 

```py
'/things/{thing_id:some_filter:optional_filter_config}'
```

And a sample request path:

```py
'/things/dd8644b9-98d3-4532-b759-57e8427d3f04/arbitrary/stuff'
```

Each filter would be defined as a callable that does the following:

1. Receives the following arguments:
    * A tuple of path segments starting with the current segment and ending with the last segment in the requested path
        - For simple conversion filters and such, they will only use the first item and ignore the rest.
        - Other filters that want to match/consume the rest of the path will make use of all segments.
    * Filter config string (default `None`)
        - Arbitrary string passed verbatim from how it is specified in the template.
        - Must escape '}' character since that is normally used to signify the end of the field definition in the template.
1. Returns a tuple consisting of the following, in the given order:
    * `True` if the filter accepted or matched the segment in the request path, `False` otherwise. If `False`, a single-element tuple may be returned, or the remaining members of the tuple must be `None`. 
        - E.g., given a "re" filter, it must match the expression. Given an "int" filter, the segment must be parsable as an `int`.
    * `True` if the filter consumed the entire remaining path (all remaining segments, starting with the current one). `False` if the filter only consumed the first segment.
    * The value to be assigned to the field name.
        - E.g., given a "re" filter, the match object or groups could be returned. Given an "int" filter, the value of the segment converted to an `int` would be returned. Other filters might simply pass through the string for the segment as-is.

To be consistent with the way non-filtered fields work, we may have to allow for templates such as:

```py
'/foo/bar.{name:filter}.png'
```

But if that ends up being complicated, we might want to break it out into a separate issue.

What do you think? Does it make sense to do it this way?

@jmvrbanac Also curious to get your thoughts on this...

**Comment by kgriffs** [comment]
Something else to think about: What is a good way to allow a filter to short-circuit a request with a specific error? For example, when parsing a UUID, if it is invalid, the filter may want to raise an instance of `HTTPBadRequest` instead of just returning `False` to indicate the segment wasn't matched/accepted, which would presumably result in a 404.

**Comment by lindseybrockman** [comment]
@kgriffs ah, yes, I'll be sure to take that into account! I believe custom filter registration was also suggested.. I was planning on going ahead with that as well, unless that has also been broken out into a separate issue (like #838)

**Comment by lindseybrockman** [comment]
@kgriffs one more follow up regarding the return value of a filter indicating that it consumed all of the remaining segments: I just want to confirm that this means falcon would only support filters that consume either the first segment _or_ the entire rest of path (presumably after it's been re-built with `/` delimiters). Only verifying because I checked the functionality in bottle, and it looks like templates like the following silly example are supported: `'/static/<static_path:path>/extra/segments/that/will/not/match'`, where the `static_path` param being passed to the controller will not contain the "/extra/segments/that/will/not/match" bit of the template.

**Comment by kgriffs** [comment]
@lindseybrockman I think custom filter registration would be good to do now, since that would help encourage a clean design. Regarding consuming any number of path segments, we could support it, but it may be something we put off for now since it would probably involve significantly more work in the router. But if we want to plan for that in the future, we could have filters return a number and just state that currently only `1` and `len(path_segments)` are supported. 

What do you think?

**Comment by lindseybrockman** [comment]
@kgriffs I agree that putting off consuming only certain path segments can be done at a later time 👍 I'll look into returning numbers and see if that would be another possible way of having them fail fast instead of having the tree return `None` and then 404.

**Comment by kgriffs** [comment]
@lindseybrockman Just following up to see if you were still working on this? If you don't have the bandwidth, no worries, just let me know and we can reassign. Thanks!

**Comment by kgriffs** [comment]
BTW, this could be a good way to score some points for https://hacktoberfest.digitalocean.com 🎃

**Comment by lindseybrockman** [comment]
@kgriffs woah jeeze, I really put this on the backburner 😖 It looks like the last bit of functionality I need to implement is filters on complex nodes! I'll dive back in this weekend and let you know if I need to hand the work off to someone else!

**Comment by lindseybrockman** [comment]
@kgriffs alrighty, working on some testing and clean up to prep for a PR. The last remaining issue was handling filters on complex nodes. You mentioned above that we may want to break it out into a separate issue. At first I thought I'd be able to tackle it, but it's been a little more time consuming than I thought it would be. Worst case scenario, I'll submit the PR with*out* support for that and work on adding it as a feature separately.

**Comment by lindseybrockman** [comment]
@kgriffs unfortunately I haven't had much time to dedicate to this feature. I will continue working on it if I get a chance, but I'm more than fine handing off the remainder of the work to a new assignee.

**Comment by kgriffs** [comment]
@lindseybrockman Thanks for everything you've done so far! Would you like to put up a WIP PR and then we can see if anyone else wants to take it and run with it?

**Comment by jaddison** [comment]
@kgriffs said that I should comment on my use case here, to make sure it's covered in any subsequent fixes.

Given URI:

```
/images/a,6;b,45;text,hello/http://www.test.com/photos/dcm_04334.jpg
```

I'd like to `add_route()` a route that matches the above like:

```
/images/{params}/{source}
```

such that `{params}` contains `a,6;b,45;text,hello` and `{source}` contains `http://www.test.com/photos/dcm_04334.jpg`.

I think a regular expression match is needed for the last bit?

**Comment by kgriffs** [comment]
@lindseybrockman just checking in to see if you are still working on this, or if you have some WIP code you would like to share for another contributor to pick up?

**Comment by lindseybrockman** [comment]
@kgriffs just opened a WIP PR for another user to grab! https://github.com/falconry/falcon/pull/976

**Comment by kgriffs** [comment]
Thanks!

**Comment by kgriffs** [comment]
Added initial support in 1.3. For the next release we still need to add `re` and `path` converters. These will need to use a different interface that allows for consuming more than one path segment. Also, these types of converters will be required to consume one or more complete path segments (no partial segments).

**Comment by kgriffs** [comment]
FWIW, I've heard from a couple people now who are looking for a way to accept forward slashes in a path segment. Most recent query from the gitter channel:

> Hi, how can I handle backslashes within a route Path? In Flask you can do: @app.route('/thing1/thing2/<path:param1>', methods=['DELETE'])
Wondering how to accomplish with Falcon? Thanks!
To expand on the above, the variable "param1" would look something like: "abc:def:ghi:a/798dfldfndk897:9odjlfndl"

**Comment by jeroenherczeg** [comment]
I would also like to comment my use-case here:

I am building a github like url strategy, where the last part of the url is a path to a blob or tree.

`app.add_route('/repo/{owner}/{repo}/tree/{branch}/{path}', treeObject)`

would match the url /repo/nikic/PHP-Parser/tree/master/lib/PhpParser/Lexer
with the **path** param being **lib/PhpParser/Lexer**

`app.add_route('/repo/{owner}/{repo}/blob/{branch}/{path}', blobObject)`

would match the url /repo/nikic/PHP-Parser/blob/master/lib/PhpParser/Lexer/Emulative.php
with the **path** param being lib/PhpParser/Lexer/Emulative.php
