### ISSUE TITLE
 Module 'falcon' has no 'HTTP_300' member (no-member)

### ISSUE THREAD

**Issue by Neetuj** [falconry/falcon#424]
travis is hitting this

 Module 'falcon' has no 'HTTP_300' member (no-member)
where i am using  resp.status = falcon.HTTP_300

 .. i see in the trunk HTTP_300 is still there .. https://github.com/racker/falcon/blob/master/falcon/status_codes.py#L29

**Comment by kgriffs** [comment]
@Neetuj  It would be cool if you could provide some sample code and instructions for reproducing the issue. If I can get the same error to happen on my box, I can help fix it.

**Comment by kgriffs** [comment]
Please reopen if this can be reproduced...
