### ISSUE TITLE
Add example code & recipes to test suite

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#44]
Need to do this in a DRY manner.

**Comment by kgriffs** [comment]
There's `test_example.py` for the "more complex example" that can be run manually, but no automated tests. We should add those tests, and also see if there is a way to have a single source of truth for this code (rather than duplicating it across test_example.py, README.rst, and the docs).

**Comment by vytas7** [comment]
It has been automated for a while, but in a fairly ugly way, breaking, for instance, how `cibuildwheel` tests operate.
