### ISSUE TITLE
Enable nitpicky in docs/conf.py and fix warnings

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#450]

**Comment by karlhigley** [comment]
I'm looking into this one.  Looks like nitpicky mode can be temporarily enabled with "-n" from the command line or perhaps through SPHINXOPTS in the Makefile.  I'm not sure which of the available targets to make, though.

**Comment by csojinb** [comment]
@karlhigley said that it looks like all of the warnings that pop up are actually problems with sphinx, so there might not be anything actionable in the falcon project

**Comment by kgriffs** [comment]
OK, sounds good, thanks!
