### ISSUE TITLE
Improve documentation around get_param vs. get_param_as_list

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#466]
Improve the docstrings for `Request.get_param()` and `Request.get_param_as_list()` to be more clear on a few points.
1. "foo=a,b,c" is considered semantically equivalent to "foo=a&foo=b&foo=c"
2. The traditional form-style where the same key is repeated for each value may be included directly in the query string, or via _application/x-www-form-urlencoded_. In the latter case, Falcon may be configured to automatically parse the body of the request and merge the result with the query string params.
3. When there are multiple instances of the same param, `req.get_param()` returns one of them. Which one it returns is undefined.
4. `req.get_param_as_list()` should be used instead.

There are currently no helpers for returning the unparsed ‘a,b,c’ value, but we can consider adding support for that according to community feedback.

**Comment by vytas7** [comment]
Most of the points raised in the issue's description have either been addressed, or become obsolete now that splitting on comma is no longer the default behavior.
