### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#473]
Proposed steps to include:
- [ ] Final performance testing/profiling and tuning (mitigate any regressions vs. previous release)
- [ ] Generate all docs, audit, and polish/fix as necessary
  - [ ] Generate Dash documents and submit PR
- [ ] Updating website with perf numbers (would be great to automate perf testing/tracking at some point)
- [ ] Create changelog
    - Update `AUTHORS` and contributors in the `towncrier` template (by running `tools/add_contributors.py`).
    - `towncrier` should generate the changes and put them in the correct _docs_ location.
- [ ] Modifying version.py
- [ ] Tagging/branching
- [ ] Beta(s)
- [ ] Release candidate(s)
- [ ] Packaging steps, including signing and uploading to pypi
- [ ] Announcement email

**Comment by vytas7** [comment]
The document should also mention the last sanity checks verifying that there are no breaking changes in a SemVer-minor release.
Because our users love SemVer (particularly @hynek :smiling_imp:).
