### ISSUE TITLE
Link to class and attribute documentation in docs

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#474]
In the docs, it would be nice to consistently link to referenced class and attribute names. In the RST files, this can be done using, e.g., `:attr:`. 

However, in the docstrings is there a way to do this without making the strings ugly to read in their raw form? I'd like to preserve readability via `help()` and while looking at the source.

**Comment by vytas7** [comment]
I'm going to close this since it seems we silently bit the bullet and proceeded with the "ugly" option, linking via `:attr:`, `:class:`, etc, where applicable.
