### ISSUE TITLE
Migrate Jython tests to tox once Jython 2.7 virtualenv problems are resolved

### ISSUE THREAD

**Issue by csojinb** [falconry/falcon#501]
Currently, Jython 2.7 doesn't play nice with virtualenv. I reported the issue [here](http://bugs.jython.org/issue2329), but it sounds like it is based in deeper issues that are already known.

**Comment by kgriffs** [comment]
Looking at the linked issue, this should be fixed now on the Jython side.

**Comment by csojinb** [comment]
Here is the original PR with a somewhat-hacky solution for getting the Jython tests to run, which may be useful if someone wants move the Jython tests to tox and rip out the existing solution. https://github.com/falconry/falcon/pull/488

**Comment by vytas7** [comment]
Closing this as we have dropped Jython support in Falcon 2.0.
