### ISSUE TITLE
Create an IRC welcome bot

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#508]

**Comment by csojinb** [comment]
Perhaps could adapt Shauna's project https://github.com/shaunagm/WelcomeBot. Looks pretty straightforward.

(I presume this is where you got the idea)

**Comment by oscarcp** [comment]
I've used in the past Supybot which is fairly easy to install and configure and it's fully featured. It allows automated management of the channel, logging, I even created a ticket query system to keep track of the new tickets being filed or solved ones. http://sourceforge.net/projects/supybot/

**Comment by kgriffs** [comment]
Ended up forking WelcomeBot after all: https://github.com/falconry/WelcomeBot
