### ISSUE TITLE
Request.get_header raises the wrong exception

### ISSUE THREAD

**Issue by TylerHendrickson** [falconry/falcon#534]
Found an issue that is making exception-handling not very intuitive when dealing with required headers...

```
try:
  my_header = req.get_header('My-Header', required=True)
except falcon.HTTPMissingHeader:
  print 'Missing header'
except falcon.HTTPMissingParam:
  print 'Missing param'
# Prints "Missing param"
```

Basically, calling ``get_header()`` with ``required=True`` should raise a ``HTTPMissingHeader`` exception, when actually what gets raised is ``HTTPMissingParam``.

This also leads to confusing error response messages, since the response title and header refer to a missing, required "query parameter" instead of a "header".

**Comment by kgriffs** [comment]
I was able to reproduce. Fixing now.

**Comment by TylerHendrickson** [comment]
Awesome!  Thanks, folks!
