### ISSUE TITLE
Add client_ip property to Request

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#539]
Add a client IP property to the Request class. A few relevant SO articles here:

* http://stackoverflow.com/questions/22868900/how-do-i-safely-get-the-users-real-ip-address-in-flask-using-mod-wsgi
* http://stackoverflow.com/questions/7835030/obtaining-client-ip-address-from-a-wsgi-app-using-eventlet

**Comment by sebasmagri** [comment]
I'd like to see this implemented as a core middleware but not enabled by default to avoid the performance penalty if some more advanced logic such as the trusted proxies stuff is implemented.

**Comment by pior** [comment]
What about in the core API, but with lazy evaluation?

**Comment by kgriffs** [comment]
[duplicate of #598]
