### ISSUE TITLE
Param validation

### ISSUE THREAD

**Issue by formbound** [falconry/falcon#549]
The exception HTTPInvalidParam indicates to the client that a query parameter is missing, even if the parameters are supplied via the HTTP body using `application/x-www-form-urlencoded` data. I think this may be confusing the the client, and also makes me wonder whether i can use the `get_param_as_xxx` methods for e.g. JSON data using a simple extension to the Request class. What's the thought behind this?

By overriding `__init__` of the `falcon.Request` class, i can for instance add this snippet:

```python
if (self.content_type is not None and
        'application/json' in self.content_type):
    self._parse_json()
```

Calling this method:

```python
def _parse_json(self):
    body = self.stream.read()

    try:
        body = body.decode('utf-8')
    except UnicodeDecodeError:
        body = None
        self.log_error('Failed to utf-8 decode HTTP body string ')

    if body:
        self._params.update(json.loads(body))
```

Doing this seems like a great idea to me, as i can now leverage the `get_param_as_xxx` methods. However, the client is now free to provide some parameters via the query string, and some via the JSON body. I see no real problems with this possibility, do you?

I'd propose the message be changed, or a separation between methods of getting body parameters and query parameters.

**Comment by kgriffs** [comment]
@formbound I think it would make sense for 0.3 to make the `HTTPInvalidParam` message a little more generic. In 0.4 we are looking at decoupling form and query param parsing (see also #418). 

Regarding your idea of merging JSON fields with query string params, I'd like to learn more about your goals. Do you expect params to come from *either* a document or a query string, and you want to be able to parse them using the same code? Or do you just want to use the `get_param_as_xxx` from the JSON document, but you don't expect the same fields to ever be passed via the query string?

**Comment by formbound** [comment]
@kgriffs, in light of #418 i think it makes sense to not merge `application/x-www-form-urlencoded`parameters into the `request.params` at all. Maybe have the `request.params` only deal with query. It sort of depends on what falcon wants to do (if anything) with the request body.

Personally my use case is simply to validate the incoming form data. Here are my steps:

1. Extended `falcon.Request`with a `body_data`property.
2. Used middleware to populate that property with a dictionary or array of dictionaries if possible, and as a lazy getter.
3. Wrote my own validator that i can hook up to resources

I still use the `get_param_as_xxx` as when dealing with query parameters, there's usually never a complex schema that needs validation. At least not in my case.

**Comment by kgriffs** [comment]
So far Falcon hasn't done much with the request body. I'm hoping we'll see some add-ons emerge from the community that help with that. I'm going to close this for now, but we can reopen later if we want to revisit the idea.
