### ISSUE TITLE
How do I integrate Falcon with AngularJS? 

### ISSUE THREAD

**Issue by advancedits** [falconry/falcon#552]
I am experimenting with the Quick Install demo application "things.py" here (http://falcon.readthedocs.org/en/latest/user/quickstart.html)

How do I serve AngularJS frontend with "add_route"?
Is there a way to redirect to my index.html?

**Comment by sebasmagri** [comment]
@advancedits while this discussion is more adequate for the [mailing list or IRC](http://falcon.readthedocs.org/en/latest/community/help.html), I'll add my thoughts here. 

Normally the API server does not deal with static or HTML files, this would be frontend Web server job. So, what I normally do in development is to keep the frontend app separated from the API project and fire up `python3 -m http.server` from the frontend app `index.html` folder to get the HTML and static files served. On production, this can be managed by nginx or your cloud files service.

**Comment by oscarcp** [comment]
As @sebasmagri falcon will only take care of the API side, the frontend has to be served by a front server like nginx/apache or any other. In my setup (I have falcon+AngularJS) I keep frontend and backend in separate projects, and also run them differently in the server. While Falcon is being run by uWSGI, the frontend is a separate instance being run by nginx itself.

**Comment by advancedits** [comment]
Thank you @sebasmagri and @oscarcp , appreciate the response. 

I'm currently using Waitress HTTP server and thought I could run Falcon+AngularJS on the same server. Is the convention to run 2 separate servers for this stack?

**Comment by lwcolton** [comment]
@advancedits Usually Javascript libraries like AngularJS are served using a conventional web browser like Apache or Nginx.

**Comment by lwcolton** [comment]
@jmvrbanac This can close

**Comment by jmvrbanac** [comment]
I think we have an answer here, but I'll just toss in my two cents anyhow. Personally, I would run two separate servers. Usually, the scalability needs are different between your API and frontend. I would also say that the ideal tooling is different as well. Personally, most of my deployments involve using gunicorn for serving Falcon, but Nginx in front of it to handle TLS connections and any static content that I may need.

**Comment by kgriffs** [comment]
@jmvrbanac perhaps we should open a documentation issue to capture this for posterity?
