### ISSUE TITLE
Add error classes for additional error codes

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#561]
We recently added additional codes per RFC 6585. It would be nice to add error classes as well.

**Comment by adamyala** [comment]
https://github.com/falconry/falcon/pull/576

**Comment by kgriffs** [comment]
The following from #576 were never merged. Did this slip through the cracks?

* 428 Precondition Required
* 431 Request Header Fields Too Large*
* 511 Network Authentication Required

There may be other codes defined in `status_codes.py` that could use corresponding classes. Note that these should conform to the pattern outlined in #777.

**Comment by lucasgnavarro** [comment]
@kgriffs #576, #973 they were merged. This can be closed I think...

**Comment by vytas7** [comment]
At least all the status codes discussed in this thread seem to have been addressed in https://github.com/falconry/falcon/pull/973.

Closing this, let's create a new issue if needed (if any status exception classes are sill missing).
