### ISSUE TITLE
URI template conflict when separating parameters by a '.' (dot)

### ISSUE THREAD

**Issue by admiralobvious** [falconry/falcon#564]
I am trying to do something like this:

```
class File:
    def on_get(self, req, resp, file_id):
        print(file_id)

class FileDetails:
    def on_get(self, req, resp, file_id, ext):
        print(file_id, ext)

api = falcon.API()
api.add_route('/files/{file_id}', File())
api.add_route('/files/{file_id}.{ext}', FileDetails())
```

but I am getting a: `ValueError: The URI template for this route conflicts with another route's template`.

I didn't see a test for this in the tests folder so I am guessing this is not supported? Is that really the case or is it simply an oversight?

**Comment by kgriffs** [comment]
@admiralobvious It isn't supported yet, but I don't see any reason why we couldn't extend the default router to handle this.

**Comment by maxking** [comment]
I am trying to attempt this isssue. I am wondering how could this be done, as my simple fix(mentioned below) breaks some tests.

```python
        path = re.split(r'[\/.]', uri_template.strip('/'))
```

So, I went through the codebase and I am of the opinion that, URI of the type `/home/file.jpg' can match either `/home/{file}' or '/home/{file}.(extension}' templates. Any pointers about how should I proceed?

**Comment by philiptzou** [comment]
@admiralobvious #647 has been merged. Please check if this fixed your problem.

**Comment by admiralobvious** [comment]
@philiptzou it did indeed. Cheers!
