### ISSUE TITLE
Update quickstart examples to inherit from object (new-style classes)

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#565]

**Comment by adamyala** [comment]
Hi. I'm new to Falcon, but have some Flask experience. I'd like to tackle this issue as my first open source contribution, but I'm not completely sure what the "new-style classes" are. I can see that the quickstart docs say:
```
class ThingsResource:
    def on_get(self, req, resp):
        """Handles GET requests"""
        resp.status = falcon.HTTP_200  # This is the default status
        resp.body = ('hello world')
```
but the API docs look more like:
```
class ThingsResource(object):
    def on_get(self, req, resp):
        """Handles GET requests"""
        resp.status = falcon.HTTP_200  # This is the default status
        resp.body = ('hello world')
```
Is the `(object)` part the only difference? If there's code I can look at to clear up my confusion I'll gladly do so.
