### ISSUE TITLE
AttributeError when accessing request uri/url

### ISSUE THREAD

**Issue by hooblei** [falconry/falcon#567]
Hi,

I'm getting this AttributeError when accessing Request uri or url using falcon 0.3.0
````
Traceback (most recent call last):
  File "falcon/api.py", line 154, in falcon.api.API.__call__ (falcon/api.c:1809)
  File "falcon/request.py", line 214, in falcon.request.Request.__init__ (falcon/request.c:1629)
  File "./dkuim/api.py", line 29, in context
    print("Create CONTEXT", req.url)
  File "falcon/request.py", line 399, in falcon.request.Request.uri (falcon/request.c:4006)
AttributeError: _cached_uri
````
I had a short look in request.py but yet no clue.

**Comment by kgriffs** [comment]
I wonder if this is a Cython bug... Have you tried uninstalling/reinstalling falcon to get a fresh compile? Also, you might try installing without Cython (or simply deleting the .so files).

**Comment by hooblei** [comment]
Hi, don't think it's a Cython bug. I have a custom conext func (context_type) wich is called like a request class method. When accessing a property within this function from request (self) the property doesn't exist since context is instantiated before self._cached_uri = None ... hm.

Would it be possible to move context at the end of __init__?

**Comment by kgriffs** [comment]
Ah, OK.

> Would it be possible to move context at the end of init?

That should be fine. If you want to fork the project and try it out to be sure it solves your problem, I'd be happy to review a PR for this change.
