### ISSUE TITLE
Remove dependency on six

### ISSUE THREAD

**Issue by underrun** [falconry/falcon#574]
it would be nice if we could avoid depending on six.

is that at all something that others are interested in?

**Comment by tbug** [comment]
Could you expand on why depending on `six` is an issue? :)

**Comment by kaidokert** [comment]
I came here to ask if six could be replaced by 'python-future' instead. 
See this :
http://python-future.org/faq.html?highlight=six#relationship-between-python-future-and-other-compatibility-tools
http://python-future.org/compatible_idioms.html

**Comment by tbug** [comment]
@kaidokert What would be the advantage of replacing six with python-future?

**Comment by kgriffs** [comment]
@underrun We could remove the dependency by basically forking the helpers from six that Falcon uses. That being said, could you elaborate on why you would like to avoid depending on six?

@kaidokert python-future is substantially larger and more complex than six, which makes me reluctant to take a dependency on it.

**Comment by kgriffs** [comment]
Thinking about this some more, there isn't a lot of six that Falcon actually uses, so this work would be fairly simple.

**Comment by kgriffs** [comment]
FWIW, I just discovered this can cause OS-dependent issues. See also:

* https://github.com/falconry/falcon/issues/1139
* https://github.com/yhat/ggpy/issues/560

**Comment by jmvrbanac** [comment]
@kgriffs We also could vendor six if that would be any easier first step.
