### ISSUE TITLE
Initial/experimental support for hosting falcon apps via twisted.web

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#582]
While the community waits for the asyncio ecosystem to mature (and for the WSGI spec evolve), Twisted remains a popular choice. I think it makes sense to support twisted.web in the interim. 

Things to consider:
- This will require some internal refactoring so we can switch between WSGI and Twisted models. We could try to translate twisted.web request to a WSGI environ, but that would reduce performance. How to best handle this?
- How can we design this so that we can accommodate asyncio things in the future?
- How will we know when a request is async? Check for a Deferred on the response?
- Must be able to create async middleware and hooks as well
- Will need extensive testing, and review by Twisted programmers

Inspiration:
- Klein
- twisted.web.proxy

**Comment by vytas7** [comment]
@kgriffs given the recent work on ASGI, and the rise of standard `async`, I'm inclined to close this.
But let me know if you object :slightly_smiling_face:
