### ISSUE TITLE
Falcon crashes on decoding query string

### ISSUE THREAD

**Issue by vanzi** [falconry/falcon#588]
When Falcon receives a request with query string that cannot be percent decoded (e.g. `x=%`), it crashes resulting in a rather unexpected 502 response.

	Traceback (most recent call last):
	  File "/opt/ads/venv/local/lib/python2.7/site-packages/falcon/api.py", line 154, in __call__
		req = self._request_type(env, options=self.req_options)
	  File "/opt/ads/venv/local/lib/python2.7/site-packages/falcon/request.py", line 237, in __init__
		keep_blank_qs_values=self.options.keep_blank_qs_values,
	  File "/opt/ads/venv/local/lib/python2.7/site-packages/falcon/util/uri.py", line 327, in parse_query_string
		params[k] = decode(v)
	  File "/opt/ads/venv/local/lib/python2.7/site-packages/falcon/util/uri.py", line 181, in decode
		char, byte = _HEX_TO_BYTE[token[:2]]
	KeyError: ''

Would it make more sense to pass-through the original value in this case without trying to decode it? It's a rather small change so I could prepare a pull request for it, but I would like to confirm first that this was not intentional behavior.

**Comment by kgriffs** [comment]
Thanks for reporting this. I agree that it would make sense for Falcon to more gracefully handle strings that don't conform to spec. If you aren't able to influence the API design, then it would make sense to have a way to pass through the value. Otherwise, if a client passes a malformed string you might want to return something like a 400.

**Comment by philiptzou** [comment]
I tested this on [Google Search](https://www.google.com/?q=%%20%25) and it works (interpret as "% %"). So I think for robust reason the best to fix this is just interpreting it like Google did since it's not ambiguous.

**Comment by philiptzou** [comment]
https://github.com/falconry/falcon/pull/597
