### ISSUE TITLE
Update docstrings for HTTP error classes according to RFC 7231

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#595]
RFC 7231 clarifies and refines the use of various status codes. Update the docstrings to suite.

**Comment by maxking** [comment]
Which docstings specifically? The list in doc/api/status.rst seems to be same as RFC 7231.

**Comment by kgriffs** [comment]
Hi maxking, sorry for the confusion. this issue refers to the docstrings for the error classes in `falcon/errors.py`.

**Comment by kgriffs** [comment]
To further clarify, many of the docstrings quote the older RFC. I'd like to update those.
