### ISSUE TITLE
Middleware post process error handling

### ISSUE THREAD

**Issue by esmalifesum** [falconry/falcon#606]
When middleware is added to the api and we have a post_process on it, any exceptions thrown in the responder are not aggregated to an appropriate response. Instead, they are ignored and the post_process attempts to run on as though nothing happened.

It does not matter whether an exception handler is added to the api or not.

Let me know if I just misunderstood how to handle these

**Comment by kgriffs** [comment]
Hi @esmalifesum, thanks for bringing up this issue. You are correct in that the framework does not skip `process_response` methods when an exception is raised. This is done in case those methods need to perform critical post-processing steps.  

When an instance of `falcon.HTTPError` is raised in a responder, the framework should render that into a response, while also executing `process_response`. Similarly, when other types of exception are raised, custom error handlers are given the chance to render that into a response. If you are seeing a situation in which the errors are not rendering into a response, that's definitely a bug.

Also, while looking at the code, I found a a case in which the exception is rendered to a response only after passing through the middleware components. Conceptually, as well as for the sake of consistency, I think it would make more sense to always render the response from the exception first.

Is there a particular type of middleware you hand in mind that should be short-circuited when an error is raised? If that functionality is useful, we can brainstorm some ways to support it.

**Comment by esmalifesum** [comment]
Hi Kurt,

We have an exception handler currently wrapped around the responders. If
any of these raise an exception, we will handle the exception as our app
needs within the handler. If this happens, I would expect for my post
processors not to even be called as they are there to process only
valid/sane responses from the responders.

Are you saying that each middleware's post process method should have an
exception handler on its own as well?

Maybe I'm not thinking around this the right way and there's a better
pattern for it. If so, can you provide a more thorough scenario/pattern for
us to follow?

Esma

**Comment by kgriffs** [comment]
There are times when you may want to perform post-processing regardless of whether an error was raised. But I can see your point about a need to be more selective in some cases.

One way we could support this would be by adding an additional middleware method, `process_successful_response()`. Thoughts?

**Comment by esmalifesum** [comment]
Yes, I think something like that would allow us more flexibility and let us avoid coding nonsense into middleware just to handle exceptions when there is already an exceptions handler. My team would definitely use your suggested method.

**Comment by collateraldamadge** [comment]
Is there any progress regarding this issue? 

I need to validate responses agains swagger schema. 
When a falcon HTTP exception is raised in a responder or in process_resource middleware method (which raises HTTPBadRequest when request body is invalid), the status code of the response is still 200 when it comes to process_response. 

At which point does falcon set appropriate response status and body when an HTTP error is raised? 
How can I process only successful responses? 
How can I identify that a response is not successful in a process_response middleware method?

**Comment by kgriffs** [comment]
Hi everyone, the middleware handling has been reworked such that the status code will now be updated before process_response is called. Please try the latest code from master and let me know how it goes. 

I've also got a patch up to pass a flag to process_response() so that the logic can key off whether the request succeeded or not. Check it out and let me know what you think: #890
