### ISSUE TITLE
pep8 and pylint failing on master (response.py)

### ISSUE THREAD

**Issue by lwcolton** [falconry/falcon#607]
pep8 and pylint are failing on the master branch, due to an undefined reference to unicode in response.py  I am investigating this and will submit a PR shortly.

**Comment by lwcolton** [comment]
$ tox -e pep8,pylint
GLOB sdist-make: /runnable/falcon/setup.py
pep8 recreate: /runnable/falcon/.tox/pep8
pep8 installdeps: flake8
pep8 inst: /runnable/falcon/.tox/dist/falcon-0.4.0.dev0.zip
pep8 runtests: PYTHONHASHSEED='2797149611'
pep8 runtests: commands[0] | flake8 --max-complexity=15 --exclude=./build,.venv,.tox,dist,doc,./falcon/bench/nuts --ignore=F403 --max-line-length=99
./falcon/response.py:548:33: F821 undefined name 'unicode'
./falcon/response.py:551:34: F821 undefined name 'unicode'
ERROR: InvocationError: '/runnable/falcon/.tox/pep8/bin/flake8 --max-complexity=15 --exclude=./build,.venv,.tox,dist,doc,./falcon/bench/nuts --ignore=F403 --max-line-length=99'
pylint recreate: /runnable/falcon/.tox/pylint
pylint installdeps: pylint
pylint inst: /runnable/falcon/.tox/dist/falcon-0.4.0.dev0.zip
pylint runtests: PYTHONHASHSEED='2797149611'
pylint runtests: commands[0] | pylint falcon --ignore=bench,tests -E
************* Module falcon.response
E:548,32: Undefined variable 'unicode' (undefined-variable)
E:551,33: Undefined variable 'unicode' (undefined-variable)
ERROR: InvocationError: '/runnable/falcon/.tox/pylint/bin/pylint falcon --ignore=bench,tests -E'
______________________________________________________________ summary ______________________________________________________________
ERROR:   pep8: commands failed
ERROR:   pylint: commands failed

**Comment by rose** [comment]
this is a problem again - looks like the fix was removed in 409194915f
