### ISSUE TITLE
Remove support for old hook methods

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#614]
When an additional `resource` parameter was added to the spec for hooks, we included a shim layer to avoid breaking existing apps. After a couple releases, it is time to remove this so that we don't have to maintain the additional shimming code going forward.

Note that this may break talons hooks... We need to work with them to get those updated (if any) before releasing this change.

**Comment by jmvrbanac** [comment]
Is this still relevant?

**Comment by vytas7** [comment]
Looks like this has been addressed in [Falcon 2.0.0](https://falcon.readthedocs.io/en/stable/changes/2.0.0.html#breaking-changes), if not earlier:
> All middleware methods and hooks must now accept the arguments as specified in the relevant interface definitions as of Falcon 1.4. All backwards-compatible shims have been removed.
