### ISSUE TITLE
installation failed on windows

### ISSUE THREAD

**Issue by majj** [falconry/falcon#616]
C:\Python27>pip install cython falcon
Requirement already satisfied (use --upgrade to upgrade): cython in c:\python27\
lib\site-packages
Downloading/unpacking falcon
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administ
rator\falcon\setup.py) egg_info for package falcon

Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in c:\pytho
n27\lib\site-packages (from falcon)
Downloading/unpacking python-mimeparse (from falcon)
  Downloading python-mimeparse-0.1.4.tar.gz
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\pip_build_Administ
rator\python-mimeparse\setup.py) egg_info for package python-mimeparse

Installing collected packages: falcon, python-mimeparse
  Running setup.py install for falcon

    cythoning falcon\api.py to falcon\api.c
    building 'falcon.api' extension
    c:\cygwin64\bin\gcc.exe -mno-cygwin -mdll -O -Wall -IC:\Python27\include -IC
:\Python27\PC -c falcon\api.c -o build\temp.win-amd64-2.7\Release\falcon\api.o
    cygwin warning:
      MS-DOS style path detected: falcon\api.c
      Preferred POSIX equivalent is: falcon/api.c
      CYGWIN environment variable option "nodosfilewarning" turns off this warni
ng.
      Consult the user's guide for more details about POSIX paths:
        http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
    gcc: error: unrecognized command line option 鈥?mno-cygwin鈥?
    error: command 'c:\\cygwin64\\bin\\gcc.exe' failed with exit status 1
    Complete output from command C:\Python27\python.exe -c "import setuptools, t
okenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip_build_Administr
ator\\falcon\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).r
ead().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admin
i~1\appdata\local\temp\pip-fe3fmx-record\install-record.txt --single-version-ext
ernally-managed --compile:
    running install

running build

running build_py

creating build

creating build\lib.win-amd64-2.7

creating build\lib.win-amd64-2.7\falcon

copying falcon\api.py -> build\lib.win-amd64-2.7\falcon

copying falcon\api_helpers.py -> build\lib.win-amd64-2.7\falcon

copying falcon\errors.py -> build\lib.win-amd64-2.7\falcon

copying falcon\hooks.py -> build\lib.win-amd64-2.7\falcon

copying falcon\http_error.py -> build\lib.win-amd64-2.7\falcon

copying falcon\http_status.py -> build\lib.win-amd64-2.7\falcon

copying falcon\request.py -> build\lib.win-amd64-2.7\falcon

copying falcon\request_helpers.py -> build\lib.win-amd64-2.7\falcon

copying falcon\responders.py -> build\lib.win-amd64-2.7\falcon

copying falcon\response.py -> build\lib.win-amd64-2.7\falcon

copying falcon\response_helpers.py -> build\lib.win-amd64-2.7\falcon

copying falcon\status_codes.py -> build\lib.win-amd64-2.7\falcon

copying falcon\version.py -> build\lib.win-amd64-2.7\falcon

copying falcon\__init__.py -> build\lib.win-amd64-2.7\falcon

creating build\lib.win-amd64-2.7\falcon\bench

copying falcon\bench\bench.py -> build\lib.win-amd64-2.7\falcon\bench

copying falcon\bench\create.py -> build\lib.win-amd64-2.7\falcon\bench

copying falcon\bench\__init__.py -> build\lib.win-amd64-2.7\falcon\bench

creating build\lib.win-amd64-2.7\falcon\cmd

copying falcon\cmd\bench.py -> build\lib.win-amd64-2.7\falcon\cmd

copying falcon\cmd\__init__.py -> build\lib.win-amd64-2.7\falcon\cmd

creating build\lib.win-amd64-2.7\falcon\routing

copying falcon\routing\compiled.py -> build\lib.win-amd64-2.7\falcon\routing

copying falcon\routing\util.py -> build\lib.win-amd64-2.7\falcon\routing

copying falcon\routing\__init__.py -> build\lib.win-amd64-2.7\falcon\routing

creating build\lib.win-amd64-2.7\falcon\testing

copying falcon\testing\base.py -> build\lib.win-amd64-2.7\falcon\testing

copying falcon\testing\helpers.py -> build\lib.win-amd64-2.7\falcon\testing

copying falcon\testing\resource.py -> build\lib.win-amd64-2.7\falcon\testing

copying falcon\testing\srmock.py -> build\lib.win-amd64-2.7\falcon\testing

copying falcon\testing\__init__.py -> build\lib.win-amd64-2.7\falcon\testing

creating build\lib.win-amd64-2.7\falcon\util

copying falcon\util\misc.py -> build\lib.win-amd64-2.7\falcon\util

copying falcon\util\structures.py -> build\lib.win-amd64-2.7\falcon\util

copying falcon\util\time.py -> build\lib.win-amd64-2.7\falcon\util

copying falcon\util\uri.py -> build\lib.win-amd64-2.7\falcon\util

copying falcon\util\__init__.py -> build\lib.win-amd64-2.7\falcon\util

creating build\lib.win-amd64-2.7\falcon\bench\nuts

copying falcon\bench\nuts\config.py -> build\lib.win-amd64-2.7\falcon\bench\nuts

copying falcon\bench\nuts\setup.py -> build\lib.win-amd64-2.7\falcon\bench\nuts

copying falcon\bench\nuts\__init__.py -> build\lib.win-amd64-2.7\falcon\bench\nu
ts

creating build\lib.win-amd64-2.7\falcon\bench\queues

copying falcon\bench\queues\api.py -> build\lib.win-amd64-2.7\falcon\bench\queue
s

copying falcon\bench\queues\claims.py -> build\lib.win-amd64-2.7\falcon\bench\qu
eues

copying falcon\bench\queues\messages.py -> build\lib.win-amd64-2.7\falcon\bench\
queues

copying falcon\bench\queues\queues.py -> build\lib.win-amd64-2.7\falcon\bench\qu
eues

copying falcon\bench\queues\stats.py -> build\lib.win-amd64-2.7\falcon\bench\que
ues

copying falcon\bench\queues\__init__.py -> build\lib.win-amd64-2.7\falcon\bench\
queues

creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts

copying falcon\bench\nuts\nuts\app.py -> build\lib.win-amd64-2.7\falcon\bench\nu
ts\nuts

copying falcon\bench\nuts\nuts\__init__.py -> build\lib.win-amd64-2.7\falcon\ben
ch\nuts\nuts

creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts\controllers

copying falcon\bench\nuts\nuts\controllers\root.py -> build\lib.win-amd64-2.7\fa
lcon\bench\nuts\nuts\controllers

copying falcon\bench\nuts\nuts\controllers\__init__.py -> build\lib.win-amd64-2.
7\falcon\bench\nuts\nuts\controllers

creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts\model

copying falcon\bench\nuts\nuts\model\__init__.py -> build\lib.win-amd64-2.7\falc
on\bench\nuts\nuts\model

creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts\tests

copying falcon\bench\nuts\nuts\tests\config.py -> build\lib.win-amd64-2.7\falcon
\bench\nuts\nuts\tests

copying falcon\bench\nuts\nuts\tests\test_functional.py -> build\lib.win-amd64-2
.7\falcon\bench\nuts\nuts\tests

copying falcon\bench\nuts\nuts\tests\test_units.py -> build\lib.win-amd64-2.7\fa
lcon\bench\nuts\nuts\tests

copying falcon\bench\nuts\nuts\tests\__init__.py -> build\lib.win-amd64-2.7\falc
on\bench\nuts\nuts\tests

running egg_info

writing requirements to falcon.egg-info\requires.txt

writing falcon.egg-info\PKG-INFO

writing top-level names to falcon.egg-info\top_level.txt

writing dependency_links to falcon.egg-info\dependency_links.txt

writing entry points to falcon.egg-info\entry_points.txt

warning: manifest_maker: standard file '-c' not found

reading manifest file 'falcon.egg-info\SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'falcon.egg-info\SOURCES.txt'

running build_ext

cythoning falcon\api.py to falcon\api.c

building 'falcon.api' extension

creating build\temp.win-amd64-2.7

creating build\temp.win-amd64-2.7\Release

creating build\temp.win-amd64-2.7\Release\falcon

c:\cygwin64\bin\gcc.exe -mno-cygwin -mdll -O -Wall -IC:\Python27\include -IC:\Py
thon27\PC -c falcon\api.c -o build\temp.win-amd64-2.7\Release\falcon\api.o

cygwin warning:

  MS-DOS style path detected: falcon\api.c

  Preferred POSIX equivalent is: falcon/api.c

  CYGWIN environment variable option "nodosfilewarning" turns off this warning.

  Consult the user's guide for more details about POSIX paths:

    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames

gcc: error: unrecognized command line option 鈥?mno-cygwin鈥?

error: command 'c:\\cygwin64\\bin\\gcc.exe' failed with exit status 1

----------------------------------------
Cleaning up...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\use
rs\\admini~1\\appdata\\local\\temp\\pip_build_Administrator\\falcon\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pi
p-fe3fmx-record\install-record.txt --single-version-externally-managed --compile
 failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip_build_Admi
nistrator\falcon
Traceback (most recent call last):
  File "C:\Python27\Scripts\pip-script.py", line 8, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "C:\Python27\lib\site-packages\pip\__init__.py", line 185, in main
    return command.main(cmd_args)
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal
 not in range(128)

**Comment by philiptzou** [comment]
Related perhaps: http://stackoverflow.com/questions/6034390/compiling-with-cython-and-mingw-produces-gcc-error-unrecognized-command-line-o

**Comment by majj** [comment]
my environment: 
Windows 2008 Server 64-bit
Python: 2.7.10
pip: 7.1.2
gcc: (tdm64-1) 5.1.0

still got error:

C:\Python27> pip install --upgrade falcon
Collecting falcon
  Using cached falcon-0.3.0.tar.gz
Requirement already up-to-date: six>=1.4.0 in c:\python27\lib\site-packages (fro
m falcon)
Requirement already up-to-date: python-mimeparse in c:\python27\lib\site-package
s (from falcon)
Building wheels for collected packages: falcon
  Running setup.py bdist_wheel for falcon
  Complete output from command C:\Python27\python.exe -c "import setuptools;__fi
le__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-build-_83o9d\\falcon\\setup
.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec')
)" bdist_wheel -d c:\users\admini~1\appdata\local\temp\tmpfatbabpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\falcon
  copying falcon\api.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\api_helpers.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\errors.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\hooks.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\http_error.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\http_status.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\request.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\request_helpers.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\responders.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\response.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\response_helpers.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\status_codes.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\version.py -> build\lib.win-amd64-2.7\falcon
  copying falcon\__init__.py -> build\lib.win-amd64-2.7\falcon
  creating build\lib.win-amd64-2.7\falcon\bench
  copying falcon\bench\bench.py -> build\lib.win-amd64-2.7\falcon\bench
  copying falcon\bench\create.py -> build\lib.win-amd64-2.7\falcon\bench
  copying falcon\bench\__init__.py -> build\lib.win-amd64-2.7\falcon\bench
  creating build\lib.win-amd64-2.7\falcon\cmd
  copying falcon\cmd\bench.py -> build\lib.win-amd64-2.7\falcon\cmd
  copying falcon\cmd\__init__.py -> build\lib.win-amd64-2.7\falcon\cmd
  creating build\lib.win-amd64-2.7\falcon\routing
  copying falcon\routing\compiled.py -> build\lib.win-amd64-2.7\falcon\routing
  copying falcon\routing\util.py -> build\lib.win-amd64-2.7\falcon\routing
  copying falcon\routing\__init__.py -> build\lib.win-amd64-2.7\falcon\routing
  creating build\lib.win-amd64-2.7\falcon\testing
  copying falcon\testing\base.py -> build\lib.win-amd64-2.7\falcon\testing
  copying falcon\testing\helpers.py -> build\lib.win-amd64-2.7\falcon\testing
  copying falcon\testing\resource.py -> build\lib.win-amd64-2.7\falcon\testing
  copying falcon\testing\srmock.py -> build\lib.win-amd64-2.7\falcon\testing
  copying falcon\testing\__init__.py -> build\lib.win-amd64-2.7\falcon\testing
  creating build\lib.win-amd64-2.7\falcon\util
  copying falcon\util\misc.py -> build\lib.win-amd64-2.7\falcon\util
  copying falcon\util\structures.py -> build\lib.win-amd64-2.7\falcon\util
  copying falcon\util\time.py -> build\lib.win-amd64-2.7\falcon\util
  copying falcon\util\uri.py -> build\lib.win-amd64-2.7\falcon\util
  copying falcon\util\__init__.py -> build\lib.win-amd64-2.7\falcon\util
  creating build\lib.win-amd64-2.7\falcon\bench\nuts
  copying falcon\bench\nuts\config.py -> build\lib.win-amd64-2.7\falcon\bench\nu
ts
  copying falcon\bench\nuts\setup.py -> build\lib.win-amd64-2.7\falcon\bench\nut
s
  copying falcon\bench\nuts\__init__.py -> build\lib.win-amd64-2.7\falcon\bench\
nuts
  creating build\lib.win-amd64-2.7\falcon\bench\queues
  copying falcon\bench\queues\api.py -> build\lib.win-amd64-2.7\falcon\bench\que
ues
  copying falcon\bench\queues\claims.py -> build\lib.win-amd64-2.7\falcon\bench\
queues
  copying falcon\bench\queues\messages.py -> build\lib.win-amd64-2.7\falcon\benc
h\queues
  copying falcon\bench\queues\queues.py -> build\lib.win-amd64-2.7\falcon\bench\
queues
  copying falcon\bench\queues\stats.py -> build\lib.win-amd64-2.7\falcon\bench\q
ueues
  copying falcon\bench\queues\__init__.py -> build\lib.win-amd64-2.7\falcon\benc
h\queues
  creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts
  copying falcon\bench\nuts\nuts\app.py -> build\lib.win-amd64-2.7\falcon\bench\
nuts\nuts
  copying falcon\bench\nuts\nuts\__init__.py -> build\lib.win-amd64-2.7\falcon\b
ench\nuts\nuts
  creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts\controllers
  copying falcon\bench\nuts\nuts\controllers\root.py -> build\lib.win-amd64-2.7\
falcon\bench\nuts\nuts\controllers
  copying falcon\bench\nuts\nuts\controllers\__init__.py -> build\lib.win-amd64-
2.7\falcon\bench\nuts\nuts\controllers
  creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts\model
  copying falcon\bench\nuts\nuts\model\__init__.py -> build\lib.win-amd64-2.7\fa
lcon\bench\nuts\nuts\model
  creating build\lib.win-amd64-2.7\falcon\bench\nuts\nuts\tests
  copying falcon\bench\nuts\nuts\tests\config.py -> build\lib.win-amd64-2.7\falc
on\bench\nuts\nuts\tests
  copying falcon\bench\nuts\nuts\tests\test_functional.py -> build\lib.win-amd64
-2.7\falcon\bench\nuts\nuts\tests
  copying falcon\bench\nuts\nuts\tests\test_units.py -> build\lib.win-amd64-2.7\
falcon\bench\nuts\nuts\tests
  copying falcon\bench\nuts\nuts\tests\__init__.py -> build\lib.win-amd64-2.7\fa
lcon\bench\nuts\nuts\tests
  running egg_info
  writing requirements to falcon.egg-info\requires.txt
  writing falcon.egg-info\PKG-INFO
  writing top-level names to falcon.egg-info\top_level.txt
  writing dependency_links to falcon.egg-info\dependency_links.txt
  writing entry points to falcon.egg-info\entry_points.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'falcon.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'falcon.egg-info\SOURCES.txt'
  running build_ext
  cythoning falcon\api.py to falcon\api.c
  building 'falcon.api' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\falcon
  C:\TDM-GCC-64\bin\gcc.exe -mdll -O -Wall -IC:\Python27\include -IC:\Python27\P
C -c falcon\api.c -o build\temp.win-amd64-2.7\Release\falcon\api.o
  falcon\api.c: In function '__Pyx_RaiseArgtupleInvalid':
  falcon\api.c:9169:18: warning: unknown conversion type character 'z' in format
 [-Wformat=]
                    "%.200s() takes %.8s %" CYTHON_FORMAT_SSIZE_T "d positional
argument%.1s (%" CYTHON_FORMAT_SSIZE_T "d given)",
                    ^
  falcon\api.c:9169:18: warning: format '%s' expects argument of type 'char *',
but argument 5 has type 'Py_ssize_t {aka int}' [-Wformat=]
  falcon\api.c:9169:18: warning: unknown conversion type character 'z' in format
 [-Wformat=]
  falcon\api.c:9169:18: warning: too many arguments for format [-Wformat-extra-a
rgs]
  falcon\api.c: In function '__Pyx_RaiseTooManyValuesError':
  falcon\api.c:9276:18: warning: unknown conversion type character 'z' in format
 [-Wformat=]
                    "too many values to unpack (expected %" CYTHON_FORMAT_SSIZE_
T "d)", expected);
                    ^
  falcon\api.c:9276:18: warning: too many arguments for format [-Wformat-extra-a
rgs]
  falcon\api.c: In function '__Pyx_RaiseNeedMoreValuesError':
  falcon\api.c:9281:18: warning: unknown conversion type character 'z' in format
 [-Wformat=]
                    "need more than %" CYTHON_FORMAT_SSIZE_T "d value%.1s to unp
ack",
                    ^
  falcon\api.c:9281:18: warning: format '%s' expects argument of type 'char *',
but argument 3 has type 'Py_ssize_t {aka int}' [-Wformat=]
  falcon\api.c:9281:18: warning: too many arguments for format [-Wformat-extra-a
rgs]
  writing build\temp.win-amd64-2.7\Release\falcon\api.def
  C:\TDM-GCC-64\bin\gcc.exe -shared -s build\temp.win-amd64-2.7\Release\falcon\a
pi.o build\temp.win-amd64-2.7\Release\falcon\api.def -LC:\Python27\libs -LC:\Pyt
hon27\PCbuild\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\falcon\api.p
yd
  build\temp.win-amd64-2.7\Release\falcon\api.o:api.c:(.text+0x14754): undefined
 reference to `__imp_Py_InitModule4'
  collect2.exe: error: ld returned 1 exit status
  error: command 'C:\\TDM-GCC-64\\bin\\gcc.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for falcon
Failed to build falcon
Installing collected packages: falcon
  Running setup.py install for falcon
    Complete output from command C:\Python27\python.exe -c "import setuptools, t
okenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-build-_83o9d\\f
alcon\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().r
eplace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admini~1\app
data\local\temp\pip-jftmnn-record\install-record.txt --single-version-externally
-managed --compile:
    running install
    running build
    running build_py
    running egg_info
    writing requirements to falcon.egg-info\requires.txt
    writing falcon.egg-info\PKG-INFO
    writing top-level names to falcon.egg-info\top_level.txt
    writing dependency_links to falcon.egg-info\dependency_links.txt
    writing entry points to falcon.egg-info\entry_points.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'falcon.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'falcon.egg-info\SOURCES.txt'
    running build_ext
    skipping 'falcon\api.c' Cython extension (up-to-date)
    building 'falcon.api' extension
    C:\TDM-GCC-64\bin\gcc.exe -mdll -O -Wall -IC:\Python27\include -IC:\Python27
\PC -c falcon\api.c -o build\temp.win-amd64-2.7\Release\falcon\api.o
    falcon\api.c: In function '__Pyx_RaiseArgtupleInvalid':
    falcon\api.c:9169:18: warning: unknown conversion type character 'z' in form
at [-Wformat=]
                      "%.200s() takes %.8s %" CYTHON_FORMAT_SSIZE_T "d positiona
l argument%.1s (%" CYTHON_FORMAT_SSIZE_T "d given)",
                      ^
    falcon\api.c:9169:18: warning: format '%s' expects argument of type 'char *'
, but argument 5 has type 'Py_ssize_t {aka int}' [-Wformat=]
    falcon\api.c:9169:18: warning: unknown conversion type character 'z' in form
at [-Wformat=]
    falcon\api.c:9169:18: warning: too many arguments for format [-Wformat-extra
-args]
    falcon\api.c: In function '__Pyx_RaiseTooManyValuesError':
    falcon\api.c:9276:18: warning: unknown conversion type character 'z' in form
at [-Wformat=]
                      "too many values to unpack (expected %" CYTHON_FORMAT_SSIZ
E_T "d)", expected);
                      ^
    falcon\api.c:9276:18: warning: too many arguments for format [-Wformat-extra
-args]
    falcon\api.c: In function '__Pyx_RaiseNeedMoreValuesError':
    falcon\api.c:9281:18: warning: unknown conversion type character 'z' in form
at [-Wformat=]
                      "need more than %" CYTHON_FORMAT_SSIZE_T "d value%.1s to u
npack",
                      ^
    falcon\api.c:9281:18: warning: format '%s' expects argument of type 'char *'
, but argument 3 has type 'Py_ssize_t {aka int}' [-Wformat=]
    falcon\api.c:9281:18: warning: too many arguments for format [-Wformat-extra
-args]
    writing build\temp.win-amd64-2.7\Release\falcon\api.def
    C:\TDM-GCC-64\bin\gcc.exe -shared -s build\temp.win-amd64-2.7\Release\falcon
\api.o build\temp.win-amd64-2.7\Release\falcon\api.def -LC:\Python27\libs -LC:\P
ython27\PCbuild\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\falcon\api
.pyd
    build\temp.win-amd64-2.7\Release\falcon\api.o:api.c:(.text+0x14754): undefin
ed reference to `__imp_Py_InitModule4'
    collect2.exe: error: ld returned 1 exit status
    error: command 'C:\\TDM-GCC-64\\bin\\gcc.exe' failed with exit status 1

    ----------------------------------------
Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\us
ers\\admini~1\\appdata\\local\\temp\\pip-build-_83o9d\\falcon\\setup.py';exec(co
mpile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __
file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-jftm
nn-record\install-record.txt --single-version-externally-managed --compile" fail
ed with error code 1 in c:\users\admini~1\appdata\local\temp\pip-build-_83o9d\fa
lcon

**Comment by majj** [comment]
It's works on Win 10 without cython
