### ISSUE TITLE
Make it easier to set content type

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#618]
The response content type must be set to a raw string. Make it easier to set the content type to common media types (including charset, where appropriate). One simple thing we might do is just define some constants. How else might we make this easier and less error-prone?

**Comment by ministrike3** [comment]
@kgriffs I'm interested in contributing; do you have any more information or ideas about this issue? I'm not 100% sure what im supposed to do// what the end functionality is supposed to be!

**Comment by kgriffs** [comment]
Hi @ministrike3, I think we can start by simply defining some constants for common media types that app developers can use to set the default media type in `falcon.API()` or explicitly via `resp.content_type`. 

BTW, you might like to do this as part of https://hacktoberfest.digitalocean.com 😄

**Comment by rjrhaverkamp** [comment]
I did some basic work on this, I am not sure if this is what you mean.

I am working on also being able to set it via resp.content_type but I am not familiar enough with the codebase to do this, yet.

Let me now what you think! 🎉

**Comment by rjrhaverkamp** [comment]
I just saw we already have resp.content_type.. So one could just do: `resp.content_type = falcon.XML` with my code now. I guess that is convenient enough right?

**Comment by jmvrbanac** [comment]
I believe this was tackled as a part of #1058 during the PyCon sprints and should be included in the next release (1.3).
