### ISSUE TITLE
Expose routing metadata

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#619]
Per a [discussion][1] on the mailing list, it can be useful to introspect the URI template that is associated with a given resource. One way to implement this would be to check for an attribute and fill it in as part of the `add_route` logic. For example:

```python
class Thing(object):
    def __init__(self):
        self.uri_templates = []

    def on_get(self, req, resp):
        pass

# ...

def add_route(self, uri_template, resource):

    # ...

    if hasattr(resource, 'uri_templates'):
        resource.uri_templates.append(uri_template)

    # ...
``` 

We could also do this:

```python
    if hasattr(resource, 'uri_templates'):
        resource.uri_templates.append(uri_template)
    else:
        resource.uri_templates = [uri_template]
```

But that would break in the case that `Thing` defined `__slots__`.

Another option would be to store the URI template in the routing tree and then set an attribute on each Request instance:

```python
def __call__(self, env, start_response):

    # ...

    responder, params, resource, uri_template = self._get_responder(req)
    
    req = self._request_type(env, options=self.req_options, 
                             uri_template=uri_template)

    # ...
```

Either way, this would provide a way for middleware and hooks to key off the URI template to perform additional actions.

[1]: http://librelist.com/browser//falcon/2015/7/28/getting-the-url-template-when-servicing-a-request/

**Comment by ueg1990** [comment]
Currently the line:
```
responder, params, resource, uri_template = self._get_responder(req)
```
has been moved to inside the try-catch. what about something like this:
responder, params, resource, uri_template = self._get_responder(req)
setattr(req, 'uri_template', uri_template)

**Comment by kgriffs** [comment]
Thinking about this, it may be helpful to do both. Tooling may wish to enumerate the resources, examining each for the routes associated with it. And people have asked for a way to know what route was matched for a particular request (see also #581).

We should try to do this in a non-breaking way first, if it isn't too ugly.
