### ISSUE TITLE
How to add SSL support to Falcon

### ISSUE THREAD

**Issue by geodawg** [falconry/falcon#621]
All,

We would like to SSL up the application we're building. It would appear that Flask does this pretty easily here: http://kracekumar.com/post/54437887454/ssl-for-flask-local-development

What is the best way to add SSL support to Falcon?

**Comment by wshayes** [comment]
Wouldn't you run this via an nginx or apache proxy?  In which case, you'd use SSL to the nginx service and then wouldn't need SSL between nginx and your wsgi container. https://www.nginx.com/resources/admin-guide/nginx-ssl-termination/

**Comment by jmvrbanac** [comment]
I usually run Falcon in gunicorn or uwsgi and then put that behind nginx for ssl termination.

**Comment by philiptzou** [comment]
Yes this may be suitable for browser tests. Since HTTPs referer header won't be send to HTTP server, and also accessing HTTP resources from HTTPs is prevented by default by mainstream browsers like Chromium. If ones can easily reproduce such scenes in their development environment but not through nginx, I think it would be very useful.

**Comment by kgriffs** [comment]
We've talked about adding a development sever to Falcon, although I've been having second thoughts lately because Gunicorn is really easy to us, supports reloading (`--reload`) and even [ssl/tls](http://docs.gunicorn.org/en/19.3/settings.html#ssl).

**Comment by up1and** [comment]
It's quiet simple, you can use self-signed certificates on development environment.

```python
import ssl
from wsgiref import simple_server

httpd = simple_server.make_server('', 8000, app)
httpd.socket = ssl.wrap_socket(
        httpd.socket, server_side=True,
        certfile='cert.pem',
        keyfile='key.pem')
httpd.serve_forever()
```

app is an instance of `falcon.API()`.
