### ISSUE TITLE
Adding HTTP_422, Unprocessable Entity

### ISSUE THREAD

**Issue by ourway** [falconry/falcon#627]
I guess we need such response support.

**Comment by kgriffs** [comment]
I'd like to learn more about how this is used in the wild. Are there other frameworks / guides making use of it outside WebDAV?

That being said, it would be straightforward to add support for this to Falcon (via `status_codes.py` and `errors.py`). If someone would like to submit a PR, I'd be happy to review it.

**Comment by ourway** [comment]
I don't know of any other frameworks use it or not (I only know Web2py does), But I needed it.  I just add it here cause I think falcon should handle this.

**Comment by billyshambrook** [comment]
Hey, here is an example of how GitHub uses it...https://developer.github.com/v3/#client-errors

**Comment by kgriffs** [comment]
Ah, cool. Thanks @billyshambrook for the example. Someone on IRC just asked about this as well, so it seems like it would be useful to have. Anyone have some bandwidth to work on this?

**Comment by billyshambrook** [comment]
I can get a pull request out later tonight. Thanks

**Comment by yohanboniface** [comment]
@billyshambrook still on your track or should I go for it? :)
