### ISSUE TITLE
prepare_middleware should accept a tuple

### ISSUE THREAD

**Issue by MackYoel** [falconry/falcon#630]
falcon/api_helpers.py

<pre>
<code>
47    if not isinstance(middleware, list):
48        middleware = [middleware]
</code>
</pre>

I declare the middlewares in a tuple because they are iterated faster than lists, but raises an error because prepare_middleware only accepts lists or an instance

**Comment by philiptzou** [comment]
Should we reopen this issue? Seems it's not solved.

**Comment by philiptzou** [comment]
Copied from #644:

> @MackYoel Yes I agree with you that the prepare_middleware is some kinda annoying... Personally I preferred to use def prepare_middleware(*middlewares) instead of detecting types in the function.

So the design is basically like this:

```python
def prepare_middleware(*middleware):
    """Check middleware interface and prepare it to iterate.

    ...
    """

    # PERF(kgriffs): do getattr calls once, in advance, so we don't
    # have to do them every time in the request path.
    prepared_middleware = []

    for component in middleware:
        ...

        prepared_middleware.append((process_request, process_resource,
                                    process_response))

    return prepared_middleware
```

Now the `middleware` is always a tuple.

**Comment by kgriffs** [comment]
@philiptzou I think that design could work. But you're right, this would be a breaking change. Are there other interfaces in the framework that we should also consider changing along these lines, to be consistent?

Re performance, in this case the method is only called once, when `API` is instantiated, so passing in a tuple for that reason doesn't improve your app's performance. However, converting the return value to a tuple may yield a slight performance advantage under py3k (I just did a quick comparison of iterating over a tuple under 2.7 and 3.5, and only under 3.5 was iterating over a tuple slightly faster than over a list).

**Comment by vytas7** [comment]
This seems to have staled completely by now, with the relevant parts being converted to tuples for performance as per #926, and we do accept various types of iterable containers.
