### ISSUE TITLE
SyntaxError on install 

### ISSUE THREAD

**Issue by shakna-israel** [falconry/falcon#632]
```
File "falcon/request.py", line 42
  DEFAULT_ERROR_LOG_FORMAT = (u'{0:%Y-%m-%d %H:%M:%S} [FALCON] [ERROR] '
```

This error has happened with Falcon 0.3 from Pip, and 0.4.0-dev from the master branch. 

Pip 7.0.1
Python 3.2.3

**Comment by kgriffs** [comment]
Hi @shakna-israel, do you have a hard requirement to use Python 3.2? The Falcon framework currently only supports Python 3.3 or later.

**Comment by shakna-israel** [comment]
Damn. Thanks. 

Unfortunately I do have a hard dependency on 3.2, but entirely understand why one would avoid it.
