### ISSUE TITLE
Raising errors from resource methods doesn't change status for middleware

### ISSUE THREAD

**Issue by karmux** [falconry/falcon#635]
If raising HTTPNotFound or any other error that inherits from HTTPError or HTTPStatus from resource method or hook, then `process_response` method of middleware still has `200 OK` status. Response status is changed after running `process_response` of each middleware.

```
    def on_get(self, req, resp, pk):
        raise falcon.HTTPNotFound()
```

```
    # resp.status is '200 OK' but actual status in browser is '404 NOT FOUND'
    def process_response(self, req, resp, resource):
        logging.info(resp.status)
```

I think there should be correct status already in `process_response` of middleware if error is raised.

Currently I'm using following workaround:
```api.add_error_handler(falcon.HTTPError, handler=lambda e, *_: exec('raise e'))```

Second option would be using error handler that calls `_compose_error_response`.

**Comment by kgriffs** [comment]
> I think there should be correct status already in process_response of middleware if error is raised.

Thanks for the report! Seems like a reasonable change.

**Comment by joarleymoraes** [comment]
I was able to verify this issue. Looking through the code, I noticed the reason is that  `process_response` is called before `_compose_error_response` in case of an HTTPError, so status hasn't been set by then:

```
    self._call_resp_mw(middleware_stack, req, resp, resource)
    raise

(...)
except HTTPError as ex:
    self._compose_error_response(req, resp, ex)
    self._call_resp_mw(middleware_stack, req, resp, resource)
```

To fix, I thought of checking the error type like this:

```
if not isinstance(ex, HTTPError):
    self._call_resp_mw(middleware_stack, req, resp, resource)
raise
```
Here's the pull request #745
