### ISSUE TITLE
Status of 0.4?

### ISSUE THREAD

**Issue by ariscn** [falconry/falcon#638]
Is master suitable for production? I'm new to Falcon and used some features from docs that are apparently not in 0.3. The commit log looks relatively light since May - is 0.4/master basically stable and usable in prod?

**Comment by kgriffs** [comment]
Master is fairly stable, in the sense that we have quite a few tests that must pass before anything is ever merged. On the other hand, I don't have a good sense of how many community members are using it in production today. 

0.3 is production ready (in spite of being a point release) and we hope to get to 1.0 before the end of the year. We'll probably also do a 0.4 in the interim to help ensure the new code is battle-tested before 1.0 lands.
