### ISSUE TITLE
Add support to Response for the Accept-Ranges header

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#646]
Should be fairly straightforward (see also: https://tools.ietf.org/html/rfc7233#section-2.3)

**Comment by ueg1990** [comment]
I will be working on this :)

**Comment by kgriffs** [comment]
@ueg1990 Just following up to see how this is going?

**Comment by ueg1990** [comment]
Hey @kgriffs, I already had a pull request for this: https://github.com/falconry/falcon/pull/832
