### ISSUE TITLE
No falcon.redirects module found by installing via the cmd 'pip install falcon'

### ISSUE THREAD

**Issue by lucifersteph** [falconry/falcon#657]
Previously, I installed falcon using 'pip install falcon'

I tried to use class HTTPSeeOther but I found it does not exist.

So I checked the package path which is '/usr/local/lib/python2.7/dist-packages/falcon#', and it turned out the __init__.py does NOT have 'from falcon.redirects import xxxx' inside. ( I compared my file with the file in github, and I saw the difference.)

Can anyone check the 'pip install' way of installing falcon?

Many thanks,
Feng

**Comment by philiptzou** [comment]
@lucifersteph I don't think the redirects module is included in the 0.3.0 version of Falcon. The `redirects.py` is added in #596 on September. You can install the latest version from master branch using:

```bash
pip install git+https://github.com/falconry/falcon.git
```

And I think it will solve your problem.

**Comment by lucifersteph** [comment]
@philiptzou Thanks mate I will check it now :)
