### ISSUE TITLE
Split create_http_method_map?

### ISSUE THREAD

**Issue by yohanboniface** [falconry/falcon#667]
The helper `create_http_method_map` does three things:
1. extract responders from a resource
2. add a default OPTIONS responder if not set
3. patch method map to add 405 responders for non supported verbs

This prevent from using the 2 and 3 when we don't need 1, for example when we take control over routing.

I suggest to split this helper in two, `create_http_method_map` in one hand, that would only do 1, and then call `complete_method_map` (naming suggestions welcome ;) ), that would take care of 2 and 3.

I can work on a PR for that.

Thoughts?

**Comment by wbaelen** [comment]
This sounds like a very good direction.

**Comment by kgriffs** [comment]
Sounds reasonable. The second method might be called `set_default_responders` or similar.

**Comment by kgriffs** [comment]
Note: If we can't do this in a non-breaking way, it will have to wait for Falcon 2.0

**Comment by santeyio** [comment]
@kgriffs I can send a PR for this one -- it looks like no ones currently working on this issue, right?

**Comment by santeyio** [comment]
@kgriffs would it be better if this `set_default_responders` method to take a `method_map` as an argument or a `responder` object?

**Comment by kgriffs** [comment]
Thanks @santeyio, I'll take a look!

**Comment by kgriffs** [comment]
[Implemented]
