### ISSUE TITLE
Allow to customize not_found responder

### ISSUE THREAD

**Issue by yohanboniface** [falconry/falcon#668]
AFAIK, there is [no way](https://github.com/falconry/falcon/blob/5fcfbd7d095d88d88027047998850f3503300ab8/falcon/api.py#L499) now to customize the responder when a request has no registered responder.

I suggest registering this responder as falcon.API attribute (so it's easy to override it when inheriting from falcon.API) and/or allowing to pass it as init kwargs (of course defaulting to `falcon.responder.not_found`).

I can work on a PR.

Thoughts?

**Comment by michaelgugino** [comment]
I'm not 100% sure, but I think this is addressed with https://github.com/falconry/falcon/pull/655

**Comment by yohanboniface** [comment]
@michaelgugino not sure either ;)
My point is to have a custom behaviour when a path is not found (not talking about some resource raising a 404). How would I achieve that with your PR?

**Comment by michaelgugino** [comment]
When an error is raised, behavior can be overridden with `app.add_error_handler()` See README.md "A More Complex Example" https://github.com/falconry/falcon#a-more-complex-example

Otherwise, without that PR, a 404 response with an empty body will always be delivered.

**Comment by kgriffs** [comment]
Just to clarify, before @michaelgugino's patch was merged, the framework would use a default responder when no route was found for the request. That default responder set the resp status to 404, rather than raising an error. With @michaelgugino's patch, the framework now raises an instance of `HTTPNotFound`. This can be caught using a custom error handler. I'm working hard to get 0.4 out the door ASAP, so that this change will be available in a stable release.

Alternatively, you can add a sink that will capture requests for a particular portion of your URL namespace, but that may or may not work for you depending on your use case.

**Comment by kgriffs** [comment]
Note: As of the 1.0 release, an instance of `HTTPNotFound` is raised.

**Comment by vytas7** [comment]
Hi @yohanboniface ,
I believe this issue got a one more path of solution in Falcon 2.0. If you are mostly after customizing the representation, you can [customize the default error serializer](https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.set_error_serializer), where you can act accordingly if the `exception` is of type [HTTPNotFound](https://falcon.readthedocs.io/en/stable/api/errors.html#falcon.HTTPNotFound). Customizing the error serialization feature is not new, but prior to Falcon 2.0, classes deriving from `OptionalRepresentation` could actually never reach the custom serializer.

Or, as suggested by @kgriffs and @michaelgugino, one can
* Add an error handler for [HTTPNotFound](https://falcon.readthedocs.io/en/stable/api/errors.html#falcon.HTTPNotFound) ("custom behaviour")
* Add a sink covering paths of interest (or even a generic sink last in the chain catching all)

There is still some remaining work to iron out inconsistencies among exception classes which particularly applies to `HTTPNotFound`, but that work is tracked in https://github.com/falconry/falcon/issues/777
I'm thus inclined to close this issue as Falcon 2.0+ now has different ways to execute custom logic upon router emitting `HTTPNotFound`, but do not hesitate to reopen if there are cases where the approaches discussed above don't work.

**Comment by vytas7** [comment]
Ah, a correction, I happened to miss the documentation aspect of this issue.
Yes, we should improve the docs adding recipes covering the suggestions above.

**Comment by vytas7** [comment]
Duplicates #1324
