### ISSUE TITLE
Accessing current application

### ISSUE THREAD

**Issue by lucidfrontier45** [falconry/falcon#673]
Does falcon provide something like `current_app` of Flask?
I need to add some global objects (DB e.g. connection object) to an instance of falcon.API and access them from `on_get` etc.

**Comment by jmvrbanac** [comment]
For the example of working with a DB, I usually create a DB Manager class with my common interactions abstracted and then pass it in when I instantiate a Falcon resource. This usually makes the resource much easier to test because you're not having to manage external state for your tests.

**Comment by lucidfrontier45** [comment]
thank you. I'm working on this way
