### ISSUE TITLE
Also convert '1' and '0' as booleans from query string

### ISSUE THREAD

**Issue by yohanboniface** [falconry/falcon#684]
I see that [tests](https://github.com/falconry/falcon/blob/master/tests/test_query_params.py#L194) specifically exclude `0` and `1` from valid values to be converted to boolean by `Request.get_param_as_bool` method.

I'd like to discuss this situation :)

I see no reason not to convert those values as they seem non ambiguous to me and there are a bunch of situations where 1 and 0 are de facto boolean (database outputs…), but we only deals with string in query string.

What is the rationale behind this?

Thanks! :)

**Comment by Erve1879** [comment]
+1 for supporting 1 and 0 for true and false.

It may not necessarily be standard (I'm not a Swift dev, so could be wrong either way), but I do see Swift apps sending 1 and 0 as ints for bool in HTTP GET requests.

**Comment by swizzard** [comment]
I'm +1 on this also...FWIW, Facebook's Graph API also uses `1` and `0` for
true and false.

On Wed, Jan 13, 2016 at 7:00 AM, George Irwin <notifications@github.com>
wrote:

> +1 for supporting 1 and 0 for true and false.
>
> It may not necessarily be standard (I'm not a Swift dev, so could be wrong
> either way), but I do see Swift apps sending 1 and 0 as ints for bool in
> HTTP GET requests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/falconry/falcon/issues/684#issuecomment-171268937>.
>



-- 
.

**Comment by kruchone** [comment]
+1 on that... I would also like to see the True and False python boolean types added as well (for use with the json module).
