### ISSUE TITLE
resp.location double-encodes urlencoded strings

### ISSUE THREAD

**Issue by alertedsnake** [falconry/falcon#687]
I've got a URL which contains a url-encoded URL as a parameter, and when setting resp.location, that results in it being double-encoded:

resp.location = "http://something?redirect_uri=http%3A%2F%2Fsite"

This should result in:
Location: http://something?redirect_uri=http%3A%2F%2Fsite...

But what actually happens is:
Location: http://something?redirect_uri=http%253A%252F%252Fsite

I worked around by raising a HTTPStatus() object, but this doesn't seem like the ideal situation.

**Comment by kgriffs** [comment]
Hi @alertedsnake, thanks for the report. I agree that `resp.location` should be smarter about this. Work on Falcon 0.4 is wrapping up, but I've scheduled this bug fix for the following release.

**Comment by Pressy** [comment]
Same issue  here.
Please try to fix it as soon as possible because we have planned to use it in production.

Till then, any solution to fix this issue is welcomed. 
Thank you.

**Comment by painterjd** [comment]
Possibly related: #782

**Comment by painterjd** [comment]
Hi, @alertedsnake, @pressyfdo:

Thanks for reporting this issue! 

I've been taking a fairly deep look at this and discussing with @kgriffs and others. I'm curious if you could fill me in with more details with the specific issue you are having. Specifically, I'm trying to understand why you might have an encoded URL from within your application (if the URL is coming in through Falcon in the usual way(s) it should be automatically decoded). If you know that the URL was previously encoded, why not just decode it using urllib before assigning to `resp.location`? 

The crux of the problem:
- Any value in the Location header (and others) needs to be urlencoded. 
- There is no good way to determine if URI is already encoded or not (any suggestions here appreciated). There are some heuristics that can be used to achieve a fairly high level of certainty, but there are no deterministic approaches that will work 100% of the time. 
- The typical approach for dealing with url encoding is to be explicit about when urls are encoded or not and perform encoding/decoding as necessary.

**Comment by alertedsnake** [comment]
The URL I am assigning to resp.location is not encoded - it contains URL encoded parameters. This data is not coming in from something in Falcon that should have bit didn't decode it, it is something application specific that we are generating. As was stated in my example, it is a url which has a url-encoded url as a parameter. 

Your suggestion is that I decode this data before setting resp.location? The issue I see with this is that I am passing what is a perfectly valid URL to an argument called "url" and Falcon is altering it in an unexpected way. I can see no reason for Falcon to alter this data in any way. 

At the very least, the documentation should be very explicit here if the behavior is to remain as it is now. 

Does that help?

**Comment by alertedsnake** [comment]
Now that I look too, this is definitely the same issue as with #782 and was also broken by the solution to #135.

**Comment by alertedsnake** [comment]
Ugh, cop out.

**Comment by kgriffs** [comment]
Hi @alertedsnake, we are actually still looking at this. The issue was closed prematurely.

**Comment by kgriffs** [comment]
@alertedsnake can you take a look at https://github.com/falconry/falcon/pull/869 to see if it resolves your issue?

**Comment by alertedsnake** [comment]
Looks good! I should be able to actually test later this week, but the test cases in the PR cover my use case just fine. 

Thanks for adding this!
