### ISSUE TITLE
`api.__call__()` will call `process_resource()` even if routing fails

### ISSUE THREAD

**Issue by foresmac** [falconry/falcon#691]
Run into a strange bug that a middleware was failing, and traced it back to this unusual anomaly which we found in comments on `api.py`:

```
                                resource: Resource object to which the request was
                                routed. May be None if no route was found for
                                the request.
```

It's not documented in the middleware documentation that this is the behavior, but it also seems odd since every `process_resource()` would then have to start with `if resource is not None`. If routing fails, why not immediately raise `HTTPNotFound`?

**Comment by MackYoel** [comment]
good point, but I can think that this behavior could help decide how to handle the situation, for example recorded in a log which are commonly URIS Requested and not founded.
However write <pre>if resource is not None</pre> in each process_resource seems annoying.

**Comment by MackYoel** [comment]
Good point, but I can think that this behavior could help decide how to handle the situation, for example recorded in a log which are commonly URIS Requested and not founded.
However write <code>if resource is not None</code> in each process_resource seems annoying.

**Comment by MackYoel** [comment]
Good point, but I think that this behavior could help decide how to handle the situation, for example recorded in a log which are commonly URIS Requested and not founded.
However write <code>if resource is not None</code> in each process_resource seems annoying.

**Comment by kgriffs** [comment]
It would be easy enough to skip `process_resource()` when no route is found. A sink could still be used to take action in that case, if desired. All that's needed is an `if resource is not None:` above [api.py#L181](https://github.com/falconry/falcon/blob/master/falcon/api.py#L181).

**Comment by foresmac** [comment]
@kgriffs This seems like a sensible change and I support it.
