### ISSUE TITLE
Falcon app running very slow on wsgi servers

### ISSUE THREAD

**Issue by suhas-babyoye** [falconry/falcon#695]
I apologise in advance if this is an inappropriate place to post this. I developed a falcon app using the wsgi simple_server and everything was working fine. I am using multiprocessing and I used a BaseManager implementation to keep some memory and objects available to all processes. When I started using production servers, I observed some very alarming drop in response times. I have tried using gunicorn(with sync, eventlet and gevent), uwsgi and cherrypy. None have come even close to the performance which simple_server was able to provide. With cherrypy and uwsgi, it was exceedingly obvious that the problem was due to the synchronised memory space for the objects. Is it okay to run the simple_server with nginx for reverse proxy on production?

**Comment by kgriffs** [comment]
If you are fronting simple_server with nginx you should be OK.

**Comment by suhas-babyoye** [comment]
Thanks. I managed to get equivalent performance with gunicorn. Plus it has multiple process support too. I am using it with nginx for reverse proxy.
