### ISSUE TITLE
Http Error return JSON format

### ISSUE THREAD

**Issue by skymoney** [falconry/falcon#699]
in a middleware, If an Error is raised, always return xml format info to client, 
so any settings to return json format info, or do I need to customize ?

**Comment by MackYoel** [comment]
I am not an expert, but python-mimeparse do that for you, it chooses a content-type according to client request. So if you do a request in the browser and this raise an error, you will get a XML representation, but if you do the request through Postman Client or any client that Accept application/json, you will get a JSON representation.
However you can change the behaviour and do Falcon always use JSON representation.
[http://falcon.readthedocs.org/en/latest/api/api.html#falcon.API.set_error_serializer](http://falcon.readthedocs.org/en/latest/api/api.html#falcon.API.set_error_serializer)

**Comment by skymoney** [comment]
yeah, I've already fix it by customizing a component to pre-check request, 
Still, what you said is a good solution, thanks a lot.
