### ISSUE TITLE
Path segment in one route's URI template masks the field expression in another route

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#702]
The following test demonstrates the issue. The assertion fails since the resulting status code is 404, rather than 200. "/v2.0/thing" should route to `/{version}/thing` instead of `/v2.0`.

```py
def test_string_vs_var(self):
    self.api.add_route('/v2.0', self.resource)
    self.simulate_request('/v2.0')

    self.api.add_route('/{version}/thing', testing.TestResource())
    self.simulate_request('/v2.0/thing')
    self.assertEqual(self.srmock.status, falcon.HTTP_200)
```

```
/{version}/foo/bar
/v1.0
```

**Comment by MackYoel** [comment]
someone is working to fix this bug?

**Comment by stevelle** [comment]
Adding that order of routes being added does not work around this. I just ran into this bug this week with the following

    app.add_route('/recipes/{activity}/{type_id}', ActivityResource())
    app.add_route('/recipes/baking', RecipeBakingResource())

**Comment by kgriffs** [comment]
I'm working on this. Hoping to get it in for 0.4.

**Comment by kgriffs** [comment]
@stevelle, @MackYoel if you could try out #723 to see if it fixes the issue for you (without creating any new ones!), I'd love to get your feedback. Thanks!
