### ISSUE TITLE
Passing max_age as float instead of int to set_cookie(), no cookie will be set

### ISSUE THREAD

**Issue by jgehrcke** [falconry/falcon#704]
When using `response.set_cookie()` and passing the `max_age` parameter as a `float` instead of an `int`, the cookie will not be set in the response (that's Python 3.4 and Falcon 0.3.0).

It's clearly documented in the docstring of the `set_cookie()` method that this parameter is expected to be an `int`, so I spotted the problem rather quickly after re-reading the docs. However, either a raising an exception or implicitly converting to int would be much less painful, IMO. What do you think?

**Comment by jgehrcke** [comment]
I'd also be happy to provide a PR if we decide to change this behavior.

**Comment by kgriffs** [comment]
I don't think it would harm anything to simply convert it to an int. Happy to take a PR for this change.

**Comment by jgehrcke** [comment]
See PR #711. After more investigation, the cookie actually was set in the response, with the floating point value to max-age. This violates RFC 6265, so that the cookie parser I used (the `requests` lib) simply ignored the entire cookie.
