### ISSUE TITLE
Flesh out the contributor's guide

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#716]
CONTRIBUTING.md should be the TL:DR version of what is published on RTD. The former should include a link to the latter.

Content to include (in no particular order):
- Project philosophy and scope
- Voting / review process
- Your first PR
- Code coverage
- Every bug fix requires a regression test
- Design principles (both general ones, and Falcon-specific)
- Benchmarking and profiling
- Intellectual property / copyright
- Dev process
- Code of conduct, expectations
- release process (tag, twine, sign, etc.)
- rebasing
- Coding style
- how to split up PRs
  - logical
  - usually a PR is one logical change, so 1:1
  - OK to add additional commits during review ~~but please squash when done. is helpful to check that comments have been addressed, or for reverting when experimenting with a given approach~~. No longer relevant since we switched to _Squash & Merge_.
  - ~~if you have to do a new commit to fix CI, then squash it~~
  - Each commit should pass all ~~Travis~~ CI (we use GitHub Actions) tests
- How to get on the maintainers team (and who is on it)

Prior art:
- https://cryptography.io/en/latest/development/
- http://docs.openstack.org/developer/zaqar/

**Comment by vytas7** [comment]
I'm going to close this issue; what we have no is by no means perfect, but there is a document, [`CONTRIBUTING.md`](https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md), that does cover the basics. As part of the docs revamp for 4.0, I have also hooked it into our docs via MyST Markdown: [Contribute to Falcon](https://falcon.readthedocs.io/en/stable/community/contributing.html).

Although this document doesn't cover the development process part very well, but that is tracked in another issue: #467.
