### ISSUE TITLE
Generate HTTP status string from status code

### ISSUE THREAD

**Issue by momoneko** [falconry/falcon#744]
Does falcon have any way of generating the status string from the status code? 

I have to pass the status from a HTTP call to the requester, and I get only the HTTP status code, not the entire string. Having a way to generate the string from the status would make it way easier.

**Comment by kgriffs** [comment]
This isn't in the framework, but I think it would be worth adding. We'll need to note that there's a slight performance penalty for doing the conversion, but 

I would suggest adding a utility function for this as well as a new property on the Response class that accepts just a code.

**Comment by sherwu** [comment]
I can take this!

**Comment by kgriffs** [comment]
[Merged]
