### ISSUE TITLE
HTTPMovedPermanently not found in module

### ISSUE THREAD

**Issue by joarleymoraes** [falconry/falcon#746]
I'm trying to use:
`raise falcon.HTTPMovedPermanently(location)`

But I'm getting:
`AttributeError: 'module' object has no attribute 'HTTPMovedPermanently'`

I have seen that `__init__.py` imports everything from redirects.py:

`from falcon.redirects import *  # NOQA`

So I'm not sure why I have this issue. Any ideas ?

Thanks

**Comment by joarleymoraes** [comment]
I'm doing the following as workaround:

```
    resp.status = falcon.HTTP_301
    resp.set_headers({'location': location})
```

**Comment by kgriffs** [comment]
Hi @joarleymoraes, `falcon.HTTPMovedPermanently` was added in 1.0.0rc1, so perhaps it's a version problem?

**Comment by joarleymoraes** [comment]
That's it. `pip freeze` gives me: `falcon==0.3.0`

Any plans for 1.0 be available through pip ?

Thanks

**Comment by kgriffs** [comment]
The final release should be along in another couple of weeks, but in the meantime you can use `pip --pre` to pull down the RC. Hope that helps!

**Comment by joarleymoraes** [comment]
Great, it worked. Thanks for this, @kgriffs .
