### ISSUE TITLE
Submitting anything as the body of a `simulate_request` leads to empty AssertionErrors

### ISSUE THREAD

**Issue by MasterKale** [falconry/falcon#747]
I'm trying to write a test for a resource but for some reason whenever I set a string for the `body` parameter in my `simulate_request` I see AssertionErrors from `wsgiref.validate`:

	  File "/home/me/Repos/falconproject/middleware.py", line 30, in process_request
	    body = req.stream.read()
	  File "/usr/lib/python3.4/wsgiref/validate.py", line 197, in read
	    assert_(len(args) == 1)
	  File "/usr/lib/python3.4/wsgiref/validate.py", line 128, in assert_
	    raise AssertionError(*args)
	nose.proxy.AssertionError: 

There's no associated exception text so I have no idea why it's dying there. Line 30 in my `middleware` module is part of the `JSONTranslator` middleware I pulled from the quickstart:

    def process_request(self, req, resp):
        # req.stream corresponds to the WSGI wsgi.input environ variable,
        # and allows you to read bytes from the request body.
        #
        # See also: PEP 3333
        if req.content_length in (None, 0):
            # Nothing to do
            return

        # V This is line 30 V
        body = req.stream.read()

If I set `body` to an empty string then the request goes through because the JSONTranslator just returns out, but what good is request testing if you can't include anything in the request?

The docs are frustratingly vague, especially on this:

> body (str) – A string to send as the body of the request. Accepts both byte strings and Unicode strings (default: None). If a Unicode string is provided, it will be encoded as UTF-8 in the request.

What am I doing wrong here?

**Comment by MasterKale** [comment]
I forgot to include my `TestCase`:

	import json

	import falcon
	from falcon import testing

	import app	


	class TestLoginResource(testing.TestCase):
	    def setUp(self):
	        super(TestLoginResource, self).setUp()

	        self.api = app.api

	    def test_bad_credentials_get_401(self):
	        response = self.simulate_post(
	            path='/login',
	            body=json.dumps({'username': 'foo', 'password': 'bar'})
	        )

	        self.assertEqual(response.status_code, falcon.HTTP_401)

**Comment by MasterKale** [comment]
I figured out what the issue is, I'll issue a PR with fixes once I finish documenting it and writing tests.

**Comment by kgriffs** [comment]
Fixed in #748
