### ISSUE TITLE
Add option to opt-out from comma separated value parsing

### ISSUE THREAD

**Issue by rr-** [falconry/falcon#749]
I'm porting a project to Falcon and I stumbled upon an issue regarding its parsing of CSV values inside URIs. Let's say I have filtering engine that accepts queries such as this:

    http://great.dude/api/cars?query=added:yesterday,today+spoilers:red

I obviously want to make `req.get_param('query')` return `'added:yesterday,today spoilers:red'`, and not `['added:yesterday', 'today spoilers:red']`.

Right now this [isn't really configurable](https://github.com/falconry/falcon/blob/35987b2be85456f431bbda509e884a8b0b20ed11/falcon/util/uri.py#L312-L328) and I need to check if `get_param()` returns a `list` and then join it back if needed, which looks sort of silly. Fortunately, the ability to use custom request classes alleviates the issue to some extent.

I see a few ways to improve things upstream:

1. Offer explicit `get_param_as_string` that will possibly do `','.join(...)` under the hood.
2. Add an option to disable this mechanism as an additional option to `Api`.
3. Add an option to disable this mechanism as an additional option to `add_route()`.
4. Change `get_param` to always return string.

Option 4 makes the most sense to me, but it breaks BC. If option 4 is not feasible, I'd went with option 1.

**Comment by kgriffs** [comment]
I think we can start by adding an option to `RequestOptions` to enable/disable parsing of comma-separated query string values. It can default to `True` for the sake of BC. For Falcon 2.0 we can consider changing the default to `False`. 

For more fine-grained control I like the idea of passing options to `API.add_route()`. But perhaps we should wait to see if there is demand for that from the community (unless you already have a need for it, of course).

**Comment by rr-** [comment]
FWIW for time being, I ended up rolling own solution like this:

- Input parsing facilities within custom context class: https://github.com/rr-/szurubooru/blob/master/server/szurubooru/api/context.py 
- Filling context class with user input inside middleware: https://github.com/rr-/szurubooru/blob/master/server/szurubooru/middleware/context_adapter.py#L54-L55

I don't think I currently need options within `add_route()`. The idea sounds pretty good, as it'll add some flexibility, though.

I have this idea of offering alternative to `get_param_as_x` in form of validation rules passed to the mentioned options of `add_route`. However, I'm not sure what to think about it: on one hand, it'll simplify code, as routes can assume they get called with sane parameters, period. On the other hand, I don't like huge dictionaries / config classes - current `get_param_as_x` functions are straightforward and intuitive, whereas the config approach, to be maintainable and easily documentable, would probably need to use things such as `options=RouteOptions(params={'query': TextParameter(required=True), 'page': NumberParameter(required=False, default=1, min=1)})` which kind of starts looking like Java. Just tossing ideas.

**Comment by kgriffs** [comment]
We can start with a "global" option and add support for per-route options later as needed. 

Regarding form validation rules, it may make sense to be able to attach arbitrary metadata/kwargs to a route that hooks or middleware could then use. Or the validation rules could just be specified directly in a decorators/hook declaration. Sort of like https://github.com/painterjd/stoplight.

**Comment by orcsly** [comment]
I'll look into this one.
