### ISSUE TITLE
router.find() cannot return None

### ISSUE THREAD

**Issue by warsaw** [falconry/falcon#750]
Contrary to http://falcon.readthedocs.org/en/latest/api/routing.html it seems like custom routers `.find()` method cannot return None.  AFAICT, `_get_responder()` unpacks `self._router.find(path)` without checking for a None return value and thus an exception occurs.  However, returning `(None, None, None)` seems to work.

I don't know if the docstring is wrong or the method.

**Comment by kgriffs** [comment]
Nice catch! I think the code should be changed to reflect this, with care taken to not break existing routers that may rely on the current bahavior.

**Comment by kgriffs** [comment]
Take a look at my PR and let me know what you think. Thanks!

**Comment by warsaw** [comment]
I haven't tested it with the Mailman 3 trunk, but it looks pretty reasonable.  The only thing I couldn't tell was whether method_map would get set correctly when only `None` is returned, but I'm sure you're testing for that.
