### ISSUE TITLE
Falcon based project, falcons_nest

### ISSUE THREAD

**Issue by gknight007** [falconry/falcon#752]
Hi,

I love falcon, but I wanted something a little simpler, but with all the power.  So, I put falcon inside gevent, added some daemon code, dynamic class loaders and changed the way responses are done.  I would love your feed back on the project!

https://github.com/gknight007/falcons_nest.git

**Comment by kgriffs** [comment]
Hi @gknight007, thanks for the note! You might like to add a link to the wiki: https://github.com/falconry/falcon/wiki/Higher-Level-Frameworks
