### ISSUE TITLE
How can do a internal request that like subquery in nginx or asynchttpclient in tornado?

### ISSUE THREAD

**Issue by codezq** [falconry/falcon#753]
Maybe requests or libcurl or urllib?

**Comment by kgriffs** [comment]
Hi @codezq, you can use the `requests` library along with gevent, or if you are hosting with twisted.web.wsgi, you can use the `crochet` library to perform requests via twisted. You might also try `aiohttp.wsgi` if you are on py3k.

**Comment by codezq** [comment]
Thanks a lot! Now I use the `requests` library.
