### ISSUE TITLE
Add test for hyphens and other non-arg-friendly chars in URI template field names

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#769]
Currently we only check up-front in `add_route()` for field names that start with a digit or contain whitespace. This can lead to cryptic errors later on when requests are routed to responders.

**Comment by kgriffs** [comment]
See also: `test_whitespace_not_allowed()` in `tests.test_uri_template` and `add_route()` in `routing.compiled`.

**Comment by enzzc** [comment]
Is this template supposed to be valid? '/repos/{org}/{repo}/compare/{simple-vs-complex}' (from /tests/test_default_router.py:140). `simple-vs-complex` is not a valid Python identifier.

**Comment by kgriffs** [comment]
Good catch! That will blow up if it were actually passed as kwargs to a resource responder method.
