### ISSUE TITLE
Would it make sense to support hosting falcon apps via aiohttp?

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#772]

**Comment by vytas7** [comment]
We'll probably want to close this as Won't Fix in order to focus resources on ASGI.
But maybe we could wait a bit with closing until our ASGI support matures a bit more so we would get a better feeling what advantages/disadvantages `aiohttp` provides vs ASGI.

**Comment by vytas7** [comment]
As we have now jumped on the ASGI bandwagon, I am going to close this for now.

`aiohttp` seems to have evolved into sort of a framework on its own, interestingly even bearing some similarities to Falcon. However, at the same time it does not look very suitable for layering another framework (such as Falcon atop) it. Indeed, one doesn't really find (m)any higher level frameworks in that vein: https://docs.aiohttp.org/en/stable/third_party.html

Maybe one day `aiohttp` gets ASGI support itself, even though that looked [unlikely at the time it was being discussed](https://github.com/aio-libs/aiohttp/issues/2902).
