### ISSUE TITLE
Make the title and description optional for most error classes (non-breaking)

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#776]
For most error classes we can make the title and description optional without introducing a breaking change. For example, this:

```py
    def __init__(self, title, description, **kwargs):
        super(HTTPConflict, self).__init__(status.HTTP_409, title,
                                           description, **kwargs)
```

Would become this:

```py
    def __init__(self, title=None, description=None, **kwargs):
        super(HTTPConflict, self).__init__(status.HTTP_409, title,
                                           description, **kwargs)
```

The following classes could be modified in a non-breaking way:

- [ ] HTTPBadRequest
- [ ] HTTPUnauthorized
- [ ] HTTPForbidden
- [ ] HTTPConflict
- [ ] HTTPLengthRequired
- [ ] HTTPPreconditionFailed
- [ ] HTTPRequestEntityTooLarge
- [ ] HTTPConflict
- [ ] HTTPLengthRequired
- [ ] HTTPPreconditionFailed
- [ ] HTTPUnprocessableEntity
- [ ] HTTPTooManyRequests
- [ ] HTTPUnavailableForLegalReasons
- [ ] HTTPInternalServerError
- [ ] HTTPBadGateway
- [ ] HTTPServiceUnavailable (Make retry_after optional as well)

The remainder will require breaking changes, and will be taken care of by the general normalization work to be performed in #777

**Comment by stiefel40k** [comment]
I got this as soon as we hit October 1st.
