### ISSUE TITLE
Make error initializers more consistent

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#777]
This issue involves reworking error class initializer method signatures to be more consistent and predictable. Each `__init__` should order args and kwargs as follows:
1. Required, specialized args. Most error classes will not have any required args. 
2. `title=None`
3. `description=None`
4. `**kwargs`

**Comment by kgriffs** [comment]
Moving this to 3.0 in the interest of getting 2.0 out sooner.

**Comment by CaselIT** [comment]
I'll try to work on this
