### ISSUE TITLE
HTTPError should have a handle method to set resp.status, resp.body before middleware runs

### ISSUE THREAD

**Issue by foresmac** [falconry/falcon#779]
(This issue was moved from #391 per @kgriffs' [comment](https://github.com/falconry/falcon/issues/391#issuecomment-218052853).)

Following on the updates to `HTTPError` and subclasses described in #776, #777, #778, we have also found that the current error handling happens _after_ all the middleware has run. In other words, after all other middleware has run, the generic catch for `HTTPError`s sets the status and body of the response. It would be preferable to set this before all the middleware has run, in case some additional action need to happen in certain error cases.

For instance, in our case we wrote a request logging middleware that grabbed useful data from all requests, including response status codes and bodies.

```python
class RequestLogging:

    def process_response(self, req, res, resource):
        user = req.context.get('auth_user')
        user_id = user['id'] if user else None

        request = req.context.get('data')
        if request:
            if 'password' in request:
                request['password'] = REDACTED

        response = req.context.get('result')
        if response:
            if 'token' in response:
                response['token'] = REDACTED

        origin = req.get_header('X-Forwarded-For')
        msg = {
            'environment': ENVIRONMENT,
            'origin': origin,
            'status': res.status[:3],
            'method': req.method,
            'endpoint': req.relative_uri,
            'user_id': user_id,
            'request': request,
            'response': response
        }
        logger.info(json.dumps(msg))
```

However, the standard error handling meant we _weren't_ getting this data for 4xx or 5xx conditions, since those were set after our logging middleware had run. To address this, we made a subclass of `HTTPBadRequest` with a custom `handle` method that set the response status and body before middleware could process it.

```python
class APIError(HTTPError):
    """
    This is a subclass of falcon's HTTPError that automatically
    sets the title to the text of the `status`. It also has a handler
    that will set the `resp.status` to match and the `resp.body` to a
    JSON representation of the error, e.g. the validation errors
    generated by Cerebus validators. Critically, it does this within the
    nested try/except block inside `api`, which will set status and body
    _before_ midddleware executes any `process_request()` methods, so
    all error responses can be logged via middleware.

    Args:
        status (str): HTTP status code and text, e.g. falcon.HTTP_BAD_REQUEST
        description(str or dict): An optional useful error message

    All other HTTPError kwargs can be passed in as well.
    """

    def __init__(self, status, description=None, **kwargs):
        super(APIError, self).__init__(status, title=status[4:], description=description, **kwargs)

    @staticmethod
    def handle(ex, req, resp, params):
        resp.status = ex.status
        req.context['result'] = ex.to_dict()
```

**Note:** we set the result of any call as the `result` in `request.context`. We have another middleware that then renders that based on the `content-type` of the request, e.g. JSON. Instead of writing there this could be to `response.body` directly. Also, this already uses the default title as mentioned in #778.

Another use case that comes off the top of my head is devops alert middleware that contacts sysadmins whenever certain errors arise. I'm sure there are other reasons to catch errors in middleware and do something to handle them.

Thoughts?

**Comment by kgriffs** [comment]
It sounds reasonable to make sure a raised error is composed into the response before passing it along to middleware. Looks like we need to make sure `API._compose_error_response()` is called before https://github.com/falconry/falcon/blob/master/falcon/api.py#L214. But we need to be careful we don't introduce other bugs since the error handling logic is starting to get crufty (esp. when you consider that an error handler or middleware component may, itself, raise an error). This may be a good time to clean all that up.

**Comment by foresmac** [comment]
Perhaps the response object needs a standard property that collects errors as they are generated? Hrmmmmm, not sure what the best interface is for this, but it seems as though it would be really useful to have some way for middleware to be able to interact with and react to errors before an error response is returned to the client.

**Comment by kgriffs** [comment]
I reworked the middleware handling logic (now merged to master) so that error handlers (including the default ones for HTTPError and HTTPStatus) will be called (and have the opportunity to set resp.status, etc.) before calling middleware process_response() methods. Give it a try and let me know if that helps!

**Comment by kgriffs** [comment]
Going to go ahead and close this. Please reopen if 1.1 doesn't meet your needs. Thanks!
