### ISSUE TITLE
No OPTIONS Header support

### ISSUE THREAD

**Issue by Woolworths** [falconry/falcon#781]
Most API frameworks automatically dispatch an OPTIONS header. This one doesn't so whenever you use any kind of AJAX, it just returns 204 No Content and does not dispatch the OPTIONS header with "Access-Control-Request-Method: POST"

**Comment by kgriffs** [comment]
I believe @lwcolton's [falcon-cors](https://github.com/lwcolton/falcon-cors) provides this functionality.

When a resource does not implement an `on_options()` method, Falcon uses a default OPTIONS responder that sets the Allow header. But the default responder does not detect a CORS preflight request, and so it will not respond with Access-Control-* headers.

**Comment by kgriffs** [comment]
@Woolworths have you had a chance to look at falcon-cors to see if it does what you need?

**Comment by Woolworths** [comment]
@kgriffs I don't know what I was going on about.. The options header works fine :)

**Comment by kgriffs** [comment]
OK, no worries.
