### ISSUE TITLE
Response href headers are double escaped

### ISSUE THREAD

**Issue by natedub** [falconry/falcon#782]
#135 makes an attempt to simplify things for developers, but unfortunately it actually breaks well-formed URIs by double escaping them. 

I may never have noticed this were I not trying to pass a signed URI where the double escaping broke the signature. Signed S3 URLs that are double escaped definitely don't work!

Of course, the workaround is easy enough — just use `Response.set_header()` directly — I just wanted to flag this as behaviour that was quite surprising and may not be desirable in the long run.

**Comment by kgriffs** [comment]
Hi @natedub, thanks for the report! I'm guessing all the `'%'` characters are being replaced with `'%25'`? urllib behaves in the same way, but that isn't to say Falcon can't be a little bit smarter about this. A fast heuristic would be to include `'%'` in the list of allowed characters. However, that doesn't handle the edge case of a URL containing a percent sign that isn't actually used for escaping. Not sure how common that is...

**Comment by painterjd** [comment]
Possibly related to #687
