### ISSUE TITLE
Should `falcon.HTTPNotAcceptable` support a format for listing available representations?

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#784]
Regarding _406 Not Acceptable_, RFC 7321 states in [section 6.5.6](https://tools.ietf.org/html/rfc7231#section-6.5.6):

```
The server SHOULD generate a payload containing a list of available
   representation characteristics and corresponding resource identifiers
   from which the user or user agent can choose the one most
   appropriate.  A user agent MAY automatically select the most
   appropriate choice from that list.  However, this specification does
   not define any standard for such automatic selection, as described in
   Section 6.4.1.
```

Referring to [section 6.4.1](https://tools.ietf.org/html/rfc7231#section-6.4.1) we read:

```
Note: The original proposal for the 300 status code defined the
      URI header field as providing a list of alternative
      representations, such that it would be usable for 200, 300, and
      406 responses and be transferred in responses to the HEAD method.
      However, lack of deployment and disagreement over syntax led to
      both URI and Alternates (a subsequent proposal) being dropped from
      this specification.  It is possible to communicate the list using
      a set of Link header fields [RFC5988], each with a relationship of
      "alternate", though deployment is a chicken-and-egg problem.
```

**Comment by vytas7** [comment]
MDN [states](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406):
> In practice, this error is very rarely used. Instead of responding using this error code, which would be cryptic for the end user and difficult to fix, servers ignore the relevant header and serve an actual page to the user.

Since there hasn't been any interest from the community, I don't think this is worth pursuing. Furthermore, it is unclear how to serialize the list of acceptable representations, if we don't know what the client accepts. If any users need this, they will have to customize error serialization, or convey the information via resp headers.
