### ISSUE TITLE
Mac OS X wheel distribution for Python 3.3 broken on OS X 10.11.1 (python dist installed from Python.org)

### ISSUE THREAD

**Issue by swistakm** [falconry/falcon#787]
The `falcon-1.0.0-cp33-cp33m-macosx_10_10_x86_64.whl` installed on certain version of Python on OS X raises `ImportError` exception on falcon import.

This seem to affect only Python 3.3 distribution from Python.org that is built against 10.6 version of platform SDK. I haven't tried earlier versions of Python since I found it when updating test matrix for [graceful](https://github.com/swistakm/graceful) project that targets only Python>=3.3.

Following is formatted console transcript that reproduces this error on my environment:

```console
(python3.3)swistakm@scotty:~/...747c6860961c467$ python -c 'import sys; print(sys.version)'
3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 01:12:57) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

(python3.3)swistakm@scotty:~/...747c6860961c467$ python -c 'import distutils.util; print(distutils.util.get_platform())'
macosx-10.6-x86_64

(python3.3)swistakm@scotty:~/...747c6860961c467$ pip install -U pip wheel -q
You are using pip version 6.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


(python3.3)swistakm@scotty:~/...747c6860961c467$ pip install falcon
Collecting falcon
  Using cached falcon-1.0.0-cp33-cp33m-macosx_10_10_x86_64.whl
Collecting python-mimeparse (from falcon)
Collecting six>=1.4.0 (from falcon)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: python-mimeparse, six, falcon
Successfully installed falcon-1.0.0 python-mimeparse-1.5.2 six-1.10.0

(python3.3)swistakm@scotty:~/...747c6860961c467$ python -c 'import falcon; print(falcon.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/swistakm/.envs/tmp-b747c6860961c467/lib/python3.3/site-packages/falcon/__init__.py", line 31, in <module>
    from falcon.version import __version__  # NOQA
ImportError: dlopen(/Users/swistakm/.envs/tmp-b747c6860961c467/lib/python3.3/site-packages/falcon/version.so, 2): Symbol not found: _PyExc_ImportError
  Referenced from: /Users/swistakm/.envs/tmp-b747c6860961c467/lib/python3.3/site-packages/falcon/version.so
  Expected in: /Users/swistakm/.envs/tmp-b747c6860961c467/bin/python
 in /Users/swistakm/.envs/tmp-b747c6860961c467/lib/python3.3/site-packages/falcon/version.so
```

More system information:
```console
swistakm@scotty:~/.envs$ uname -a
Darwin scotty 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

This of course does not happen when I build falcon locally for myself or install from a wheel created under Python 3.3 built with 10.6 of SDK:

```console
(python3.3)swistakm@scotty:~/...810b37f37a058be$ pip install ~/dev/falcon/dist/falcon-1.0.0-cp33-cp33m-macosx_10_6_x86_64.whl 
Processing /Users/swistakm/dev/falcon/dist/falcon-1.0.0-cp33-cp33m-macosx_10_6_x86_64.whl
Collecting python-mimeparse (from falcon==1.0.0)
Collecting six>=1.4.0 (from falcon==1.0.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: python-mimeparse, six, falcon
Successfully installed falcon-1.0.0 python-mimeparse-1.5.2 six-1.10.0

(python3.3)swistakm@scotty:~/...810b37f37a058be$ python -c 'import sys; print(sys.version)'
3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 01:12:57) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

(python3.3)swistakm@scotty:~/...810b37f37a058be$ python -c 'import falcon; print(falcon.__version__)'
1.0.0
```

As far as I know this should work without any problems because libs built on later version of SDK should be compatible with Python version build on earlier version of SDK. In other words extension built with Python using `10.10` should work under Python built with `10.6`. This is how it looks when I do the same under Python 3.4:
 
```console
(python3.4)swistakm@scotty:~/...dfd642201fb2c19$ pip install -U pip wheel
You are using pip version 6.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(python3.4)swistakm@scotty:~/...dfd642201fb2c19$ python -c 'import sys; print(sys.version)'
3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

(python3.4)swistakm@scotty:~/...dfd642201fb2c19$ python -c 'import distutils.util; print(distutils.util.get_platform())'
macosx-10.6-intel

(python3.4)swistakm@scotty:~/...dfd642201fb2c19$ pip install falcon
Collecting falcon
  Using cached falcon-1.0.0-cp34-cp34m-macosx_10_11_x86_64.whl
Collecting python-mimeparse (from falcon)
Collecting six>=1.4.0 (from falcon)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: python-mimeparse, six, falcon
Successfully installed falcon-1.0.0 python-mimeparse-1.5.2 six-1.10.0

(python3.4)swistakm@scotty:~/...dfd642201fb2c19$ python -c 'import falcon; print(falcon.__version__)'
1.0.0
```

Falcon built under 10.11 SDK successfully imports on Python built with 10.6 version of SDK. The only difference is that wheel for Py34 has `macosx_10_11_x86_64` platform tag while the one for Py33 available on PyPI has `macosx_10_10_x86_64`. In fact, only the Python 3.3 version of falcon wheel available on PyPI seems to be built against 10.10 version of SDK. It may be a clue but I did not have time to dig into that deeper.

To conclude: It seems that the reason for that issue lies in the build environment. Maybe it would be desirable to build distributions against 10.6 version of SDK that allows for the widest compatibility (as suggested on [MacPython/Spinning Wheels](https://github.com/MacPython/wiki/wiki/Spinning-wheels) wiki page. Also fat binaries (`intel`) that have both i386 and x86_64 objects may be more preferable. I know that this would be a bit painful because it is more to create repeatable build environment before each distribution with such goal in mind. I don't know if it is possible with pyenv that seems to be used right now. But looking at [Numpy's](https://pypi.python.org/pypi/numpy) list of available wheels I guess this is the approach that they already have taken. And it seems that they are really experienced in providing built distributions for Python extensions, so maybe we should follow it too.

**Comment by kgriffs** [comment]
Thanks for the report! For now, I went ahead and deleted the cp33 wheel to stop the bleeding. We'll have to look at using 10.6 for the cythonized builds in the next release.

**Comment by kgriffs** [comment]
Looks like this can be mostly avoided by building against the python.org dist. But I'll probably just not ship cythonized wheels for OS X going forward since the extra speed boost isn't really critical during development.
