### ISSUE TITLE
Since version 1.0.0 I can't get params from JQuery requests

### ISSUE THREAD

**Issue by jf86** [falconry/falcon#788]
Hi,
My code works fine with v0.3.0 and JQuery v2.2.3 but since last falcon update I can't get params from POST/PUT/PATCH/DELETE requests.

Here is my Javascript code:

```
$.ajax({
        async:true,
        dataType:'json',
        type:method,
        url:'api/' + resource,
        data:data,
});
```

And my Falcon code:

```
def process_request(self, req, resp):
  print req.query_string
  print req.params
```

Both print return empty strings with any request except if method is GET.
What I'm doing wrong?

Thanks in advance!

**Comment by kgriffs** [comment]
Hi @jf86. This may be a consequence of a breaking change in 1.0.0 where Falcon will no longer automatically parse, by default, requests that have the content type “application/x-www-form-urlencoded”. There is an option to re-enable it:

```py
app = falcon.API()
app.req_options.auto_parse_form_urlencoded = True
```

See also: https://falcon.readthedocs.io/en/stable/changes/1.0.0.html#breaking-changes

If this is indeed the problem, I'll see if we can document this in the FAQ. Just let me know!

**Comment by jf86** [comment]
It works now! Thanks
