### ISSUE TITLE
Implement get_param_as_dict()

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#789]
This helper would deserialize JSON into a `dict`. For example:

`thing=%7B%22name%22%3A%20%22value%22%2C%20%22another%22%3A%20%22field%22%2C%20%22some%22%3A%20%22thing%22%7D`

...would be interpreted by req.get_param_as_dict as:

```json
{"name": "value", "another": "field", "some": "thing"}
```

**Comment by yashmehrotra** [comment]
Hi @kgriffs, I would like to implement this feature, can you assign this issue to me.
Thanks.
