### ISSUE TITLE
Default OPTIONS responder does not set Content-Length to "0"

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#796]
Per RFC 7231:

> A server MUST generate a Content-Length field with a value of "0" if no payload body is to be sent in the response.

**Comment by yashmehrotra** [comment]
@kgriffs Can you tell me how to reproduce this bug ?

For the script below, I am getting the correct `Content-Length` ie "0".

```python
import falcon

class ThingsResource(object):
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = ('Hello World\n')

app = falcon.API()
app.add_route('/things', ThingsResource)
```

Is there anything I am missing ? ( I am running the latest falcon dev version)

```
$ curl -XOPTIONS -i localhost:8000/things
HTTP/1.0 204 No Content
Date: Thu, 26 May 2016 20:32:55 GMT
Server: WSGIServer/0.1 Python/2.7.9
allow: GET
Content-Length: 0
```

**Comment by kgriffs** [comment]
Hi @yashmehrotra, thanks for taking a look! Perhaps the web server is adding that header? The framework isn't adding it per the repo below:

```py
import falcon
from falcon import testing

class ThingsResource(object):
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200
        resp.body = ('Hello World\n')

app = falcon.API()
app.add_route('/things', ThingsResource)

env = testing.create_environ('/things', method='OPTIONS')
srmock = testing.StartResponseMock()

app(env, srmock)
print(srmock.headers)
```

**Comment by yashmehrotra** [comment]
@kgriffs You were right, the server I was using was automatically adding it. I have created a patch for this one at: https://github.com/falconry/falcon/pull/801

**Comment by w1z2g3** [comment]
@kgriffs per https://tools.ietf.org/html/rfc7230

>   A server MUST NOT send a Content-Length header field in any response
>    with a status code of 1xx (Informational) or 204 (No Content).

I think RFC 7231 really means: For HTTP code not include 1xx and 204, a server MUST generate a Content-Length field with a value of "0" if no payload body is to be sent in the response.

https://tools.ietf.org/html/rfc2616#section-9.2 mentioned 200 for OPTIONS, but RFC 7231 removed that wording. So we can return 204 as well as 200. But when they write the document, I think they may still think 200 is the only code it returns, thus causing this confusion.

Anyway, it determined by which document we take precedence. And I think we should take rfc7230, which makes more sense.

Please help to confirm whether my understanding is correct.

**Comment by kgriffs** [comment]
Hi @w1z2g3, that's a good insight. Logically, it would make sense to use 204 for an OPTIONS response when no payload is given, and in that case Content-Length should not be specified. Falcon is currently returning 204 as well as setting Content-Length, so we should probably either switch to 200 or remove Content-Length. Given that RFC 7231 specifically states that Content-Length should be zero, I'm inclined to say that 200 was assumed by the authors, but that's just speculation. 

This may be a question for ietf-http-wg@w3.org (http://www.rfc-editor.org/info/rfc7231). I couldn't find an existing erratum about this.
