### ISSUE TITLE
simple dev server?

### ISSUE THREAD

**Issue by kfir124** [falconry/falcon#799]
Hi I came across to this project and it looks like exactly what I wanted
My only problem is that the only way to locally test your app with this project seems to be installing gunicorn or uwsgi, its exactly what I will do in production but on my local PC I'm using windows.

and installing gunicorn or uwsgi on windows makes things a lot more uglier and unstable.
isn't there any way to run a simple dev server from within Falcon itself? like I'm used from Flask or any other micro framework actually

Thanks in advance

**Comment by yohanboniface** [comment]
@kfir124 see https://github.com/BaseAdresseNationale/ban/blob/master/ban/commands/server.py for an example

**Comment by kfir124** [comment]
@yohanboniface  Thanks didn't know about that feature in python
