### ISSUE TITLE
Falcon bootstrap

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#8]
Have a repo and a built-in tool or something to pull it down easily to bootstrap new projects.

**Comment by kgriffs** [comment]
This can be a separate project under falconry.

**Comment by jheld** [comment]
Is there still interest in doing something like this (yeoman/generator style or some sort of skeleton hello world code)? If so, there would have to be a falcon-based script/bin to handle this execution, and it would likely be either installed separately, or brought in under setup.py.

**Comment by nZac** [comment]
This is the old issue. New work is being tracked in #1051.
