### ISSUE TITLE
problem with redirections

### ISSUE THREAD

**Issue by b0bbywan** [falconry/falcon#802]
Hi

I'm trying to redirect a request (from POST to GET) to another page on another domain, but I'm always encountering the following error:

XMLHttpRequest cannot load mydomain.com/redirect_page. The request was redirected to 'theotherdomain/redirected_page', which is disallowed for cross-origin requests that require preflight

edit: I tried to use

```
resp.location = 'theotherdomain/redirected_page'
resp.status = falcon.HTTP_301
```
or 
`raise falcon.HTTPMovedPermanently('theotherdomain/redirected_page')`

without success. 
Can somebody please help me ?

Thanks a lot !

**Comment by Vesuvium** [comment]
Hi b0bbywan, 

from the error you are getting it seems like your problem is CORS being not enabled. See #713 and #303

**Comment by kgriffs** [comment]
https://github.com/lwcolton/falcon-cors from @lwcolton should do the trick, but feel free to reopen this issue if that approach doesn't work for you.
