### ISSUE TITLE
TestCase decode url returns string in python3

### ISSUE THREAD

**Issue by masellfoodpanda** [falconry/falcon#817]
When i create a test based on falcon.testing.TestCase or falcon.testing.TestBase and run simulate_request with:
```
url = urllib.parse.quote_plus('%C3%A4%C3%B6%C3%BC%C3%9F%E2%82%AC')
simulate_request(url, 'utf-8')
```
i get the following error:
```
  File "falcon/api.py", line 155, in falcon.api.API.__call__ (falcon/api.c:1733)
  File "falcon/request.py", line 265, in falcon.request.Request.__init__ (falcon/request.c:1784)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac' in position 13: ordinal not in range(256)
```

I think this is due to this https://github.com/falconry/falcon/blob/master/falcon/util/uri.py#L246
and this https://github.com/falconry/falcon/blob/master/falcon/request.py#L263

**Comment by yashmehrotra** [comment]
@jmvrbanac I would like to take this issue.

**Comment by yashmehrotra** [comment]
@masellfoodpanda I am unable to reproduce this error. I wrote a testing function
```python
def test_xyz(self):
    import urllib
    url = urllib.parse.quote_plus('%C3%A4%C3%B6%C3%BC%C3%9F%E2%82%AC')
    self.simulate_request(url, 'utf-8')
```

It didn't threw any error.
I am using `python3.4`. Is there anything I am missing ?

**Comment by masellfoodpanda** [comment]
Ah, sorry. Seems i made double encoding in the report.

here is a test:
```
#!/usr/bin/env python
# -*- coding: utf8 -*-

import falcon
from falcon.testing import TestBase, StartResponseMock
import urllib


class TestFalcon(TestBase):
    def setUp(self):

        class API(falcon.API):
            pass

        class Resource(object):
            def on_get(self, req, resp, data):
                pass

        self.api = API()
        self.srmock = StartResponseMock()

        self.api.add_route('/test/{data}', Resource())

        self.urls = [
            '/test/%E5%BB%B6%E5%AE%89',
            '/test/%C3%A4%C3%B6%C3%BC%C3%9F%E2%82%AC',
        ]

    def test_xyz(self):
        for url in self.urls:
            with self.subTest(data=urllib.parse.unquote_plus(url)):
                self.simulate_request(url, 'utf-8')
```

**Comment by masellfoodpanda** [comment]
At the moment i need to monkey patch this like so:
```
from falcon.util import uri 
orig_decode = uri.decode
uri.decode = lambda x: orig_decode(x).encode('utf-8').decode('latin1')
```

**Comment by ministrike3** [comment]
@yashmehrotra  If you aren't going to take this I'd like to take a look!

**Comment by yashmehrotra** [comment]
@ministrike3 Sure, have a go.

**Comment by kgriffs** [comment]
The problem is that `create_environ()` is not tunneling via ISO-8859-1 under p3k. See: https://github.com/falconry/falcon/blob/master/falcon/testing/helpers.py#L131

The fix should be as simple as checking `six.PY3` and then performing `path.encode('utf-8').decode('iso-8859-1')`.

**Comment by masellfoodpanda** [comment]
Awesome, thank you @jmvrbanac and @kgriffs
