### ISSUE TITLE
Falcon is possible to upload file ?

### ISSUE THREAD

**Issue by drayanaindra** [falconry/falcon#825]
Hello, i using falcon for develop API on my project. And i found problem when i try upload file like doc, rar, zip and etc. When i try upload file with image extension, its working. 

falcon is possible to upload file with another extension except jpeg, png ?

thanks

**Comment by Vesuvium** [comment]
Unlike other frameworks Falcon does not provide extra tools for file uploads: it provides only the raw stream, but is up to you to extract (or detect) the file type and name from there.

**Comment by vit1251** [comment]
You can use third-party parser

```python
        from werkzeug.http import parse_options_header
        from werkzeug.formparser import MultiPartParser, default_stream_factory
        #
        mimetype, options = parse_options_header(req.content_type)
        size = req.content_length
        #
        boundary = options.get('boundary')
        if boundary:
            raise ValueError('No boundary')
        #
        parser = MultiPartParser(stream_factory=default_stream_factory)
        form, files = parser.parse(req.stream, boundary, size)
        #
        self.__log.debug("Form: {form!r}".format(form=form))
        self.__log.debug("Files: {files!r}".format(files=files))
```

But I think that it is workaround.

**Comment by kgriffs** [comment]
There's an add-on in the works for this here: https://github.com/yohanboniface/falcon-multipart

Also, we are discussing adding support directly into the framework: https://github.com/falconry/falcon/issues/953 

[closing this in favor of further discussing on #953]
