### ISSUE TITLE
Provide official documentation in other languages

### ISSUE THREAD

**Issue by nomorepanic** [falconry/falcon#833]
It would be nice if Falcon had docs also in other languages. I don't know if any one has actually translated the docs; links to translated docs could be added in a section e.g. [requests](http://docs.python-requests.org/en/master/) has links to translated docs in the sidebar

**Comment by vytas7** [comment]
@shimakaze-git are you still interested in providing the Japanese documentation?

**Comment by vytas7** [comment]
> That being said, this would be an ongoing project; before each release of the framework, I would need your help to go through the process of updating all the translations for the documents that changed since the last release. Since there is a fair amount of churn in the documentation between releases, it may be best to wait until a new release is imminent until working on the translation. I could notify you at that point.

Adding to what @kgriffs said on https://github.com/falconry/falcon/issues/1225#issuecomment-387612675 :arrow_up: , I believe we would need to somehow categorize the documentation into core and additional parts, where only the core would be required for other languages (they could of course opt into translating everything). If that is allowed by Sphinx intl stuff.

**Comment by vytas7** [comment]
Closing this for now. Let's reopen if any translator wants to volunteer to get this going.
