### ISSUE TITLE
Migrate to pytest

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#844]
Pre-work

- [x] Replace nose with the pytest runner

Files to Convert

- [ ] `test_wsgiref_inputwrapper_with_size`
- [ ] `test_wsgi_errors`
- [ ] `test_utils` (minus falcon.testing unittest pieces)
- [ ] `test_uri_templates_legacy`
- [ ] `test_slots`
- [ ] `test_sinks`
- [ ] `test_response_context`
- [ ] `test_request_context`
- [ ] `test_response_body`
- [ ] `test_request_body`
- [ ] `test_req_vars`
- [ ] `test_redirects`
- [ ] `test_query_params`
- [ ] `test_options`
- [ ] `test_middleware`
- [ ] `test_httpstatus`
- [ ] `test_httperror`
- [ ] `test_http_method_routing`
- [ ] `test_hello`
- [ ] `test_headers`
- [ ] `test_error_handlers`
- [ ] `test_error`
- [ ] `test_deps`
- [ ] `test_custom_router`
- [ ] `test_cmd_print_api`
- [ ] `test_before_hooks`
- [ ] `test_after_hooks`

**Comment by thomasgoirand** [comment]
Why not using testrepository and fixtures?

**Comment by yasek** [comment]
Hi!
I'm working over it right now. I've rewritten tests, doing cosmetic changes. I hope it'll be done this week: https://github.com/yasek/falcon/tree/feature/ddt_to_pytest
