### ISSUE TITLE
make req object exception configurable

### ISSUE THREAD

**Issue by lvalladares** [falconry/falcon#847]
The apis usually tend to have a pattern of response with certain defined parameters , as this framework focuses on the development of apis the req object should have some kind of parameter that allows the user to indicate the class of the exception to rise when an error such as invalid parameters occur.

In my case we tend to send a parameter called "status" with an internal code number and we cant use the full potential of the framework because this.

**Comment by kgriffs** [comment]
Hi @lvalladares, in your case would it be possible to use a [custom error handler](http://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_error_handler) to receive the default exception type and raise a different exception instead? Or you could raise a custom exception type in the first place and use an error handler to serialize the error (setting req properties accordingly).

**Comment by lvalladares** [comment]
Yes, it should work. Thanks, I will try and come back if any problem happens

**Comment by jmvrbanac** [comment]
Closing this for now. Please re-open this issue if you run into any problems.
