### ISSUE TITLE
Add additional values on get_param_as_bool like ON, OFF

### ISSUE THREAD

**Issue by vit1251** [falconry/falcon#854]
Hello,

How about add to get_param_as_bool values 

TRUE_STRINGS = [ ... , "on" ]
FALSE_STRINGS = [..., "off" ]

This is related to default value in checkbox on Internet Explorer.

Thanx.

**Comment by ladder1984** [comment]
How about '1'/'0' ?

**Comment by kgriffs** [comment]
'1' and '0' have been implemented. We can add 'on' and 'off' as well, no problem. Thanks for the suggestion!
