### ISSUE TITLE
Falcon routes

### ISSUE THREAD

**Issue by davidtavarez** [falconry/falcon#856]
I'm wondering how do I implement routes like theses
![linear-router](https://cloud.githubusercontent.com/assets/337107/17408285/963975c2-5a38-11e6-9d35-0f3d5d18ae1f.png)

Do I have to create object for each routes?

**Comment by rr-** [comment]
I miss the ability to use `@route('/resource/{x}')` decorator.

**Comment by benjohnde** [comment]
Seems like you are looking for something like https://github.com/stratoscale/hammock.

**Comment by kgriffs** [comment]
Hi @davidtavarez, it looks like you have the following REST resources:

* Park collection
* Park item
* Trail collection
* Trail item
* Map
* Reservation collection
* Reservation item

etc.

Each of these resources would be represented by a class and implement the HTTP methods that it supports. There's an open issue for implementing a way to combine the "collection" and "item" resources into a single class, if desired. Everyone's feedback is welcome: #584
