### ISSUE TITLE
How about make get_params_* as method in class Params

### ISSUE THREAD

**Issue by vit1251** [falconry/falcon#866]
How about make class params for reusing on query string, post data and put data from middleware to make single interface for any user client data access?

**Comment by kgriffs** [comment]
That could make sense, but we would need to benchmark to make sure the extra level of indirection doesn't significantly degrade performance (or if it does, try to offset that loss somewhere else). We have some parameter work scheduled for 1.2 so let's keep this discussion going and see what we can come up with.

**Comment by kgriffs** [comment]
Closing in favor of #418 and #953. Please share your thoughts on those other issues. Thanks!
