### ISSUE TITLE
Change comma-delimited list rendering and parsing defaults

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#872]
Wherever we currently default to the comma-delimited list format for query string parameters (e.g, `thing=1,2,3`), change to defaulting to rendering and parsing only the more common HTML forms-style (e.g., `thing=1&thing=2&thing=3`).

**Comment by vytas7** [comment]
The change has already been made for Falcon 2.0 by https://github.com/falconry/falcon/pull/1318.
