### ISSUE TITLE
how to parse data from a post request when content-type is form-data

### ISSUE THREAD

**Issue by pikkupr** [falconry/falcon#886]
I want to send form-data to the api, but I cannot find a way to parse that data. I am using python3 on ubuntu.

**Comment by kgriffs** [comment]
Hi @pikkupr, if the data is encoded as `application/x-www-form-urlencoded`, you can use the [auto_parse_form_urlencoded](http://falcon.readthedocs.io/en/latest/api/api.html#RequestOptions.auto_parse_form_urlencoded) option to parse it. 

Alternatively, you can manually read the body of the request and decode it via [falcon.uri.decode()](http://falcon.readthedocs.io/en/latest/api/util.html#falcon.uri.decode).

Finally, if the body is `multipart/form-data` you should be able to use `FieldStorage` from the standard library's [cgi](https://docs.python.org/2/library/cgi.html) module, e.g.:

```py
form = FieldStorage(fp=req.stream, environ=req.env)
```

**Comment by kgriffs** [comment]
P.S. - You may also want to check out this add-on: https://github.com/yohanboniface/falcon-multipart

**Comment by kgriffs** [comment]
See also: #825

**Comment by pikkupr** [comment]
@kgriffs Thank you for your reply. It was helpful. Thanks

**Comment by kgriffs** [comment]
See also: #953
