### ISSUE TITLE
Use `inspect.signature` to allow type hint annotaitons in hook functions

### ISSUE THREAD

**Issue by lucidfrontier45** [falconry/falcon#911]
Type hint is useful to tell the signature of a function to ide or editor like PyCharm/Atom. When I add type hint to hook function, python raises the exception

```python
def require_json(req: Request, resp: Response, resource, params):
    if req.method in ('POST', 'PUT'):
        if 'application/json' not in req.content_type:
            raise falcon.HTTPUnsupportedMediaType(
                'This API only supports requests encoded as JSON.',
                href='http://docs.examples.com/api/json')
```
```python
  File "/usr/lib/python3.5/inspect.py", line 1045, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

The error message says `getargspec` does not allow annotations and suggests I use `getfullargspec`.
Checking the codes of `getargspec` and `getfullargspec`, I found they are both deprecated and we should use  `inspect.signature`. 

How about follow this? 

Note that python2 does not have `inspect.signature` function. It has added since python3.3.
So we needs some special treatment for python2.

Maybe middleware has the same issue.

**Comment by kgriffs** [comment]
Hi, thanks for the report! We use getargspec in several places to facilitate backwards-compatibility. I think it would make sense to use `inspect.signature` instead on py3k.
