### ISSUE TITLE
DELETE methods don't parse the form parameters into their query string

### ISSUE THREAD

**Issue by abompard** [falconry/falcon#919]
Commit b36ffe6 removed the auto-parsing of form parameters into the query string for requests other than `POST`. Commit da0eec2 re-enabled it for `PUT` and `PATCH` requests. In my app (Mailman3) I also have `DELETE` methods that use form data and are broken by this change.

Could you allow `DELETE` requests to auto-parse the form parameters too? Or do you have an alternative way to parse this data into the `params` attribute (or another one)? Thanks.

**Comment by kgriffs** [comment]
Hi @abompard, thanks for the report! We'll fix this; I certainly don't want to break anyone with a point release. 😄
