### ISSUE TITLE
How can I get the IP of the client?

### ISSUE THREAD

**Issue by yssoe** [falconry/falcon#939]
Hello, 

I need to have the IP numbers of the client who is making requests in Falcon, I can't seem to find this, how can I do this? 

Thanks for the help. 

Cheers.

**Comment by jmvrbanac** [comment]
Answering this even though it was closed as others might have the same question. 
Falcon relies on WSGI to provide those values. Usually these can be retrieved via `access_route` or `remote_addr` on the Request object. https://falcon.readthedocs.io/en/stable/api/request_and_response.html#Request.access_route
