### ISSUE TITLE
only part of the api need to use auth middleware?

### ISSUE THREAD

**Issue by tyan4g** [falconry/falcon#955]
I build apis .and some of them need the auth info and some of them don't need the auth info..
so how could I construct an auth middleware??
As the doc suggest,

> Unlike hooks, middleware methods apply globally to the entire API.

so I guess I have to use hooks????or I should stick to middleware and detect the request.url in the middleware and check auth state or just use a hook,,,

I guess I need some general help on authentication and authorization??I already build a RBAC on current system and just don't have the idea how to construct  those things with falcon api///

**Comment by arashsoheili** [comment]
The `@falccon.before()` hook is your best choice for this. Just decorate any route that needs the auth with it.

**Comment by jmvrbanac** [comment]
It really depends on your use case. If you only have a couple of simple routes such as a healthcheck endpoint, then it's quite easy just to add simple conditional in your auth middleware's `process_request(...)`. If you need more expansive and/or granular controls, then I would either add an attribute to the resource and check it in the middleware `process_resource()` or use the hook/decorating option.
