### ISSUE TITLE
Interop with wsgiref.simple_server?

### ISSUE THREAD

**Issue by randomphrase** [falconry/falcon#956]
Hi, I'm a newbie to wsgi in general and falcon in particular. However I'd like to clarify exactly what level of interop to expect when falcon is used with wsgiref.simple_server?

For example, the following is slightly adapted from the tutorial:

    import falcon
    import mimetypes
    import os
    from wsgiref.simple_server import make_server
     
    api = application = falcon.API()
     
    class Resource(object):
     
        def on_get(self, req, resp):
            fullpath = os.path.realpath(__file__)
            resp.content_type = mimetypes.guess_type(fullpath)[0]
            resp.stream = open(fullpath, 'r')
            resp.stream_len = os.path.getsize(fullpath)
     
    images = Resource()
    api.add_route('/images', images)
     
    srv = make_server("127.0.0.1", 8000, application)
    srv.serve_forever()

Remove the last two lines and this runs fine under gunicorn. However when run like "python3 app.py" it will produce an error like the following:

    127.0.0.1 - - [05/Dec/2016 15:05:30] "GET /images HTTP/1.1" 500 59
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 43702)
    Traceback (most recent call last):
      File "/spare/local/miniconda3/lib/python3.5/wsgiref/handlers.py", line 138, in run
        self.finish_response()
      File "/spare/local/miniconda3/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
        self.write(data)
      File "/spare/local/miniconda3/lib/python3.5/wsgiref/handlers.py", line 266, in write
        "write() argument must be a bytes instance"
    AssertionError: write() argument must be a bytes instance

(If it matters this is python 3.5.2 on Fedora 22)

Again I am not exactly sure what the correct behavior is here - maybe it is working as intended, however it would be good to get some clarification, possibly in documentation?

Thanks in advance.

**Comment by arashsoheili** [comment]
Add binary to your stream and it works in both cases.
`resp.stream = open(fullpath, 'rb')`

**Comment by jmvrbanac** [comment]
To @arashsoheili's point, I believe this is a Python 2 vs 3 issue here. Your code should work perfectly fine under Python 2.7 as `bytes` is just a string in 2.7. However, in Python 3, bytes is actually a real concept which is why wsgiref is having a problem with your stream.

As a side note, Falcon should work under any server that supports the WSGI spec. Personally, I've only used Falcon under gunicorn, uwsgi, and webtest. However, If there is an issue with running Falcon under wsgiref then please let us know.
