### ISSUE TITLE
"Field names must be valid identifiers" error when field is one character long

### ISSUE THREAD

**Issue by fastingsamurai** [falconry/falcon#959]
I have a route that looks like: /blah/{t}

Upon upgrading Falcon to 1.1.0, adding this route results in the error in the title.

I have to assume that the regex used here is wrong:

```
is_identifier = re.match('[A-Za-z_][A-Za-z0-9_]+$', field)
```

It should be:

```
is_identifier = re.match('[A-Za-z_][A-Za-z0-9_]*$', field)
```

I love Falcon! Thanks.

**Comment by kgriffs** [comment]
Fixed by https://github.com/falconry/falcon/pull/937
