### ISSUE TITLE
Support closing filelike response streams

### ISSUE THREAD

**Issue by hozn** [falconry/falcon#960]
We ran into an issue wanting to provide a TemporaryFile (for e.g. very large file downloads) as a stream to the response.  These files would be removed when closed, but the iterator that Falcon uses does not expose a close method to close the underlying stream.

In short, I'd like to propose that the iterator implementation calls `close()` on the stream, if the method is exposed on the stream.

(I will submit a PR for this.)

**Comment by kgriffs** [comment]
Sounds good, we'll take a look at the PR. Thanks!
