### ISSUE TITLE
HTTPError in middleware results in AttributeError when parsing body

### ISSUE THREAD

**Issue by jdno** [falconry/falcon#962]
Hi,

I am getting the following error when I try to access certain routes in my application:

```
self = <falcon.api.API object at 0x10d227758>, resp = <falcon.response.Response object at 0x10d227f50>
wsgi_file_wrapper = None

    def _get_body(self, resp, wsgi_file_wrapper=None):
        body = resp.body
        if body is not None:
            if not isinstance(body, bytes):
>               body = body.encode('utf-8')
E               AttributeError: 'dict' object has no attribute 'encode'

venv/lib/python2.7/site-packages/falcon/api.py:647: AttributeError
```

I use a middleware ([jhildreth/falcon-jwt-checker](https://github.com/jhildreth/falcon-jwt-checker) to validate and decode JWTs, and the error is raised every time the middleware raises an `HTTPUnauthorized` error.

I spent some time with the debugger and found out that during the exception handling, the error from the middleware is converted into a suitable representation and put into `resp.body` as a `dict` like this:

    body = {'description': 'Please provide a valid auth token.', 'title': 'Authentication Required'}

This breakes `_get_body` which doesn't expect a `dict`. I am super confused by this, because from my research so far raising an error is actually the expected behavior of a middleware.

Is this a weird edge case, a bug or an error on my part?

**Comment by jmvrbanac** [comment]
Sorry about taking so long in responding to this issue. I personally haven't run into this issue before. However it sounds like you're relying on a another middleware to convert your body dictionary as JSON. Out of the box, Falcon assumes the body is just string that can be encoded. So if you're not currently using a middleware to handle this, a simple `json.dumps(...)` should solve the problem.

We're currently trying to make this a little more straightforward for user. As a result, we do have a feature currently in review to add a `media` attribute to request and response which will accept an object and correctly handle the de/serialization. We're currently planning to have this included in Falcon 1.3.

**Comment by bootrino** [comment]
I got this error when returning a Python object instead of a json dump of an object.

**Comment by vytas7** [comment]
Hi @jdno and @bootrino !
Depending on the middleware order, things can indeed get complicated when different layers morph [`req.body`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.body) along the way.
As @jmvrbanac mentioned, that was actually one of the major reasons behind unifying [media handling](https://falcon.readthedocs.io/en/stable/api/media.html).

I'm thus going to close this issue suggesting the revamped [media handling](https://falcon.readthedocs.io/en/stable/api/media.html) as the preferred solution. It has been out in the wild for a while now :wink:
To be precise, using [`resp.media`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.media) in lieu of [`resp.body`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.body) should eliminate the ambiguity whether one is referring to the serialized version, or a raw response body (FWIW [`resp.body`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.body) is now documented as of type string/bytestring, so setting it to a `dict` would be a somewhat loose interpretation of this attribute).
