### ISSUE TITLE
Provide complete example of resource in documentation

### ISSUE THREAD

**Issue by mikebski** [falconry/falcon#963]
In the documentation, all of the resource examples show `on_get(self, req, resp)` methods only.  There is not a list of all the methods that can be implemented by a resource:

* on_get
* on_post
* on_put
* on_head
...

A basic list of all HTTP verbs and which methods they map to would be good to have in the documentation/quickstart since this is a key part of the framework.  The first explanation I found for this is halfway down the API class documentation and it says:

`Responder names start with on_ and are named according to which HTTP method they handle, as in on_get, on_post, on_put, etc.`

**Comment by FFX01** [comment]
Agreed. Documenting this would be a good idea. Falcon has a rather strange way of writing Resource classes in that methods do not explicitly return the response object. There is also the issue of explaining to people that they need to read `Request.stream` in order to get the body of the request.

**Comment by vytas7** [comment]
Addressed in https://github.com/falconry/falcon/pull/1247
