### ISSUE TITLE
Adding new feature : Rate Limiting(Throttling)

### ISSUE THREAD

**Issue by sagarrshd** [falconry/falcon#969]
Rate limiting(throttling) is an important feature every web framework should possess. Please consider adding it to your feature list.

**Comment by kgriffs** [comment]
Would this be better as a standalone package (ala flask-limiter) or built into the framework?

**Comment by phoenix911** [comment]
we can always use **exception falcon.HTTPTooManyRequests** to limit rate

**Comment by Woolworths** [comment]
I would also want this, but it is absolutely not appropriate for a "bare metal" framework as it would require database i/o to work.

**Comment by kgriffs** [comment]
OK, sounds like it would be best to make this a standalone package, perhaps under the falconry org unless someone else would like to maintain it.

**Comment by ZelphirKaltstahl** [comment]
Here is a project which does almost what I need: https://github.com/piotrmaslanka/falcon-ratelimit/blob/master/falconratelimit/ratelimit.py
Only that it returns HTTP code 200 even when there are too many requests. So I will fork it and try to fix that by setting the HTTP status code in the case of too many requests.

**Comment by vytas7** [comment]
I'm going to close this in favour of https://github.com/falconry/falcon/issues/1054 since both issues seem to track the same thing.

@ZelphirKaltstahl thanks for pointing out the said project, I'll add your comment to https://github.com/falconry/falcon/issues/1054
