### ISSUE TITLE
Evaluate the design and implementation of middleware as a whole

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#975]
Things to discuss:

- Free functions vs. grouping in a class
- Quality of the implementation of independent execution
- ~~Defaulting to independent execution~~ already default as of 2.0+

**Comment by kgriffs** [comment]
See also: https://github.com/falconry/falcon/pull/926

**Comment by vytas7** [comment]
Closing this, let's open new issues if needed. From the description it sounds that this issue was mostly revolving improving independent middleware, and switching the default to independent execution. That has already happened in Falcon 2.0.
