### ISSUE TITLE
Falcon and memory footprint

### ISSUE THREAD

**Issue by pcdinh** [falconry/falcon#98]
Any idea how Falcon deals with memory footprint? It looks like that both Bottle and Flask micro framework consume more memory than an average PHP framework.

I use Bottle right now because its memory footprint is acceptable.

Ref:
http://nuald.blogspot.com/2011/08/web-application-framework-comparison-by.html

**Comment by kgriffs** [comment]
I know this is a very old issue, but I just wanted to comment real quick in case anyone else is searching for info on this. Falcon 1.0 takes about 10 MB for a small-ish API test, not using any additional libraries, and running under CPython 2.7.11.
