### ISSUE TITLE
Worker timeout when posting between handlers

### ISSUE THREAD

**Issue by montao** [falconry/falcon#998]
I got a worker timeout when trying to do http from one handler to another in the same app. This was due to starting with only one worker, so it has be resolved.

**Comment by jmvrbanac** [comment]
This sounds like an issue with your WSGI server configuration. How are you hosting your Falcon App? Gunicorn, uWSGI, wsgiref, something else?

**Comment by montao** [comment]
I used Gunicorn when this issue appeared, but I could reconfigure and resolve the issue. You may close this issue because I have no more problem. Thanks
